# Generated by Django 3.2.15 on 2022-12-16 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0034_auto_20221017_1301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pssiDataInventory', '0003_auto_20221214_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainventory',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.CreateModel(
            name='InventoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='national administrator?')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pssiDataInventory_users', to='shared_models.region', verbose_name='regional administrator?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pssiDataInventory_user', to=settings.AUTH_USER_MODEL, verbose_name='DM Apps user')),
            ],
            options={
                'ordering': ['-is_admin', 'user__first_name'],
            },
        ),
    ]
