# Generated by Django 3.2.15 on 2022-12-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pssiDataInventory', '0006_auto_20221216_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='InventoryID',
            field=models.ManyToManyField(related_name='topic', to='pssiDataInventory.DataInventory'),
        ),
    ]
