# Generated by Django 2.0.4 on 2018-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('5', 'Active'), ('2', 'Resolved'), ('6', 'Idle'), ('7', 'Unresolved'), ('8', 'Wishlist')], default='5', max_length=1),
        ),
    ]
