# Generated by Django 2.1.4 on 2019-04-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dm_tickets', '0002_auto_20190408_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assign_to',
            new_name='assigned_to',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='app',
            field=models.CharField(blank=True, choices=[('general', 'General Issue'), ('dm_tickets', 'Data management tickets'), ('inventory', 'metadata inventory'), ('grais', 'grAIS'), ('oceanography', 'Oceanography'), ('herring', 'HerMorrhage'), ('camp', 'CAMP db'), ('snowcrab', 'Snowcrab'), ('meq', 'Marine environmental quality (MEQ)'), ('diets', 'Marine diets'), ('projects', 'Science project planning'), ('ihub', 'iHub'), ('scifi', 'SciFi'), ('masterlist', 'Masterlist'), ('shares', 'Gulf Shares'), ('travel', 'Travel Plans')], default='general', max_length=25, null=True, verbose_name='application name'),
        ),
    ]
