# Generated by Django 2.1.4 on 2019-04-08 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0003_auto_20190408_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='app',
            field=models.CharField(blank=True, choices=[('general', 'General Issue'), ('camp', 'CAMP db'), ('diets', 'Marine diets'), ('dm_tickets', 'Data management tickets'), ('grais', 'grAIS'), ('herring', 'HerMorrhage'), ('ihub', 'iHub'), ('inventory', 'metadata inventory'), ('masterlist', 'Masterlist'), ('meq', 'Marine environmental quality (MEQ)'), ('oceanography', 'Oceanography'), ('projects', 'Science project planning'), ('scifi', 'SciFi'), ('shares', 'Gulf Shares'), ('snowcrab', 'Snowcrab'), ('travel', 'Travel Plans')], default='general', max_length=25, null=True, verbose_name='application name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ticket assigned to'),
        ),
    ]
