# Generated by Django 2.1.4 on 2019-03-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0011_remove_ticket_fiscal_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='year',
            new_name='fiscal_year',
        ),
    ]
