# Generated by Django 2.1.4 on 2019-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0013_ticket_github_issue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='github_resolved',
            field=models.NullBooleanField(),
        ),
    ]
