# Generated by Django 2.1.4 on 2019-04-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0014_ticket_github_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='github_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
