# Generated by Django 2.1.4 on 2019-03-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0014_remove_ticket_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='section2',
            new_name='section',
        ),
    ]
