# Generated by Django 2.1.4 on 2019-03-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0015_auto_20190320_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
