# Generated by Django 2.1.4 on 2019-03-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0018_ticket_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
