# Generated by Django 2.1.4 on 2019-03-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0019_remove_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status1',
            new_name='status',
        ),
    ]
