# Generated by Django 2.1.4 on 2019-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0020_merge_20190514_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='app',
            field=models.CharField(blank=True, choices=[('general', 'n/a'), ('esee', 'ESEE (not part of site)'), ('plankton', 'Plankton Net (not part of site)'), ('publications', 'Project Publications Inventory'), ('tickets', 'Data Management Ticketing App')], default='general', max_length=25, null=True, verbose_name='application name'),
        ),
    ]
