# Generated by Django 2.1.4 on 2019-05-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0021_auto_20190514_1530'),
        ('dm_tickets', '0019_auto_20190516_2158'),
    ]

    operations = [
    ]
