# Generated by Django 2.1.4 on 2019-03-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0021_auto_20190320_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dm_tickets.Status'),
        ),
    ]
