# Generated by Django 2.1.4 on 2019-03-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0026_auto_20190321_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['status', '-date_modified']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='people',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tags',
        ),
    ]
