# Generated by Django 2.1.4 on 2019-03-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0029_remove_ticket_sd_primary_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='sd_primary_contact1',
            new_name='sd_primary_contact',
        ),
    ]
