# Generated by Django 2.1.4 on 2019-03-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_tickets', '0030_auto_20190321_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low'), ('4', 'Wish List'), ('5', 'Urgent')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='dm_tickets.Status'),
        ),
    ]
