# Generated by Django 2.1.4 on 2019-03-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, verbose_name='hostname')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP address')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC address')),
                ('server_type', models.IntegerField(choices=[(1, 'DSM'), (2, 'Ubuntu')], verbose_name='server type')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('local_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='local path')),
                ('mounted_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='mounted path')),
                ('network_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='network path')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='shares.Server')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='notes')),
                ('flag_for_deletion', models.BooleanField(default=False, verbose_name='flag for deletion')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shares.Server')),
            ],
        ),
        migrations.AddField(
            model_name='share',
            name='users',
            field=models.ManyToManyField(to='shares.User'),
        ),
    ]
