# Generated by Django 2.2.2 on 2020-04-29 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, verbose_name='hostname')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP address')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC address')),
                ('server_type', models.IntegerField(choices=[(1, 'DSM'), (2, 'Ubuntu')], verbose_name='server type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='color')),
            ],
            options={
                'ordering': ['server_type', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('status', models.IntegerField(choices=[(1, 'Initiated'), (2, 'Activated'), (3, 'Flagged for deletion')], default=1, verbose_name='status')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shares.Server')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['server', 'username'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('local_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='local path')),
                ('mounted_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='mounted path')),
                ('network_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='network path')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='shares.Server')),
                ('users', models.ManyToManyField(blank=True, related_name='shares', to='shares.User')),
            ],
            options={
                'ordering': ['server', 'name'],
            },
        ),
    ]
