# Generated by Django 2.1.4 on 2019-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_share_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='share',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
