# Generated by Django 2.1.4 on 2019-03-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_auto_20190305_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='activated'),
        ),
        migrations.AlterField(
            model_name='share',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shares', to='shares.User'),
        ),
    ]
