# Generated by Django 2.1.4 on 2019-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_auto_20190305_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='flag_for_deletion',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiated'), (2, 'Activated'), (3, 'Flagged for deletion')], default=2, verbose_name='status'),
            preserve_default=False,
        ),
    ]
