# Generated by Django 2.1.4 on 2019-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_auto_20190305_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiated'), (2, 'Activated'), (3, 'Flagged for deletion')], default=1, verbose_name='status'),
        ),
    ]
