# Generated by Django 3.2.15 on 2023-01-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pssi', '0003_auto_20230112_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='apm_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='APM ID'),
        ),
    ]
