# Generated by Django 3.1.2 on 2021-02-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_auto_20210126_1540'),
        ('events', '0003_auto_20210204_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitee',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='invitee',
            name='person',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_fr',
        ),
        migrations.AddField(
            model_name='invitee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='work email'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='first_name',
            field=models.CharField(default='test', max_length=100, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitee',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.language', verbose_name='language preference'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='work phone'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='status',
            field=models.IntegerField(choices=[(0, 'invited'), (1, 'accepted'), (2, 'declined'), (9, 'not response')], default=0, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.invitee', verbose_name='attendee')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('invitee', 'date')},
            },
        ),
    ]
