# Generated by Django 3.1.2 on 2021-02-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210207_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='email body'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.event', verbose_name='parent event'),
        ),
    ]
