# Generated by Django 3.1.6 on 2021-03-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210209_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_email',
            field=models.EmailField(default='DoNotReply-nepasrepondre.DMApps@dfo-mpo.gc.ca', max_length=254, verbose_name='FROM email address (on invitation)'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='role',
            field=models.IntegerField(choices=[(1, 'Participant'), (2, 'Chair'), (3, 'Expert'), (4, 'Steering Committee Member')], default=1, verbose_name='Function'),
        ),
    ]
