# Generated by Django 3.2.2 on 2021-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0002_auto_20210128_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dive',
            name='end_latitude',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='end_latitude_d',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='end_latitude_mm',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='end_longitude_d',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='end_longitude_mm',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='start_latitude_d',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='start_latitude_mm',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='start_longitude',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='start_longitude_d',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='start_longitude_mm',
        ),
        migrations.AlterField(
            model_name='transect',
            name='end_latitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='end latitude'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='end_latitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='end latitude (minutes)'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='end_longitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='end longitude'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='end_longitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='end longitude (minutes)'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='start_latitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='start latitude'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='start_latitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='start latitude (minutes)'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='start_longitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='start longitude'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='start_longitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='start longitude (minutes)'),
        ),
    ]
