# Generated by Django 3.2.4 on 2021-10-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0028_alter_organization_uuid'),
        ('res', '0004_application_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='res_applications', to='shared_models.fiscalyear', verbose_name='fiscal year'),
        ),
    ]
