# Generated by Django 3.2.4 on 2021-10-14 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('res', '0008_auto_20211013_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='res_applications', to=settings.AUTH_USER_MODEL, verbose_name='applicant name'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='res.application'),
        ),
    ]
