# Generated by Django 3.2.4 on 2021-10-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('res', '0010_auto_20211014_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='manager',
            field=models.ForeignKey(help_text='This is the person who will provide a recommendation on this application', on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_res_applications', to=settings.AUTH_USER_MODEL, verbose_name='manager name'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='applicant_comment',
            field=models.TextField(blank=True, help_text='no more than 250 words', null=True, verbose_name='applicant comment'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='applicant_signed',
            field=models.DateTimeField(editable=False, verbose_name='signed by applicant'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='decision',
            field=models.IntegerField(blank=True, choices=[(0, 'In my opinion, the dossier contains sufficient evidence to warrant consideration of the application by the appropriate committee.'), (1, 'In my opinion, the dossier does not contain sufficient evidence to warrant consideration of the application by the appropriate committee.')], null=True, verbose_name='decision'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='manager_signed',
            field=models.DateTimeField(editable=False, verbose_name='signed by manager'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_text',
            field=models.TextField(blank=True, help_text='no more than 250 words', null=True, verbose_name="manager's assessment"),
        ),
    ]
