# Generated by Django 3.2.4 on 2021-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_auto_20211014_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='applicant_signed',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='signed by applicant'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='manager_signed',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='signed by manager'),
        ),
    ]
