# Generated by Django 3.2.4 on 2021-10-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0023_auto_20211025_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
    ]
