# Generated by Django 3.2.4 on 2021-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0026_rename_sitetext_sitesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('code', models.CharField(max_length=5, verbose_name='category code')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
