# Generated by Django 3.2.5 on 2021-12-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0034_ressubuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='detail',
            field=models.TextField(verbose_name='detail'),
        ),
    ]
