# Generated by Django 2.1.4 on 2019-04-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios2', '0002_remove_mooring_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooring',
            name='instruments',
            field=models.ManyToManyField(blank=True, through='ios2.InstrumentMooring', to='ios2.Instrument'),
        ),
    ]
