# Generated by Django 2.1.4 on 2019-04-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios2', '0003_auto_20190416_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('AMAR', 'AMAR'), ('Baker Traps', 'Baker Traps'), ('SBE uCat', 'SB uCat'), ('SBE ODO', 'SB ODO'), ('SBE IDO', 'SB IDO'), ('SBE16+', 'SBE16+'), ('SBE19+', 'SBE19+'), ('SBE37 NoPump', 'SBE37 NoPump'), ('SBE37 W/Pump', 'SBE37 W/Pump'), ('SBE SeaFET', 'SBE SeaFET'), ('SBE SeapHox', 'SBE SeapHox'), ('TRDI LR75kHz', 'TRDI LR75kHz'), ('ADCP 150kHz', 'ADCP 150kHz'), ('ADCP 300kHz', 'ADCP 300kHz'), ('ADCP 600kHz', 'ADCP 600kHz'), ('Nortek Aquadopps', 'Nortek Aquadopps'), ('SONTEK Argonaut', 'SONTEK Argonaut'), ('RBR Virtuoso', 'RBR Virtuoso'), ('Wildlife Acoustics SM2M+', 'Wildlife Acoustics SM2M+'), ('Wildlife Acoustics SM3M', 'Wildlife Acoustics SM3M'), ('Multi Electronique Aural M2', 'Multi Electronique Aural M2'), ('AR861 Acoustic Release', 'AR861 Acoustic Release'), ('CTD', 'CTD'), ('OXY', 'OXY')], default='SBE16+', max_length=20, verbose_name='Instrument Type'),
        ),
    ]
