# Generated by Django 3.1.2 on 2020-12-02 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dm_apps.custom_widgets
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_models', '0032_auto_20201201_1040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('cost_type', models.IntegerField(choices=[(1, 'Salary'), (2, 'O&M')])),
                ('exclude_from_rollup', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FunctionalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('sections', models.ManyToManyField(blank=True, related_name='functional_groups', to='shared_models.Section')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['funding_source_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FundingSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('eng_text', models.TextField(verbose_name='English text')),
                ('fra_text', models.TextField(blank=True, null=True, verbose_name='French text')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OMCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.IntegerField(choices=[(1, 'Travel'), (2, 'Equipment Purchase'), (3, 'Material and Supplies'), (4, 'Human Resources'), (5, 'Contracts, Leases, Services'), (6, 'Other')])),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', dm_apps.custom_widgets.OracleTextField(verbose_name='Project title')),
                ('is_national', models.IntegerField(blank=True, choices=[(None, 'Unknown'), (1, 'National'), (0, 'Regional')], default=False, null=True, verbose_name='National or regional?')),
                ('is_competitive', models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], default=0, null=True, verbose_name='Is the funding competitive?')),
                ('is_approved', models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Has this project already been approved')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date of project')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date of project')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project objective & description')),
                ('priorities', models.TextField(blank=True, null=True, verbose_name='Project-specific priorities')),
                ('deliverables', models.TextField(blank=True, null=True, verbose_name='Project deliverables / activities')),
                ('requires_specialized_equipment', models.BooleanField(default=False, verbose_name='Will the project require the purchase, design or fabrication of specialized laboratory or field equipment?')),
                ('technical_service_needs', models.TextField(blank=True, null=True, verbose_name='What technical services are being requested?')),
                ('mobilization_needs', models.TextField(blank=True, null=True, verbose_name='Do you anticipate needing assistance with mobilization/demobilization of this equipment?')),
                ('has_travel', models.BooleanField(default=False, verbose_name='Does this project involved a field component?')),
                ('vehicle_needs', models.TextField(blank=True, null=True, verbose_name='Describe need for vehicle (type of vehicle, number of weeks, time-frame)')),
                ('ship_needs', models.TextField(blank=True, null=True, verbose_name='Ship (Coast Guard, charter vessel) Requirements')),
                ('coip_reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='If this project links to a ship time request in COIP, please include the COIP application number here.')),
                ('instrumentation', models.TextField(blank=True, null=True, verbose_name='What field instrumentation will be deployed during this project?')),
                ('owner_of_instrumentation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Who is the owner/curator of this instrumentation, if known?')),
                ('requires_field_staff', models.BooleanField(default=False, verbose_name='Do you require field support staff?')),
                ('field_staff_needs', models.TextField(blank=True, null=True, verbose_name='If so, please include some additional detail, e.g., how many people are likely to be required and when')),
                ('has_new_data', models.BooleanField(default=False, verbose_name='Will new data be collected or generated?')),
                ('data_collection', models.TextField(blank=True, null=True, verbose_name='What type of data will be collected')),
                ('data_products', models.TextField(blank=True, null=True, verbose_name='What data products will be generated (e.g. models, indices)?')),
                ('open_data_eligible', models.BooleanField(default=True, verbose_name='Are these data / data products eligible to be placed on the Open Data Platform?')),
                ('data_storage', models.TextField(blank=True, null=True, verbose_name='Data storage / archiving Plan')),
                ('regional_dm_needs', models.TextField(blank=True, null=True, verbose_name='Describe what data management support is required, if any.')),
                ('has_lab_work', models.BooleanField(default=False, verbose_name='Does this project involve laboratory work?')),
                ('abl_services_required', models.BooleanField(default=False, verbose_name='Does this project require the services of Aquatic Biotechnology Lab (ABL)?')),
                ('lab_space_required', models.BooleanField(default=False, verbose_name='Is laboratory space required?')),
                ('requires_other_lab_support', models.BooleanField(default=False, verbose_name='Does this project require other specialized laboratory support or services (provide details below)?')),
                ('other_lab_support_needs', models.TextField(blank=True, null=True, verbose_name='Describe other laboratory requirements relevant for project planning purposes.')),
                ('it_needs', models.TextField(blank=True, null=True, verbose_name='Special IT requirements (software, licenses, hardware)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='additional notes')),
                ('submitted', models.BooleanField(default=False, verbose_name='Submit project for review')),
                ('recommended_for_funding', models.BooleanField(default=False, verbose_name='recommended')),
                ('approved', models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='approved')),
                ('allocated_budget', models.FloatField(blank=True, null=True, verbose_name='Allocated budget')),
                ('notification_email_sent', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Notification Email Sent')),
                ('meeting_notes', models.TextField(blank=True, null=True, verbose_name='administrative notes')),
                ('is_hidden', models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], default=False, null=True, verbose_name='Should the project be hidden from other users?')),
                ('date_last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified')),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.activitytype', verbose_name='activity type')),
                ('allotment_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects', to='shared_models.allotmentcode', verbose_name='allotment code (if known)')),
                ('default_funding_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='projects.fundingsource', verbose_name='primary funding source')),
                ('existing_project_codes', models.ManyToManyField(blank=True, to='shared_models.Project', verbose_name='existing project codes (if known)')),
                ('functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='projects.functionalgroup', verbose_name='Functional group')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('responsibility_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects', to='shared_models.responsibilitycenter', verbose_name='responsibility center (if known)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='shared_models.section', verbose_name='section')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('used_for', models.IntegerField(choices=[(1, 'Projects'), (2, 'Status reports'), (3, 'Milestones')])),
                ('order', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['used_for', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpcomingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.TextField(verbose_name='description (en)')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description (fr)')),
                ('date', models.DateField()),
                ('is_deadline', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_upcoming_dates', to='shared_models.region', verbose_name='region')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_accomplishments', models.TextField(blank=True, null=True, verbose_name='major accomplishments (this can be left blank if reported at the milestone level)')),
                ('major_issues', models.TextField(blank=True, null=True, verbose_name='major issues encountered')),
                ('target_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='target completion date')),
                ('rationale_for_modified_completion_date', models.TextField(blank=True, null=True, verbose_name='rationale for a modified completion date')),
                ('general_comment', models.TextField(blank=True, null=True, verbose_name='general comments')),
                ('section_head_comment', models.TextField(blank=True, null=True, verbose_name='section head comment')),
                ('section_head_reviewed', models.BooleanField(default=False, verbose_name='reviewed by section head')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
                ('status', models.ForeignKey(limit_choices_to={'used_for': 2}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='projects.status')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('file', models.FileField(upload_to=projects.models.ref_mat_directory_path, verbose_name='file attachment')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_materials', to='shared_models.region', verbose_name='region')),
            ],
            options={
                'ordering': ['region', 'file'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'used_for': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.status', verbose_name='project status'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Tag', verbose_name='Tags / keywords (used for searching)'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.ForeignKey(blank=True, default=2022, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='shared_models.fiscalyear', verbose_name='fiscal year'),
        ),
        migrations.CreateModel(
            name='OMCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('budget_requested', models.FloatField(default=0, verbose_name='budget requested')),
                ('funding_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='om_costs', to='projects.fundingsource', verbose_name='funding source')),
                ('om_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='om_costs', to='projects.omcategory', verbose_name='category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='om_costs', to='projects.project', verbose_name='project')),
            ],
            options={
                'ordering': ['om_category'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GCCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recipient organization')),
                ('project_lead', models.CharField(blank=True, max_length=255, null=True, verbose_name='project lead')),
                ('proposed_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proposed title of agreement')),
                ('gc_program', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of G&C program')),
                ('budget_requested', models.FloatField(default=0, verbose_name='budget requested')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gc_costs', to='projects.project', verbose_name='project')),
            ],
            options={
                'ordering': ['recipient_org'],
            },
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='funding_source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='funding_sources', to='projects.fundingsourcetype'),
        ),
        migrations.AddField(
            model_name='functionalgroup',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functional_groups', to='projects.theme'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='resource name')),
                ('file', models.FileField(blank=True, null=True, upload_to=projects.models.file_directory_path, verbose_name='file attachment')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='external URL')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('status_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.statusreport')),
            ],
            options={
                'ordering': ['project', 'status_report', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('critical', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Critical to project delivery')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='projects.project', verbose_name='project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollaborativeAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='collaborating organization')),
                ('project_lead', models.CharField(blank=True, max_length=255, null=True, verbose_name='project lead')),
                ('agreement_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the agreement')),
                ('new_or_existing', models.IntegerField(choices=[(1, 'New'), (2, 'Existing')], verbose_name='new or existing')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='projects.project', verbose_name='project')),
            ],
            options={
                'ordering': ['partner_organization'],
            },
        ),
        migrations.CreateModel(
            name='CapitalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'IM / IT - computers, hardware'), (2, 'Lab Equipment'), (3, 'Field Equipment'), (4, 'Other')], verbose_name='category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('budget_requested', models.FloatField(default=0, verbose_name='budget requested')),
                ('funding_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='capital_costs', to='projects.fundingsource', verbose_name='funding source')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_costs', to='projects.project', verbose_name='project')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False, verbose_name='project lead')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Person name (leave blank if user is selected)')),
                ('student_program', models.IntegerField(blank=True, choices=[(1, 'FSWEP'), (2, 'Coop')], null=True, verbose_name='student program')),
                ('duration_weeks', models.FloatField(blank=True, default=0, null=True, verbose_name='duration in weeks')),
                ('overtime_hours', models.FloatField(blank=True, default=0, null=True, verbose_name='overtime in hours')),
                ('overtime_description', models.TextField(blank=True, null=True, verbose_name='overtime description')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='cost')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.employeetype', verbose_name='employee type')),
                ('funding_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_members', to='projects.fundingsource', verbose_name='funding source')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.level', verbose_name='level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_instances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['employee_type', 'level'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='executive summary')),
                ('pressures', models.TextField(blank=True, null=True, verbose_name='pressures')),
                ('functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.functionalgroup')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.fundingsource')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='shared_models.section')),
            ],
            options={
                'unique_together': {('section', 'functional_group'), ('funding_source', 'functional_group')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.milestone')),
                ('status', models.ForeignKey(default=9, limit_choices_to={'used_for': 3}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updates', to='projects.status')),
                ('status_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.statusreport')),
            ],
            options={
                'ordering': ['-status_report', 'status'],
                'unique_together': {('milestone', 'status_report')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='fundingsource',
            unique_together={('funding_source_type', 'name')},
        ),
    ]
