# Generated by Django 2.1.4 on 2019-03-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190320_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='division',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_head',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
