# Generated by Django 2.1.4 on 2019-01-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190114_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcode',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='time_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='time_start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_lead',
        ),
        migrations.AlterField(
            model_name='staff',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='duration_weeks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Level'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='student_program',
            field=models.IntegerField(blank=True, choices=[('FWSEP', 'Salary'), ('COOP', 'O&M')], null=True),
        ),
    ]
