# Generated by Django 2.1.4 on 2019-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190516_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.NullBooleanField(verbose_name='Has this project already been approved'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_competitive',
            field=models.NullBooleanField(verbose_name='Is the funding for this project competitive (e.g. ACRDP, PARR, SPERA)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_national',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'National'), (False, 'Regional')], verbose_name='National or regional?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_negotiable',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Negotiable'), (False, 'Non-negotiable')], verbose_name='Negotiable or Non-negotiable (e.g. Core vs. Non-core)?'),
        ),
    ]
