# Generated by Django 2.1.4 on 2019-05-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190517_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deliverables_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priorities_html',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_competitive',
            field=models.NullBooleanField(default=False, verbose_name='Is the funding for this project competitive (e.g. ACRDP, PARR, SPERA)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_national',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'National'), (False, 'Regional')], default=False, verbose_name='National or regional?'),
        ),
    ]
