# Generated by Django 2.2.2 on 2019-10-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191030_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='impacts_if_not_approved',
            new_name='notes',
        ),
    ]
