# Generated by Django 2.1.4 on 2019-01-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_section_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='overtime_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
