# Generated by Django 2.2.2 on 2019-10-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191030_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='metadata_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Provide link to existing metadata record, if available'),
        ),
        migrations.AlterField(
            model_name='project',
            name='regional_dm_needs',
            field=models.TextField(blank=True, null=True, verbose_name='Describe assistance required from the branch data manager, if applicable'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sectional_dm_needs',
            field=models.TextField(blank=True, null=True, verbose_name='Describe assistance required from the section data manager, if applicable'),
        ),
    ]
