# Generated by Django 2.2.2 on 2019-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20191030_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Program2', verbose_name='Science regional program name(s)'),
        ),
    ]
