# Generated by Django 2.2.2 on 2019-11-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20191106_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='program2',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
