# Generated by Django 2.2.2 on 2019-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190605_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_responsibility_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('national_responsibility_fra', models.CharField(blank=True, max_length=255, null=True)),
                ('program_inventory', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_source_and_type', models.CharField(blank=True, max_length=255, null=True)),
                ('regional_program_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('regional_program_name_fra', models.CharField(blank=True, max_length=255, null=True)),
                ('examples', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['national_responsibility_eng', 'regional_program_name_eng'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
