# Generated by Django 2.2.2 on 2020-06-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_auto_20200526_2100'),
        ('projects', '0012_auto_20200526_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.FundingSource'),
        ),
        migrations.AddField(
            model_name='project',
            name='recommended_for_funding',
            field=models.BooleanField(default=False, verbose_name='recommended'),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_funding_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='projects.FundingSource', verbose_name='primary funding source'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.ForeignKey(blank=True, default=2022, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='shared_models.FiscalYear', verbose_name='fiscal year'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='student_program',
            field=models.IntegerField(blank=True, choices=[(1, 'FSWEP'), (2, 'Coop')], null=True, verbose_name='student program'),
        ),
        migrations.AlterUniqueTogether(
            name='fundingsource',
            unique_together={('funding_source_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('funding_source', 'functional_group'), ('section', 'functional_group')},
        ),
    ]
