# Generated by Django 2.2.2 on 2019-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_program2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program2',
            field=models.ManyToManyField(blank=True, to='projects.Program2', verbose_name='Linkage to Science programs'),
        ),
    ]
