# Generated by Django 2.2.2 on 2019-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190702_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.Tag', verbose_name='Tags / keywords'),
        ),
    ]
