# Generated by Django 2.2.2 on 2019-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0025_region_head'),
        ('projects', '0015_auto_20191216_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicgroup',
            name='sections',
            field=models.ManyToManyField(to='shared_models.Section'),
        ),
    ]
