# Generated by Django 2.2.2 on 2019-12-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_thematicgroup_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='program',
        ),
    ]
