# Generated by Django 2.2.2 on 2020-06-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('projects', '0013_auto_20200616_1822'),
        ('projects', '0013_upcomingdate'),
        ('projects', '0016_referencematerial'),
    ]

    operations = [
    ]
