# Generated by Django 3.1.2 on 2020-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20201029_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_hidden',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], default=False, null=True, verbose_name='Should the project be hidden from other users?'),
        ),
    ]
