# Generated by Django 2.2.2 on 2019-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20190702_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='exclude_from_rollup',
            field=models.BooleanField(default=False),
        ),
    ]
