# Generated by Django 2.2.2 on 2019-12-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20191216_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funding_sources',
        ),
        migrations.AddField(
            model_name='project',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.ActivityType', verbose_name='activity_type'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_funding_source',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.FundingSource', verbose_name='default funding source'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_instances', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
