# Generated by Django 2.2.2 on 2019-09-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_employeetype_exclude_from_rollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('eng_text', models.CharField(max_length=1000)),
                ('fra_text', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
    ]
