# Generated by Django 2.1.4 on 2019-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_employeetype_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.NullBooleanField(default=False, verbose_name='Has this project already been approved?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priorities',
            field=models.TextField(blank=True, null=True, verbose_name='Project-specific priorities in 2019/2020 (e.g., what will be the project emphasis in this fiscal year?)'),
        ),
    ]
