# Generated by Django 2.2.2 on 2020-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200107_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
