# Generated by Django 2.1.4 on 2019-01-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_section_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='division',
        ),
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='projects.Section', verbose_name='section (Division)'),
        ),
    ]
