# Generated by Django 2.2.2 on 2019-10-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20191002_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['used_for', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='used_for',
            field=models.IntegerField(choices=[(1, 'Projects'), (2, 'Status reports')]),
        ),
    ]
