# Generated by Django 2.2.2 on 2019-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20191002_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='major_accomplishments',
            field=models.TextField(blank=True, null=True, verbose_name='major accomplishments (leave blank if using milestones)'),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='major_issues',
            field=models.TextField(blank=True, null=True, verbose_name='major issues encountered'),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='rationale_for_modified_completion_date',
            field=models.TextField(blank=True, null=True, verbose_name='rationale for a modified completion date'),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='target_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='target completion date'),
        ),
    ]
