# Generated by Django 2.1.4 on 2019-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20190218_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
