# Generated by Django 2.2.2 on 2020-01-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200108_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.FunctionalGroup', verbose_name='Functional group'),
        ),
    ]
