# Generated by Django 3.1.2 on 2020-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20201105_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='other_lab_support_needs',
            field=models.TextField(blank=True, null=True, verbose_name='Describe laboratory requirements relevant for project planning purposes.'),
        ),
    ]
