# Generated by Django 3.1.2 on 2020-11-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20201105_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='notification_email_sent',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Notification Email Sent'),
        ),
    ]
