# Generated by Django 2.2.2 on 2020-01-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_delete_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program2',
            new_name='Program',
        ),
    ]
