# Generated by Django 2.2.2 on 2020-01-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20200108_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='regional_dm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sectional_dm',
        ),
    ]
