# Generated by Django 2.2.2 on 2019-10-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20191003_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='caption',
        ),
    ]
