# Generated by Django 2.1.4 on 2019-02-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20190218_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='gccost',
            name='funding_source',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gc_costs', to='projects.FundingSource', verbose_name='funding source'),
        ),
    ]
