# Generated by Django 2.2.2 on 2020-01-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20200109_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='projects.FunctionalGroup', verbose_name='Functional group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='meeting_notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes / comments'),
        ),
    ]
