# Generated by Django 2.2.2 on 2019-10-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20191003_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='status',
        ),
    ]
