# Generated by Django 2.2.2 on 2020-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20200110_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Tag', verbose_name='Tags / keywords (used for searching)'),
        ),
    ]
