# Generated by Django 2.1.4 on 2019-02-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0026_auto_20190204_0936'),
        ('projects', '0033_staff_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_allotment_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects', to='scifi.AllotmentCode'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects', to='scifi.BusinessLine'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_line_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects', to='scifi.LineObject'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_responsibility_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects', to='scifi.ResponsibilityCenter'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lead',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False, verbose_name='project lead'),
        ),
    ]
