# Generated by Django 2.1.4 on 2019-02-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20190219_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='default_allotment_code',
            new_name='allotment_code',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='default_business_line',
            new_name='business_line',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='default_line_object',
            new_name='line_object',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='default_responsibility_center',
            new_name='responsibility_center',
        ),
    ]
