# Generated by Django 2.2.2 on 2020-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0026_auto_20200107_1614'),
        ('projects', '0035_auto_20200114_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='executive summary'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('section', 'functional_group')},
        ),
    ]
