# Generated by Django 2.2.2 on 2019-10-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20191003_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.StatusReport'),
        ),
    ]
