# Generated by Django 2.2.2 on 2019-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20191003_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Program2', verbose_name='linkage to Science programs'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Tag', verbose_name='Tags / keywords'),
        ),
    ]
