# Generated by Django 2.1.4 on 2019-02-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20190225_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='fiscal_year2',
            new_name='year',
        ),
    ]
