# Generated by Django 2.1.4 on 2019-03-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20190226_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='abbrev',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='abbrev',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='projects.Division'),
        ),
    ]
