# Generated by Django 2.2.2 on 2020-01-24 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='TripRequest',
        ),
    ]
