# Generated by Django 2.2.2 on 2019-10-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_group_trip',
            field=models.BooleanField(default=False, verbose_name='Is this a group trip (i.e., is this a request for multiple individuals)?'),
        ),
    ]
