# Generated by Django 3.1.2 on 2021-02-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20210224_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultreviewer',
            old_name='special_roles',
            new_name='special_role',
        ),
    ]
