# Generated by Django 2.2.2 on 2020-02-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_triprequest_exclude_from_travel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_requests', to='shared_models.Section', verbose_name='DFO section'),
        ),
    ]
