# Generated by Django 3.1.2 on 2021-03-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20210305_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='travellercost',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='travel.traveller', verbose_name='traveller'),
        ),
    ]
