# Generated by Django 2.2.2 on 2020-02-28 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20200225_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='original_submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='original submission date'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_leads', to='shared_models.Region', verbose_name='Which region is the lead on this trip?'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location',
            field=models.CharField(max_length=1000, null=True, verbose_name='location (city, province, country)'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date submitted'),
        ),
    ]
