# Generated by Django 2.1.4 on 2019-03-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20190312_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Purpose', verbose_name='rurpose of travel'),
        ),
        migrations.AddField(
            model_name='event',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Reason', verbose_name='reason for travel'),
        ),
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Role', verbose_name='role of participant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='accommodations',
            field=models.FloatField(blank=True, null=True, verbose_name='accommodation costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='air',
            field=models.FloatField(blank=True, null=True, verbose_name='air fare costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='incidentals',
            field=models.FloatField(blank=True, null=True, verbose_name='incidental costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=1000, verbose_name='location (e.g., city, province, country)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meals',
            field=models.FloatField(blank=True, null=True, verbose_name='meal costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='other',
            field=models.FloatField(blank=True, null=True, verbose_name='other costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='other_transport',
            field=models.FloatField(blank=True, null=True, verbose_name='other transport costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='personal_motor_vehicle',
            field=models.FloatField(blank=True, null=True, verbose_name='personal motor vehicles costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rail',
            field=models.FloatField(blank=True, null=True, verbose_name='rail costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rental_motor_vehicle',
            field=models.FloatField(blank=True, null=True, verbose_name='rental motor vehicles costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='taxi',
            field=models.FloatField(blank=True, null=True, verbose_name='taxi costs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='total trip cost'),
        ),
    ]
