# Generated by Django 3.1.2 on 2021-01-26 16:42

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20210126_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('file_en', models.FileField(upload_to=travel.models.ref_mat_directory_path, verbose_name='file attachment (English)')),
                ('file_fr', models.FileField(blank=True, null=True, upload_to=travel.models.ref_mat_directory_path, verbose_name='file attachment (French)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
