# Generated by Django 2.2.2 on 2019-10-18 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0005_auto_20191018_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_events', to='travel.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('user', 'parent_event')},
        ),
    ]
