# Generated by Django 3.1.6 on 2021-04-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_auto_20210225_1538'),
        ('travel', '0005_auto_20210305_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, default=2022, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='shared_models.fiscalyear', verbose_name='fiscal year'),
        ),
    ]
