# Generated by Django 2.2.2 on 2020-04-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20200430_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultreviewer',
            old_name='branch',
            new_name='branchs',
        ),
        migrations.RenameField(
            model_name='defaultreviewer',
            old_name='section',
            new_name='sections',
        ),
    ]
