# Generated by Django 2.2.2 on 2020-04-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20200316_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, default=2021, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_requests', to='shared_models.FiscalYear', verbose_name='fiscal year'),
        ),
    ]
