# Generated by Django 3.1.2 on 2021-01-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20210126_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencematerial',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='referencematerial',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
