# Generated by Django 2.2.2 on 2020-01-24 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0007_auto_20200124_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ['trip_request', 'order']},
        ),
        migrations.RenameField(
            model_name='reviewer',
            old_name='trip',
            new_name='trip_request',
        ),
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together={('trip_request', 'user', 'role')},
        ),
    ]
