# Generated by Django 3.2 on 2021-05-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_triprequest_objective_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='travel.triprequest'),
        ),
    ]
