# Generated by Django 3.2.4 on 2021-06-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_reviewer_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='needs_gov_vehicle',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Use of a government vehicle required?'),
        ),
    ]
