# Generated by Django 2.2.2 on 2020-05-14 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_conference_trip_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trippurpose',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='purpose',
            old_name='description_eng',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='purpose',
            old_name='description_fre',
            new_name='description_fr',
        ),
    ]
