# Generated by Django 2.1.4 on 2019-03-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20190312_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', 'last_name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='destination_location',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='conf_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='conf_start_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='departure_location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='departure location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Purpose', verbose_name='purpose of travel'),
        ),
    ]
