# Generated by Django 2.2.2 on 2019-10-24 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0010_auto_20191024_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='adm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_trips', to=settings.AUTH_USER_MODEL, verbose_name='ADM'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rdg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rdg_trips', to=settings.AUTH_USER_MODEL, verbose_name='RDG'),
        ),
    ]
