# Generated by Django 2.2.2 on 2020-05-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20200513_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(default='temp', max_length=100, verbose_name='name (eng)'),
            preserve_default=False,
        ),
    ]
