# Generated by Django 2.2.2 on 2019-10-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20191011_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approver_approval_status',
            field=models.ForeignKey(default=1, limit_choices_to={'used_for': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver_trips', to='travel.Status', verbose_name='expenditure initiation approval status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recommender_1_approval_status',
            field=models.ForeignKey(default=1, limit_choices_to={'used_for': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rec1_trips', to='travel.Status', verbose_name='recommender 1 approval status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recommender_2_approval_status',
            field=models.ForeignKey(default=1, limit_choices_to={'used_for': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rec2_trips', to='travel.Status', verbose_name='recommender 2 approval status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recommender_3_approval_status',
            field=models.ForeignKey(default=1, limit_choices_to={'used_for': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rec3_trips', to='travel.Status', verbose_name='recommender 3 approval status'),
        ),
    ]
