# Generated by Django 3.1.2 on 2021-02-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20210210_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.IntegerField(choices=[(30, 'Unverified'), (31, 'Under review'), (32, 'Reviewed'), (41, 'Verified'), (43, 'Cancelled')], default=30, editable=False, verbose_name='trip status'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.IntegerField(choices=[(8, 'Draft'), (10, 'Denied'), (11, 'Approved'), (12, 'Pending Recommendation'), (14, 'Pending ADM Approval'), (15, 'Pending RDG Approval'), (16, 'Changes Requested'), (17, 'Pending Review'), (22, 'Cancelled')], default=8, verbose_name='trip request status'),
        ),
    ]
