# Generated by Django 2.2.2 on 2020-01-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20200124_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='shared_models.FiscalYear', verbose_name='fiscal year'),
        ),
    ]
