# Generated by Django 2.2.2 on 2019-10-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20191015_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_denied',
            field=models.BooleanField(default=False, verbose_name='is this trip approved'),
        ),
    ]
