# Generated by Django 2.1.4 on 2019-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20190313_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='funding_source',
            field=models.TextField(blank=True, null=True, verbose_name='funding source'),
        ),
    ]
