# Generated by Django 2.2.2 on 2020-05-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20200513_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
