# Generated by Django 3.1.2 on 2021-02-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20210210_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreviewer',
            name='role',
            field=models.IntegerField(choices=[(1, 'Reviewer'), (2, 'Recommender'), (3, 'NCR Travel Coordinators'), (4, 'ADM Recommender'), (5, 'ADM'), (6, 'RDG')], verbose_name='role'),
        ),
    ]
