# Generated by Django 2.2.2 on 2020-05-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_auto_20200513_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerrole',
            name='name',
            field=models.CharField(default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewerrole',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
