# Generated by Django 3.1.2 on 2021-02-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_auto_20210210_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='destination',
        ),
    ]
