# Generated by Django 2.2.2 on 2020-02-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_auto_20200203_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='njcrates',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='triprequestcost',
            name='number_of_days',
            field=models.FloatField(blank=True, null=True, verbose_name='number of days'),
        ),
        migrations.AlterField(
            model_name='triprequestcost',
            name='rate_cad',
            field=models.FloatField(blank=True, null=True, verbose_name='daily rate (CAD/day)'),
        ),
    ]
