# Generated by Django 2.2.2 on 2020-05-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_remove_conference_trip_purpose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripSubPurpose',
            new_name='TripSubcategory',
        ),
    ]
