# Generated by Django 2.2.2 on 2019-11-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_auto_20191106_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='event',
            new_name='is_conference',
        ),
    ]
