# Generated by Django 3.1.2 on 2021-02-11 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0020_auto_20210211_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triprequest1',
            old_name='lead',
            new_name='created_by',
        ),
    ]
