# Generated by Django 2.2.2 on 2019-11-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_auto_20191106_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='registered_event',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
