# Generated by Django 2.2.2 on 2019-11-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_auto_20191106_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='registered_event',
            new_name='conference',
        ),
    ]
