# Generated by Django 2.2.2 on 2020-05-14 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_auto_20200513_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='trip_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='travel.TripSubcategory', verbose_name='trip purpose'),
        ),
        migrations.AlterField(
            model_name='tripsubcategory',
            name='trip_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='travel.TripCategory'),
        ),
    ]
