# Generated by Django 2.2.2 on 2019-11-07 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0025_trip_is_international'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ['trip', 'order']},
        ),
        migrations.AddField(
            model_name='reviewer',
            name='trip',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewers', to='travel.Trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date of travel'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='is_international',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='is this an international trip OR are international travellers included in this request?'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='shared_models.Region', verbose_name='DFO region'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='section',
            field=models.ForeignKey(limit_choices_to={'division__branch': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Section', verbose_name='DFO section'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='start date of travel'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together={('trip', 'user', 'role')},
        ),
    ]
