# Generated by Django 3.1.2 on 2021-02-18 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_auto_20210217_1303'),
        ('travel', '0027_auto_20210217_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_leads', to='shared_models.region', verbose_name='Which region is the lead on this trip?'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travellers', to='travel.triprequest1'),
        ),
        migrations.AlterField(
            model_name='triprequestcost',
            name='trip_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_request_costs', to='travel.triprequest', verbose_name='trip request'),
        ),
    ]
