# Generated by Django 2.2.2 on 2019-11-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_auto_20191107_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='travel.Trip'),
        ),
    ]
