# Generated by Django 2.2.2 on 2020-06-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_tripcategory_days_when_eligible_for_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='multiple_attendee_rationale',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='purpose',
        ),
        migrations.AddField(
            model_name='defaultreviewer',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
