# Generated by Django 2.2.2 on 2019-11-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_auto_20191108_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='public_servant',
            new_name='is_public_servant',
        ),
    ]
