# Generated by Django 3.1.2 on 2021-02-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_auto_20210217_1303'),
        ('travel', '0032_auto_20210222_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest1',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='unique identifier'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_leads', to='shared_models.region', verbose_name='Which region is the lead on this trip?'),
        ),
    ]
