# Generated by Django 2.2.2 on 2020-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_processstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, 'Travel Request Process Overview'), (2, 'Review Process Overview')], null=True),
        ),
    ]
