# Generated by Django 2.2.2 on 2020-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_processstep_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, 'Travel request process outline'), (2, 'Review process outline')], null=True),
        ),
    ]
