# Generated by Django 2.2.2 on 2020-06-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('travel', '0034_auto_20200616_1823'),
        ('travel', '0034_auto_20200615_1553'),
        ('travel', '0035_remove_triprequest_reason'),
    ]

    operations = [
    ]
