# Generated by Django 2.2.2 on 2019-11-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0025_region_head'),
        ('travel', '0042_auto_20191126_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='event_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_leads', to='shared_models.Region', verbose_name='Regional event lead'),
        ),
        migrations.AddField(
            model_name='conference',
            name='has_event_template',
            field=models.NullBooleanField(default=False, verbose_name='Is there an event template being completed for this conference or meeting?'),
        ),
    ]
