# Generated by Django 3.1.2 on 2020-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0043_auto_20201130_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, 'Travel Request Process Outline'), (2, 'Review Process Outline')], null=True),
        ),
    ]
