# Generated by Django 2.2.2 on 2019-11-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0025_region_head'),
        ('travel', '0043_auto_20191126_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='event_lead',
        ),
        migrations.AddField(
            model_name='conference',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_leads', to='shared_models.Region', verbose_name='Which region is taking the lead?'),
        ),
    ]
