# Generated by Django 2.2.2 on 2019-11-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0044_auto_20191126_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='is_international',
            new_name='is_adm_approval_required',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='event_lead',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='has_event_template',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_conference',
        ),
    ]
