# Generated by Django 2.2.2 on 2019-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0046_auto_20191126_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='meals',
        ),
        migrations.AddField(
            model_name='trip',
            name='breakfasts',
            field=models.FloatField(blank=True, null=True, verbose_name='meals'),
        ),
        migrations.AddField(
            model_name='trip',
            name='lunches',
            field=models.FloatField(blank=True, null=True, verbose_name='meals'),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_breakfasts',
            field=models.FloatField(blank=True, null=True, verbose_name='meals'),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_lunches',
            field=models.FloatField(blank=True, null=True, verbose_name='meals'),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_suppers',
            field=models.FloatField(blank=True, null=True, verbose_name='meals'),
        ),
        migrations.AddField(
            model_name='trip',
            name='suppers',
            field=models.FloatField(blank=True, null=True, verbose_name='meals'),
        ),
    ]
