# Generated by Django 2.2.2 on 2019-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0047_auto_20191126_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='breakfasts',
            field=models.FloatField(blank=True, null=True, verbose_name='breakfast'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lunches',
            field=models.FloatField(blank=True, null=True, verbose_name='lunch'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='no_breakfasts',
            field=models.FloatField(blank=True, null=True, verbose_name='Number of breakfasts'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='no_lunches',
            field=models.FloatField(blank=True, null=True, verbose_name='Number of lunches'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='no_suppers',
            field=models.FloatField(blank=True, null=True, verbose_name='Number of suppers'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='suppers',
            field=models.FloatField(blank=True, null=True, verbose_name='supper'),
        ),
    ]
