# Generated by Django 2.2.2 on 2019-11-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0052_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='benefit_to_dfo',
            field=models.TextField(blank=True, null=True, verbose_name='benefit to DFO'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='departure location (city, province, country)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='destination location (city, province, country)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='optional notes'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='objective_of_event',
            field=models.TextField(blank=True, null=True, verbose_name='objective of the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='role_of_participant',
            field=models.TextField(blank=True, null=True, verbose_name='role of participant'),
        ),
    ]
