# Generated by Django 2.2.2 on 2019-11-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0054_conference_is_adm_approval_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_adm_approval_required',
        ),
    ]
