# Generated by Django 2.2.2 on 2019-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0055_remove_trip_is_adm_approval_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='abstract_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='abstract submission deadline'),
        ),
        migrations.AddField(
            model_name='conference',
            name='meeting_url',
            field=models.URLField(blank=True, null=True, verbose_name='meeting URL'),
        ),
        migrations.AddField(
            model_name='conference',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='general notes'),
        ),
        migrations.AddField(
            model_name='conference',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registration deadline'),
        ),
    ]
