# Generated by Django 2.2.2 on 2020-01-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0026_auto_20200107_1614'),
        ('travel', '0059_auto_20200110_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conferences', to='shared_models.FiscalYear', verbose_name='fiscal year'),
        ),
    ]
