# Generated by Django 3.1.2 on 2020-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='acronyms_defined',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: Acronyms are defined upon first use'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='activities_elibigle',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: All Activities/tasks are eligible'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='amounts_correct',
            field=models.BooleanField(default=False, verbose_name='The annual contribution amount(s) (3.1) match(es) the budget in Schedule 5 and do(es) not exceed the amount(s) approved by the Minister'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='budget_adds_up',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: The budget adds up correctly.'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='budget_reflects_activity',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: The budget reflects the nature of the Activity(ies).'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='cashflow_adds_up',
            field=models.BooleanField(default=False, verbose_name='Schedule 6: The cash flow adds up correctly and reflects the timing of Activities.'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='clear_language',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: Language is clear, concise and can be generally understood by someone who is not a specialist'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='confirmation_letters_2_path',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: Confirmation letters for all confirmed cash support have been posted to PATH.  Confirmation letters for large amount/potentially inflated in-kind support have also been posted to PATH.'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='conflict_of_interest_assessed',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: If a current or former federal public servant is involved in the project, a conflict of interest assessment has been completed (conflict of interest assessment tool found in CA checklist folder in national shared folder) and conflicts, if any, have been addressed, as appropriate.'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='correct_clause_selected',
            field=models.BooleanField(default=False, verbose_name='The clauses selected in the CA reflect the risk level and contribution amount'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='deliverables',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: All Activities/tasks have associated deliverables that will demonstrate that the former were completed as planned and as budgeted'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='detail_commensurate_with_budget',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: The level of detail for each Activity (i.e., task description) is commensurate with its budget'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='expenses_eligible',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: All expenses are eligible'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='financial_information_2_path',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: Financial information has been updated/entered in PATH as per Data Entry Procedures'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='formatting_correct',
            field=models.BooleanField(default=False, verbose_name='There are no hanging/orphan lines/titles'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='key_tasks_outlined',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: All key tasks required to be undertaken for each Activity to be achieved are outlined'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='maximum_amounts_set',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: If applicable, maximum amounts for expense categories have been set (i.e., identified with an asterisk (*)).'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='no_funding_redundancy',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: The activities and budget items have been cross-checked against DFO Aboriginal program CAs (e.g., SPI-FHRI, AAROM, AFSAR) to ensure no funding redundancy.'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='performance_measures_in_path',
            field=models.BooleanField(default=False, verbose_name='Schedule 7: Performance measures are updated in the ‘Planned’ column of the performance tab in PATH as per Data Entry Procedures'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='pre_filled_sched7',
            field=models.BooleanField(default=False, verbose_name='Schedule 7: is pre-filled and mirrors Schedule 5'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='project_budgets_adds_up',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: The sum of all individual project Activity budgets adds up to the agreement total'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='realistic_timeframe',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: Each Activity can be reasonably expected to be completed within its accorded timeframe'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='reasonable_costs',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: All costs are reasonable'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='risk_assessment_complete',
            field=models.BooleanField(default=False, verbose_name='The risk assessment has been completed/approved and posted to PATH'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='stacking_identified',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: Funding directly related to the RFCPP project coming from DFO Aboriginal programs has been included in the federal and stacking support.'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='stacking_limits_respected',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: The federal and stacking limit have been respected, based on confirmed funding.'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='sufficient_budget_detail',
            field=models.BooleanField(default=False, verbose_name='Schedule 5: Sufficient budget details have been provided to confirm that the costs are eligible and reasonable'),
        ),
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='team_leader_reviewed',
            field=models.BooleanField(default=False, verbose_name='The Team Leader has reviewed and approves the CA'),
        ),
        migrations.AlterField(
            model_name='expressionofinterest',
            name='project_eligible',
            field=models.BooleanField(default=False, verbose_name='is the project eligible?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='materials_submitted',
            field=models.BooleanField(default=False, verbose_name='were all necessary materials submitted?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='has the payment been confirmed?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='submission_accepted',
            field=models.BooleanField(default=False, verbose_name='was the submission accepted?'),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='funding_recovery_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='funds_recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='lapsing_funds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='accurate_reporting_period',
            field=models.BooleanField(default=False, verbose_name='Reporting period: Where this is the first report submitted by a recipient under the CA, the reporting period commences on the day that RFCPP-funded activities first started taking place.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='actuals_entered',
            field=models.BooleanField(default=False, verbose_name='All financial information has been entered in the ‘Actual’ section of the financial tab in PATH.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='budgeted_amounts_not_exceeded',
            field=models.BooleanField(default=False, verbose_name='Claimed expenses for expense categories tagged with an asterisk (*) do not exceed the budgeted amount.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='compliant_signage',
            field=models.BooleanField(default=False, verbose_name='RFCPP signage follows the RFCPP-FIP Guidelines'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='confirmation_letters',
            field=models.BooleanField(default=False, verbose_name='Confirmation letters for all previously unconfirmed cash support and large in-kind support have been received and posted to PATH (applies to multi-year agreements with supplemental conditions for unconfirmed support).'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='deliverables_check_out',
            field=models.BooleanField(default=False, verbose_name='The status of deliverables matches the claimed expenses and timing of Activities in Schedule 5.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='invoices_check_out',
            field=models.BooleanField(default=False, verbose_name='Where invoices were provided as deliverables, the total(s) of the invoices match what is reported/claimed in Section 1, Table 1.1.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='matching_funds',
            field=models.BooleanField(default=False, verbose_name='The “RFCPP funds received year to date” matches the amount in RFCPP records.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='no_missing_period',
            field=models.BooleanField(default=False, verbose_name='Reporting period: Where a previous report has been submitted by the recipient under the CA, the reporting period for this report commences the day after the end of the previous reporting period.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='reimbursable_taxes_not_claimed',
            field=models.BooleanField(default=False, verbose_name='Reimbursable taxes have not been claimed (see application form for percentages reimbursable).'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='sched6_to_path',
            field=models.BooleanField(default=False, verbose_name='If a multi-year agreement, Schedule 6 for next year has been received and posted to PATH.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='sched7_to_path',
            field=models.BooleanField(default=False, verbose_name='Schedule 7 and all supporting documents (e.g., deliverables) have been posted to PATH.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='section3_path_recored',
            field=models.BooleanField(default=False, verbose_name='All information provided in Section 3 has been recorded in PATH (for final/annual reports only).'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='section4_signed',
            field=models.BooleanField(default=False, verbose_name='Section 4 has been signed by an authorised representative of the Recipient (does not need to be the CA signatory).'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='site_visit_summary_provided',
            field=models.BooleanField(default=False, verbose_name='If a site visit was completed for the CA, a summary thereof is provided in the comments section below.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='sounds_sched7',
            field=models.BooleanField(default=False, verbose_name='Schedule 7 matches the one in the signed CA and all sections have been duly filled in.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='sufficient_detail',
            field=models.BooleanField(default=False, verbose_name='The quality/level of detail of the deliverables provided is sufficient to recommend payment under s. 34 of the Financial Administration Act (i.e., sufficient information has been provided to justify payment).'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='summed_correctly',
            field=models.BooleanField(default=False, verbose_name='Amounts in Table 1.1 are summed correctly.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='support_matches',
            field=models.BooleanField(default=False, verbose_name='Support received matches what was detailed in the CA. If different, then no effect on federal and stacking limits has been confirmed.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='tab11_no_issues',
            field=models.BooleanField(default=False, verbose_name='The amounts reported in Table 1.1 raise no issues and align with the timing of Activities in Schedule 5 and the reporting period.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='tab12_filled',
            field=models.BooleanField(default=False, verbose_name='Table 1.2 has been filled in where budgeted amounts exceed the allowed deviation: a) If the deviation was previously approved by DFO: no action required. b) If the deviation was not previously approved by DFO: review the reason for the deviation and recommend to NHQ (when submitting the report for payment) whether or not the over-expenditure(s) should be reimbursed.  Whether the over-expenditures are reimbursed or not, the recipient must be informed that as per the CA (Sch. 5 s. 6.3) requests for budget reallocations in excess of the set percentage must be submitted to DFO prior to deviating from planned expenditures.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='tab22_complete',
            field=models.BooleanField(default=False, verbose_name='Where Table 2.2 has been filled in: a) Determine whether the explanation may impact the payment amount being requested by the recipient - address with NHQ when submitting the report for payment. b) Determine whether an amendment may be required – address with NHQ when submitting the report for payment (does not apply to final reports). c) Determine whether as a result of cancelled/delayed activities the stacking limit may be exceeded.  If so, the recipient must confirm the actual amounts received from other sources.  If the stacking limit was/will be exceeded, the RFCPP recommended payment must be reduced accordingly to ensure that the staking limit is met.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='tab31_actuals',
            field=models.BooleanField(default=False, verbose_name='The “actuals” in Table 3.1 align with the activities and budget table.'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='tab32_complete',
            field=models.BooleanField(default=False, verbose_name='All capital acquisitions purchased have been included in Table 3.2 (and align with the costs identified in the budget table).'),
        ),
        migrations.AlterField(
            model_name='reportchecklist',
            name='team_leader_reviewed',
            field=models.BooleanField(default=False, verbose_name='The Team Leader has reviewed and approved the recipient report and recommends payment.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c1',
            field=models.BooleanField(default=False, verbose_name='C.1 Was the work completed as proposed in the CA (activities/tasks, timing and budget)? If not, is an amendment or note-to-file required? Provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c10',
            field=models.BooleanField(default=False, verbose_name='C.10 Are there concerns with any aspect of the work? If yes, provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c11',
            field=models.BooleanField(default=False, verbose_name='C.11 Were any suggestions made for future projects? If yes, provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c2',
            field=models.BooleanField(default=False, verbose_name='C.2 Are there any challenges affecting delivery of the project (e.g., contractors/personnel issues, required permits, site conditions)? If so, provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c3',
            field=models.BooleanField(default=False, verbose_name='C.3 Was the sign installed?  If not, provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c4',
            field=models.BooleanField(default=False, verbose_name='C.4 Were photos taken? If so, ensure that photos are posted to PATH.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c5',
            field=models.BooleanField(default=False, verbose_name='C.5 Is a follow up site visit (or other follow-up) required? If yes, describe reasons for requiring follow-up, the type of follow-up, and when it is to occur.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c6',
            field=models.BooleanField(default=False, verbose_name='C.6 Does the group have any feedback on the Program (positive feedback or suggested improvements)?  Provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c7',
            field=models.BooleanField(default=False, verbose_name='C.7 Were the structure(s)/works designed/installed properly?  If not, provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c8',
            field=models.BooleanField(default=False, verbose_name='C.8 Did the work address the key issues at the site / is it functioning as intended? If not, provide details.'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='c9',
            field=models.BooleanField(default=False, verbose_name='C.9 Are recreational fish using the site/have access to the site?'),
        ),
    ]
