# Generated by Django 3.1.2 on 2021-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='province',
            new_name='province_state',
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Name'),
        ),
    ]
