# Generated by Django 3.1.2 on 2021-02-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_auto_20210126_1540'),
        ('spot', '0002_auto_20210223_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesused',
            name='analysis_program',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='databases', to='spot.analysisprogramused', verbose_name='analysis program used'),
        ),
        migrations.AlterField(
            model_name='databasesused',
            name='data_format',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_format', to='spot.dataformat', verbose_name='data format'),
        ),
        migrations.AlterField(
            model_name='databasesused',
            name='data_quality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_quality', to='spot.dataquality', verbose_name='data quality'),
        ),
        migrations.AlterField(
            model_name='databasesused',
            name='database',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='database', to='spot.database', verbose_name='database'),
        ),
        migrations.AlterField(
            model_name='databasesused',
            name='models_used',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='models_used', to='spot.modelsused', verbose_name='models used'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='FN_communications',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='spot.fncommunications', verbose_name='FN communications'),
        ),
        migrations.AlterField(
            model_name='method',
            name='database',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='method_database', to='spot.database', verbose_name='database'),
        ),
        migrations.AlterField(
            model_name='method',
            name='document_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_category', to='spot.documentcategory', verbose_name='document category'),
        ),
        migrations.AlterField(
            model_name='method',
            name='document_topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_topic', to='spot.documenttopic', verbose_name='document topic'),
        ),
        migrations.AlterField(
            model_name='method',
            name='form_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_category', to='spot.formcategory', verbose_name='form category'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='method_category', to='spot.methodcategory', verbose_name='method category'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='method_type', to='spot.specificmethodtype', verbose_name='specific method type'),
        ),
        migrations.AlterField(
            model_name='method',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='methods', to='shared_models.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='data_quality_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_quality_level', to='spot.dataqualitylevel', verbose_name='data quality level'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='data_quality_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_quality_type', to='spot.dataqualitytype', verbose_name='data quality type'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objective_category', to='spot.objectivecategory', verbose_name='Objective Category'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='outcomes_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outcomes_category', to='spot.outcomecategory', verbose_name='outcomes category'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='outcomes_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outcomes_contact', to='spot.person', verbose_name='Outcomes Contact'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='salmon_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salmon_stage', to='spot.salmonstage', verbose_name='salmon stage'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='sample_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_type', to='spot.sampletype', verbose_name='sample type/specific data item'),
        ),
    ]
