# Generated by Django 3.1.2 on 2021-01-06 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_auto_20201029_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectyear',
            name='expenditure_initiation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 1, 0, 0), null=True),
        ),
    ]
