# Generated by Django 3.1.2 on 2021-07-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_auto_20210714_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='salmon_life_cycle',
            field=models.CharField(blank=True, default=None, max_length=32, verbose_name='salmon life cycle'),
        ),
    ]
