# Generated by Django 3.2.5 on 2021-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Name'),
        ),
    ]
