# Generated by Django 3.1.2 on 2021-10-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_auto_20211019_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectivedatatypequality',
            options={'ordering': ['sampling_outcome']},
        ),
        migrations.AlterModelOptions(
            name='objectiveoutcome',
            options={'ordering': ['report_link']},
        ),
        migrations.RemoveField(
            model_name='objectivedatatypequality',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='objectiveoutcome',
            name='outcome_category',
        ),
        migrations.RemoveField(
            model_name='objectiveoutcome',
            name='report_reference',
        ),
        migrations.AddField(
            model_name='objectivedatatypequality',
            name='sampling_outcome',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Sampling Outcome'),
        ),
        migrations.AddField(
            model_name='objectiveoutcome',
            name='outcome_delivered',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Was the outcome deliverable met?'),
        ),
        migrations.AddField(
            model_name='objectiveoutcome',
            name='report_link',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Report Link'),
        ),
        migrations.AddField(
            model_name='objectiveoutcome',
            name='reporting_outcome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reporting Outcome'),
        ),
        migrations.AlterField(
            model_name='objectivedatatypequality',
            name='outcome_delivered',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Was the Sampling Outcome Met?'),
        ),
    ]
