# Generated by Django 3.1.2 on 2022-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_auto_20220119_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cu_index',
            field=models.ManyToManyField(blank=True, to='spot.CUIndex', verbose_name='CU Index'),
        ),
    ]
