# Generated by Django 3.1.2 on 2021-10-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_auto_20211019_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['species']},
        ),
        migrations.RemoveField(
            model_name='data',
            name='samples_data_database',
        ),
        migrations.RemoveField(
            model_name='data',
            name='species_data',
        ),
        migrations.AddField(
            model_name='data',
            name='samples_collected_database',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Sample Collected Database'),
        ),
        migrations.AddField(
            model_name='data',
            name='species',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='method',
            name='knowledge_consideration',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Traditional Ecological Knowledge Consideration'),
        ),
        migrations.AddField(
            model_name='reports',
            name='published',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Was this report Published?'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, to='spot.River', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='objectiveoutcome',
            name='report_link',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spot.reports', verbose_name='Report Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='DFO_technicians',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DFO_technicians', to='spot.person', verbose_name='DFO Technicians/Biologists'),
        ),
    ]
