# Generated by Django 3.1.2 on 2021-07-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_auto_20210714_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_purpose',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='project purpose'),
        ),
    ]
