# Generated by Django 3.1.2 on 2021-07-17 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spot', '0004_auto_20210714_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgreementDatabase',
        ),
        migrations.DeleteModel(
            name='AgreementStatus',
        ),
        migrations.DeleteModel(
            name='AgreementType',
        ),
        migrations.DeleteModel(
            name='CapacityBuilding',
        ),
        migrations.DeleteModel(
            name='CoreComponent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CUIndex',
        ),
        migrations.DeleteModel(
            name='CUName',
        ),
        migrations.DeleteModel(
            name='DataAnalysisMethodType',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.DeleteModel(
            name='DataCheckEntryBarrier',
        ),
        migrations.DeleteModel(
            name='DataCommunicationRecipient',
        ),
        migrations.DeleteModel(
            name='DataEntryMethodType',
        ),
        migrations.DeleteModel(
            name='DataFormat',
        ),
        migrations.DeleteModel(
            name='DataProducts',
        ),
        migrations.DeleteModel(
            name='DataProgram',
        ),
        migrations.DeleteModel(
            name='DataPrograms',
        ),
        migrations.DeleteModel(
            name='DataQuality',
        ),
        migrations.DeleteModel(
            name='DataQualityLevel',
        ),
        migrations.DeleteModel(
            name='DataQualityType',
        ),
        migrations.DeleteModel(
            name='DataSubType',
        ),
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.DeleteModel(
            name='DFOLink',
        ),
        migrations.DeleteModel(
            name='EcoSystemType',
        ),
        migrations.DeleteModel(
            name='FieldWorkMethodType',
        ),
        migrations.DeleteModel(
            name='FisherySupportLink',
        ),
        migrations.DeleteModel(
            name='FNRelationshipLevel',
        ),
        migrations.DeleteModel(
            name='FundingAmount',
        ),
        migrations.DeleteModel(
            name='FundingSource',
        ),
        migrations.DeleteModel(
            name='LinkedGovernmentOrganizations',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='ModelsUsed',
        ),
        migrations.DeleteModel(
            name='MonitoringApproach',
        ),
        migrations.DeleteModel(
            name='ObjectiveCategory',
        ),
        migrations.DeleteModel(
            name='OrgType',
        ),
        migrations.DeleteModel(
            name='OutcomeBarrier',
        ),
        migrations.DeleteModel(
            name='OutcomeCategory',
        ),
        migrations.DeleteModel(
            name='OutcomeDeliverable',
        ),
        migrations.DeleteModel(
            name='OutcomeQuality',
        ),
        migrations.DeleteModel(
            name='PlanningMethodType',
        ),
        migrations.DeleteModel(
            name='ProjectClass',
        ),
        migrations.DeleteModel(
            name='ProjectComponent',
        ),
        migrations.DeleteModel(
            name='ProjectLeadOrganization',
        ),
        migrations.DeleteModel(
            name='ProjectPurpose',
        ),
        migrations.DeleteModel(
            name='ProjectStage',
        ),
        migrations.DeleteModel(
            name='ProjectStrategicLink',
        ),
        migrations.DeleteModel(
            name='ProjectSubType',
        ),
        migrations.DeleteModel(
            name='ProjectTheme',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='ReportClient',
        ),
        migrations.DeleteModel(
            name='ReportFormatProgramLevel',
        ),
        migrations.DeleteModel(
            name='ReportFormatProjectLevel',
        ),
        migrations.DeleteModel(
            name='ReportingMethodType',
        ),
        migrations.DeleteModel(
            name='ReportProblemAddressedContent',
        ),
        migrations.DeleteModel(
            name='ReportPurpose',
        ),
        migrations.DeleteModel(
            name='ReportSentTo',
        ),
        migrations.DeleteModel(
            name='ReportTimeline',
        ),
        migrations.DeleteModel(
            name='ReportTopicProgramLevel',
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='SalmonStage',
        ),
        migrations.DeleteModel(
            name='SampleBarrier',
        ),
        migrations.DeleteModel(
            name='SampleFormat',
        ),
        migrations.DeleteModel(
            name='SampleProcessingMethodType',
        ),
        migrations.DeleteModel(
            name='SamplesCollected',
        ),
        migrations.DeleteModel(
            name='SamplesCollectedDatabase',
        ),
        migrations.DeleteModel(
            name='SampleType',
        ),
        migrations.DeleteModel(
            name='SMUCode',
        ),
        migrations.DeleteModel(
            name='SMUName',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='StrategicAgreementLink',
        ),
        migrations.DeleteModel(
            name='SupportComponent',
        ),
        migrations.RemoveField(
            model_name='agreementlineage',
            name='funding_years',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_scale',
        ),
        migrations.AddField(
            model_name='objectivedatatypequality',
            name='date_last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified'),
        ),
        migrations.AddField(
            model_name='objectivedatatypequality',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='objectiveoutcome',
            name='date_last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified'),
        ),
        migrations.AddField(
            model_name='objectiveoutcome',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='watershed',
            name='group_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='group code'),
        ),
        migrations.AlterField(
            model_name='agreementlineage',
            name='agreement_database',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='agreement database'),
        ),
        migrations.AlterField(
            model_name='agreementlineage',
            name='agreement_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='agreement status'),
        ),
        migrations.AlterField(
            model_name='agreementlineage',
            name='agreement_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='agreement type '),
        ),
        migrations.AlterField(
            model_name='agreementlineage',
            name='funding_sources',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='funding sources'),
        ),
        migrations.AlterField(
            model_name='agreementlineage',
            name='project_lead_organization',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='project lead organization'),
        ),
        migrations.AlterField(
            model_name='data',
            name='barrier_data_check_entry',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Barriers to data checks/entry to database?'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_communication',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='how was data communicated to recipient'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_products',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='data products'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_products_database',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='data products database'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_programs',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='data programs'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_barrier',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='barriers to sample collection'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_format',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='sample format'),
        ),
        migrations.AlterField(
            model_name='data',
            name='samples_collected',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='sameples collected'),
        ),
        migrations.AlterField(
            model_name='data',
            name='samples_collected_database',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='samples collected database'),
        ),
        migrations.AlterField(
            model_name='data',
            name='species_data',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='species data'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, choices=[('PEOPLE', 'People'), ('PROJECTS', 'Projects'), ('OBJECTIVES', 'Objectives'), ('METHODS', 'Methods'), ('DATA', 'Data'), ('ORGANIZATIONS', 'Organizations'), ('OTHER', 'Other')], default=None, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='FN_communications',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='FN communications'),
        ),
        migrations.AlterField(
            model_name='method',
            name='data_entry_method_type',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='data entry method type'),
        ),
        migrations.AlterField(
            model_name='method',
            name='field_work_method_type',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='field work methods type/class'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_document_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='method document type'),
        ),
        migrations.AlterField(
            model_name='method',
            name='planning_method_type',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='planning method type'),
        ),
        migrations.AlterField(
            model_name='method',
            name='sample_processing_method_type',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='sample processing method type'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='activity',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='capacity_building',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='what capacity building did this project provide'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='key_element',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='key element'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Objective Category'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='outcome_barrier',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='barrier to achieve outcomes?'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='species',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='species'),
        ),
        migrations.AlterField(
            model_name='objectivedatatypequality',
            name='outcome_quality',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='quality of outcome'),
        ),
        migrations.AlterField(
            model_name='objectivedatatypequality',
            name='report_sent_to',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='reporting sent to'),
        ),
        migrations.AlterField(
            model_name='objectivedatatypequality',
            name='sample_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='sample type/specific data item'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='organization type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province/state'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province/state'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='DFO_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='other DFO project link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='core_component',
            field=models.CharField(blank=True, max_length=255, verbose_name='core component'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ecosystem_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='eco system type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='government_organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='government organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='monitoring_approach',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='monitoring approach'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_first_nations_contact_role',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='primary first nations contact role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='project purpose'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_stage',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='project stage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_sub_type',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='project sub type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_theme',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='project theme'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='project type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='project',
            name='salmon_life_cycle',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='salmon life cycle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='smu_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='SMU name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='species',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='target species'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supportive_component',
            field=models.CharField(blank=True, max_length=255, verbose_name='supportive component'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_timeline',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='report timeline'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='report type'),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='FNCommunications',
        ),
        migrations.DeleteModel(
            name='FundingYear',
        ),
        migrations.DeleteModel(
            name='MethodDocumentType',
        ),
        migrations.DeleteModel(
            name='ProjectScale',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
