# Generated by Django 3.2.13 on 2022-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_auto_20220621_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='knowledge_consideration',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='capacity_building',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='key_lesson',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='missed_opportunities',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='outcome_barrier',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='outcomes_contact',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, choices=[('', ''), ('People', 'People'), ('Projects', 'Projects'), ('Objectives', 'Objectives'), ('Methods', 'Methods'), ('Data', 'Data'), ('Organizations', 'Organizations'), ('Other', 'Other')], default=None, max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='element_title',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Element Title'),
        ),
    ]
