# Generated by Django 2.1.4 on 2019-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_project_eccc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
