# Generated by Django 3.1.2 on 2021-03-01 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_auto_20210301_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='FN_communications',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spot.fncommunications', verbose_name='FN communications'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spot.location', verbose_name='location'),
        ),
    ]
