# Generated by Django 2.2.2 on 2020-03-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_status_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='test',
        ),
    ]
