# Generated by Django 3.1.2 on 2021-10-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_auto_20211026_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectivedatatypequality',
            name='location',
        ),
        migrations.AddField(
            model_name='objectivedatatypequality',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, to='spot.River', verbose_name='Location'),
        ),
    ]
