# Generated by Django 2.2.2 on 2020-04-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0005_remove_status_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.ForeignKey(default=2022, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gc_projects', to='shared_models.FiscalYear'),
        ),
    ]
