# Generated by Django 3.1.2 on 2021-03-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0005_auto_20210301_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='sample_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_type', to='spot.sampletype', verbose_name='sample type/specific data item'),
        ),
    ]
