# Generated by Django 3.1.2 on 2022-02-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0006_auto_20220119_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleoutcome',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sampleoutcome',
            name='species',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='location',
        ),
        migrations.AddField(
            model_name='objective',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spot.river', verbose_name='Location'),
        ),
        migrations.RemoveField(
            model_name='objective',
            name='species',
        ),
        migrations.AddField(
            model_name='objective',
            name='species',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spot.species', verbose_name='Species'),
        ),
    ]
