# Generated by Django 2.1.4 on 2019-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0007_auto_20190506_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_abbrev',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
