# Generated by Django 3.1.2 on 2022-02-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0007_auto_20220201_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingyears',
            name='agreement_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Annual Agreement Cost'),
        ),
        migrations.AlterField(
            model_name='fundingyears',
            name='project_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Annual Project Cost'),
        ),
    ]
