# Generated by Django 3.1.2 on 2022-02-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0008_auto_20220201_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='objective_id',
            new_name='objective_unique',
        ),
    ]
