# Generated by Django 3.1.2 on 2021-11-25 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0009_auto_20211124_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='management_area',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='species',
            field=models.CharField(blank=True, choices=[('CH', 'Chinook Salmon (Oncorhynchus tshawytscha)'), ('CM', 'Chum Salmon (Oncorhynchus keta)'), ('CO', 'Coho Salmon (Oncorhynchus kisutch)'), ('PK', 'Pink Salmon (Oncorhynchus gorbuscha)'), ('SK', 'Sockeye Salmon (Oncorhynchus nerka)'), ('SH', 'Steelhead (Oncorhynchus mykiss)'), ('Unknown', 'Unknown'), ('Not applicable', 'Not applicable'), ('Other', 'Other')], default=None, max_length=255, null=True, verbose_name='Target Species'),
        ),
    ]
