# Generated by Django 3.1.2 on 2022-02-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0010_auto_20220201_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportoutcome',
            options={'ordering': ['reporting_outcome']},
        ),
    ]
