# Generated by Django 3.1.2 on 2021-11-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0011_auto_20211128_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objective_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
