# Generated by Django 2.1.4 on 2019-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0012_auto_20190506_1424'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('project_year', 'claim_number')},
        ),
    ]
