# Generated by Django 2.1.4 on 2019-05-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0013_language'),
        ('spot', '0015_auto_20190506_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='regions',
            field=models.ManyToManyField(default=1, to='shared_models.Region'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gc_projects', to='shared_models.FiscalYear'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='spot.Status'),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='years', to='spot.Project', verbose_name='project language'),
        ),
        migrations.AlterUniqueTogether(
            name='projectyear',
            unique_together={('project', 'fiscal_year')},
        ),
    ]
