# Generated by Django 3.1.2 on 2021-03-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0016_auto_20210315_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_country', to='spot.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='This is help text ', max_length=1000, verbose_name='name'),
        ),
    ]
