# Generated by Django 3.1.2 on 2022-03-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0017_auto_20220223_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is this organization still active?'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is this person still active?'),
        ),
    ]
