# Generated by Django 2.1.4 on 2019-05-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0017_auto_20190507_0925'),
        ('spot', '0018_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_people', to='masterlist.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_people', to='spot.Project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_people', to='spot.Role')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(blank=True, through='spot.ProjectPerson', to='masterlist.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='projectperson',
            unique_together={('project', 'person', 'role')},
        ),
    ]
