# Generated by Django 3.1.2 on 2022-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0018_auto_20220228_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['agreement_number', 'name', 'area', 'primary_river']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='region',
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, choices=[('Yukon', 'Yukon/Transboundary'), ('NCA', 'North Coast'), ('SCA', 'South Coast'), ('FIA', 'Fraser')], default=None, max_length=255, null=True, verbose_name='Area'),
        ),
    ]
