# Generated by Django 3.1.2 on 2022-03-08 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0019_auto_20220304_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='river',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.river', verbose_name='River'),
        ),
        migrations.AlterField(
            model_name='project',
            name='management_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pacific Region Management Area'),
        ),
    ]
