# Generated by Django 2.1.4 on 2019-05-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0020_auto_20190507_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_year', 'program']},
        ),
        migrations.AlterModelOptions(
            name='projectyear',
            options={'ordering': ['project', 'fiscal_year']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='nhq_notified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NHQ notified'),
        ),
    ]
