# Generated by Django 3.1.2 on 2022-03-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0021_auto_20220310_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['agreement_number', 'name', 'area']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='cu_index',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cu_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='primary_river',
        ),
        migrations.RemoveField(
            model_name='project',
            name='salmon_life_stage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='secondary_river',
        ),
        migrations.RemoveField(
            model_name='project',
            name='species',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stock_management_unit',
        ),
        migrations.AddField(
            model_name='project',
            name='river',
            field=models.ManyToManyField(blank=True, related_name='river', to='spot.River', verbose_name='River(s)'),
        ),
        migrations.AddField(
            model_name='river',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='river',
            name='cu_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.cuindex', verbose_name='CU Index'),
        ),
        migrations.AddField(
            model_name='river',
            name='cu_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.cuname', verbose_name='CU Name'),
        ),
        migrations.AddField(
            model_name='river',
            name='pop_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Stock Management Unit'),
        ),
        migrations.AddField(
            model_name='river',
            name='species',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.species', verbose_name='Target Species'),
        ),
        migrations.AddField(
            model_name='river',
            name='stock_management_unit',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Stock Management Unit'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='barrier_data_check_entry',
        ),
        migrations.AddField(
            model_name='data',
            name='barrier_data_check_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.databarrier', verbose_name='Barriers to data checks/entry to database?'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_communication',
        ),
        migrations.AddField(
            model_name='data',
            name='data_communication',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.datacommunication', verbose_name='How Was Data Communicated to Recipient?'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_products',
        ),
        migrations.AddField(
            model_name='data',
            name='data_products',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.dataproducts', verbose_name='Data Product(s)'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_products_database',
        ),
        migrations.AddField(
            model_name='data',
            name='data_products_database',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_products', to='spot.databasechoice', verbose_name='Data Products Database(s)'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_programs',
        ),
        migrations.AddField(
            model_name='data',
            name='data_programs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.dataprograms', verbose_name='Data Program(s)'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='sample_barrier',
        ),
        migrations.AddField(
            model_name='data',
            name='sample_barrier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.samplebarrier', verbose_name='Barriers to Sample Collection'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='sample_format',
        ),
        migrations.AddField(
            model_name='data',
            name='sample_format',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.sampleformat', verbose_name='Sample Format(s)'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='samples_collected',
        ),
        migrations.AddField(
            model_name='data',
            name='samples_collected',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.samplescollected', verbose_name='Samples Collected'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='samples_collected_database',
        ),
        migrations.AddField(
            model_name='data',
            name='samples_collected_database',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_database', to='spot.databasechoice', verbose_name='Sample Collected Database'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='species',
        ),
        migrations.AddField(
            model_name='data',
            name='species',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.species', verbose_name='Species'),
        ),
        migrations.RemoveField(
            model_name='method',
            name='field_work_method_type',
        ),
        migrations.AddField(
            model_name='method',
            name='field_work_method_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.fieldworkmethodtype', verbose_name='Field Work Methods Type'),
        ),
        migrations.RemoveField(
            model_name='method',
            name='planning_method_type',
        ),
        migrations.AddField(
            model_name='method',
            name='planning_method_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.planningmethodtype', verbose_name='Planning Method Type'),
        ),
        migrations.RemoveField(
            model_name='method',
            name='sample_processing_method_type',
        ),
        migrations.AddField(
            model_name='method',
            name='sample_processing_method_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='spot.sampleprocessingmethodtype', verbose_name='Sample Processing Method Type'),
        ),
    ]
