# Generated by Django 2.1.4 on 2019-05-09 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0022_auto_20190508_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date/time of application submission'),
        ),
        migrations.AlterField(
            model_name='project',
            name='initiation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
