# Generated by Django 3.1.2 on 2022-03-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0023_auto_20220323_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='salmon_life_stage',
            field=models.ManyToManyField(blank=True, default=None, to='spot.SalmonLifeStage', verbose_name='Salmon Life Stage'),
        ),
    ]
