# Generated by Django 3.1.2 on 2021-03-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0023_remove_province_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='river',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spot.orgtype', verbose_name='organization type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ManyToManyField(blank=True, default=None, to='spot.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='starting date'),
        ),
    ]
