# Generated by Django 3.1.2 on 2021-03-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0024_auto_20210326_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='merged_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merged_number', to='spot.objective', verbose_name='merged agreement number'),
        ),
    ]
