# Generated by Django 3.1.2 on 2022-03-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0025_auto_20220324_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='species',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='river_species', to='spot.species', verbose_name='Target Species'),
        ),
    ]
