# Generated by Django 3.1.2 on 2022-04-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0027_auto_20220419_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='DFO_tenure',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='DFO Tenure'),
        ),
    ]
