# Generated by Django 3.2.13 on 2022-05-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0030_auto_20220503_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCommunication',
        ),
        migrations.DeleteModel(
            name='SamplesCollected',
        ),
    ]
