# Generated by Django 2.1.4 on 2019-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0031_project_submission_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionofinterest',
            name='eoi_project_eligible',
            field=models.NullBooleanField(),
        ),
    ]
