# Generated by Django 2.1.4 on 2019-05-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0034_auto_20190509_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='description_test',
            new_name='description_text',
        ),
    ]
