# Generated by Django 2.1.4 on 2019-05-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0036_auto_20190509_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expressionofinterest',
            old_name='eoi_project_description',
            new_name='description',
        ),
    ]
