# Generated by Django 2.1.4 on 2019-05-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0039_auto_20190509_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionagreementchecklist',
            name='completed_by',
        ),
    ]
