# Generated by Django 2.1.4 on 2019-05-10 16:30

from django.db import migrations, models
import spot.models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0040_remove_contributionagreementchecklist_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='draft_ca',
            field=models.FileField(blank=True, null=True, upload_to=spot.models.draft_ca_file_directory_path, verbose_name='draft CA'),
        ),
        migrations.AlterField(
            model_name='project',
            name='schedule_5_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='schedule 5 is complete'),
        ),
    ]
