# Generated by Django 2.1.4 on 2019-06-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0041_auto_20190510_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionagreementchecklist',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ca_checklist', to='spot.Project'),
        ),
    ]
