# Generated by Django 2.2.2 on 2019-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0043_auto_20190606_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name (English)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (French)')),
                ('descr_eng', models.CharField(blank=True, max_length=1000, null=True, verbose_name='description (English)')),
                ('descr_fre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='description (French)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='activity_types',
            field=models.ManyToManyField(blank=True, to='spot.ActivityType'),
        ),
    ]
