# Generated by Django 2.2.2 on 2019-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0044_auto_20190617_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='project overview'),
        ),
    ]
