# Generated by Django 2.2.2 on 2019-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0047_auto_20190617_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activities',
            field=models.ManyToManyField(blank=True, to='spot.Activity'),
        ),
    ]
