# Generated by Django 2.2.2 on 2019-06-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0048_project_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='spot.Program', verbose_name='funding program'),
        ),
    ]
