# Generated by Django 2.2.2 on 2019-06-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0050_remove_project_priority_area_or_threat'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority_area_or_threats',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='spot.PriorityAreaOrThreat', verbose_name='priority areas or threats'),
        ),
    ]
