# Generated by Django 2.2.2 on 2019-06-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0062_auto_20190617_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['file_type']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='file_type',
        ),
    ]
