# Generated by Django 2.2.2 on 2019-07-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0063_auto_20190618_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
    ]
