# Generated by Django 2.2.2 on 2019-07-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0067_auto_20190725_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name (English)')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='name (French)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['program', 'category_eng', 'name']},
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_visit',
        ),
        migrations.AlterField(
            model_name='site',
            name='restoration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sites', to='spot.RestorationType', verbose_name='restoration type'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sites', to='spot.SiteType', verbose_name='site type'),
            preserve_default=False,
        ),
    ]
