# Generated by Django 2.2.2 on 2019-07-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0068_auto_20190725_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sites', to='spot.Project'),
            preserve_default=False,
        ),
    ]
