# Generated by Django 2.2.2 on 2019-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0071_auto_20190725_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
    ]
