# Generated by Django 2.2.2 on 2019-07-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0009_auto_20190725_1528'),
        ('spot', '0074_auto_20190725_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spp',
            field=models.ManyToManyField(blank=True, to='sar_search.Species', verbose_name='species'),
        ),
    ]
