# Generated by Django 2.2.2 on 2019-07-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0077_auto_20190726_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='habitat',
            field=models.IntegerField(blank=True, choices=[(1, 'Freshwater'), (2, 'Marine')], null=True),
        ),
    ]
