# Generated by Django 2.2.2 on 2019-07-26 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0080_auto_20190726_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='lat',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='latitude (DD.dddddd)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='long',
            field=models.FloatField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='longitude (DD.dddddd)'),
        ),
    ]
