# Generated by Django 3.1.2 on 2021-01-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anidetailxref',
            name='grp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='animal_details', to='bio_diversity.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='adsc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='anix_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_details', to='bio_diversity.anidetailxref', verbose_name='Animal Detail Cross Reference'),
        ),
        migrations.CreateModel(
            name='DataLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('data_csv', models.FileField(blank=True, null=True, upload_to='', verbose_name='Datafile')),
                ('evnt_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.event', verbose_name='Event')),
                ('evntc_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.eventcode', verbose_name='Data Format')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
