# Generated by Django 3.2.4 on 2021-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envcode',
            name='max_val',
            field=models.DecimalField(blank=True, db_column='MAX_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='min_val',
            field=models.DecimalField(blank=True, db_column='MIN_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Minimum Value'),
        ),
    ]
