# Generated by Django 3.1.2 on 2020-11-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0002_instrumentcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=250, verbose_name='Serial Number')),
                ('comments', models.CharField(max_length=2000, verbose_name='Comments')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('instc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_code', to='bio_diversity.instrumentcode', verbose_name='Instrument Code')),
            ],
        ),
    ]
