# Generated by Django 3.2 on 2021-04-21 16:27

import bio_diversity.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0002_auto_20210408_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamXRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['pit_tag', 'indv_year']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_id',
        ),
        migrations.AddField(
            model_name='location',
            name='end_lat',
            field=models.DecimalField(blank=True, db_column='END_LATITUDE', decimal_places=5, max_digits=7, null=True, verbose_name='End Latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='end_lon',
            field=models.DecimalField(blank=True, db_column='END_LONGITUDE', decimal_places=5, max_digits=8, null=True, verbose_name='End Longitude'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='contx_id',
            field=models.ForeignKey(blank=True, db_column='CONTAINER_XREF_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='evnt_id',
            field=models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='final_contx_flag',
            field=models.BooleanField(blank=True, db_column='FINAL_CONTAINER_FLAG', default=None, null=True, verbose_name='Final Container in movement'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='grp_id',
            field=models.ForeignKey(blank=True, db_column='GROUP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='indv_id',
            field=models.ForeignKey(blank=True, db_column='INDIV_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.individual', verbose_name='Individual'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='indvt_id',
            field=models.ForeignKey(blank=True, db_column='IND_TREATMENT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.indtreatment', verbose_name='Individual Treatment'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='loc_id',
            field=models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='pair_id',
            field=models.ForeignKey(blank=True, db_column='PAIR_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.pairing', verbose_name='Pairing'),
        ),
        migrations.AlterField(
            model_name='anidetsubjcode',
            name='anidc_id',
            field=models.ForeignKey(db_column='ANI_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Type of measurement'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='ani_subj_flag',
            field=models.BooleanField(db_column='ANI_SUBJ_FLAG', verbose_name='Subjective?'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='max_val',
            field=models.DecimalField(blank=True, db_column='MAX_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='min_val',
            field=models.DecimalField(blank=True, db_column='MIN_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='cont_subj_flag',
            field=models.BooleanField(db_column='CONT_SUBJ_FLAG', verbose_name='Subjective detail?'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='max_val',
            field=models.DecimalField(db_column='MAX_VAL', decimal_places=5, max_digits=11, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='min_val',
            field=models.DecimalField(db_column='MIN_VAL', decimal_places=5, max_digits=11, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='cup_id',
            field=models.ForeignKey(blank=True, db_column='CUP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.cup', verbose_name='Cup'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='draw_id',
            field=models.ForeignKey(blank=True, db_column='DRAWER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.drawer', verbose_name='Drawer'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='evnt_id',
            field=models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='heat_id',
            field=models.ForeignKey(blank=True, db_column='HEATH_UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.heathunit', verbose_name='Heath Unit'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='tank_id',
            field=models.ForeignKey(blank=True, db_column='TANK_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.tank', verbose_name='Tank'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='tray_id',
            field=models.ForeignKey(blank=True, db_column='TRAY_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.tray', verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='trof_id',
            field=models.ForeignKey(blank=True, db_column='TROUGH_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.trough', verbose_name='Trough'),
        ),
        migrations.AlterField(
            model_name='contdetsubjcode',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container detail code'),
        ),
        migrations.AlterField(
            model_name='count',
            name='cnt',
            field=models.DecimalField(db_column='COUNT', decimal_places=0, max_digits=6, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='count',
            name='cntc_id',
            field=models.ForeignKey(db_column='CNT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.countcode', verbose_name='Count Code'),
        ),
        migrations.AlterField(
            model_name='count',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='count',
            name='contx_id',
            field=models.ForeignKey(blank=True, db_column='CONTAINER_XREF_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='count',
            name='est',
            field=models.BooleanField(db_column='ESTIMATED', verbose_name='Estimated?'),
        ),
        migrations.AlterField(
            model_name='count',
            name='loc_id',
            field=models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='count',
            name='spec_id',
            field=models.ForeignKey(db_column='SPEC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.speciescode', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='adsc_id',
            field=models.ForeignKey(blank=True, db_column='ANI_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='anidc_id',
            field=models.ForeignKey(db_column='ANI_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Animal Detail Code'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='cnt_id',
            field=models.ForeignKey(db_column='COUNT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='bio_diversity.count', verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='draw_id',
            field=models.ForeignKey(db_column='DRAWER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cups', to='bio_diversity.drawer', verbose_name='Drawer'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='end_date',
            field=models.DateField(blank=True, db_column='END_DATE', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='start_date',
            field=models.DateField(db_column='START_DATE', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='cup_id',
            field=models.ForeignKey(db_column='CUP_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.cup', verbose_name='Cup'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='drawer',
            name='heat_id',
            field=models.ForeignKey(db_column='HEATH_UNIT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='bio_diversity.heathunit', verbose_name='Heath Unit'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='env_subj_flag',
            field=models.BooleanField(db_column='ENV_SUBJ_FLAG', verbose_name='Objective observation?'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='max_val',
            field=models.DecimalField(db_column='MAX_VAL', decimal_places=5, max_digits=11, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='min_val',
            field=models.DecimalField(db_column='MIN_VAL', decimal_places=5, max_digits=11, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='envcondfile',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='envcondfile',
            name='env_id',
            field=models.OneToOneField(db_column='ENV_COND_ID', on_delete=django.db.models.deletion.CASCADE, related_name='envcf_id', to='bio_diversity.envcondition', verbose_name='Environment Condition'),
        ),
        migrations.AlterField(
            model_name='envcondfile',
            name='env_pdf',
            field=models.FileField(blank=True, db_column='RAW_FILE', null=True, upload_to=bio_diversity.models.envcf_directory_path, verbose_name='Environment Condition File'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='contx_id',
            field=models.ForeignKey(blank=True, db_column='CONTAINER_XREF_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_condition', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_column='END', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='env_avg',
            field=models.BooleanField(db_column='AVERAGED', default=False, verbose_name='Is value an average?'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='env_val',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='envc_id',
            field=models.ForeignKey(db_column='ENV_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envcode', verbose_name='Environment variable'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='envsc_id',
            field=models.ForeignKey(blank=True, db_column='ENV_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envsubjcode', verbose_name='Environment Subjective Code'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='inst_id',
            field=models.ForeignKey(blank=True, db_column='INSTRUM_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.instrument', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='loc_id',
            field=models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_condition', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality of observation'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='start_datetime',
            field=models.DateTimeField(db_column='START', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='envsubjcode',
            name='envc_id',
            field=models.ForeignKey(blank=True, db_column='ENV_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envcode', verbose_name='Environment Code'),
        ),
        migrations.AlterField(
            model_name='envtreatcode',
            name='manufacturer',
            field=models.CharField(db_column='MANUFACTURER', max_length=50, verbose_name='Treatment Manufacturer'),
        ),
        migrations.AlterField(
            model_name='envtreatcode',
            name='rec_dose',
            field=models.CharField(blank=True, db_column='ENV_REC_DOSAGE', max_length=400, null=True, verbose_name='Recommended Dosage'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='amt',
            field=models.DecimalField(db_column='AMOUNT', decimal_places=3, max_digits=7, verbose_name='Dose'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='concentration',
            field=models.DecimalField(blank=True, db_column='CONCENTRATION', decimal_places=7, max_digits=8, null=True, verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='contx_id',
            field=models.ForeignKey(db_column='CONTAINER_XREF_ID', on_delete=django.db.models.deletion.CASCADE, related_name='env_treatment', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='duration',
            field=models.DecimalField(db_column='DURATION', decimal_places=0, max_digits=5, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='envtc_id',
            field=models.ForeignKey(db_column='ENV_TREAT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envtreatcode', verbose_name='Environment Treatment Code'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='lot_num',
            field=models.CharField(blank=True, db_column='LOT_NUMBER', max_length=30, null=True, verbose_name='Lot Number'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='unit_id',
            field=models.ForeignKey(db_column='UNIT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_column='END', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='evntc_id',
            field=models.ForeignKey(db_column='EVT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.eventcode', verbose_name='Event Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='perc_id',
            field=models.ForeignKey(db_column='PER_ID', limit_choices_to={'perc_valid': True}, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.personnelcode', verbose_name='Personnel Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prog_id',
            field=models.ForeignKey(db_column='PROGRAM_ID', limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(db_column='START', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='evnt_id',
            field=models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='evntf_xls',
            field=models.FileField(blank=True, db_column='EVENT_FILE', null=True, upload_to=bio_diversity.models.evntf_directory_path, verbose_name='Event File'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='evntfc_id',
            field=models.ForeignKey(db_column='EVT_FILE_CODE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='bio_diversity.eventfilecode', verbose_name='Event File Code'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='stok_id',
            field=models.ForeignKey(blank=True, db_column='STOCK_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='bio_diversity.stockcode', verbose_name='Stock Code'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='alpha',
            field=models.DecimalField(db_column='A', decimal_places=3, max_digits=10, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='beta',
            field=models.DecimalField(db_column='B', decimal_places=3, max_digits=10, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='coll_id',
            field=models.ForeignKey(blank=True, db_column='COLLECTION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.collection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='stok_id',
            field=models.ForeignKey(db_column='STOCK_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.stockcode', verbose_name='Stock Code'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='feedcode',
            name='manufacturer',
            field=models.CharField(db_column='MANUFACTURER', max_length=50, verbose_name='Maufacturer'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='amt',
            field=models.DecimalField(db_column='AMOUNT', decimal_places=3, max_digits=7, verbose_name='Amount of Feed'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='contx_id',
            field=models.OneToOneField(db_column='CONTAINER_XREF_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feedc_id',
            field=models.ForeignKey(db_column='FEED_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.feedcode', verbose_name='Feeding Code'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feedm_id',
            field=models.ForeignKey(db_column='FEEDMETHOD_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.feedmethod', verbose_name='Feeding Method'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='freq',
            field=models.CharField(blank=True, db_column='FREQUENCY', max_length=40, null=True, verbose_name='Description of frequency'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='lot_num',
            field=models.CharField(blank=True, db_column='LOT_NUMBER', max_length=40, null=True, verbose_name='Lot Number'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='unit_id',
            field=models.ForeignKey(db_column='UNIT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='group',
            name='coll_id',
            field=models.ForeignKey(db_column='COLLECTION_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.collection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grp_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Group still valid?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grp_year',
            field=models.IntegerField(db_column='YEAR', default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Collection year'),
        ),
        migrations.AlterField(
            model_name='group',
            name='spec_id',
            field=models.ForeignKey(db_column='SPEC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.speciescode', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='group',
            name='stok_id',
            field=models.ForeignKey(db_column='STOCK_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.stockcode', verbose_name='Stock Code'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='adsc_id',
            field=models.ForeignKey(blank=True, db_column='ANI_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='anidc_id',
            field=models.ForeignKey(db_column='ANI_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Animal Detail Code'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='anix_id',
            field=models.ForeignKey(db_column='ANI_DET_XREF_ID', on_delete=django.db.models.deletion.CASCADE, related_name='group_details', to='bio_diversity.anidetailxref', verbose_name='Animal Detail Cross Reference'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='detail_date',
            field=models.DateField(db_column='DETAIL_DATE', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='frm_grp_id',
            field=models.ForeignKey(blank=True, db_column='FROM_GROUP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.group', verbose_name='From Parent Group'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='grpd_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='heathunit',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='heathunit',
            name='inservice_date',
            field=models.DateField(db_column='INSERVICE_DATE', verbose_name='Date unit was put into service'),
        ),
        migrations.AlterField(
            model_name='heathunit',
            name='manufacturer',
            field=models.CharField(db_column='MANUFACTURER', max_length=35, verbose_name='Maufacturer'),
        ),
        migrations.AlterField(
            model_name='heathunit',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='heathunit',
            name='serial_number',
            field=models.CharField(db_column='SERIAL_NUMBER', max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='heat_id',
            field=models.ForeignKey(db_column='HEATH_UNIT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.heathunit', verbose_name='Heath Unit'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cntd_id',
            field=models.ForeignKey(blank=True, db_column='COUNT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.countdet', verbose_name='Count Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cupd_id',
            field=models.ForeignKey(blank=True, db_column='CUP_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.cupdet', verbose_name='Cup Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='draw_id',
            field=models.ForeignKey(blank=True, db_column='DRAWER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.drawer', verbose_name='Drawer'),
        ),
        migrations.AlterField(
            model_name='image',
            name='grpd_id',
            field=models.ForeignKey(blank=True, db_column='GROUP_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.groupdet', verbose_name='Group Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='heatd_id',
            field=models.ForeignKey(blank=True, db_column='HEATH_UNIT_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.heathunitdet', verbose_name='Heath Unit Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_png',
            field=models.FileField(blank=True, db_column='IMAGE', null=True, upload_to=bio_diversity.models.img_directory_path, verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgc_id',
            field=models.ForeignKey(db_column='IMG_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.imagecode', verbose_name='Image Code'),
        ),
        migrations.AlterField(
            model_name='image',
            name='indvd_id',
            field=models.ForeignKey(blank=True, db_column='INDIV_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.individualdet', verbose_name='Individual Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='loc_id',
            field=models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='image',
            name='sampd_id',
            field=models.ForeignKey(blank=True, db_column='SAMP_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.sampledet', verbose_name='Sample Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spwnd_id',
            field=models.ForeignKey(blank=True, db_column='SPAWN_DETAIL_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.spawndet', verbose_name='Spawn Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tankd_id',
            field=models.ForeignKey(blank=True, db_column='TANK_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.tankdet', verbose_name='Tank Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='trayd_id',
            field=models.ForeignKey(blank=True, db_column='TRAY_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.traydet', verbose_name='Tray Detail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='trofd_id',
            field=models.ForeignKey(blank=True, db_column='TROUGH_DET_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio_diversity.troughdet', verbose_name='Trough Detail'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='coll_id',
            field=models.ForeignKey(blank=True, db_column='COLLECTION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.collection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='grp_id',
            field=models.ForeignKey(blank=True, db_column='GROUP_ID', limit_choices_to={'grp_valid': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.group', verbose_name='From Parent Group'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='indv_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Entry still valid?'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='indv_year',
            field=models.IntegerField(db_column='YEAR', default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Collection year'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='pit_tag',
            field=models.CharField(blank=True, db_column='PIT_TAG', max_length=50, null=True, unique=True, verbose_name='PIT tag ID'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='spec_id',
            field=models.ForeignKey(db_column='SPEC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.speciescode', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='stok_id',
            field=models.ForeignKey(db_column='STOCK_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.stockcode', verbose_name='Stock Code'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ufid',
            field=models.CharField(blank=True, db_column='UFID', max_length=50, null=True, unique=True, verbose_name='ABL Fish UFID'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='adsc_id',
            field=models.ForeignKey(blank=True, db_column='ANI_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='anidc_id',
            field=models.ForeignKey(db_column='ANI_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Animal Detail Code'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='anix_id',
            field=models.ForeignKey(db_column='ANI_DET_XREF_ID', on_delete=django.db.models.deletion.CASCADE, related_name='individual_details', to='bio_diversity.anidetailxref', verbose_name='Animal Detail Cross Reference'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='detail_date',
            field=models.DateField(db_column='DETAIL_DATE', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='indvd_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='indtreatcode',
            name='manufacturer',
            field=models.CharField(db_column='IND_MANUFACTURER', max_length=50, verbose_name='Treatment Manufacturer'),
        ),
        migrations.AlterField(
            model_name='indtreatcode',
            name='rec_dose',
            field=models.CharField(db_column='IND_REC_DOSAGE', max_length=400, verbose_name='Recommended Dosage'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='dose',
            field=models.DecimalField(db_column='DOSE', decimal_places=3, max_digits=7, verbose_name='Dose'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_column='END', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='indvtc_id',
            field=models.ForeignKey(db_column='IND_TEART_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.indtreatcode', verbose_name='Individual Treatment Code'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='lot_num',
            field=models.CharField(db_column='LOT_NUMBER', max_length=30, verbose_name='Lot Number'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='start_datetime',
            field=models.DateTimeField(db_column='START', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='unit_id',
            field=models.ForeignKey(db_column='UNIT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instc_id',
            field=models.ForeignKey(db_column='INST_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.instrumentcode', verbose_name='Instrument Code'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=250, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='det_value',
            field=models.DecimalField(db_column='VAL', decimal_places=5, max_digits=11, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='inst_id',
            field=models.ForeignKey(db_column='INSTRUM_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.instrument', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='instdc_id',
            field=models.ForeignKey(db_column='INST_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.instdetcode', verbose_name='Instrument Detail Code'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='location',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='location',
            name='evnt_id',
            field=models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_date',
            field=models.DateTimeField(db_column='LOCATION_DATE', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_lat',
            field=models.DecimalField(blank=True, db_column='LATITUDE', decimal_places=5, max_digits=7, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_lon',
            field=models.DecimalField(blank=True, db_column='LONGITUDE', decimal_places=5, max_digits=8, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locc_id',
            field=models.ForeignKey(db_column='LOC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.loccode', verbose_name='Location Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='relc_id',
            field=models.ForeignKey(blank=True, db_column='SITE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='bio_diversity.releasesitecode', verbose_name='Site Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='rive_id',
            field=models.ForeignKey(blank=True, db_column='RIVER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.rivercode', verbose_name='River'),
        ),
        migrations.AlterField(
            model_name='location',
            name='subr_id',
            field=models.ForeignKey(blank=True, db_column='SUBRIVER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.subrivercode', verbose_name='SubRiver Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='trib_id',
            field=models.ForeignKey(blank=True, db_column='TRIB_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.tributary', verbose_name='Tributary'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='cross',
            field=models.IntegerField(db_column='CROSS', verbose_name='Cross'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='indv_id',
            field=models.ForeignKey(db_column='DAM', limit_choices_to={'indv_valid': True, 'pit_tag__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='bio_diversity.individual', verbose_name='Dam'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='pair_prio_id',
            field=models.ForeignKey(db_column='PAIR_PRIORITY_ID', on_delete=django.db.models.deletion.CASCADE, related_name='pair_priorities', to='bio_diversity.prioritycode', verbose_name='Priority of Pair'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='prio_id',
            field=models.ForeignKey(db_column='PRIORITY_ID', on_delete=django.db.models.deletion.CASCADE, related_name='female_priorities', to='bio_diversity.prioritycode', verbose_name='Priority of Female'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='personnelcode',
            name='initials',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Initials'),
        ),
        migrations.AlterField(
            model_name='progauthority',
            name='proga_first_name',
            field=models.CharField(db_column='PROG_AUTH_FIRST_NAME', max_length=32, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='progauthority',
            name='proga_last_name',
            field=models.CharField(db_column='PROG_AUTH_LAST_NAME', max_length=32, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='orga_id',
            field=models.ForeignKey(db_column='ORG_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_desc',
            field=models.CharField(db_column='PROGRAM_DESC', max_length=4000, verbose_name='Program Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_name',
            field=models.CharField(db_column='PROGRAM_NAME', max_length=30, unique=True, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='proga_id',
            field=models.ForeignKey(db_column='PROG_AUTH_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.progauthority', verbose_name='Program Authority'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='evntc_id',
            field=models.ForeignKey(blank=True, db_column='EVT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.eventcode', verbose_name='Event Code'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(db_column='PROTOCOL_NAME', max_length=25, verbose_name='Protocol Name'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='prog_id',
            field=models.ForeignKey(db_column='PROGRAM_ID', limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='bio_diversity.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='prot_desc',
            field=models.CharField(db_column='PROTOCOL_DESC', max_length=4000, verbose_name='Protocol Description'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protc_id',
            field=models.ForeignKey(db_column='PROTO_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.protocode', verbose_name='Protocol Code'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='protofile',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='protofile',
            name='prot_id',
            field=models.ForeignKey(db_column='PROTOCOL_ID', limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, related_name='protf_id', to='bio_diversity.protocol', verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='protofile',
            name='protf_pdf',
            field=models.FileField(blank=True, db_column='PROTO_FILE', null=True, upload_to=bio_diversity.models.protf_directory_path, verbose_name='Protocol File'),
        ),
        migrations.AlterField(
            model_name='releasesitecode',
            name='max_lat',
            field=models.DecimalField(blank=True, db_column='MAX_LATITUDE', decimal_places=5, max_digits=7, null=True, verbose_name='Max Latitude'),
        ),
        migrations.AlterField(
            model_name='releasesitecode',
            name='max_lon',
            field=models.DecimalField(blank=True, db_column='MAX_LONGITUDE', decimal_places=5, max_digits=8, null=True, verbose_name='Max Longitude'),
        ),
        migrations.AlterField(
            model_name='releasesitecode',
            name='min_lat',
            field=models.DecimalField(blank=True, db_column='MIN_LATITUDE', decimal_places=5, max_digits=7, null=True, verbose_name='Min Latitude'),
        ),
        migrations.AlterField(
            model_name='releasesitecode',
            name='min_lon',
            field=models.DecimalField(blank=True, db_column='MIN_LONGITUDE', decimal_places=5, max_digits=8, null=True, verbose_name='Min Longitude'),
        ),
        migrations.AlterField(
            model_name='releasesitecode',
            name='rive_id',
            field=models.ForeignKey(db_column='RIVER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='bio_diversity.rivercode', verbose_name='River'),
        ),
        migrations.AlterField(
            model_name='releasesitecode',
            name='subr_id',
            field=models.ForeignKey(blank=True, db_column='SUBRIVER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.subrivercode', verbose_name='SubRiver Code'),
        ),
        migrations.AlterField(
            model_name='releasesitecode',
            name='trib_id',
            field=models.ForeignKey(blank=True, db_column='TRIB_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.tributary', verbose_name='Tributary'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='loc_id',
            field=models.ForeignKey(db_column='LOCATION_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='samp_num',
            field=models.IntegerField(db_column='SAMPLE_FISHNO', verbose_name='Sample Fish Number'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampc_id',
            field=models.ForeignKey(db_column='SAMP_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.samplecode', verbose_name='Sample Code'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='spec_id',
            field=models.ForeignKey(db_column='SPEC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.speciescode', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='adsc_id',
            field=models.ForeignKey(blank=True, db_column='ANI_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='anidc_id',
            field=models.ForeignKey(db_column='ANI_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Animal Detail Code'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='samp_id',
            field=models.ForeignKey(db_column='SAMPLE_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.sample', verbose_name='Sample'),
        ),
        migrations.AlterField(
            model_name='sire',
            name='choice',
            field=models.IntegerField(db_column='CHOICE', verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='sire',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sire',
            name='indv_id',
            field=models.ForeignKey(db_column='UFID', limit_choices_to={'indv_valid': True, 'pit_tag__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='sires', to='bio_diversity.individual', verbose_name='Sire'),
        ),
        migrations.AlterField(
            model_name='sire',
            name='pair_id',
            field=models.ForeignKey(db_column='PAIR_ID', limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sires', to='bio_diversity.pairing', verbose_name='Pairing'),
        ),
        migrations.AlterField(
            model_name='sire',
            name='prio_id',
            field=models.ForeignKey(db_column='PRIORITY_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.prioritycode', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='pair_id',
            field=models.ForeignKey(db_column='PAIR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='spawning_details', to='bio_diversity.pairing', verbose_name='Pairing'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='spwndc_id',
            field=models.ForeignKey(db_column='SPAWN_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.spawndetcode', verbose_name='Spawning Detail Code'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='spwnsc_id',
            field=models.ForeignKey(blank=True, db_column='SPAWN_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.spawndetsubjcode', verbose_name='Spawning Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='spawndetcode',
            name='max_val',
            field=models.DecimalField(blank=True, db_column='MAX_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='spawndetcode',
            name='min_val',
            field=models.DecimalField(blank=True, db_column='MIN_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='spawndetcode',
            name='spwn_subj_flag',
            field=models.BooleanField(db_column='SPAWN_SUBJ_FLAG', verbose_name='Subjective?'),
        ),
        migrations.AlterField(
            model_name='spawndetcode',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='speciescode',
            name='com_name',
            field=models.CharField(blank=True, db_column='COMMON_NAME', max_length=35, null=True, verbose_name='Species Common Name'),
        ),
        migrations.AlterField(
            model_name='speciescode',
            name='name',
            field=models.CharField(db_column='SPEC_SHORT', max_length=10, verbose_name='Species Name'),
        ),
        migrations.AlterField(
            model_name='speciescode',
            name='species',
            field=models.CharField(db_column='SPECIES', max_length=100, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='subrivercode',
            name='rive_id',
            field=models.ForeignKey(db_column='RIVER_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.rivercode', verbose_name='River'),
        ),
        migrations.AlterField(
            model_name='subrivercode',
            name='trib_id',
            field=models.ForeignKey(blank=True, db_column='TRIB_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.tributary', verbose_name='Tributary'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='tank_id',
            field=models.ForeignKey(db_column='TANK_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.tank', verbose_name='Tank'),
        ),
        migrations.AlterField(
            model_name='tray',
            name='end_date',
            field=models.DateField(blank=True, db_column='END_DATE', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='tray',
            name='start_date',
            field=models.DateField(db_column='START_DATE', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tray',
            name='trof_id',
            field=models.ForeignKey(db_column='TROUGH_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='bio_diversity.trough', verbose_name='Trough'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='tray_id',
            field=models.ForeignKey(db_column='TRAY_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.tray', verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='tributary',
            name='rive_id',
            field=models.ForeignKey(db_column='RIVER_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.rivercode', verbose_name='River'),
        ),
        migrations.AlterField(
            model_name='trough',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='trough',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='trof_id',
            field=models.ForeignKey(db_column='TROUGH_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.trough', verbose_name='Trough'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='teamxref',
            name='evnt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='teamxref',
            name='loc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='teamxref',
            name='perc_id',
            field=models.ForeignKey(limit_choices_to={'perc_valid': True}, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.personnelcode', verbose_name='Team Member'),
        ),
        migrations.AddField(
            model_name='teamxref',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.rolecode', verbose_name='Role Code'),
        ),
        migrations.AddConstraint(
            model_name='teamxref',
            constraint=models.UniqueConstraint(fields=('perc_id', 'role_id', 'evnt_id', 'loc_id'), name='Team_Uniqueness'),
        ),
    ]
