# Generated by Django 3.2 on 2021-04-14 16:40

import bio_diversity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0003_auto_20210409_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anidetailxref',
            name='contx_id',
            field=models.ForeignKey(blank=True, db_column='CONTAINER_XREF_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='evnt_id',
            field=models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='final_contx_flag',
            field=models.BooleanField(blank=True, db_column='FINAL_CONTAINER_FLAG', default=None, null=True, verbose_name='Final Container in movement'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='grp_id',
            field=models.ForeignKey(blank=True, db_column='GROUP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='indv_id',
            field=models.ForeignKey(blank=True, db_column='INDIV_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.individual', verbose_name='Individual'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='indvt_id',
            field=models.ForeignKey(blank=True, db_column='IND_TREATMENT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.indtreatment', verbose_name='Individual Treatment'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='loc_id',
            field=models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='pair_id',
            field=models.ForeignKey(blank=True, db_column='PAIR_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.pairing', verbose_name='Pairing'),
        ),
        migrations.AlterField(
            model_name='anidetsubjcode',
            name='anidc_id',
            field=models.ForeignKey(db_column='ANI_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Type of measurement'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='ani_subj_flag',
            field=models.BooleanField(db_column='ANI_SUBJ_FLAG', verbose_name='Subjective?'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='max_val',
            field=models.DecimalField(blank=True, db_column='MAX_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='min_val',
            field=models.DecimalField(blank=True, db_column='MIN_VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='animaldetcode',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='cont_subj_flag',
            field=models.BooleanField(db_column='CONT_SUBJ_FLAG', verbose_name='Subjective detail?'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='max_val',
            field=models.DecimalField(db_column='MAX_VAL', decimal_places=5, max_digits=11, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='min_val',
            field=models.DecimalField(db_column='MIN_VAL', decimal_places=5, max_digits=11, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='containerdetcode',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='cup_id',
            field=models.ForeignKey(blank=True, db_column='CUP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.cup', verbose_name='Cup'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='draw_id',
            field=models.ForeignKey(blank=True, db_column='DRAWER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.drawer', verbose_name='Drawer'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='evnt_id',
            field=models.ForeignKey(db_column='EVENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='heat_id',
            field=models.ForeignKey(blank=True, db_column='HEATH_UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.heathunit', verbose_name='Heath Unit'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='tank_id',
            field=models.ForeignKey(blank=True, db_column='TANK_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.tank', verbose_name='Tank'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='tray_id',
            field=models.ForeignKey(blank=True, db_column='TRAY_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.tray', verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='trof_id',
            field=models.ForeignKey(blank=True, db_column='TROUGH_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.trough', verbose_name='Trough'),
        ),
        migrations.AlterField(
            model_name='contdetsubjcode',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container detail code'),
        ),
        migrations.AlterField(
            model_name='count',
            name='cnt',
            field=models.DecimalField(db_column='COUNT', decimal_places=0, max_digits=6, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='count',
            name='cntc_id',
            field=models.ForeignKey(db_column='CNT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.countcode', verbose_name='Count Code'),
        ),
        migrations.AlterField(
            model_name='count',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='count',
            name='contx_id',
            field=models.ForeignKey(blank=True, db_column='CONTAINER_XREF_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='count',
            name='est',
            field=models.BooleanField(db_column='ESTIMATED', verbose_name='Estimated?'),
        ),
        migrations.AlterField(
            model_name='count',
            name='loc_id',
            field=models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='count',
            name='spec_id',
            field=models.ForeignKey(db_column='SPEC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.speciescode', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='adsc_id',
            field=models.ForeignKey(blank=True, db_column='ANI_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='anidc_id',
            field=models.ForeignKey(db_column='ANI_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Animal Detail Code'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='cnt_id',
            field=models.ForeignKey(db_column='COUNT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='bio_diversity.count', verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='det_val',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='countdet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='draw_id',
            field=models.ForeignKey(db_column='DRAWER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cups', to='bio_diversity.drawer', verbose_name='Drawer'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='end_date',
            field=models.DateField(blank=True, db_column='END_DATE', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='start_date',
            field=models.DateField(db_column='START_DATE', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='cup_id',
            field=models.ForeignKey(db_column='CUP_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.cup', verbose_name='Cup'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='cupdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='drawer',
            name='heat_id',
            field=models.ForeignKey(db_column='HEATH_UNIT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='bio_diversity.heathunit', verbose_name='Heath Unit'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='env_subj_flag',
            field=models.BooleanField(db_column='ENV_SUBJ_FLAG', verbose_name='Objective observation?'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='max_val',
            field=models.DecimalField(db_column='MAX_VAL', decimal_places=5, max_digits=11, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='min_val',
            field=models.DecimalField(db_column='MIN_VAL', decimal_places=5, max_digits=11, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='envcode',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='envcondfile',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='envcondfile',
            name='env_id',
            field=models.OneToOneField(db_column='ENV_COND_ID', on_delete=django.db.models.deletion.CASCADE, related_name='envcf_id', to='bio_diversity.envcondition', verbose_name='Environment Condition'),
        ),
        migrations.AlterField(
            model_name='envcondfile',
            name='env_pdf',
            field=models.FileField(blank=True, db_column='RAW_FILE', null=True, upload_to=bio_diversity.models.envcf_directory_path, verbose_name='Environment Condition File'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='contx_id',
            field=models.ForeignKey(blank=True, db_column='CONTAINER_XREF_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_condition', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_column='END', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='env_avg',
            field=models.BooleanField(db_column='AVERAGED', default=False, verbose_name='Is value an average?'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='env_val',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='envc_id',
            field=models.ForeignKey(db_column='ENV_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envcode', verbose_name='Environment variable'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='envsc_id',
            field=models.ForeignKey(blank=True, db_column='ENV_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envsubjcode', verbose_name='Environment Subjective Code'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='inst_id',
            field=models.ForeignKey(blank=True, db_column='INSTRUM_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.instrument', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='loc_id',
            field=models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_condition', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality of observation'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='start_datetime',
            field=models.DateTimeField(db_column='START', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='envsubjcode',
            name='envc_id',
            field=models.ForeignKey(blank=True, db_column='ENV_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envcode', verbose_name='Environment Code'),
        ),
        migrations.AlterField(
            model_name='envtreatcode',
            name='manufacturer',
            field=models.CharField(db_column='MANUFACTURER', max_length=50, verbose_name='Treatment Manufacturer'),
        ),
        migrations.AlterField(
            model_name='envtreatcode',
            name='rec_dose',
            field=models.CharField(blank=True, db_column='ENV_REC_DOSAGE', max_length=400, null=True, verbose_name='Recommended Dosage'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='amt',
            field=models.DecimalField(db_column='AMOUNT', decimal_places=3, max_digits=7, verbose_name='Dose'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='concentration',
            field=models.DecimalField(blank=True, db_column='CONCENTRATION', decimal_places=7, max_digits=8, null=True, verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='contx_id',
            field=models.ForeignKey(db_column='CONTAINER_XREF_ID', on_delete=django.db.models.deletion.CASCADE, related_name='env_treatment', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='duration',
            field=models.DecimalField(db_column='DURATION', decimal_places=0, max_digits=5, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='envtc_id',
            field=models.ForeignKey(db_column='ENV_TREAT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.envtreatcode', verbose_name='Environment Treatment Code'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='lot_num',
            field=models.CharField(blank=True, db_column='LOT_NUMBER', max_length=30, null=True, verbose_name='Lot Number'),
        ),
        migrations.AlterField(
            model_name='envtreatment',
            name='unit_id',
            field=models.ForeignKey(db_column='UNIT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.unitcode', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_column='END', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='evntc_id',
            field=models.ForeignKey(db_column='EVT_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.eventcode', verbose_name='Event Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='perc_id',
            field=models.ForeignKey(db_column='PER_ID', limit_choices_to={'perc_valid': True}, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.personnelcode', verbose_name='Personnel Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prog_id',
            field=models.ForeignKey(db_column='PROGRAM_ID', limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(db_column='START', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='fecundity',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='groupdet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='heathunit',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='heathunit',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='heathunitdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='individualdet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_column='END', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='start_datetime',
            field=models.DateTimeField(db_column='START', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='program',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='end_date',
            field=models.DateField(blank=True, db_column='END', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='start_date',
            field=models.DateField(db_column='START', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='valid',
            field=models.BooleanField(db_column='STILL_VALID', default='True', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='det_val',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='det_val',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='qual_id',
            field=models.ForeignKey(db_column='QUAL_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.qualcode', verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='tankdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='traydet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
        migrations.AlterField(
            model_name='trough',
            name='facic_id',
            field=models.ForeignKey(db_column='FAC_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='trough',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='cdsc_id',
            field=models.ForeignKey(blank=True, db_column='CONT_DET_SUBJ_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.contdetsubjcode', verbose_name='Container Detail Subjective Code'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='comments',
            field=models.CharField(blank=True, db_column='COMMENTS', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='contdc_id',
            field=models.ForeignKey(db_column='CONT_DET_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerdetcode', verbose_name='Container Detail Code'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='det_valid',
            field=models.BooleanField(db_column='STILL_VALID', default='False', verbose_name='Detail still valid?'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='det_value',
            field=models.DecimalField(blank=True, db_column='VAL', decimal_places=5, max_digits=11, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='end_date',
            field=models.DateField(blank=True, db_column='DET_END', null=True, verbose_name='Last Date Detail is valid'),
        ),
        migrations.AlterField(
            model_name='troughdet',
            name='start_date',
            field=models.DateField(db_column='DET_START', verbose_name='Date detail was recorded'),
        ),
    ]
