# Generated by Django 3.1.2 on 2020-11-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0003_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('det_value', models.DecimalField(decimal_places=5, max_digits=11, verbose_name='Value')),
                ('start_date', models.DateField(verbose_name='Date of change')),
                ('end_date', models.DateField(verbose_name='Last Date Change is valid')),
                ('valid', models.BooleanField(default='False', verbose_name='Detail still valid?')),
                ('comments', models.CharField(max_length=2000, verbose_name='Comments')),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inst', to='bio_diversity.instrument', verbose_name='Instrument')),
                ('instdc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inst_det_code', to='bio_diversity.instdetcode', verbose_name='Instrument Detail Code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
