# Generated by Django 3.2.4 on 2021-07-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0003_auto_20210628_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='coll_id',
            field=models.ForeignKey(db_column='COLLECTION_ID', default=25, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.collection', verbose_name='Collection'),
        ),
    ]
