# Generated by Django 3.1.2 on 2021-02-05 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0004_auto_20210129_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envcondition',
            name='env_end',
        ),
        migrations.RemoveField(
            model_name='envcondition',
            name='env_start',
        ),
        migrations.AddField(
            model_name='envcondition',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='envcondition',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 19, 51, 32, 249297, tzinfo=utc), verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anidetsubjcode',
            name='anidc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Type of measurement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countdet',
            name='cnt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='bio_diversity.count', verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='event',
            name='evnt_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='evnt_start',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='indtreatment',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 19, 51, 44, 794244, tzinfo=utc), verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_date',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='indv_id',
            field=models.ForeignKey(limit_choices_to={'indv_valid': True, 'pit_tag__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='bio_diversity.individual', verbose_name='Dam'),
        ),
        migrations.AlterField(
            model_name='sire',
            name='indv_id',
            field=models.ForeignKey(limit_choices_to={'indv_valid': True, 'pit_tag__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='sires', to='bio_diversity.individual', verbose_name='Sire UFID'),
        ),
        migrations.CreateModel(
            name='CommentKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('adsc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
    ]
