# Generated by Django 3.1.2 on 2021-01-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0004_auto_20210112_1341'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='containerxref',
            name='Container Cross Reference Uniqueness',
        ),
        migrations.RemoveField(
            model_name='containerxref',
            name='tank_id',
        ),
        migrations.AddField(
            model_name='containerxref',
            name='tank_id',
            field=models.ManyToManyField(blank=True, null=True, to='bio_diversity.Tank', verbose_name='Tank'),
        ),
        migrations.AddConstraint(
            model_name='containerxref',
            constraint=models.UniqueConstraint(fields=('evnt_id', 'trof_id', 'tray_id', 'heat_id', 'draw_id', 'cup_id'), name='Container Cross Reference Uniqueness'),
        ),
    ]
