# Generated by Django 3.1.2 on 2021-01-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0004_auto_20210129_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anidetsubjcode',
            name='anidc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.animaldetcode', verbose_name='Type of measurement'),
            preserve_default=False,
        ),
    ]
