# Generated by Django 3.2 on 2021-05-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0004_auto_20210526_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='contx_id',
            field=models.ForeignKey(db_column='CONTAINER_XREF_ID', on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
    ]
