# Generated by Django 3.2.4 on 2021-07-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0004_alter_envtreatment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasesitecode',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tributary',
            name='subr_id',
            field=models.ForeignKey(blank=True, db_column='SUBRIVER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.subrivercode', verbose_name='Subriver'),
        ),
        migrations.AlterField(
            model_name='subrivercode',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='tributary',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterUniqueTogether(
            name='subrivercode',
            unique_together={('name', 'rive_id', 'trib_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tributary',
            unique_together={('name', 'rive_id', 'subr_id')},
        ),
    ]
