# Generated by Django 3.2 on 2021-04-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0005_auto_20210414_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='sampledet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='spawndet',
            name='det_val',
            field=models.CharField(blank=True, db_column='VAL', max_length=20, null=True, verbose_name='Value'),
        ),
    ]
