# Generated by Django 3.1.2 on 2021-02-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0005_auto_20210129_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdet',
            name='cnt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='bio_diversity.count', verbose_name='Count'),
        ),
    ]
