# Generated by Django 3.2.4 on 2021-07-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0005_auto_20210720_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataloader',
            name='evnt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='dataloader',
            name='evntc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.eventcode', verbose_name='Data Format'),
        ),
        migrations.AlterField(
            model_name='dataloader',
            name='facic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Data Format'),
        ),
    ]
