# Generated by Django 3.2.4 on 2021-06-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0005_alter_feeding_contx_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anidetailxref',
            name='Animal_Detail_Cross_Reference_Uniqueness',
        ),
        migrations.RemoveField(
            model_name='anidetailxref',
            name='indvt_id',
        ),
        migrations.AddField(
            model_name='indtreatment',
            name='anix_id',
            field=models.ForeignKey(db_column='ANI_DET_XREF_ID', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='individual_treatments', to='bio_diversity.anidetailxref', verbose_name='Animal Detail Cross Reference'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='anidetailxref',
            constraint=models.UniqueConstraint(fields=('evnt_id', 'contx_id', 'loc_id', 'indv_id', 'pair_id', 'grp_id', 'team_id'), name='Animal_Detail_Cross_Reference_Uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='indtreatment',
            constraint=models.UniqueConstraint(fields=('anix_id', 'indvtc_id'), name='Individual_Treatment_Uniqueness'),
        ),
    ]
