# Generated by Django 3.2.4 on 2021-07-27 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0005_auto_20210720_1258'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='count',
            name='Count_Uniqueness',
        ),
        migrations.AddField(
            model_name='count',
            name='cnt_year',
            field=models.IntegerField(blank=True, db_column='YEAR', default=2000, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Collection year'),
        ),
        migrations.AddField(
            model_name='count',
            name='coll_id',
            field=models.ForeignKey(blank=True, db_column='COLLECTION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.collection', verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='count',
            name='stok_id',
            field=models.ForeignKey(blank=True, db_column='STOCK_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.stockcode', verbose_name='Stock Code'),
        ),
        migrations.AlterField(
            model_name='dataloader',
            name='evnt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='dataloader',
            name='evntc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.eventcode', verbose_name='Data Format'),
        ),
        migrations.AlterField(
            model_name='dataloader',
            name='facic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.facilitycode', verbose_name='Data Format'),
        ),
        migrations.AlterUniqueTogether(
            name='count',
            unique_together={('loc_id', 'contx_id', 'cntc_id', 'spec_id')},
        ),
    ]
