# Generated by Django 3.1.2 on 2021-01-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0006_auto_20210112_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdet',
            name='adsc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subjective Code'),
        ),
    ]
