# Generated by Django 3.2.4 on 2021-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0006_auto_20210615_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indtreatment',
            name='lot_num',
            field=models.CharField(blank=True, db_column='LOT_NUMBER', max_length=30, null=True, verbose_name='Lot Number'),
        ),
    ]
