# Generated by Django 3.1.2 on 2021-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0006_auto_20210201_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='envcondition',
            name='env_endtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Event end time'),
        ),
        migrations.AddField(
            model_name='envcondition',
            name='env_starttime',
            field=models.TimeField(blank=True, null=True, verbose_name='Event start time'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='env_end',
            field=models.DateField(blank=True, null=True, verbose_name='Event end date'),
        ),
        migrations.AlterField(
            model_name='envcondition',
            name='env_start',
            field=models.DateField(verbose_name='Event start date'),
        ),
    ]
