# Generated by Django 3.1.2 on 2021-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0006_auto_20210209_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualdet',
            name='indvd_valid',
            field=models.BooleanField(default='True', verbose_name='Detail still valid?'),
        ),
    ]
