# Generated by Django 3.2 on 2021-04-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0006_auto_20210416_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamXRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_id',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='teamxref',
            name='evnt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='teamxref',
            name='loc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='teamxref',
            name='perc_id',
            field=models.ForeignKey(limit_choices_to={'perc_valid': True}, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.personnelcode', verbose_name='Team Member'),
        ),
        migrations.AddField(
            model_name='teamxref',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.rolecode', verbose_name='Role Code'),
        ),
        migrations.AddConstraint(
            model_name='teamxref',
            constraint=models.UniqueConstraint(fields=('perc_id', 'role_id', 'evnt_id', 'loc_id'), name='Team_Uniqueness'),
        ),
    ]
