# Generated by Django 3.2.4 on 2021-08-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0007_auto_20210727_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heathunit',
            name='inservice_date',
        ),
        migrations.RemoveField(
            model_name='heathunit',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='heathunit',
            name='serial_number',
        ),
    ]
