# Generated by Django 3.2 on 2021-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0007_auto_20210419_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelcode',
            name='initials',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Initials'),
        ),
    ]
