# Generated by Django 3.1.2 on 2021-02-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0008_auto_20210209_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='anidetailxref',
            name='final_contx_flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Final Container in movement'),
        ),
    ]
