# Generated by Django 3.1.2 on 2020-12-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0009_auto_20201201_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date of change')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Last Date Change is valid')),
                ('valid', models.BooleanField(default='False', verbose_name='Detail still valid?')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('prog_name', models.CharField(max_length=30, verbose_name='Program Name')),
                ('prog_desc', models.CharField(max_length=4000, verbose_name='Program Description')),
                ('orga_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.organization', verbose_name='Organization')),
                ('proga_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.progauthority', verbose_name='Program Authority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.instrumentcode', verbose_name='Instrument Code'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.instrument', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumentdet',
            name='instdc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.instdetcode', verbose_name='Instrument Detail Code'),
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date of change')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Last Date Change is valid')),
                ('valid', models.BooleanField(default='False', verbose_name='Detail still valid?')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('prot_desc', models.CharField(max_length=4000, verbose_name='Program Description')),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.program', verbose_name='Program')),
                ('protc_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.protocode', verbose_name='Protocol Code')),
                ('protf_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.protofile', verbose_name='Protocol File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
