# Generated by Django 3.1.2 on 2021-02-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0009_commentkeywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentkeywords',
            old_name='adsc',
            new_name='adsc_id',
        ),
    ]
