# Generated by Django 3.1.2 on 2021-02-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0010_auto_20210202_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentkeywords',
            name='adsc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.anidetsubjcode', verbose_name='Animal Detail Subject Code'),
            preserve_default=False,
        ),
    ]
