# Generated by Django 3.1.2 on 2021-03-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0011_auto_20210316_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anidetailxref',
            name='contx_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='indvt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.indtreatment', verbose_name='Individual Treatment'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='loc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='anidetailxref',
            name='pair_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='bio_diversity.pairing', verbose_name='Pairing'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='evntfc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='bio_diversity.eventfilecode', verbose_name='Event File Code'),
        ),
    ]
