# Generated by Django 3.1.2 on 2021-02-10 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0011_auto_20210210_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdet',
            name='detail_date',
            field=models.DateField(default=datetime.date(2021, 2, 10), verbose_name='Date detail was recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualdet',
            name='detail_date',
            field=models.DateField(default=datetime.date(2021, 2, 10), verbose_name='Date detail was recorded'),
            preserve_default=False,
        ),
    ]
