# Generated by Django 3.1.2 on 2021-02-11 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0012_auto_20210210_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grp_year',
            field=models.IntegerField(default=2000, max_length=4, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Collection year'),
        ),
        migrations.AddField(
            model_name='individual',
            name='indv_year',
            field=models.IntegerField(default=2000, max_length=4, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Collection year'),
        ),
    ]
