# Generated by Django 3.2.10 on 2022-01-11 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bio_diversity', '0013_auto_20211208_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='app administrator')),
                ('is_author', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='app author')),
                ('is_user', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='app user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_user', to=settings.AUTH_USER_MODEL, verbose_name='DM Apps user')),
            ],
            options={
                'ordering': ['-is_admin', 'user__first_name'],
            },
        ),
    ]
