# Generated by Django 3.1.2 on 2020-12-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0014_auto_20201203_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='protf_id',
        ),
        migrations.AlterField(
            model_name='protofile',
            name='prot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='protocol_files', to='bio_diversity.protocol', verbose_name='Protocol'),
        ),
    ]
