# Generated by Django 3.2.10 on 2022-02-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0016_auto_20220203_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='contx_ref',
            field=models.ForeignKey(blank=True, db_column='CONT_XREF_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='bio_diversity.containerxref', verbose_name='Container Reference'),
        ),
        migrations.AlterUniqueTogether(
            name='count',
            unique_together={('loc_id', 'anix_id', 'cntc_id', 'contx_ref', 'spec_id', 'cnt_year', 'coll_id', 'stok_id')},
        ),
    ]
