# Generated by Django 3.2.10 on 2022-02-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0017_auto_20220207_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='biouser',
            name='facic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio_diversity.facilitycode', verbose_name='Facility'),
        ),
        migrations.AddField(
            model_name='biouser',
            name='mode',
            field=models.IntegerField(choices=[(1, 'read'), (2, 'edit')], default=1),
        ),
    ]
