# Generated by Django 3.1.2 on 2020-12-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0019_contdetsubjcode_cupdet_tankdet_traydet_troughdet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupdet',
            old_name='det_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='cupdet',
            old_name='det_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='tankdet',
            old_name='det_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tankdet',
            old_name='det_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='traydet',
            old_name='det_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='traydet',
            old_name='det_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='troughdet',
            old_name='det_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='troughdet',
            old_name='det_start',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='contdetsubjcode',
            name='contdc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.containerdetcode', verbose_name='Container detail code'),
        ),
    ]
