# Generated by Django 3.1.2 on 2021-02-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0020_auto_20210215_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anidetailxref',
            name='contx_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anixs', to='bio_diversity.containerxref', verbose_name='Container Cross Reference'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='cup_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.cup', verbose_name='Cup'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='draw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.drawer', verbose_name='Drawer'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='heat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.heathunit', verbose_name='Heath Unit'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='tray_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.tray', verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='containerxref',
            name='trof_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contxs', to='bio_diversity.trough', verbose_name='Trough'),
        ),
    ]
