# Generated by Django 3.1.2 on 2021-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0021_auto_20210216_0920'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sire',
            constraint=models.UniqueConstraint(fields=('indv_id', 'pair_id'), name='Sire_Uniqueness'),
        ),
    ]
