# Generated by Django 3.2.10 on 2022-03-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0021_auto_20220308_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grp_end_date',
            field=models.DateField(blank=True, db_column='GROUP_END_DATE', null=True, verbose_name='Group end date'),
        ),
    ]
