# Generated by Django 3.1.2 on 2021-02-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0022_auto_20210217_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataloader',
            name='tank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.tank', verbose_name='Destination Tank'),
        ),
        migrations.AlterField(
            model_name='location',
            name='relc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio_diversity.releasesitecode', verbose_name='Site Code'),
        ),
    ]
