# Generated by Django 3.1.2 on 2020-12-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0029_auto_20201207_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='protf_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.protofile', verbose_name='Protocol File'),
        ),
    ]
