# Generated by Django 3.1.2 on 2020-12-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0047_auto_20201210_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecundity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('valid', models.BooleanField(default='False', verbose_name='Detail still valid?')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('created_by', models.CharField(max_length=32, verbose_name='Created By')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('alpha', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='A')),
                ('beta', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='B')),
                ('coll_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.collection', verbose_name='Collection')),
                ('stok_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bio_diversity.stockcode', verbose_name='Stock Code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
