# Generated by Django 3.1.2 on 2020-12-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0067_auto_20201216_1352'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrumentdet',
            name='Instrument Detail Uniqueness',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='instc',
            new_name='instc_id',
        ),
        migrations.RenameField(
            model_name='instrumentdet',
            old_name='inst',
            new_name='inst_id',
        ),
        migrations.RenameField(
            model_name='instrumentdet',
            old_name='instdc',
            new_name='instdc_id',
        ),
        migrations.AddConstraint(
            model_name='instrumentdet',
            constraint=models.UniqueConstraint(fields=('inst_id', 'instdc_id', 'start_date'), name='Instrument Detail Uniqueness'),
        ),
    ]
