# Generated by Django 3.1.2 on 2020-12-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0068_auto_20201217_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envcondfile',
            name='env_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='envcf_id', to='bio_diversity.envcondition', verbose_name='Environment Condition'),
        ),
    ]
