# Generated by Django 3.1.2 on 2020-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0071_auto_20201218_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='indv_valid',
            field=models.BooleanField(default='True', verbose_name='Entry still valid?'),
        ),
    ]
