# Generated by Django 3.1.2 on 2021-01-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_diversity', '0074_auto_20201223_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='prog_id',
            field=models.ForeignKey(limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='protocols', to='bio_diversity.program', verbose_name='Program'),
        ),
    ]
