from django.db import models
from django.utils.translation import gettext_lazy as _


YES_NO_UNKNOWN = (
    ('', ''),
    ('Yes', 'Yes'),
    ('No', 'No'),
    ('Unknown', 'Unknown'),
    ('Not Applicable', 'Not Applicable')
)

YES_NO_FLAG = (
    ('Yes', 'Yes'),
    ('No', 'No'),
    ('No-Remains in Paper copy', 'No-Remains in Paper copy'),
    ('No-Flag for Scanning', 'No-Flag for Scanning'),
    ('Other', 'Other'),
    ('Not applicable', 'Not applicable'),
    ('Unknown', 'Unknown'),
)

YES_NO = (
    ('', ''),
    ('Yes', 'Yes'),
    ('No', 'No'),
)

AGREEMENT_DATABASE = (
    ('GCATS (Grants & Contributions Agreement Tracking System)',
     'GCATS (Grants & Contributions Agreement Tracking System)'),
    ('AAROM Shared Drive', 'AAROM Shared Drive'),
    ('South Coast Shared Drive', 'South Coast Shared Drive'),
    ('North Coast Shared Drive', 'North Coast Shared Drive'),
    ('Fraser/Interior Shared Drive', 'Fraser/Interior Shared Drive'),
    ('Yukon/Transboundary Shared Drive', 'Yukon/Transboundary Shared Drive'),
    ('SEP Shared Drive', 'SEP Shared Drive'),
    ('Unknown', 'Unknown'),
    ('Not Applicable', 'Not Applicable'),
    ('PaRR Tracker', 'PaRR Tracker'),
    ('BCSRIF Shared Drive', 'BCSRIF Shared Drive'),
    ('Project Registry Atlas', 'Project Registry Atlas'),
    ('Stock Assessment Web Atlas', 'Stock Assessment Web Atlas'),
    ('Individual computer', 'Individual computer'),
    ('CFISH', 'CFISH'),
)

AGREEMENT_TYPE = (
    ('', ''),
    ('Primary Agreement', 'Primary Agreement'),
    ('Amendment', 'Amendment'),
    ('First Nations Treaty Agreement', 'First Nations Treaty Agreement'),
    ('Supply Arrangement', 'Supply Arrangement'),
    ('Contract', 'Contract'),
    ('Unknown', 'Unknown'),
    ('Not applicable', 'Not applicable'),
    ('Other', 'Other'),
)

LEAD_ORGANIZATION = (
    ('DFO - Other', 'DFO - Other'),
    ('First Nations', 'First Nations'),
    ('Collaborative', 'Collaborative'),
    ('Unknown', 'Unknown'),
    ('Not applicable', 'Not applicable'),
    ('Stewardship Society', 'Stewardship Society'),
    ('CCG', 'CCG'),
    ('EMB - FFHPP', 'EMB - FFHPP'),
    ('EMB - Oceans', 'EMB - Oceans'),
    ('SEP', 'SEP'),
    ('EMB - E-Watch Program', 'EMB - E-Watch Program'),
    ('EMB - TMX', 'EMB - TMX'),
    ('EMB - Lakes Program', 'EMB - Lakes Program'),
    ('EMB - Yukon', 'EMB - Yukon'),
    ('FAM - Salmon', 'FAM - Salmon'),
    ('FAM', 'FAM'),
    ('FAM - RM', 'FAM - RM'),
    ('FAM - Aquaculture', 'FAM - Aquaculture'),
    ('R&P - RA', 'R&P - RA'),
    ('R&P - BCSRIF', 'R&P - BCSRIF'),
    ('R&P - IPD', 'R&P - IPD'),
    ('R&P - PICFI', 'R&P - PICFI'),
    ('EMB - TMX', 'EMB - TMX'),
    ('R&P - Treaties', 'R&P - Treaties'),
    ('SCH', 'SCH'),
    ('Science - Aquatic Animal Health', 'Science - Aquatic Animal Health'),
    ('Science - Herring', 'Science - Herring'),
    ('Science - Groundfish', 'Science - Groundfish'),
    ('Science - Salmon Stock Assessment', 'Science - Salmon Stock Assessment'),
    ('Science - Ocean Protection Program', 'Science - Ocean Protection Program'),
    ('Science - Shellfish', 'Science - Shellfish'),
    ('Science - Genetics', 'Science - Genetics'),
    ('Science', 'Science'),
    ('C&P', 'C&P'),
    ('PSSI - Conservation and Stewardship', 'PSSI - Conservation and Stewardship'),
    ('PSSI - Enhanced Hatchery Production', 'PSSI - Enhanced Hatchery Production'),
    ('PSSI - Harvest Transformation', 'PSSI - Harvest Transformation'),
    ('PSSI - Integrated Management & Collaboration', 'PSSI - Integrated Management & Collaboration'),

)

AREA = (
    ('', ''),
    ("YTRA", "YTRA"),
    ("NCA", "NCA"),
    ("SCA", "SCA"),
    ("FIA", "FIA"),)


PROJECT_STAGE = (
    ('', ''),
    ('Proposed', 'Proposed'),
    ('Planning', 'Planning'),
    ('Pilot', 'Pilot'),
    ('Active', 'Active'),
    ('Complete', 'Complete'),
    ('Terminated', 'Terminated'),
    ('Unknown', 'Unknown'),
    ('Not applicable', 'Not applicable'),
    ('Other', 'Other'),
)

LEVEL_1 = (
    ('Population', 'Population'),
    ('Habitat', 'Habitat'),
    ('Catch', 'Catch'),
    ('Unknown', 'Unknown'),
    ('Operational Support', 'Operational Support'),
    ('Not applicable', 'Not applicable'),
)

GOVERNMENT_LINK = (
    ('Municipality', 'Municipality'),
    ('Province of British Columbia', 'Province of British Columbia'),
    ('Government of Yukon', 'Government of Yukon'),
    ('Environment Canada', 'Environment Canada'),
    ('Climate Change Canada', 'Climate Change Canada'),
    ('Alaska Department of Fish & Game', 'Alaska Department of Fish & Game'),
    ('Washington State', 'Washington State'),
    ('Unknown', 'Unknown'),
    ('Not applicable', 'Not applicable'),
    ('Other', 'Other'),
    ('Province of British Columbia - Ministry of Environment', 'Province of British Columbia - Ministry of Environment'),
    ('Canadian Food Inspection agency', 'Canadian Food Inspection agency'),
    ('Orgeon State', 'Orgeon State'),

)

ROLE = (
    ('', ''),
    ('Chief', 'Chief'),
    ('Biologist', 'Biologist'),
    ('Aquatics Manager', 'Aquatics Manager'),
    ('Technician', 'Technician'),
    ('Director', 'Director'),
    ('Fisheries Manager', 'Fisheries Manager'),
    ('Refuge Manager', 'Refuge Manager'),
    ('Scientist', 'Scientist'),
    ('Stewardship Director', 'Stewardship Director'),
    ('Unknown', 'Unknown'),
    ('Other', 'Other'),
)

COUNTRY_CHOICES = (
    ('', ''),
    ('Canada', 'Canada'),
    ('United States of America', 'United States of America'),
)

PROVINCE_STATE_CHOICES = (
    ('', ''),
    ('Alberta', 'Alberta'),
    ('British Columbia', 'British Columbia'),
    ('Manitoba', 'Manitoba'),
    ('New Brunswick', 'New Brunswick'),
    ('Newfoundland & Labrador', 'Newfoundland & Labrador'),
    ('Nova Scotia', 'Nova Scotia'),
    ('Ontario', 'Ontario'),
    ('Prince Edward Island', 'Prince Edward Island'),
    ('Quebec', 'Quebec'),
    ('Saskatchewan', 'Saskatchewan'),
    ('Northwest Territories', 'Northwest Territories'),
    ('Nunavut', 'Nunavut'),
    ('Yukon', 'Yukon'),
    ('Washington', 'Washington'),
    ('Alaska', 'Alaska'),
    ('Oregon', 'Oregon'),
)

ORGANIZATION_TYPE = (
    ('', ''),
    ('First Nation', 'First Nation'),
    ('Company', 'Company'),
    ('Government', 'Government'),
    ('Non-Profit Organization', 'Non-Profit Organization'),
    ('University', 'University'),
)

PLANNING_METHOD = (
    ('Feasibility Study', 'Feasibility Study'),
    ('Land Use Planning', 'Land Use Planning'),
    ('Not applicable', 'Not applicable'),
    ('Objective-setting', 'Objective-setting'),
    ('Other', 'Other'),
    ('Priority Setting', 'Priority Setting'),
    ('Project Design', 'Project Design'),
    ('Resource Allocation', 'Resource Allocation'),
    ('Project Review', 'Project Review'),
    ('Project Evaluation', 'Project Evaluation'),
    ('Method Development', 'Method Development'),
    ('Unknown', 'Unknown'),
)

FIELD_WORK = (
    ('Acoustic - Hydroacoustic', 'Acoustic - Hydroacoustic'),
    ('Acoustic - Trawl', 'Acoustic - Trawl'),
    ('Aerial - Drone', 'Aerial - Drone'),
    ('Aerial - Fixed Wing Aircraft', 'Aerial - Fixed Wing Aircraft'),
    ('Aerial - Helicopter', 'Aerial - Helicopter'),
    ('Aerial - Unspecified', 'Aerial - Unspecified'),
    ('Barrier Removal', 'Barrier Removal'),
    ('Biodata - Physical Measurement', 'Biodata - Physical Measurement'),
    ('Biodata - Tissue Collection', 'Biodata - Tissue Collection'),
    ('Biodata - Unspecified', 'Biodata - Unspecified'),
    ('Biodata - Visual Observation', 'Biodata - Visual Observation'),
    ('Boat', 'Boat'),
    ('Catch - Angling', 'Catch - Angling'),
    ('Catch - Creel', 'Catch - Creel'),
    ('Data Management', 'Data Management'),
    ('Deadpitch', 'Deadpitch'),
    ('Egg Collection', 'Egg Collection'),
    ('Electrofishing', 'Electrofishing'),
    ('Fence - Resistivity', 'Fence - Resistivity'),
    ('Fence - Unknown', 'Fence - Unknown'),
    ('Fence - Video', 'Fence - Video'),
    ('Fence - Visual', 'Fence - Visual'),
    ('Fish Health Condition', 'Fish Health Condition'),
    ('Fishway - Tunnels', 'Fishway - Tunnels'),
    ('Fishway - Unspecified', 'Fishway - Unspecified'),
    ('Floats', 'Floats'),
    ('Habitat Modifications - General', 'Habitat Modifications - General'),
    ('Habitat Monitoring - Composition/Condition', 'Habitat Monitoring - Composition/Condition'),
    ('Habitat Monitoring - General', 'Habitat Monitoring - General'),
    ('Habitat Monitoring - Spawning Grounds', 'Habitat Monitoring - Spawning Grounds'),
    ('Hatchery - Brood Collection', 'Hatchery - Brood Collection'),
    ('Hatchery - Enumeration', 'Hatchery - Enumeration'),
    ('Hatchery - Fish Culture', 'Hatchery - Fish Culture'),
    ('Hatchery - Fry Release', 'Hatchery - Fry Release'),
    ('Hatchery - Gamete Incubation', 'Hatchery - Gamete Incubation'),
    ('Hatchery - Pond Fry', 'Hatchery - Pond Fry'),
    ('Hatchery - Spawn Brood', 'Hatchery - Spawn Brood'),
    ('Indigenous Knowledge', 'Indigenous Knowledge'),
    ('Invasive Species Survey', 'Invasive Species Survey'),
    ('Mapping', 'Mapping'),
    ('Mark-Recapture-other', 'Mark-Recapture-other'),
    ('Microtrolling', 'Microtrolling'),
    ('Not applicable', 'Not applicable'),
    ('Other', 'Other'),
    ('Peak Live and Dead Count', 'Peak Live and Dead Count'),
    ('Photo Point', 'Photo Point'),
    ('Plankton Sampling', 'Plankton Sampling'),
    ('Raft', 'Raft'),
    ('Redd Counts', 'Redd Counts'),
    ('Riparian Monitoring', 'Riparian Monitoring'),
    ('River Surveyor', 'River Surveyor'),
    ('Roving', 'Roving'),
    ('Snorkle', 'Snorkle'),
    ('Sonar - ARIS', 'Sonar - ARIS'),
    ('Sonar - DIDSON', 'Sonar - DIDSON'),
    ('Sonar - unspecified', 'Sonar - unspecified'),
    ('Spot Checks', 'Spot Checks'),
    ('Stream Walks', 'Stream Walks'),
    ('Strip Counts', 'Strip Counts'),
    ('Tagging - Coded Wire Tag Recovery', 'Tagging - Coded Wire Tag Recovery'),
    ('Tagging - Coded Wire', 'Tagging - Coded Wire'),
    ('Tagging - Finclips', 'Tagging - Finclips'),
    ('Tagging - Hallprint', 'Tagging - Hallprint'),
    ('Taggng - Otolith Mark', 'Taggng - Otolith Mark'),
    ('Tagging - Parental Based', 'Tagging - Parental Based'),
    ('Tagging - PIT', 'Tagging - PIT'),
    ('Tagging - Radio', 'Tagging - Radio'),
    ('Tagging - Spaghetti', 'Tagging - Spaghetti'),
    ('Telemetry', 'Telemetry'),
    ('Tower', 'Tower'),
    ('Trapping - Cast Nets', 'Trapping - Cast Nets'),
    ('Trapping - Fishwheel', 'Trapping - Fishwheel'),
    ('Trapping - Fyke Net', 'Trapping - Fyke Net'),
    ('Trapping - Gill Net', 'Trapping - Gill Net'),
    ('Trapping - Rotary Screw Trap', 'Trapping - Rotary Screw Trap'),
    ('Trapping - Seine', 'Trapping - Seine'),
    ('Trapping - Smolt', 'Trapping - Smolt'),
    ('Trapping - Tangle Nets', 'Trapping - Tangle Nets'),
    ('Unknown', 'Unknown'),
    ('Vegetation Planting', 'Vegetation Planting'),
    ('Vegetation Survey', 'Vegetation Survey'),
    ('Water Sampling - Biological', 'Water Sampling - Biological'),
    ('Water Sampling - Chemical', 'Water Sampling - Chemical'),
    ('Water Sampling - Chemical - Oxygen', 'Water Sampling - Chemical - Oxygen'),
    ('Water Sampling - Physical', 'Water Sampling - Physical'),
    ('Water Sampling - Physical - Temperature', 'Water Sampling - Physical - Temperature'),
    ('Weir', 'Weir'),

)

SAMPLE_PROCESSING = (
    ('DNA', 'DNA'),
    ('Heads', 'Heads'),
    ('Instrument Data Processing', 'Instrument Data Processing'),
    ('Not applicable', 'Not applicable'),
    ('Other', 'Other'),
    ('Otoliths', 'Otoliths'),
    ('Pathogens/Disease', 'Pathogens/Disease'),
    ('Scales', 'Scales'),
    ('Tag Processing', 'Tag Processing'),
    ('Unknown', 'Unknown'),

)

DATA_ENTRY = (
    ('', ''),
    ('Direct entry into computer', 'Direct entry into computer'),
    ('Direct entry into database', 'Direct entry into database'),
    ('Direct entry into database', 'Paper, Followed by Entry into Computer'),
    ('Unknown', 'Unknown'),
    ('Not applicable', 'Not applicable'),
    ('Other', 'Other'),
)

METHOD_DOCUMENT = (
    ('Program Document', 'Program Document'),
    ('Administration Document ', 'Administration Document '),
    ('Conference paper/abstract', 'Conference paper/abstract'),
    ('Book', 'Book'),
    ('CSAS document', 'CSAS document'),
    ('Contract', 'Contract'),
    ('Statement of Work ', 'Statement of Work '),
    ('Training Document', 'Training Document'),
    ('Protocol', 'Protocol'),
    ('Field Notes', 'Field Notes'),
    ('Journal Article', 'Journal Article'),
    ('Guidance Document', 'Guidance Document'),
    ('Unknown', 'Unknown'),
    ('Other', 'Other'),

)


DATABASE = (
    ('ADF&G Zander ', 'ADF&G Zander '),
    ('PSMFC CWT', 'PSMFC CWT'),
    ('ADF&G Rergion 1', 'ADF&G Rergion 1'),
    ('ADF&G CWT Online Release', 'ADF&G CWT Online Release'),
    ('ADF&G SF Research and Technical Services', 'ADF&G SF Research and Technical Services'),
    ('NuSEDs', 'NuSEDs'),
    ('iREC', 'iREC'),
    ('KREST', 'KREST'),
    ('First Nations databases', 'First Nations databases'),
    ('Shared DFO Drives', 'Shared DFO Drives'),
    ('First Nations Harvest (AHMS)', 'First Nations Harvest (AHMS)'),
    ('Fishery Operations System (FOS)', 'Fishery Operations System (FOS)'),
    ('Mark Recovery Program (MRPRO)', 'Mark Recovery Program (MRPRO)'),
    ('Clockwork', 'Clockwork'),
    ('Biodatabase (South Coast DFO)', 'Biodatabase (South Coast DFO)'),
    ('PADS', 'PADS'),
    ('Otomanager', 'Otomanager'),
    ('Pacific Salmon Commission', 'Pacific Salmon Commission'),
    ('Genetics Group (PBS)', 'Genetics Group (PBS)'),
    ('Individual computer', 'Individual computer'),
    ('Pacific States Marine Fisheries Commission (www.rmpc.org)',
     'Pacific States Marine Fisheries Commission (www.rmpc.org)'),
    ('Central Coast FSC Catch', 'Central Coast FSC Catch'),
    ('Private', 'Private'),
    ('PIT Tag Information System (PTAGIS)', 'PIT Tag Information System (PTAGIS)'),
    ('Not Applicable', 'Not Applicable'),
    ('Other', 'Other'),
    ('CREST', 'CREST'),
    ('EPADS', 'EPADS'),
    ('ATS (Acoustic Trawl)', 'ATS (Acoustic Trawl)'),
    ('E-PRO', 'E-PRO'),
    ('Unknown', 'Unknown'),
    ('SIL/AUC Database', 'SIL/AUC Database'),
    ('ENPRO', 'ENPRO'),
    ('Excel Spreadsheet', 'Excel Spreadsheet'),
    ('CFISH', 'CFISH'),

)

SAMPLE_BARRIER = (
    ('', ''),
    ('Weather', 'Weather'),
    ('Site Access', 'Site Access'),
    ('Equipment Failure', 'Equipment Failure'),
    ('Equipment Not Available', 'Equipment Not Available'),
    ('Staffing Unavailable', 'Staffing Unavailable'),
    ('Staffing Not Trained', 'Staffing Not Trained'),
    ('Unknown', 'Unknown'),
    ('Not Applicable', 'Not Applicable'),
    ('Other', 'Other'),
)

DATA_BARRIER = (
    ('', ''),
    ('No Person Available', 'No Person Available'),
    ('Sample Data Requires More Work Before it can be Entered into Database', 'Sample Data Requires More Work Before it can be Entered into Database'),
    ('Person Available but Lack of Training', 'Person Available but Lack of Training'),
    ('Equipment is Available but not Working', 'Equipment is Available but not Working'),
    ('Equipment is not Available', 'Equipment is not Available'),
    ('IT Issues', 'IT Issues'),
    ('Network Connection Issues', 'Network Connection Issues'),
    ('UNKNOWN', 'Unknown'),
    ('Not Applicable', 'Not Applicable'),
    ('Other', 'Other'),
)

SAMPLE_FORMAT = (
    ('Excel', 'Excel'),
    ('Paper', 'Paper'),
    ('Log Books', 'Log Books'),
    ('Word', 'Word'),
    ('SIL-hardcopy', 'SIL-hardcopy'),
    ('SIL-digitized', 'SIL-digitized'),
    ('Instrument Program', 'Instrument Program'),
    ('Direct Entry into Computer', 'Direct Entry into Computer'),
    ('SENS', 'SENS'),
    ('Not Applicable', 'Not Applicable'),
    ('Other', 'Other'),
    ('Video', 'Video'),
    ('Unknown', 'Unknown'),
)

DATA_PRODUCTS = (
    ('Relative Abundance', 'Relative Abundance'),
    ('Escapement Estimate - expanded/final', 'Escapement Estimate - expanded/final'),
    ('Escapement Estimate - unexpanded/preliminary', 'Escapement Estimate - unexpanded/preliminary'),
    ('Habitat data', 'Habitat data'),
    ('Harvest rate', 'Harvest rate'),
    ('Stock Recruitment', 'Stock Recruitment'),
    ('Survival Rate ', 'Survival Rate '),
    ('Marked status', 'Marked status'),
    ('Proportion of sampled fish effort/time', 'Proportion of sampled fish effort/time'),
    ('Proportion of in-river salmon destined for spawning', 'Proportion of in-river salmon destined for spawning'),
    ('Sex Composition', 'Sex Composition'),
    ('Age Composition Data', 'Age Composition Data'),
    ('Stock composition (GSI / DNA)Data', 'Stock composition (GSI / DNA)Data'),
    ('Condition of Fish - (DNA based)', 'Condition of Fish - (DNA based)'),
    ('Ratio of catchability', 'Ratio of catchability'),
    ('ESSR Targets', 'ESSR Targets'),
    ('Hatchery Production', 'Hatchery Production'),
    ('Biomass Data', 'Biomass Data'),
    ('Spawning Success', 'Spawning Success'),
    ('Fish Passage Data', 'Fish Passage Data'),
    ('Predation rates', 'Predation rates'),
    ('Other', 'Other'),
    ('Hatchery data', 'Hatchery data'),
    ('Unknown', 'Unknown'),
    ('Not applicable', 'Not applicable'),
)

DATA_COMMUNICATION = (
    ('', ''),
    ('Presentations', 'Presentations'),
    ('Workshops', 'Workshops'),
    ('Reports', 'Reports'),
    ('Data Summaries', 'Data Summaries'),
    ('Bulletins', 'Bulletins'),
    ('Unknown', 'Unknown'),
    ('Not Applicable', 'Not Applicable'),
    ('Other', 'Other'),
)

REPORT_TIMELINE = (
    ('Progress', 'Progress'),
    ('Final', 'Final'),
    ('Preliminary', 'Preliminary'),
    ('Other', 'Other'),
    ('Not applicable', 'Not applicable'),
    ('Unknown', 'Unknown'),
    ('Interim', 'Interim'),
    ('Quarterly', 'Quarterly'),
)

REPORT_TYPE = (
    ('Community - Communication', 'Community - Communication'),
    ('Community - Other', 'Community - Other'),
    ('Community - Report', 'Community - Report'),
    ('Management - Administration Report', 'Management - Administration Report'),
    ('Management - Briefing Note', 'Management - Briefing Note'),
    ('Management - Memorandum of Understanding', 'Management - Memorandum of Understanding'),
    ('Management - Other', 'Management - Other'),
    ('Management - Planning Report', 'Management - Planning Report'),
    ('Management - Service Agreement', 'Management - Service Agreement'),
    ('Not applicable', 'Not applicable'),
    ('Other', 'Other'),
    ('Program - Administration - General Report', 'Program - Administration - General Report'),
    ('Program - Administration - Finance Report', 'Program - Administration - Finance Report'),
    ('Program - Funding - Annual Report', 'Program - Funding - Annual Report'),
    ('Program - Funding - Meeting Summary', 'Program - Funding - Meeting Summary'),
    ('Program - Funding - Other', 'Program - Funding - Other'),
    ('Program - Funding - Pacific Salmon Commission Report', 'Program - Funding - Pacific Salmon Commission Report'),
    ('Program - Funding - Schedule 7', 'Program - Funding - Schedule 7'),
    ('Program - Funding - Schedule E', 'Program - Funding - Schedule E'),
    ('Program - Salmon Enhancement - Annual Hatchery Report', 'Program - Salmon Enhancement - Annual Hatchery Report'),
    ('Program - Salmon Enhancement - Data Summary', 'Program - Salmon Enhancement - Data Summary'),
    ('Program - Salmon Enhancement - Meeting Summary', 'Program - Salmon Enhancement - Meeting Summary'),
    ('Program - Salmon Enhancement - Hatchery Review', 'Program - Salmon Enhancement - Hatchery Review'),
    ('Program - Salmon Enhancement - Modelling', 'Program - Salmon Enhancement - Modelling'),
    ('Program - Salmon Enhancement - Other Report', 'Program - Salmon Enhancement - Other Report'),
    ('Program - Salmon Enhancement - Spacial Data', 'Program - Salmon Enhancement - Spacial Data'),
    ('Program - Salmon Enhancement - Year End Report', 'Program - Salmon Enhancement - Year End Report'),
    ('Program - Salmon Enhancement - Habitat Report', 'Program - Salmon Enhancement - Habitat Report'),
    ('Program - Science - Annual Stream Report', 'Program - Science - Annual Stream Report'),
    ('Program - Science - Commissioned Area Report', 'Program - Science - Commissioned Area Report'),
    ('Program - Science - Data Summary', 'Program - Science - Data Summary'),
    ('Program - Science - Meeting Summary', 'Program - Science - Meeting Summary'),
    ('Program - Science - Modelling', 'Program - Science - Modelling'),
    ('Program - Science - Other Report', 'Program - Science - Other Report'),
    ('Program - Science - Spacial Data', 'Program - Science - Spacial Data'),
    ('Program - Science - Technical Committee Report', 'Program - Science - Technical Committee Report'),
    ('Program - Science - Year End Report', 'Program - Science - Year End Report'),
    ('Program - Science - Habitat Report', 'Program - Science - Habitat Report'),
    ('Project - Administration Report', 'Project - Administration Report'),
    ('Project - General Summary', 'Project - General Summary'),
    ('Project - Information Technology Report', 'Project - Information Technology Report'),
    ('Project - Operations Report', 'Project - Operations Report'),
    ('Project - Activities Summary', 'Project - Activities Summary'),
    ('Project - Other Report', 'Project - Other Report'),
    ('Project - Peer Reviewed Publication', 'Project - Peer Reviewed Publication'),
    ('Project - Restoration Summary', 'Project - Restoration Summary'),
    ('Project - Study Design Report', 'Project - Study Design Report'),
    ('Project - Habitat Report', 'Project - Habitat Report'),
    ('Project - Methods Report', 'Project - Methods Report'),
    ('Project - Escapement Report', 'Project - Escapement Report'),
    ('Project - Enhancement Production Report', 'Project - Enhancement Production Report'),
    ('Project - Technical Report', 'Project - Technical Report'),
    ('Public - Bulletin', 'Public - Bulletin'),
    ('Public - CSAS Reports', 'Public - CSAS Reports'),
    ('Public - Fact Sheet', 'Public - Fact Sheet'),
    ('Public - Newsletter', 'Public - Newsletter'),
    ('Public - Open Data', 'Public - Open Data'),
    ('Public - Press Release', 'Public - Press Release'),
    ('Public - Website', 'Public - Website'),
    ('Unknown', 'Unknown'),

)

KEY_ELEMENT = (
    ('', ''),
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'B'),
    ('D', 'D'),
    ('OTHER', 'Other'),
)

ACTIVITY_NUMBER = (
    ('', ''),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('OTHER', 'Other'),
)

SAMPLE_TYPE_OUTCOMES = (
    ('Brood Collection', 'Brood Collection'),
    ('Catch Effort', 'Catch Effort'),
    ('Clips - Adipose', 'Clips - Adipose'),
    ('Clips - Auxillary Appendage', 'Clips - Auxillary Appendage'),
    ('Clips - Fin', 'Clips - Fin'),
    ('Egg Characteristics', 'Egg Characteristics'),
    ('Egg Take', 'Egg Take'),
    ('Enhancement Targets', 'Enhancement Targets'),
    ('Enhancement-Unspecified', 'Enhancement-Unspecified'),
    ('Fish Condition - General Health', 'Fish Condition - General Health'),
    ('Fish Condition - Length', 'Fish Condition - Length'),
    ('Fish Condition - Secondary Marks', 'Fish Condition - Secondary Marks'),
    ('Fish Condition - Sex', 'Fish Condition - Sex'),
    ('Fish Condition - Species Identification', 'Fish Condition - Species Identification'),
    ('Fish Condition - Weight', 'Fish Condition - Weight'),
    ('Fish Distribution', 'Fish Distribution'),
    ('Fish Enumeration', 'Fish Enumeration'),
    ('Forestry Data-Unspecified', 'Forestry Data-Unspecified'),
    ('Habitat Composition', 'Habitat Composition'),
    ('Habitat Condition', 'Habitat Condition'),
    ('Habitat Use', 'Habitat Use'),
    ('Incubation', 'Incubation'),
    ('Mark/Tagging-Unspecified', 'Mark/Tagging-Unspecified'),
    ('Not applicable', 'Not applicable'),
    ('Predation', 'Predation'),
    ('Sea Lice Count', 'Sea Lice Count'),
    ('Tag Recovery - CWT', 'Tag Recovery - CWT'),
    ('Tag Recovery - PIT', 'Tag Recovery - PIT'),
    ('Tag Recovery - Spaghetti', 'Tag Recovery - Spaghetti'),
    ('Tag Recovery - Unspecified', 'Tag Recovery - Unspecified'),
    ('Tagging - CWT', 'Tagging - CWT'),
    ('Tagging - PIT', 'Tagging - PIT'),
    ('Tagging - Spaghetti', 'Tagging - Spaghetti'),
    ('Tagging - Unspecified', 'Tagging - Unspecified'),
    ('Tissue Collection - DNA', 'Tissue Collection - DNA'),
    ('Tissue Collection - Heads', 'Tissue Collection - Heads'),
    ('Tissue Collection - Otoliths', 'Tissue Collection - Otoliths'),
    ('Tissue Collection - Pathogen', 'Tissue Collection - Pathogen'),
    ('Tissue Collection - Scales', 'Tissue Collection - Scales'),
    ('Tissue Collection - Unspecified Biodata', 'Tissue Collection - Unspecified Biodata'),
    ('Unknown', 'Unknown'),
    ('Water - Hydrology', 'Water - Hydrology'),
    ('Water - Physical - Dissolved Oxygen', 'Water - Physical - Dissolved Oxygen'),
    ('Water - Physical - Salinity', 'Water - Physical - Salinity'),
    ('Water - Physical - Other', 'Water - Physical - Other'),
    ('Water - Physical - Temperature', 'Water - Physical - Temperature'),
    ('Water Samples - Biotoxin', 'Water Samples - Biotoxin'),
    ('Water Samples - eDNA', 'Water Samples - eDNA'),
    ('Water Samples - Microscopic Examination', 'Water Samples - Microscopic Examination'),
    ('Water Samples - Toxicology', 'Water Samples - Toxicology'),
    ('Water Samples - Unspecified', 'Water Samples - Unspecified'),

)

# Outcomes category, drop downs column V
REPORT_OUTCOMES = (
    ('Administrative Activity - General', 'Administrative Activity - General'),
    ('Analyzed Data - Data Summary', 'Analyzed Data - Data Summary'),
    ('Analyzed Data - Expanded Estimates', 'Analyzed Data - Expanded Estimates'),
    ('Analyzed Data - Non-expanded Estimates', 'Analyzed Data - Non-expanded Estimates'),
    ('Analyzed Data - Other', 'Analyzed Data - Other'),
    ('Analyzed Data - Outlooks', 'Analyzed Data - Outlooks'),
    ('Analyzed Data - Trends', 'Analyzed Data - Trends'),
    ('Aquaculture Activity', 'Aquaculture Activity'),
    ('Assessment Activity', 'Assessment Activity'),
    ('Biological Activity - Monitoring', 'Biological Activity - Monitoring'),
    ('Biological Activity - General', 'Biological Activity - General'),
    ('Catch Activity - General', 'Catch Activity - General'),
    ('Communication Activity', 'Communication Activity'),
    ('Data Entry - General', 'Data Entry - General'),
    ('Educational Activity - Classroom', 'Educational Activity - Classroom'),
    ('Educational Activity - Cultural', 'Educational Activity - Cultural'),
    ('Educational Activity - Event', 'Educational Activity - Event'),
    ('Educational Activity - General', 'Educational Activity - General'),
    ('Educational Activity - Outreach', 'Educational Activity - Outreach'),
    ('Educational Activity - Public', 'Educational Activity - Public'),
    ('Educational Activity - Tour', 'Educational Activity - Tour'),
    ('Educational Activity - Volunteer', 'Educational Activity - Volunteer'),
    ('Enhancement Activity - Hatchery', 'Enhancement Activity - Hatchery'),
    ('Enhancement Activity - Production Numbers', 'Enhancement Activity - Production Numbers'),
    ('Enhancement Activity - Brood Year Summary', 'Enhancement Activity - Brood Year Summary'),
    ('Enhancement Activity - Egg Take Summary', 'Enhancement Activity - Egg Take Summary'),
    ('Enhancement Activity - General', 'Enhancement Activity - General'),
    ('Feedback - Barrier to Achieving Outcome', 'Feedback - Barrier to Achieving Outcome'),
    ('Feedback - Improved Community Capacity', 'Feedback - Improved Community Capacity'),
    ('Feedback - Key Lessons Learned (by DFO)', 'Feedback - Key Lessons Learned (by DFO)'),
    ('Feedback - Report Concerns', 'Feedback - Report Concerns'),
    ('Feedback - Missed Opportunity (by DFO)', 'Feedback - Missed Opportunity (by DFO)'),
    ('Feedback - Other', 'Feedback - Other'),
    ('Habitat Activity - General', 'Habitat Activity - General'),
    ('Habitat Activity - Site Detail', 'Habitat Activity - Site Detail'),
    ('Indigenous Activity - General', 'Indigenous Activity - General'),
    ('Indigenous Activity - Knowledge', 'Indigenous Activity - Knowledge'),
    ('Infrastructure Activity - Construction', 'Infrastructure Activity - Construction'),
    ('Infrastructure Activity - General', 'Infrastructure Activity - General'),
    ('Infrastructure Activity - Installation', 'Infrastructure Activity - Installation'),
    ('Infrastructure Activity - Maintenance', 'Infrastructure Activity - Maintenance'),
    ('Jobs - New Staff', 'Jobs - New Staff'),
    ('Jobs - Staff Maintained', 'Jobs - Staff Maintained'),
    ('Jobs - Staff Trained', 'Jobs - Staff Trained'),
    ('Other', 'Other'),
    ('Administrative Activity - Partners', 'Administrative Activity - Partners'),
    ('Planning Activity - General', 'Planning Activity - General'),
    ('Planning Activity - Framework', 'Planning Activity - Framework'),
    ('Planning Activity - Meeting Summary', 'Planning Activity - Meeting Summary'),
    ('Planning Activity - Workshop', 'Planning Activity - Workshop'),
    ('Raw Data', 'Raw Data'),
    ('Report Document - Other', 'Report Document - Other'),
    ('Restoration Activity - Estuarine', 'Restoration Activity - Estuarine'),
    ('Restoration Activity - Fish Passage', 'Restoration Activity - Fish Passage'),
    ('Restoration Activity - Floodplain Connectivity', 'Restoration Activity - Floodplain Connectivity'),
    ('Restoration Activity - Instream Structure', 'Restoration Activity - Instream Structure'),
    ('Restoration Activity - Nearshore and Marine', 'Restoration Activity - Nearshore and Marine'),
    ('Restoration Activity - Riparian ', 'Restoration Activity - Riparian '),
    ('Submitted Samples', 'Submitted Samples'),
    ('Unknown', 'Unknown'),
    ('Citizen Science Activity - Sample Collection', 'Citizen Science Activity - Sample Collection'),
    ('Citizen Science Activity - Equipment Support', 'Citizen Science Activity - Equipment Support'),
    ('Citizen Science Activity - DFO Support', 'Citizen Science Activity - DFO Support'),
    ('Non-funded Supporting Group - Sample Collection', 'Non-funded Supporting Group - Sample Collection'),
    ('Non-funded Supporting Group - Equipment Support', 'Non-funded Supporting Group - Equipment Support'),
    ('Non-funded Supporting Group - DFO Support', 'Non-funded Supporting Group - DFO Support'),
    ('In-kind Contribution', 'In-kind Contribution'),
    ('Planning Activity - Goal Setting', 'Planning Activity - Goal Setting'),
    ('Planning Activity - Definition Setting', 'Planning Activity - Definition Setting'),
    ('Report Document - Guidance Development', 'Report Document - Guidance Development'),
    ('Report Document - Method Development', 'Report Document - Method Development'),
    ('Report Document - Summary of Activities', 'Report Document - Summary of Activities'),
    ('Report Document - Stream Inspection Log', 'Report Document - Stream Inspection Log'),

)

CAPACITY = (
    ('', ''),
    ('NEW TRAINING', 'New Training'),
    ('NEW STAFF INTEREST', 'New staff interest'),
    ('VOLUNTEERS SHOWED INTEREST', 'Volunteers showed interest'),
    ('COMMUNITY CONNECTIONS MADE', 'Community connections made'),
    ('PUBLIC ENGAGEMENT', 'Public engagement'),
    ('PREVIOUS STAFF TRAINING UPGRADED', 'Previous Staff Training upgraded'),
    ('EQUIPMENT RESOURCES IMPROVED', 'Equipment resources improved'),
    ('IMPROVED FISHERIES KNOWLEDGE AMONG COMMUNITY', 'Improved fisheries knowledge among community'),
    ('IMPROVED COMMUNICATION BETWEEN DFO AND FUNDING RECIPIENT', 'Improved communication between DFO and funding recipient'),
)

DATA_QUALITY = (
    ('', ''),
    ('Level 1 (Very High Quality)', 'Level 1 (Very High Quality)'),
    ('Level 2 (High Quality)', 'Level 2 (High Quality)'),
    ('Level 3 (Good Quality)', 'Level 3 (Good Quality)'),
    ('Level 4 (Moderate Quality)', 'Level 4 (Moderate Quality)'),
    ('Level 5 (Low Quality)', 'Level 5 (Low Quality)'),
    ('Unknown', 'Unknown'),
    ('Not Applicable', 'Not Applicable'),
)

OUTCOME_BARRIER = (
    ('', ''),
    ('Site Access', 'Site Access'),
    ('Equipment Failure', 'Equipment Failure'),
    ('Equipment not Available', 'Equipment not Available'),
    ('Staffing Unavailable', 'Staffing Unavailable'),
    ('Staffing not Trained', 'Staffing not Trained'),
    ('Weather', 'Weather'),
)

SUBJECT = (
    ('', ''),
    ('People', 'People'),
    ('Projects', 'Projects'),
    ('Objectives', 'Objectives'),
    ('Methods', 'Methods'),
    ('Data', 'Data'),
    ('Organizations', 'Organizations'),
    ('Other', 'Other'),
)

FN_COMMUNICATIONS = (
    ('', ''),
    ('Presentations', 'Presentations'),
    ('Workshops', 'Workshops'),
    ('Reports', 'Reports'),
    ('Data Summaries', 'Data Summaries'),
    ('Bulletins', 'Bulletins'),
    ('Other', 'Other'),
    ('Not Applicable', 'Not Applicable'),
)

ELEMENT_TITLE = (
    ('', ''),
    ('Aquatic Resource Management and Stewardship', 'Aquatic Resource Management and Stewardship'),
    ('Food, Social and Ceremonial (FSC) Fisheries Manangement', 'Food, Social and Ceremonial (FSC) Fisheries Manangement'),
    ('Economic Opportunities', 'Economic Opportunities'),
    ('Aquatic Resource Management Compliance and Accountability', 'Aquatic Resource Management Compliance and Accountability'),
    ('Annual Work Plan', 'Annual Work Plan'),
    ('Unknown', 'Unknown'),
    ('Not Applicable', 'Not Applicable'),

)

FUNDING_YEARS = (
    ('', ''),
    ('17/18', '17/18'),
    ('18/19', '18/19'),
    ('19/20', '19/20'),
    ('20/21', '20/21'),
    ('21/22', '21/22'),
    ('22/23', '22/23'),
    ('23/24', '23/24'),
    ('24/25', '24/25'),
    ('25/26', '25/26'),
    ('26/27', '26/27'),
    ('27/28', '27/28'),
    ('28/29', '28/29'),
    ('29/30', '29/30'),
    ('30/31', '30/31'),
    ('31/32', '31/32'),
    ('32/33', '32/33'),
    ('33/34', '33/34'),
    ('34/35', '34/35'),
    ('35/36', '35/36'),
    ('36/37', '36/37'),
    ('37/38', '37/38'),
    ('38/39', '38/39'),
    ('39/40', '39/40'),
    ('40/41', '40/41'),
    ('41/42', '41/42'),
    ('42/43', '42/43'),
    ('43/44', '43/44'),
    ('44/45', '44/45'),
    ('45/46', '45/46'),
    ('46/47', '46/47'),
    ('47/48', '47/48'),
    ('48/49', '48/49'),
    ('49/50', '49/50'),

)

POLICY_PROGRAM = (
    ('', ''),
    ('Strategic Species At Risk Act (SARA) Recovery Plans', 'Strategic Species At Risk Act (SARA) Recovery Plans'),
    ('COSEWIC Assessed Populations', 'COSEWIC Assessed Populations'),
    ('WSP Implementation', 'WSP Implementation'),
    ('Fisheries Act Rebuilding Plans', 'Fisheries Act Rebuilding Plans'),
    ('Southern BC Chinook Initiative', 'Southern BC Chinook Initiative'),
    ('Pacific Salmon Treaty', 'Pacific Salmon Treaty'),
    ('Pacific Salmon Strategy Initiative', 'Pacific Salmon Strategy Initiative'),
    ('Unknown', 'Unknown'),
    ('Not Applicable', 'Not Applicable'),
    ('Other', 'Other'),
)

STOCK_MANAGEMENT_UNIT = (
    ('', ''),
    ('FRASER SOCKEYE SALMON -EARLY STUART', 'FRASER SOCKEYE SALMON -EARLY STUART'),
    ('Unknown', 'Unknown'),
    ('NO DESIGNATED SMU', 'NO DESIGNATED SMU'),
    ('CENTRAL COAST COHO SALMON', 'CENTRAL COAST COHO SALMON'),
    ('CENTRAL COAST PINK SALMON', 'CENTRAL COAST PINK SALMON'),
    ('CENTRAL COAST CHUM SALMON', 'CENTRAL COAST CHUM SALMON'),
    ('CENTRAL COAST CHINOOK SALMON', 'CENTRAL COAST CHINOOK SALMON'),
    ('FRASER SOCKEYE SALMON - SUMMER', 'FRASER SOCKEYE SALMON - SUMMER'),
    ('JOHNSTONE STRAIT/MAINLAND INLET COHO SALMON', 'JOHNSTONE STRAIT/MAINLAND INLET COHO SALMON'),
    ('ECVI/MAINLAND PINK SALMON - EVEN', 'ECVI/MAINLAND PINK SALMON - EVEN'),
    ('ECVI/MAINLAND PINK SALMON - ODD', 'ECVI/MAINLAND PINK SALMON - ODD'),
    ('INNER SOUTH COAST CHUM SALMON', 'INNER SOUTH COAST CHUM SALMON'),
    ('NA', 'NA'),
    ('FRASER SOCKEYE SALMON - LATE', 'FRASER SOCKEYE SALMON - LATE'),
    ('FRASER SUMMER RUN 41 CHINOOK SALMON', 'FRASER SUMMER RUN 41 CHINOOK SALMON'),
    ('INTERIOR FRASER COHO SALMON', 'INTERIOR FRASER COHO SALMON'),
    ('FRASER PINK SALMON - ODD', 'FRASER PINK SALMON - ODD'),
    ('HAIDA GWAII PINK SALMON', 'HAIDA GWAII PINK SALMON'),
    ('HAIDA GWAII CHUM SALMON', 'HAIDA GWAII CHUM SALMON'),
    ('FRASER SPRING RUN 52 CHINOOK SALMON', 'FRASER SPRING RUN 52 CHINOOK SALMON'),
    ('HAIDA GWAII SOCKEYE SALMON', 'HAIDA GWAII SOCKEYE SALMON'),
    ('SKEENA COHO SALMON', 'SKEENA COHO SALMON'),
    ('SKEENA SOCKEYE SALMON', 'SKEENA SOCKEYE SALMON'),
    ('SKEENA PINK SALMON', 'SKEENA PINK SALMON'),
    ('SKEENA CHUM SALMON', 'SKEENA CHUM SALMON'),
    ('WCVI CHUM SALMON', 'WCVI CHUM SALMON'),
    ('Not a CU but a category to hold sites that for some reason are not assigned to a CU.',
     'Not a CU but a category to hold sites that for some reason are not assigned to a CU.'),
    ('Extirpated', 'Extirpated'),
    ('FRASER CHUM SALMON', 'FRASER CHUM SALMON'),
    ('NASS PINK SALMON', 'NASS PINK SALMON'),
    ('SKEENA - NASS COASTAL', 'SKEENA - NASS COASTAL'),
    ('ALSEK CHINOOK SALMON', 'ALSEK CHINOOK SALMON'),
    ('SKEENA CHINOOK SALMON', 'SKEENA CHINOOK SALMON'),
    ('WCVI COHO SALMON', 'WCVI COHO SALMON'),
    ('WCVI PINK SALMON', 'WCVI PINK SALMON'),
    ('RIVERS/SMITH SOCKEYE SALMON', 'RIVERS/SMITH SOCKEYE SALMON'),
    ('STRAIT OF GEORGIA COHO SALMON', 'STRAIT OF GEORGIA COHO SALMON'),
    ('FRASER SOCKEYE SALMON - EARLY SUMMER', 'FRASER SOCKEYE SALMON - EARLY SUMMER'),
    ('WCVI -OTHER SOCKEYE SALMON', 'WCVI -OTHER SOCKEYE SALMON'),
    ('NASS COHO SALMON', 'NASS COHO SALMON'),
    ('NASS CHUM SALMON', 'NASS CHUM SALMON'),
    ('NASS CHINOOK SALMON', 'NASS CHINOOK SALMON'),
    ('VREQ[Not a CU]', 'VREQ[Not a CU]'),
    ('CENTRAL COAST SOCKEYE SALMON', 'CENTRAL COAST SOCKEYE SALMON'),
    ('FRASER SUMMER RUN 52 CHINOOK SALMON', 'FRASER SUMMER RUN 52 CHINOOK SALMON'),
    ('STIKINE CHINOOK SALMON', 'STIKINE CHINOOK SALMON'),
    ('FRASER SPRING RUN 42 CHINOOK SALMON', 'FRASER SPRING RUN 42 CHINOOK SALMON'),
    ('YUKON CHINOOK SALMON', 'YUKON CHINOOK SALMON'),
    ('LOWER FRASER COHO SALMON', 'LOWER FRASER COHO SALMON'),
    ('NASS SOCKEYE SALMON', 'NASS SOCKEYE SALMON'),
    ('STIKINE COHO SALMON', 'STIKINE COHO SALMON'),
    ('YUKON CHUM SALMON', 'YUKON CHUM SALMON'),
    ('STIKINE SOCKEYE SALMON', 'STIKINE SOCKEYE SALMON'),
    ('HAIDA GWAII CHINOOK SALMON', 'HAIDA GWAII CHINOOK SALMON'),
    ('TAKU COHO SALMON', 'TAKU COHO SALMON'),
    ('TAKU CHINOOK SALMON', 'TAKU CHINOOK SALMON'),
    ('PORCUPINE CHUM SALMON', 'PORCUPINE CHUM SALMON'),
    ('ECVI/MAINLAND SOCKEYE SALMON', 'ECVI/MAINLAND SOCKEYE SALMON'),
    ('VREQ[Extirpated]', 'VREQ[Extirpated]'),
    ('FRASER FALL RUN 41 CHINOOK SALMON', 'FRASER FALL RUN 41 CHINOOK SALMON'),
    ('WCVI - BARKLEY SOCKEYE SALMON', 'WCVI - BARKLEY SOCKEYE SALMON'),
    ('TAKU SOCKEYE SALMON', 'TAKU SOCKEYE SALMON'),
    ('MAINLAND INLET CHINOOK SALMON', 'MAINLAND INLET CHINOOK SALMON'),
    ('ALSEK SOCKEYE SALMON', 'ALSEK SOCKEYE SALMON'),
    ('ALSEK COHO SALMON', 'ALSEK COHO SALMON'),
    ('PORCUPINE CHINOOK SALMON', 'PORCUPINE CHINOOK SALMON'),
    ('Transboundary Pink Salmon', 'Transboundary Pink Salmon'),
    ('MIDDLE GEORGIA STRAIT', 'MIDDLE GEORGIA STRAIT'),
    ('OKANAGAN SOCKEYE SALMON', 'OKANAGAN SOCKEYE SALMON'),

)

SPECIES = (
    ('', ''),
    ('Chum','Chum'),
    ('Coho','Coho'),
    ('Chinook','Chinook'),
    ('Pink-Even','Pink-Even'),
    ('Pink-Odd','Pink-Odd'),
    ('Sockeye-Lake','Sockeye-Lake'),
    ('Sockeye-River','Sockeye-River'),
    ('Unknown','Unknown'),

)

LEVEL_2 = (
    ('Population Distribution and Abundance', 'Population Distribution and Abundance'),
    ('Stock-recruit Dynamics', 'Stock-recruit Dynamics'),
    ('Demographics', 'Demographics'),
    ('Mortality Sources', 'Mortality Sources'),
    ('Dispersal and Migration Behaviour', 'Dispersal and Migration Behaviour'),
    ('Foraging Behaviour / Growth', 'Foraging Behaviour / Growth'),
    ('Intraspecific Interactions', 'Intraspecific Interactions'),
    ('Invasive Species', 'Invasive Species'),
    ('Diseases, Pathogens, and Parasites', 'Diseases, Pathogens, and Parasites'),
    ('Fish Physiology', 'Fish Physiology'),
    ('Hydrology', 'Hydrology'),
    ('Water Quality', 'Water Quality'),
    ('Ecosystem Process and Function', 'Ecosystem Process and Function'),
    ('Habitat Restoration', 'Habitat Restoration'),
    ('Physical Oceanography', 'Physical Oceanography'),
    ('Adaptive Diversity', 'Adaptive Diversity'),
    ('Genetic Baselines and Taxonomy', 'Genetic Baselines and Taxonomy'),
    ('Hatchery Genetics and Management', 'Hatchery Genetics and Management'),
    ('Climate Change Impacts / Resiliency', 'Climate Change Impacts / Resiliency'),
    ('Cumulative Effects / Stressors', 'Cumulative Effects / Stressors'),
)