# Generated by Django 3.1.2 on 2020-10-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190712_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffingplan',
            options={'ordering': ['fiscal_year__full', 'responsibility_center__name', 'position_number', 'position_title']},
        ),
    ]
