# Generated by Django 2.2.2 on 2020-03-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edaequipmentattachment',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='whalesdb.DepDeployment', verbose_name='Deployment'),
        ),
        migrations.AlterField(
            model_name='edaequipmentattachment',
            name='eqp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment', to='whalesdb.EqpEquipment', verbose_name='Equipment'),
        ),
    ]
