# Generated by Django 2.2.2 on 2020-03-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqpequipment',
            name='eqp_deployed',
            field=models.BooleanField(default=False, verbose_name='Deployed?'),
        ),
    ]
