# Generated by Django 2.2.2 on 2020-01-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecpchannelproperty',
            name='ecp_gain',
        ),
        migrations.RemoveField(
            model_name='rstrecordingstage',
            name='rst_gain',
        ),
        migrations.AddField(
            model_name='recrecordingevent',
            name='rec_hf_channel_gain',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recrecordingevent',
            name='rec_hf_channel_volts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recrecordingevent',
            name='rec_lf_channel_gain',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recrecordingevent',
            name='rec_lf_channel_volts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EtrTechnicalRepairEvent',
            fields=[
                ('etr_id', models.AutoField(primary_key=True, serialize=False)),
                ('etr_date', models.DateField()),
                ('etr_issue_desc', models.CharField(blank=True, max_length=4000, null=True)),
                ('etr_repair_desc', models.CharField(blank=True, max_length=4000, null=True)),
                ('etr_repaired_by', models.CharField(blank=True, max_length=50, null=True)),
                ('eqp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='whalesdb.EqpEquipment')),
            ],
        ),
    ]
