# Generated by Django 2.2.2 on 2020-02-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stestationevent',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_events', to='whalesdb.DepDeployment', verbose_name='Deployment'),
        ),
    ]
