# Generated by Django 2.2.13 on 2020-10-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0002_auto_20200609_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stestationevent',
            name='crs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Cruise', verbose_name='Cruise'),
        ),
    ]
