# Generated by Django 2.2.2 on 2020-03-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0002_auto_20200318_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecpchannelproperty',
            name='emm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channels', to='whalesdb.EmmMakeModel', verbose_name='Recorder'),
        ),
    ]
