# Generated by Django 2.2.2 on 2020-03-06 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid




class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0002_auto_20200227_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depdeployment',
            name='mor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moorings', to='whalesdb.MorMooringSetup', verbose_name='Mooring Setup'),
        ),
        migrations.AlterField(
            model_name='depdeployment',
            name='prj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='whalesdb.PrjProject', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='depdeployment',
            name='stn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stations', to='whalesdb.StnStation', verbose_name='Station'),
        ),
    ]
