# Generated by Django 3.1.2 on 2020-10-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0002_auto_20201013_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='stestationevent',
            name='rtt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='whalesdb.rtttimezonecode', verbose_name='Timezone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stestationevent',
            name='ste_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
