# Generated by Django 2.2.2 on 2020-06-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0003_auto_20200609_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reerecordingevent',
            name='rec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='whalesdb.RecDataset', verbose_name='Dataset'),
        ),
    ]
