# Generated by Django 2.2.2 on 2020-02-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0003_auto_20200206_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mormooringsetup',
            name='mor_setup_image',
            field=models.ImageField(blank=True, null=True, upload_to='whalesdb/mooring_setup', verbose_name='Setup Image'),
        ),
    ]
