# Generated by Django 2.2.2 on 2020-02-07 15:58

from django.db import migrations, models
import whalesdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0005_auto_20200206_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mormooringsetup',
            name='mor_setup_image',
            field=models.FileField(blank=True, null=True, upload_to=whalesdb.models.mooring_directory_path, verbose_name='Setup Image'),
        ),
    ]
