# Generated by Django 2.2.13 on 2020-10-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0008_auto_20201002_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecccalibrationvalue',
            name='eca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curve_values', to='whalesdb.EcaCalibrationEvent', verbose_name='Calibration Event'),
        ),
    ]
