# Generated by Django 3.1.6 on 2021-03-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0009_helptext_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edaequipmentattachment',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='whalesdb.depdeployment', verbose_name='Deployment'),
        ),
        migrations.AlterField(
            model_name='eqtequipmenttypecode',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipment Type (fr)'),
        ),
        migrations.AlterField(
            model_name='stestationevent',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_events', to='whalesdb.depdeployment', verbose_name='Deployment'),
        ),
    ]
