# Generated by Django 3.2 on 2021-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0012_auto_20210408_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecpchannelproperty',
            name='ecp_voltage_range_max',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True, verbose_name='Minimum voltage'),
        ),
        migrations.AlterField(
            model_name='ecpchannelproperty',
            name='ecp_voltage_range_min',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True, verbose_name='Maximum voltage'),
        ),
    ]
