# Generated by Django 3.2 on 2021-04-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0012_auto_20210408_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='etrtechnicalrepairevent',
            name='hyd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etr_hydrophones', to='whalesdb.eqpequipment', verbose_name='Hydrophone'),
        ),
        migrations.AlterField(
            model_name='ecpchannelproperty',
            name='ecp_voltage_range_max',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True, verbose_name='Minimum voltage'),
        ),
        migrations.AlterField(
            model_name='ecpchannelproperty',
            name='ecp_voltage_range_min',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True, verbose_name='Maximum voltage'),
        ),
    ]
