# Generated by Django 2.2.13 on 2020-10-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalesdb', '0012_auto_20201008_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehehydrophoneevent',
            name='ecp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Hydrophones', to='whalesdb.EcpChannelProperty', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='ehehydrophoneevent',
            name='hyd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='channels', to='whalesdb.EqhHydrophoneProperty', verbose_name='Hydrophone'),
        ),
    ]
