# Generated by Django 2.2.2 on 2020-04-23 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shiny', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shiny_apps', to=settings.AUTH_USER_MODEL),
        ),
    ]
