# Generated by Django 2.1.4 on 2019-03-14 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import cruises.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_uid', models.CharField(max_length=10, unique=True)),
                ('station', models.CharField(blank=True, max_length=25, null=True, verbose_name='Station')),
                ('stratum', models.IntegerField(blank=True, null=True, verbose_name='Stratum')),
                ('set', models.IntegerField(blank=True, null=True, verbose_name='Set #')),
                ('event', models.CharField(blank=True, max_length=510, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(choices=[('AST', 'Atlantic Standard Time'), ('ADT', 'Atlantic Daylight Time'), ('UTC', 'Coordinated Universal Time')], max_length=3)),
                ('date_time_UTC', models.DateTimeField(blank=True, null=True, verbose_name='Date / time (UTC)')),
                ('sounding_m', models.FloatField(blank=True, null=True, verbose_name='Sounding (m)')),
                ('bottle_depth_m', models.FloatField(blank=True, null=True, verbose_name='Bottle depth (m)')),
                ('temp_c', models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('salinity', models.FloatField(blank=True, null=True, verbose_name='Salinity')),
                ('sal_units', models.CharField(blank=True, choices=[('PPT', 'parts per thousand (PPT)'), ('PSU', 'practical salinity unit (PSU)')], max_length=5, null=True, verbose_name='Salinity units')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH')),
                ('lat_DDdd', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long_DDdd', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('ctd_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=510, null=True)),
                ('samples_collected', models.CharField(blank=True, max_length=510, null=True)),
            ],
            options={
                'ordering': ['mission', 'bottle_uid'],
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=cruises.models.img_file_name)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=cruises.models.file_directory_path)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbrev', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=255)),
                ('mission_number', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_scientist', models.CharField(max_length=255)),
                ('samplers', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('area_of_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_profiles', models.IntegerField()),
                ('meds_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='MEDS ID')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oceanography.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('call_sign', models.CharField(blank=True, max_length=56, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='probe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oceanography.Probe'),
        ),
        migrations.AddField(
            model_name='mission',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='missions', to='oceanography.Vessel'),
        ),
        migrations.AddField(
            model_name='file',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='oceanography.Mission'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='oceanography.Mission'),
        ),
    ]
