# Generated by Django 2.2.13 on 2020-10-23 11:39

import cruises.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_models', '0009_auto_20201023_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=cruises.models.file_directory_path)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='shared_models.Cruise')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
