# Generated by Django 3.1.2 on 2020-10-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0003_auto_20201028_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='mission',
            new_name='cruise',
        ),
    ]
