# Generated by Django 3.1.2 on 2020-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0006_instrument_cruise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
