# Generated by Django 2.1.4 on 2019-02-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (French)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (French)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=1000, verbose_name='english Name')),
                ('name_fre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='french Name')),
                ('name_ind', models.CharField(blank=True, max_length=1000, null=True, verbose_name='indigenous Name')),
                ('abbrev', models.CharField(max_length=30, verbose_name='abbreviation')),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_election', models.CharField(blank=True, max_length=100, null=True)),
                ('election_term', models.CharField(blank=True, max_length=100, null=True)),
                ('population_on_reserve', models.IntegerField(blank=True, null=True)),
                ('population_off_reserve', models.IntegerField(blank=True, null=True)),
                ('population_other_reserve', models.IntegerField(blank=True, null=True)),
                ('fin', models.CharField(blank=True, max_length=100, null=True, verbose_name='FIN')),
                ('grouping', models.ManyToManyField(to='masterlist.Grouping')),
            ],
            options={
                'ordering': ['name_eng'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='masterlist.Organization')),
            ],
            options={
                'ordering': ['organization', 'person'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_1', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=25, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name (English)')),
                ('name_fre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name (French)')),
                ('country', models.CharField(choices=[('Canada', 'Canada'), ('United States', 'United States')], max_length=25)),
                ('abbrev_eng', models.CharField(blank=True, max_length=25, null=True)),
                ('abbrev_fre', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name (English)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (French)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name (English)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (French)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='masterlist.Person'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='roles',
            field=models.ManyToManyField(to='masterlist.MemberRole'),
        ),
        migrations.AddField(
            model_name='organization',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.Province'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'person')},
        ),
    ]
