# Generated by Django 2.1.4 on 2019-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0004_auto_20190221_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbrev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='abbreviation'),
        ),
    ]
