# Generated by Django 2.1.4 on 2019-05-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0005_auto_20190503_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='masterlist.Role'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role_notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='role notes'),
        ),
    ]
