# Generated by Django 2.2.2 on 2020-08-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0005_delete_consultationinstructionrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrole',
            name='to_cc',
            field=models.IntegerField(choices=[(1, 'TO'), (2, 'CC'), (3, 'CC (Commercial Only)')], verbose_name='TO / CC'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='grouping',
            field=models.ManyToManyField(to='masterlist.Grouping', verbose_name='grouping'),
        ),
    ]
