# Generated by Django 3.1.2 on 2020-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0006_auto_20200805_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='consultation_protocol',
        ),
        migrations.AlterField(
            model_name='organization',
            name='dfo_contact_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='DFO contacts'),
        ),
    ]
