# Generated by Django 3.1.2 on 2020-11-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0007_auto_20201104_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ihub_vetted',
        ),
    ]
