# Generated by Django 2.1.4 on 2019-02-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0008_auto_20190221_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='sector',
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role_notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='role'),
        ),
    ]
