# Generated by Django 3.1.2 on 2020-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0032_auto_20201201_1040'),
        ('masterlist', '0008_remove_person_ihub_vetted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='regions',
            field=models.ManyToManyField(blank=True, to='shared_models.Region', verbose_name='regions'),
        ),
    ]
