# Generated by Django 3.2 on 2021-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0015_auto_20210601_1247'),
        ('masterlist', '0008_alter_organization_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='shared_models.Region', verbose_name='regions'),
        ),
    ]
