# Generated by Django 3.1.2 on 2021-01-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0010_auto_20210113_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='spot_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.role', verbose_name='spot role'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterlist.role', verbose_name='role'),
        ),
    ]
