# Generated by Django 2.1.4 on 2019-02-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0010_auto_20190225_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='roles',
        ),
    ]
