# Generated by Django 3.2.5 on 2021-12-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0011_alter_sector_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='designation',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='title'),
        ),
    ]
