# Generated by Django 2.1.4 on 2019-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0011_remove_organizationmember_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberRole',
        ),
    ]
