# Generated by Django 2.1.4 on 2019-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0012_delete_memberrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmember',
            old_name='role_notes',
            new_name='role',
        ),
    ]
