# Generated by Django 2.1.4 on 2019-05-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0013_remove_organizationmember_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmember',
            old_name='notes',
            new_name='role_notes',
        ),
    ]
