# Generated by Django 2.1.4 on 2019-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0014_auto_20190227_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='is_indigenous',
            field=models.BooleanField(default=False, verbose_name='indigenous?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone 2'),
        ),
    ]
