# Generated by Django 2.1.4 on 2019-05-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0014_auto_20190507_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmember',
            old_name='old_notes',
            new_name='notes',
        ),
    ]
