# Generated by Django 2.1.4 on 2019-05-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0017_auto_20190507_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='masterlist.Person'),
        ),
    ]
