# Generated by Django 2.1.4 on 2019-02-28 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterlist', '0019_auto_20190228_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationInstructionRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_cc', models.IntegerField(choices=[(1, 'TO'), (2, 'CC')], verbose_name='TO / CC')),
                ('date_last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified')),
                ('consultation_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='masterlist.ConsultationInstruction')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_instructions', to='masterlist.OrganizationMember')),
            ],
            options={
                'ordering': ['to_cc', 'member'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='consultationinstructionrecipients',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='consultationinstructionrecipients',
            name='consultation_instruction',
        ),
        migrations.RemoveField(
            model_name='consultationinstructionrecipients',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='consultationinstructionrecipients',
            name='member',
        ),
        migrations.AlterField(
            model_name='person',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone 1'),
        ),
        migrations.DeleteModel(
            name='ConsultationInstructionRecipients',
        ),
        migrations.AlterUniqueTogether(
            name='consultationinstructionrecipient',
            unique_together={('consultation_instruction', 'member')},
        ),
    ]
