# Generated by Django 2.2.2 on 2019-07-25 12:16

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0023_auto_20190724_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=masterlist.models.audio_file_directory_path, verbose_name='audio file'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='wharf',
            field=models.BooleanField(choices=[(None, '------'), (True, 'Yes'), (False, 'No')], default=False, verbose_name='wharf on reserve?'),
        ),
    ]
