# Generated by Django 2.2.2 on 2019-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0025_auto_20190731_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'grouping__is_indigenous': 1}, to='masterlist.Organization', verbose_name='Associated organizations'),
        ),
    ]
