# Generated by Django 2.2.2 on 2019-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0026_auto_20190731_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='processing_plant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='processing plant on reserve?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='wharf',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='wharf on reserve?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ihub_vetted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='vetted by iHub'),
        ),
    ]
