# Generated by Django 2.0.4 on 2018-11-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_auto_20181108_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
