# Generated by Django 2.0.4 on 2018-11-09 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_auto_20181109_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 14, 25, 41, 915035, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
