# Generated by Django 2.2.2 on 2020-02-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_auto_20190807_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stations', to='camp.Site'),
        ),
    ]
