# Generated by Django 2.0.4 on 2018-11-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_auto_20181109_1025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('sample_start_date', 'station')},
        ),
    ]
