# Generated by Django 2.2.2 on 2020-02-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_auto_20200212_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date / time (yyyy-mm-dd hh:mm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start date / time (yyyy-mm-dd hh:mm)'),
        ),
    ]
