# Generated by Django 2.0.4 on 2018-11-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_auto_20181109_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speciesobservations',
            unique_together={('sample', 'species')},
        ),
    ]
