# Generated by Django 2.0.4 on 2018-11-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0011_auto_20181109_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-sample_start_date', 'station']},
        ),
        migrations.AddField(
            model_name='sample',
            name='species',
            field=models.ManyToManyField(through='camp.SpeciesObservations', to='camp.Species'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='disolved_o2',
            field=models.FloatField(blank=True, null=True, verbose_name='dissolved oxygen (?mgl?)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='mean_sediment_grain_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Mean sediment grain size (??)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='per_sediment_organic_cont',
            field=models.FloatField(blank=True, null=True, verbose_name='sediment organic content (%)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='per_sediment_water_cont',
            field=models.FloatField(blank=True, null=True, verbose_name='sediment water content (%)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='salinity',
            field=models.FloatField(blank=True, null=True, verbose_name='Salinity (ppt)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='temperature_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
    ]
