# Generated by Django 2.0.4 on 2018-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0013_station_station_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
