# Generated by Django 2.0.4 on 2018-11-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0015_auto_20181115_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='excessive_green_algae_shore',
            field=models.BooleanField(default=False, verbose_name='Excessive green algae on shore?'),
        ),
        migrations.AddField(
            model_name='sample',
            name='excessive_green_algae_water',
            field=models.BooleanField(default=False, verbose_name='Excessive green algae in water?'),
        ),
        migrations.AddField(
            model_name='sample',
            name='percent_gravel',
            field=models.FloatField(blank=True, null=True, verbose_name='Gravel (%)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='percent_mud',
            field=models.FloatField(blank=True, null=True, verbose_name='Mud (%)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='percent_rock',
            field=models.FloatField(blank=True, null=True, verbose_name='Rock (%)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='percent_sand',
            field=models.FloatField(blank=True, null=True, verbose_name='Sand (%)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='rain_past_24_hours',
            field=models.BooleanField(default=False, verbose_name='Has it rained in the past 24 h?'),
        ),
        migrations.AddField(
            model_name='sample',
            name='samplers',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sav_survey_conducted',
            field=models.BooleanField(default=False, verbose_name='Was SAV survey conducted?'),
        ),
        migrations.AddField(
            model_name='sample',
            name='tide_direction',
            field=models.CharField(blank=True, choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('h', 'high'), ('l', 'Low'), ('l', 'Low')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='unsampled_vegetation_inside',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Vegetation present inside sample area (underwater) but outside of quadrat'),
        ),
        migrations.AddField(
            model_name='sample',
            name='unsampled_vegetation_outside',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Vegetation present outside of sample area (underwater)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='visual_sediment_obs',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Visual sediment observations'),
        ),
        migrations.AddField(
            model_name='sample',
            name='water_turbidity',
            field=models.IntegerField(blank=True, choices=[(1, 'Turbid'), (2, 'Clear')], null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='weather_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='disolved_o2',
            field=models.FloatField(blank=True, null=True, verbose_name='dissolved oxygen (mg/L)'),
        ),
    ]
