# Generated by Django 2.0.4 on 2018-11-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0018_auto_20181119_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-start_date', 'station']},
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='sample_start_date',
            new_name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('start_date', 'station')},
        ),
    ]
