# Generated by Django 2.0.4 on 2018-11-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0021_sample_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='uid',
        ),
        migrations.AddField(
            model_name='sample',
            name='camp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='CAMP Id'),
        ),
    ]
