# Generated by Django 2.0.4 on 2018-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('camp', '0028_species_sav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesobservation',
            old_name='unknown',
            new_name='category_level',
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='yoy',
            field=models.FloatField(blank=True, null=True, verbose_name='young of the year (YOY)'),
        ),
    ]
