# Generated by Django 2.0.4 on 2018-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0031_auto_20181206_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesobservation',
            name='total_sav',
            field=models.FloatField(blank=True, null=True, verbose_name='SAV level'),
        ),
    ]
