# Generated by Django 2.0.4 on 2018-12-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0033_auto_20181206_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='nutrient_sample_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='nutrient sample ID'),
        ),
        migrations.AlterField(
            model_name='species',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
