# Generated by Django 2.2.2 on 2020-01-21 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_file', models.FileField(upload_to='temp_file')),
            ],
        ),
        migrations.CreateModel(
            name='SciFiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_centers', models.ManyToManyField(related_name='scifi_users', to='shared_models.ResponsibilityCenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scifi_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Allocation'), (2, 'Adjustment'), (3, 'Expenditure')], default=3)),
                ('supplier_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('expected_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('obligation_cost', models.FloatField(blank=True, null=True)),
                ('outstanding_obligation', models.FloatField(blank=True, null=True)),
                ('invoice_cost', models.FloatField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('consignee_suffix', models.IntegerField(blank=True, null=True, verbose_name='consignee suffix')),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('in_mrs', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='In MRS')),
                ('amount_paid_in_mrs', models.FloatField(blank=True, null=True, verbose_name='amount paid in MRS')),
                ('mrs_notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='MRS notes')),
                ('procurement_hub_contact', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('exclude_from_rollup', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Exclude from rollup')),
                ('allotment_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.AllotmentCode')),
                ('business_line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.BusinessLine')),
                ('consignee_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.CosigneeCode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.FiscalYear', verbose_name='fiscal year')),
                ('line_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.LineObject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.Project')),
                ('responsibility_center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.ResponsibilityCenter')),
            ],
            options={
                'ordering': ['-creation_date'],
                'unique_together': {('consignee_code', 'consignee_suffix')},
            },
        ),
    ]
