# Generated by Django 2.1.4 on 2019-03-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotmentcode',
            name='allotment_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_allotment_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_business_line',
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_line_object',
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_responsibility_center',
        ),
        migrations.RemoveField(
            model_name='responsibilitycenter',
            name='responsible_manager',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='allotment_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.AllotmentCode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='business_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.BusinessLine'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='in_mrs',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='In MRS'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='line_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.LineObject'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.Project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='responsibility_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='shared_models.ResponsibilityCenter'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Allocation'), (2, 'Adjustment'), (3, 'Expenditure')], default=3),
        ),
        migrations.DeleteModel(
            name='AllotmentCategory',
        ),
        migrations.DeleteModel(
            name='AllotmentCode',
        ),
        migrations.DeleteModel(
            name='BusinessLine',
        ),
        migrations.DeleteModel(
            name='LineObject',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ResponsibilityCenter',
        ),
    ]
