# Generated by Django 2.1.4 on 2019-01-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0008_auto_20190128_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsibilitycenter',
            old_name='name',
            new_name='names',
        ),
    ]
