# Generated by Django 2.2.2 on 2019-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0017_auto_20190605_1100'),
        ('scifi', '0008_auto_20190626_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='consignee_suffix',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='consignee suffix'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('consignee_code', 'consignee_suffix')},
        ),
    ]
