# Generated by Django 2.2.2 on 2019-12-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0010_auto_20190626_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_file', models.FileField(upload_to='temp_file')),
            ],
        ),
    ]
