# Generated by Django 2.1.4 on 2019-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0010_auto_20190128_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allotmentcode',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='businessline',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lineobject',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='responsibilitycenter',
            options={'ordering': ['name']},
        ),

        migrations.RenameField(
            model_name='allotmentcode',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='allotmentcode',
            old_name='description',
            new_name='name',
        ),

        migrations.RenameField(
            model_name='businessline',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='businessline',
            old_name='description',
            new_name='name',
        ),

        migrations.RenameField(
            model_name='responsibilitycenter',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='responsibilitycenter',
            old_name='description',
            new_name='name',
        ),

    ]
