# Generated by Django 2.1.4 on 2019-01-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0019_auto_20190130_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['creation_date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='requisition_date',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Expenditure'), (2, 'Adjustment'), (3, 'Initial allocation')], default=1),
        ),
    ]
