# Generated by Django 2.1.4 on 2019-01-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0020_auto_20190130_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='outstanding_obligation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
