# Generated by Django 2.1.4 on 2019-02-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0028_remove_transaction_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fiscal_year',
            field=models.ForeignKey(default=2019, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='scifi.FiscalYear', verbose_name='fiscal_year'),
            preserve_default=False,
        ),
    ]
