# Generated by Django 2.1.4 on 2019-02-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scifi', '0031_transaction_exclude_from_rollup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-creation_date']},
        ),
    ]
