# Generated by Django 3.2 on 2021-04-16 11:31

import csas2.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0007_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSASRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Previous')], null=True, verbose_name='type')),
                ('language', models.IntegerField(choices=[(1, 'English'), (2, 'French')], default=1, verbose_name='language of request')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='tittle (en)')),
                ('nom', models.CharField(blank=True, max_length=1000, null=True, verbose_name='tittle (fr)')),
                ('is_multiregional', models.BooleanField(default=False, verbose_name='Does this request involve more than one region (zonal) or more than one client sector?')),
                ('multiregional_text', models.TextField(blank=True, null=True, verbose_name='Please provide the contact name, sector, and region.')),
                ('issue', models.TextField(help_text='Should be phrased as a question to be answered by Science.', verbose_name='Issue requiring science information and/or advice.')),
                ('had_assistance', models.BooleanField(default=False, verbose_name='Have you had assistance from Science in developing the question/request (with CSAS and/or DFO science staff)?')),
                ('assistance_text', models.TextField(blank=True, null=True, verbose_name=' If yes, please indicate with whom')),
                ('request_rationale', models.TextField(help_text='Rationale or context for the request: What will the information/advice be used for? Who will be the end user(s)? Will it impact other DFO programs or regions?', verbose_name='Rationale for Request')),
                ('risk_text', models.TextField(blank=True, null=True, verbose_name='What is the expected consequence if science advice is not provided?')),
                ('advice_needed_by', models.DateTimeField(verbose_name='Latest Possible Date to Receive Science Advice')),
                ('rationale_for_timeline', models.TextField(blank=True, help_text='e.g., COSEWIC or consultation meetings, Environmental Assessments, legal or regulatory requirement, Treaty obligation, international commitments, etc). Please elaborate and provide anticipatory dates', null=True, verbose_name='Rationale for deadline?')),
                ('client_has_funding', models.BooleanField(default=False, help_text='i.e., special analysis, meeting costs, translation)?', verbose_name='Do you have funds to cover any extra costs associated with this request?')),
                ('client_funding_description', models.TextField(blank=True, null=True, verbose_name='If so, please elaborate.')),
                ('client_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date of client signature')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=csas2.models.request_directory_path, verbose_name='attachment')),
                ('status', models.IntegerField(editable=False, verbose_name='status')),
                ('submission_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='submission date')),
                ('old_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_client_requests', to=settings.AUTH_USER_MODEL, verbose_name='DFO client')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_coordinator_requests', to=settings.AUTH_USER_MODEL, verbose_name='Regional CSAS coordinator')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequest_created_by', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_requests', to='shared_models.fiscalyear', verbose_name='fiscal year')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_requests', to='shared_models.section', verbose_name='DFO Section / Team')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequest_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='location')),
                ('proponent', models.CharField(blank=True, max_length=1000, null=True, verbose_name='proponent')),
                ('type', models.IntegerField(choices=[(1, 'CSAS Regional Advisory Process (RAP)'), (2, 'CSAS Science Management Meeting'), (3, 'CSAS Steering Committee Meeting'), (9, 'other')], verbose_name='type of event')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='initial activity date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='anticipated end date')),
                ('rsvp_email', models.EmailField(max_length=254, verbose_name='RSVP email address (on invitation)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_created_by', to=settings.AUTH_USER_MODEL)),
                ('csas_request', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='csas2.csasrequest', verbose_name='process')),
                ('fiscal_year', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to='shared_models.fiscalyear', verbose_name='fiscal year')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='tittle (en)')),
                ('nom', models.CharField(blank=True, max_length=1000, null=True, verbose_name='tittle (fr)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_created_by', to=settings.AUTH_USER_MODEL)),
                ('csas_requests', models.ManyToManyField(to='csas2.CSASRequest')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_en', models.FileField(blank=True, null=True, upload_to=csas2.models.resource_directory_path, verbose_name='file attachment (English)')),
                ('file_fr', models.FileField(blank=True, null=True, upload_to=csas2.models.resource_directory_path, verbose_name='file attachment (French)')),
                ('url_en', models.URLField(blank=True, null=True, verbose_name='url (English)')),
                ('url_fr', models.URLField(blank=True, null=True, verbose_name='url (French)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingresource_created_by', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='csas2.meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingresource_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'To Do'), (2, 'Next step'), (3, 'General comment')], verbose_name='type')),
                ('note', models.TextField(verbose_name='note')),
                ('is_complete', models.BooleanField(default=False, verbose_name='complete?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingnote_created_by', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='csas2.meeting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingnote_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_complete', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Participant'), (2, 'Chair'), (3, 'Expert'), (4, 'Steering Committee Member')], default=1, verbose_name='Function')),
                ('status', models.IntegerField(choices=[(0, 'Invited'), (1, 'Accepted'), (2, 'Declined'), (9, 'No response')], default=0, verbose_name='status')),
                ('invitation_sent_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date invitation was sent')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='csas2.meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invites', to='shared_models.person')),
                ('resources_received', models.ManyToManyField(editable=False, to='csas2.MeetingResource')),
            ],
            options={
                'ordering': ['person__first_name', 'person__last_name'],
                'unique_together': {('meeting', 'person')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_created_by', to=settings.AUTH_USER_MODEL)),
                ('meetings', models.ManyToManyField(blank=True, to='csas2.Meeting')),
                ('process', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='csas2.process')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSASRequestReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Date a decision was made')),
                ('decision', models.IntegerField(blank=True, editable=False, null=True, verbose_name='decision')),
                ('decision_explanation', models.IntegerField(blank=True, null=True, verbose_name='Decision Explanation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequestreview_created_by', to=settings.AUTH_USER_MODEL)),
                ('csas_request', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='csas2.csasrequest')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequestreview_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='csas2.invitee', verbose_name='attendee')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('invitee', 'date')},
            },
        ),
    ]
