# Generated by Django 3.2.13 on 2022-05-02 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ppt', '0001_initial'),
        ('csas2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0031_subjectmatter_is_csas_request_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='csas_processes', to='ppt.Project', verbose_name='Links to PPT Projects'),
        ),
        migrations.AddField(
            model_name='process',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingresource',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingresource_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingresource',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='csas2.meeting'),
        ),
        migrations.AddField(
            model_name='meetingresource',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingresource_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingnote_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='csas2.meeting'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetingnote_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingfile',
            name='meeting',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='csas2.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to='shared_models.fiscalyear', verbose_name='fiscal year of meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='process',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='csas2.process', verbose_name='process'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='csas2.meeting'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_invites', to='shared_models.person'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_invites', to='shared_models.region', verbose_name='DFO Region (if applicable)'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='resources_received',
            field=models.ManyToManyField(editable=False, to='csas2.MeetingResource'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='roles',
            field=models.ManyToManyField(to='csas2.InviteeRole', verbose_name='Function(s)'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_chair_positions', to='shared_models.person', verbose_name='chairperson'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documenttracking_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_directors', to='shared_models.person', verbose_name='director'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='division_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_division_managers', to='shared_models.person', verbose_name='division manager'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='csas2.document'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='proof_sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_proof_sent', to='shared_models.person', verbose_name='proof will be sent to which author'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='section_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_section_heads', to='shared_models.person', verbose_name='section head'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_submissions', to='shared_models.person', verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='translation_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translation_review', to='shared_models.person', verbose_name='translation review completed by'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documenttracking_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentnote_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='csas2.document'),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentnote_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas2.documenttype', verbose_name='document type'),
        ),
        migrations.AddField(
            model_name='document',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='documents', to='csas2.Meeting', verbose_name='csas meeting linkages'),
        ),
        migrations.AddField(
            model_name='document',
            name='people',
            field=models.ManyToManyField(editable=False, through='csas2.Author', to='shared_models.Person', verbose_name='authors'),
        ),
        migrations.AddField(
            model_name='document',
            name='process',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='csas2.process', verbose_name='process'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csasrequestreview',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequestreview_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csasrequestreview',
            name='csas_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='csas2.csasrequest'),
        ),
        migrations.AddField(
            model_name='csasrequestreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequestreview_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csasrequestnote',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequestnote_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csasrequestnote',
            name='csas_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='csas2.csasrequest'),
        ),
        migrations.AddField(
            model_name='csasrequestnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequestnote_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csasrequestfile',
            name='csas_request',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='csas2.csasrequest'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='advice_fiscal_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_request_advice', to='shared_models.fiscalyear', verbose_name='advice FY'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_client_requests', to=settings.AUTH_USER_MODEL, verbose_name='DFO client'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequest_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_requests', to='shared_models.fiscalyear', verbose_name='request FY'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='office',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_offices', to='csas2.csasoffice', verbose_name='CSAS office'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_requests', to='shared_models.section', verbose_name='client section'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_csas_request_tag': True}, to='shared_models.SubjectMatter', verbose_name='keyword tags'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csasrequest_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csasoffice',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='csas_offices_administrators', to=settings.AUTH_USER_MODEL, verbose_name='administrators'),
        ),
        migrations.AddField(
            model_name='csasoffice',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='csas_offices_advisors', to=settings.AUTH_USER_MODEL, verbose_name='science advisors'),
        ),
        migrations.AddField(
            model_name='csasoffice',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_offices', to=settings.AUTH_USER_MODEL, verbose_name='coordinator / CSA'),
        ),
        migrations.AddField(
            model_name='csasoffice',
            name='ppt_default_section',
            field=models.ForeignKey(blank=True, help_text='When exporting CSAS processes to projects, what should be the default section to use?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_offices', to='shared_models.section', verbose_name='default section for PPT'),
        ),
        migrations.AddField(
            model_name='csasoffice',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_offices', to='shared_models.region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='csasadminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csas_admin_user', to=settings.AUTH_USER_MODEL, verbose_name='DM Apps user'),
        ),
        migrations.AddField(
            model_name='author',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='csas2.document', verbose_name='document'),
        ),
        migrations.AddField(
            model_name='author',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorship', to='shared_models.person', verbose_name='person'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='csas2.invitee', verbose_name='attendee'),
        ),
        migrations.AlterUniqueTogether(
            name='torreviewer',
            unique_together={('tor', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='invitee',
            unique_together={('meeting', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('document', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('invitee', 'date')},
        ),
    ]
