# Generated by Django 3.2 on 2021-04-26 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csas2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='role',
            field=models.IntegerField(choices=[(1, 'Chair'), (2, 'Participant'), (3, 'Expert'), (4, 'Steering Committee Member (is this is good category?)')], default=1, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='status',
            field=models.IntegerField(choices=[(0, 'Invited'), (1, 'Accepted'), (2, 'Declined'), (3, 'Tentative')], default=0, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='DocumentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'To Do'), (2, 'Next step'), (3, 'General comment')], verbose_name='type')),
                ('note', models.TextField(verbose_name='note')),
                ('is_complete', models.BooleanField(default=False, verbose_name='complete?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentnote_created_by', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='csas2.document')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentnote_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_complete', '-updated_at'],
            },
        ),
    ]
