# Generated by Django 3.2.5 on 2021-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttracking',
            name='chair_comments',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='coordinator_comments',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='director_comments',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='division_manager_comments',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='section_head_comments',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date submitted by author'),
        ),
    ]
