# Generated by Django 3.2 on 2021-04-30 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0002_remove_meeting_hide_from_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='est_quarter',
            field=models.IntegerField(blank=True, choices=[(1, 'Spring (Apr-Jun)'), (2, 'Summer (Jul-Sept)'), (3, 'Fall (Oct-Dec)'), (4, 'Winter (Jan-Mar)')], null=True, verbose_name='estimated quarter'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='est_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='estimated year'),
        ),
    ]
