# Generated by Django 3.2.5 on 2021-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0030_remove_river_fishing_area_code'),
        ('csas2', '0002_auto_20211208_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='csasrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shared_models.SubjectMatter', verbose_name='keyword tags'),
        ),
    ]
