# Generated by Django 3.2 on 2021-04-19 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0007_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csas2', '0004_rename_request_rationale_csasrequest_rationale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csasrequest',
            options={'ordering': ('fiscal_year', 'name')},
        ),
        migrations.AddField(
            model_name='csasrequestreview',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='coordinator notes'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='assistance_text',
            field=models.TextField(blank=True, null=True, verbose_name=' Please provide details about the assistance received'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_client_requests', to='auth.user', verbose_name='DFO client'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_coordinator_requests', to='auth.user', verbose_name='Regional CSAS coordinator'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='had_assistance',
            field=models.BooleanField(default=False, help_text='E.g. with CSAS and/or DFO science staff.', verbose_name='Have you had assistance from Science in developing the question/request?'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='has_funding',
            field=models.BooleanField(default=False, help_text='i.e., special analysis, meeting costs, translation)?', verbose_name='Do you have funds to cover any extra costs associated with this request?'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='is_multiregional',
            field=models.BooleanField(default=False, verbose_name='Does this request involve more than one region (zonal) or more than one client sector?'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='issue',
            field=models.TextField(help_text='Should be phrased as a question to be answered by Science', verbose_name='Issue requiring science information and/or advice'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='multiregional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Please provide the contact name, sector, and region for all involved.'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_requests', to='shared_models.section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='status',
            field=models.IntegerField(default=1, editable=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='type',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Previous')], default=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='decision',
            field=models.IntegerField(blank=True, choices=[(1, 'on'), (2, 'off'), (3, 'tentative')], null=True, verbose_name='decision'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='decision_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date a decision was made'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='decision_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Decision Explanation'),
        ),
    ]
