# Generated by Django 3.2.5 on 2021-12-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0004_auto_20211209_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Ready for review'), (4, 'Under review'), (5, 'Fulfilled'), (6, 'Withdrawn'), (11, 'Reviewed'), (12, 'Flagged'), (13, 'Re-scoping')], default=1, editable=False, verbose_name='status'),
        ),
    ]
