# Generated by Django 3.2 on 2021-04-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0005_auto_20210419_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csasrequestreview',
            old_name='decision_explanation',
            new_name='decision_text',
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='csas_request',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='csas2.csasrequest'),
        ),
    ]
