# Generated by Django 3.2 on 2021-04-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0005_auto_20210427_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csasrequest',
            options={'ordering': ('fiscal_year', 'title'), 'verbose_name_plural': 'CSAS Requests'},
        ),
        migrations.RenameField(
            model_name='csasrequest',
            old_name='name',
            new_name='title',
        ),
    ]
