# Generated by Django 3.2.13 on 2022-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0006_auto_20220527_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_confirmed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Has been confirmed?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='documents', to='csas2.Meeting', verbose_name='linkage to peer-review meetings'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='has_media_attention',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='The answer to this question will be used by NCR for regular reporting on the meeting (i.e., TAB7)', verbose_name='will this meeting generate media attention?'),
        ),
        migrations.AlterField(
            model_name='meetingfile',
            name='is_somp',
            field=models.BooleanField(default=False, editable=False, verbose_name='is this the SoMP?'),
        ),
    ]
