# Generated by Django 3.2.13 on 2022-05-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0007_auto_20220530_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lead_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='csas2.csasoffice', verbose_name='lead CSAS office'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed'), (2, 'Submitted by author'), (3, 'Under review by chair'), (4, 'Approved by chair'), (5, 'Under review by CSAS coordinator'), (6, 'Approved by CSAS coordinator'), (13, 'Under review by section head'), (14, 'Approved by section head'), (15, 'Under review by division manager'), (16, 'Approved by division manager'), (7, 'Under review by director'), (8, 'Approved by director'), (9, 'Submitted to CSAS office'), (10, 'Proof sent to author'), (11, 'Proof approved by author'), (12, 'Posted'), (17, 'Posted (updated)')], default=1, editable=False, verbose_name='status'),
        ),
    ]
