# Generated by Django 3.2 on 2021-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0007_auto_20210430_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='translation_status',
            field=models.IntegerField(choices=[(0, 'Not translated'), (1, 'In translation'), (2, 'Translation complete')], default=0, editable=False, verbose_name='translation status'),
        ),
    ]
