# Generated by Django 3.2 on 2021-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0008_alter_document_translation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-is_lead', 'person__first_name', 'person__last_name']},
        ),
        migrations.RemoveField(
            model_name='process',
            name='context',
        ),
        migrations.RemoveField(
            model_name='process',
            name='expected_publications',
        ),
        migrations.RemoveField(
            model_name='process',
            name='objectives',
        ),
        migrations.AddField(
            model_name='process',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='posted?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'Tracking initiated'), (2, 'Submitted by author'), (3, 'Under review by chair'), (4, 'Approved by chair'), (5, 'Under review by CSAS coordinator'), (6, 'Approved by CSAS coordinator'), (7, 'Under review by director'), (8, 'Approved by director'), (9, 'Submitted to CSAS office'), (10, 'Proof sent to author'), (11, 'Proof approved by author'), (12, 'Posted')], default=1, editable=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='translation_status',
            field=models.IntegerField(choices=[(0, '---'), (1, 'In-progress'), (2, 'Complete')], default=0, editable=False, verbose_name='translation status'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='is_review_complete',
            field=models.BooleanField(default=False, verbose_name='has the CSA office completed a translation review?'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='was submitted as an urgent request?'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.IntegerField(choices=[(1, 'Planning'), (3, 'Keystone')], verbose_name='type of meeting'),
        ),
    ]
