# Generated by Django 3.2 on 2021-04-27 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csas2', '0010_auto_20210427_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_client_requests', to=settings.AUTH_USER_MODEL, verbose_name='DFO client'),
        ),
    ]
