# Generated by Django 3.2.10 on 2022-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0019_activity_parent'),
        ('csas2', '0010_auto_20220106_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='projects',
            field=models.ManyToManyField(related_name='csas_processes', to='ppt.Project', verbose_name='Links to PPT Projects'),
        ),
    ]
