# Generated by Django 3.2 on 2021-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0011_alter_csasrequest_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='title',
            field=models.CharField(default=1, max_length=1000, verbose_name='title'),
            preserve_default=False,
        ),
    ]
