# Generated by Django 3.2.14 on 2022-08-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0012_torreviewer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='torreviewer',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='reminder sent date'),
        ),
    ]
