# Generated by Django 3.2 on 2021-04-27 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0012_alter_csasrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='csasrequestreview',
            name='advice_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date by when to receive Science advice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csasrequestreview',
            name='deferred_text',
            field=models.TextField(blank=True, null=True, verbose_name='Please provide rationale for the deferred date'),
        ),
        migrations.AddField(
            model_name='csasrequestreview',
            name='is_deferred',
            field=models.BooleanField(default=False, verbose_name='What the original request date deferred?'),
        ),
    ]
