# Generated by Django 3.2.14 on 2022-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0013_torreviewer_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='torreviewer',
            name='review_completed',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='review completed'),
        ),
        migrations.AddField(
            model_name='torreviewer',
            name='review_started',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='review started'),
        ),
    ]
