# Generated by Django 3.2 on 2021-05-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0013_auto_20210430_0759'),
        ('csas2', '0013_auto_20210504_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttracking',
            name='date_number_requested',
        ),
        migrations.RemoveField(
            model_name='documenttracking',
            name='number_approved',
        ),
        migrations.AddField(
            model_name='document',
            name='pub_number_request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of publication number request'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='pub_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='publication number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pub_number',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, verbose_name='publication number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'Tracking initiated'), (2, 'Submitted by author'), (3, 'Under review by chair'), (4, 'Approved by chair'), (5, 'Under review by CSAS coordinator'), (6, 'Approved by CSAS coordinator'), (13, 'Under review by section head'), (14, 'Approved by section head'), (15, 'Under review by division manager'), (16, 'Approved by division manager'), (7, 'Under review by director'), (8, 'Approved by director'), (9, 'Submitted to CSAS office'), (10, 'Proof sent to author'), (11, 'Proof approved by author'), (12, 'Posted'), (17, 'Posted (updated)')], default=1, editable=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='translation_status',
            field=models.IntegerField(choices=[(0, '----'), (1, 'In progress'), (2, 'Translated, unreviewed'), (3, 'Translated, reviewed')], default=0, editable=False, verbose_name='translation status'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='translation_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translation_review', to='shared_models.person', verbose_name='translation review completed by'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_posted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is posted on CSAS website?'),
        ),
    ]
