# Generated by Django 3.2.14 on 2022-08-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csas2', '0014_auto_20220816_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torreviewer',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='process',
            name='advice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Target date to provide Science advice'),
        ),
        migrations.AlterField(
            model_name='torreviewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='torreviewer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='RequestReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(null=True, verbose_name='process order')),
                ('decision', models.IntegerField(blank=True, choices=[(1, 'Accept'), (2, 'Request changes')], null=True, verbose_name='decision')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('status', models.IntegerField(choices=[(10, 'Draft'), (20, 'Queued'), (30, 'Pending'), (40, 'Complete')], default=10, verbose_name='status')),
                ('reminder_sent', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='reminder sent date')),
                ('review_started', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='review started')),
                ('review_completed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='review completed')),
                ('role', models.IntegerField(choices=[(1, 'Approver'), (2, 'Reviewer')], verbose_name='role')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestreviewer_created_by', to=settings.AUTH_USER_MODEL)),
                ('csas_request', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='csas2.csasrequest')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestreviewer_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestreviewer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
