# Generated by Django 3.2 on 2021-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0014_auto_20210504_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pub_number',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True, verbose_name='publication number'),
        ),
    ]
