# Generated by Django 3.2 on 2021-04-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0014_alter_csasrequestreview_advice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='csasrequestreview',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='regional reference number (optional)'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='advice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date to receive Science advice'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='is_deferred',
            field=models.BooleanField(default=False, verbose_name='was the original request date deferred?'),
        ),
    ]
