# Generated by Django 3.2 on 2021-05-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0013_auto_20210430_0759'),
        ('csas2', '0015_alter_document_pub_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_invites', to='shared_models.region', verbose_name='DFO Region (if applicable)'),
        ),
        migrations.AlterField(
            model_name='documentcost',
            name='cost_category',
            field=models.IntegerField(choices=[(1, 'Translation'), (2, 'Travel'), (3, 'Hospitality'), (4, 'Space rental'), (5, 'Simultaneous translation'), (9, 'Other')], verbose_name='cost category'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date submitted for review'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_invites', to='shared_models.person'),
        ),
        migrations.AlterField(
            model_name='meetingcost',
            name='cost_category',
            field=models.IntegerField(choices=[(1, 'Translation'), (2, 'Travel'), (3, 'Hospitality'), (4, 'Space rental'), (5, 'Simultaneous translation'), (9, 'Other')], verbose_name='cost category'),
        ),
    ]
