# Generated by Django 3.2.14 on 2022-08-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0015_auto_20220817_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Under client review'), (30, 'Ready for CSAS review'), (40, 'Under CSAS review'), (41, 'Reviewed'), (42, 'Flagged'), (43, 'Re-scoping'), (70, 'Accepted'), (80, 'Fulfilled'), (99, 'Withdrawn')], default=10, editable=False, verbose_name='status'),
        ),
    ]
