# Generated by Django 3.2.14 on 2022-08-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0016_alter_csasrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasoffice',
            name='disable_request_notifications',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='disable notifications from new requests?'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Under client review'), (25, 'Awaiting changes'), (30, 'Ready for CSAS review'), (40, 'Under CSAS review'), (41, 'Reviewed'), (42, 'Flagged'), (43, 'Re-scoping'), (70, 'Accepted'), (80, 'Fulfilled'), (99, 'Withdrawn')], default=10, editable=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='requestreviewer',
            name='csas_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='csas2.csasrequest'),
        ),
        migrations.AlterField(
            model_name='requestreviewer',
            name='role',
            field=models.IntegerField(choices=[(1, 'Approver'), (2, 'Recommender')], verbose_name='role'),
        ),
    ]
