# Generated by Django 3.2 on 2021-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0016_auto_20210428_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='csasrequest',
            name='ref_number',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='reference number'),
        ),
    ]
