# Generated by Django 3.2 on 2021-04-28 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csas2', '0017_csasrequest_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_coordinator_requests', to=settings.AUTH_USER_MODEL, verbose_name='Regional CSAS coordinator'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Under review'), (11, 'On'), (12, 'Off'), (13, 'Withdrawn'), (14, 'Deferred')], default=1, editable=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='decision',
            field=models.IntegerField(blank=True, choices=[(1, 'On'), (2, 'Off'), (3, 'Withdrawn'), (4, 'Deferred')], null=True, verbose_name='decision'),
        ),
        migrations.CreateModel(
            name='DocumentTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documenttracking_created_by', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='csas2.document')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documenttracking_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
