# Generated by Django 3.2 on 2021-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0018_auto_20210428_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='role',
            field=models.IntegerField(choices=[(1, 'Chair'), (7, 'CSAS coordinator'), (3, 'Expert'), (6, 'External reviewer'), (5, 'Internal reviewer'), (2, 'Participant'), (8, 'Rapporteur'), (9, 'Science advisor'), (4, 'Steering Committee Member')], default=1, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='meetingresource',
            name='url_en',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='url (English)'),
        ),
        migrations.AlterField(
            model_name='meetingresource',
            name='url_fr',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='url (French)'),
        ),
    ]
