# Generated by Django 3.2 on 2021-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0018_auto_20210504_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='days_due',
            field=models.IntegerField(blank=True, null=True, verbose_name='days due following meeting'),
        ),
    ]
