# Generated by Django 3.2.14 on 2022-10-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0018_merge_20220819_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Under Client Approval'), (25, 'Awaiting Changes'), (30, 'Ready for CSAS Review'), (40, 'Under CSAS Review'), (41, 'Screened-in'), (42, 'Flagged'), (43, 'Re-scoping'), (70, 'Refer to Process'), (80, 'Fulfilled'), (99, 'Withdrawn')], default=10, editable=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.IntegerField(choices=[(1, 'Science Advisory Meeting'), (2, 'Science Response Process')], verbose_name='type'),
        ),
    ]
