# Generated by Django 3.2 on 2021-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0020_process_posting_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofreference',
            name='expected_document_types',
            field=models.ManyToManyField(blank=True, to='csas2.DocumentType', verbose_name='expected publications'),
        ),
        migrations.AlterField(
            model_name='document',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='documents', to='csas2.Meeting', verbose_name='csas meeting linkages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pub_number_request_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date of publication number request'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='is posted on CSAS website?'),
        ),
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.IntegerField(choices=[(1, 'Advisory Meeting'), (2, 'Science Response Process')], verbose_name='type'),
        ),
    ]
