# Generated by Django 3.2.14 on 2022-11-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0021_alter_csasrequest_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages_fr',
            field=models.IntegerField(blank=True, null=True, verbose_name='pages (fr)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='pages (en)'),
        ),
    ]
