# Generated by Django 3.2 on 2021-04-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0024_auto_20210429_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True, verbose_name='context')),
                ('objectives', models.TextField(blank=True, null=True, verbose_name='objectives')),
                ('expected_publications', models.TextField(blank=True, null=True, verbose_name='expected publications')),
                ('participation', models.TextField(blank=True, null=True, verbose_name='participation')),
                ('references', models.TextField(blank=True, null=True, verbose_name='references')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tor', to='csas2.meeting')),
            ],
        ),
    ]
