# Generated by Django 3.2 on 2021-04-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0027_auto_20210429_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofreference',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tor', to='csas2.meeting'),
        ),
        migrations.AlterField(
            model_name='termsofreference',
            name='process',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tor', to='csas2.process'),
        ),
    ]
