# Generated by Django 3.2 on 2021-04-29 13:15

import csas2.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0032_alter_meetingresource_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=csas2.models.meeting_directory_path)),
                ('meeting', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='csas2.meeting')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
