# Generated by Django 3.2 on 2021-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0033_meetingfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_virtual',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is this a virtual meeting?'),
        ),
    ]
