# Generated by Django 3.2.4 on 2021-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0033_rename_document_csasrequestnote_csas_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingfile',
            name='is_somp',
            field=models.BooleanField(default=False, verbose_name='is this the SoMP?'),
        ),
    ]
