# Generated by Django 3.2 on 2021-04-30 11:01

import csas2.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0013_auto_20210430_0759'),
        ('csas2', '0034_meeting_is_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dev_link_en',
            field=models.URLField(blank=True, max_length=2000, null=True, unique=True, verbose_name='dev link (en)'),
        ),
        migrations.AddField(
            model_name='document',
            name='dev_link_fr',
            field=models.URLField(blank=True, max_length=2000, null=True, unique=True, verbose_name='dev link (fr)'),
        ),
        migrations.AddField(
            model_name='document',
            name='ekme_gcdocs_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='EKME# / GCDocs (en)'),
        ),
        migrations.AddField(
            model_name='document',
            name='ekme_gcdocs_fr',
            field=models.CharField(blank=True, max_length=244, null=True, unique=True, verbose_name='EKME# / GCDocs (fr)'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to=csas2.models.doc_directory_path, verbose_name='file attachment (en)'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_fr',
            field=models.FileField(blank=True, null=True, upload_to=csas2.models.doc_directory_path, verbose_name='file attachment (fr)'),
        ),
        migrations.AddField(
            model_name='document',
            name='lib_cat_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='library catalogue # (en)'),
        ),
        migrations.AddField(
            model_name='document',
            name='lib_cat_fr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='library catalogue # (fr)'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='actual_posting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actual posting date'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='anticipated_posting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anticipated posting date'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_chair_positions', to='shared_models.person', verbose_name='chairperson'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='client_ref_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='client reference number'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_chair_appr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date approved by chair'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_chair_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date sent to chair'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_coordinator_appr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date approved by coordinator'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_coordinator_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date sent to coordinator'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_director_appr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date approved by director'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_director_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date sent to director'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_doc_submitted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date document submitted to CSAS office'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_due',
            field=models.DateField(blank=True, null=True, verbose_name='product due date'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_number_requested',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date number requested'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_proof_author_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date PDF proof approved by author'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_proof_author_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date PDF proof sent to author'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date back from translation'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='date submitted to CSAS office by author'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='date_translation_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date sent to translation'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_directors', to='shared_models.person', verbose_name='director'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='invoice number'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='is_review_complete',
            field=models.BooleanField(default=True, verbose_name='has the CSA office completed a translation review?'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='is_urgent',
            field=models.BooleanField(default=True, verbose_name='was submitted as an urgent request?'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='number_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date number approved'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='proof_sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_proof_sent', to='shared_models.person', verbose_name='proof will be sent to which author'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_submissions', to='shared_models.person', verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='target_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.language', verbose_name='target language'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='translation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='translation notes'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='translation_ref_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='translation reference number'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='updated_posting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated posting date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url_en',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='document url (en)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url_fr',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='document url (fr)'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(1, 'In-progress'), (2, 'Complete'), (3, 'Deferred'), (4, 'Delayed'), (5, 'Tentative')], default=1, verbose_name='status'),
        ),
    ]
