# Generated by Django 3.2.4 on 2021-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0035_auto_20210824_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='is_multiregional',
            field=models.IntegerField(blank=True, choices=[(None, 'Unsure'), (1, 'Yes'), (0, 'No')], default=False, help_text='(e.g., frameworks, tools, issues and/or aquatic species widely distributed throughout more than one region)', null=True, verbose_name='Could the advice provided potentially be applicable to other regions and/or sectors?'),
        ),
        migrations.AlterField(
            model_name='csasrequest',
            name='multiregional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Please list other sectors and/or regions and provide brief rationale'),
        ),
    ]
