# Generated by Django 3.2 on 2021-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0038_auto_20210430_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ekme_gcdocs_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EKME# / GCDocs (en)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ekme_gcdocs_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EKME# / GCDocs (fr)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='lib_cat_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='library catalogue # (en)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='lib_cat_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='library catalogue # (fr)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(1, 'OK'), (2, 'In preparation'), (3, 'Submitted'), (4, 'Under review'), (5, 'In translation'), (6, 'Translated'), (7, 'Posted')], default=1, editable=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='date_coordinator_appr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date approved by CSAS coordinator'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='date_coordinator_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date sent to CSAS coordinator'),
        ),
    ]
