# Generated by Django 3.2.4 on 2021-09-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0038_auto_20210922_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
