# Generated by Django 3.2.4 on 2021-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0040_auto_20210929_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofreference',
            name='is_complete',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are the ToRs complete?'),
        ),
    ]
