# Generated by Django 3.2.4 on 2021-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0045_auto_20211007_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Ready for review'), (4, 'Under review'), (5, 'Fulfilled'), (11, 'Accepted'), (12, 'Withdrawn')], default=1, editable=False, verbose_name='status'),
        ),
    ]
