# Generated by Django 3.2.5 on 2021-11-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0051_auto_20211109_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='translation_tracking_only',
        ),
    ]
