# Generated by Django 3.2.5 on 2021-11-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0054_alter_csasrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasrequestreview',
            name='decision',
            field=models.IntegerField(blank=True, choices=[(1, 'Screen in'), (2, 'Return to client')], null=True, verbose_name='recommendation'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recommendation date'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='decision_text',
            field=models.TextField(blank=True, null=True, verbose_name='recommendation explanation'),
        ),
        migrations.AlterField(
            model_name='csasrequestreview',
            name='is_feasible',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No'), (9, 'Unsure')], null=True, verbose_name='is this feasible from a Science perspective'),
        ),
    ]
