# Generated by Django 3.2.5 on 2021-11-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0028_alter_organization_uuid'),
        ('csas2', '0058_auto_20211119_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csasrequest',
            options={'ordering': ('fiscal_year', 'title'), 'verbose_name': 'CSAS Request', 'verbose_name_plural': 'CSAS Requests'},
        ),
        migrations.RemoveField(
            model_name='csasrequest',
            name='request_fiscal_year',
        ),
        migrations.RemoveField(
            model_name='csasrequest',
            name='submission_fiscal_year',
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='advice_fiscal_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_request_advice', to='shared_models.fiscalyear', verbose_name='advice fiscal year'),
        ),
        migrations.AddField(
            model_name='csasrequest',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_requests', to='shared_models.fiscalyear', verbose_name='request fiscal year'),
        ),
    ]
