# Generated by Django 3.2.5 on 2021-11-23 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0028_alter_organization_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csas2', '0062_auto_20211122_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csasoffice',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='csas_offices_administrators', to=settings.AUTH_USER_MODEL, verbose_name='administrators'),
        ),
        migrations.AlterField(
            model_name='csasoffice',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='csas_offices_advisors', to=settings.AUTH_USER_MODEL, verbose_name='science advisors'),
        ),
        migrations.AlterField(
            model_name='csasoffice',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_offices', to=settings.AUTH_USER_MODEL, verbose_name='coordinator / CSA'),
        ),
        migrations.AlterField(
            model_name='csasoffice',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_offices', to='shared_models.region', verbose_name='region'),
        ),
    ]
