# Generated by Django 3.2.5 on 2021-11-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0028_alter_organization_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csas2', '0064_alter_csasrequest_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='coordinator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_coordinator_processes', to=settings.AUTH_USER_MODEL, verbose_name='Lead coordinator'),
        ),
        migrations.AlterField(
            model_name='process',
            name='lead_region',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_lead_regions', to='shared_models.region', verbose_name='lead region'),
        ),
        migrations.AlterField(
            model_name='process',
            name='other_regions',
            field=models.ManyToManyField(blank=True, editable=False, to='shared_models.Region', verbose_name='other regions'),
        ),
    ]
