# Generated by Django 3.2.5 on 2021-11-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas2', '0065_auto_20211123_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='csasoffice',
            name='no_staff_emails',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='do not send emails directly to office staff?'),
        ),
        migrations.AlterField(
            model_name='csasoffice',
            name='disable_request_notifications',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='disable notifications of new requests?'),
        ),
        migrations.AlterField(
            model_name='process',
            name='lead_office',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_lead_offices', to='csas2.csasoffice', verbose_name='lead CSAS office'),
        ),
    ]
