# Generated by Django 2.2.2 on 2020-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('subject_en', models.CharField(max_length=150)),
                ('subject_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('message_en', models.TextField()),
                ('message_fr', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone (office)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='position (English)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_fre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='position (French)'),
        ),
    ]
