# Generated by Django 2.0.7 on 2018-08-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180824_1319'),
        ('bugs', '0008_auto_20180823_1202'),
        ('grais', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
