# Generated by Django 3.2.16 on 2023-01-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_announcement_subject_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
