# Generated by Django 2.2.2 on 2020-02-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohHonorific',
            fields=[
                ('coh_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LanLanguage',
            fields=[
                ('lan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NotNotificationPreference',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='RolRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SecSector',
            fields=[
                ('sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ConContact',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Some help here', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
                ('region', models.IntegerField()),
                ('expertise', models.CharField(max_length=100)),
                ('cc_grad', models.BooleanField()),
                ('notes', models.CharField(max_length=400)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.CotType')),
                ('honorific', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.CohHonorific')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.LanLanguage')),
                ('notification_preference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.NotNotificationPreference')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.RolRole')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.SecSector')),
            ],
        ),
    ]
