# Generated by Django 2.2.2 on 2020-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
        ('csas', '0003_auto_20200226_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='metmeeting',
            name='other_region',
            field=models.ManyToManyField(related_name='other_region', to='shared_models.Region'),
        ),
        migrations.AlterField(
            model_name='metmeeting',
            name='program_contact',
            field=models.ManyToManyField(related_name='program_contact', to='csas.ConContact'),
        ),
    ]
