# Generated by Django 3.1.2 on 2020-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0004_auto_20201021_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubpublicationdoclocation',
            name='p1',
            field=models.CharField(blank=True, max_length=1, verbose_name='p1'),
        ),
    ]
