# Generated by Django 3.1.2 on 2021-02-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0005_auto_20201201_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (en)')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description (fr)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (en)')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description (fr)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='assistance',
            field=models.BooleanField(blank=True, null=True, verbose_name='Assistance'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='assistance_text',
            field=models.TextField(blank=True, null=True, verbose_name='Assistance Text'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='consequence_text',
            field=models.TextField(blank=True, null=True, verbose_name='Consequence Text'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='coordinator_name',
            field=models.ManyToManyField(blank=True, related_name='coordinator_name', to='csas.ConContact', verbose_name='Name of Coordinator'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='director_name',
            field=models.ManyToManyField(blank=True, related_name='director_name', to='csas.ConContact', verbose_name='Name of Director'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='file',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='fiscal_year_text',
            field=models.TextField(blank=True, null=True, verbose_name='Fiscal Year Text'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='manager_name',
            field=models.ManyToManyField(blank=True, related_name='manager_name', to='csas.ConContact', verbose_name='Manager Name'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Received Date'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='zonal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Zonal'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='zonal_text',
            field=models.TextField(blank=True, null=True, verbose_name='Zonal Text'),
        ),
        migrations.AlterField(
            model_name='concontact',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='concontact',
            name='contact_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csas.cottype', verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='concontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='concontact',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csas.lanlanguage', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='concontact',
            name='notification_preference',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csas.notnotificationpreference', verbose_name='Communication Preference'),
        ),
        migrations.AlterField(
            model_name='pubpublication',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csas.psepublicationseries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='pubpublicationdoclocation',
            name='p1',
            field=models.CharField(blank=True, max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reqrequest',
            name='assigned_req_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned Request Number'),
        ),
        migrations.RemoveField(
            model_name='reqrequest',
            name='client_name',
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='client_name',
            field=models.ManyToManyField(blank=True, related_name='client_name', to='csas.ConContact', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='reqrequest',
            name='in_year_request',
            field=models.BooleanField(blank=True, null=True, verbose_name='In-Year Request'),
        ),
        migrations.AlterField(
            model_name='reqrequestcsas',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='req_status', serialize=False, to='csas.reqrequest'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='directorate_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csas.brabranch', verbose_name='Directorate Branch'),
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csas.rettype', verbose_name='Request Type'),
        ),
    ]
