# Generated by Django 3.1.2 on 2021-01-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0005_auto_20201201_0741'),
        ('csas', '0002_reqrequest_received_date'),
    ]

    operations = [
    ]
