# Generated by Django 2.2.2 on 2020-02-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0005_auto_20200226_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loclocation',
            old_name='mct_id',
            new_name='loc_id',
        ),
        migrations.AlterField(
            model_name='metmeeting',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.LocLocation', to_field='mct_id'),
        ),
        migrations.AlterField(
            model_name='pubpublicationdetails',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csas.LocLocation', to_field='mct_id'),
        ),
    ]
