# Generated by Django 3.1.2 on 2021-02-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0006_auto_20210204_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqrequest',
            name='directorate_branch',
        ),
        migrations.AddField(
            model_name='reqrequest',
            name='directorate_branch',
            field=models.ManyToManyField(blank=True, to='csas.BraBranch', verbose_name='Directorate Branch'),
        ),
    ]
