# Generated by Django 3.1.6 on 2021-03-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0004_auto_20210207_2032'),
        ('csas', '0010_auto_20210224_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omcost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects2.omcategory'),
        ),
        migrations.AlterField(
            model_name='omcost',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='csas_om_costs', to='projects2.fundingsource'),
        ),
    ]
