# Generated by Django 2.2.2 on 2019-10-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='cosewic_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sara_spp', to='sar_search.SpeciesStatus', verbose_name='SARA status'),
        ),
        migrations.AlterField(
            model_name='species',
            name='sara_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'used_for': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cosewic_spp', to='sar_search.SpeciesStatus', verbose_name='COSEWIC status'),
        ),
    ]
