# Generated by Django 2.2.2 on 2020-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0004_auto_20200122_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionpolygon',
            name='type',
        ),
        migrations.AddField(
            model_name='region',
            name='type',
            field=models.IntegerField(choices=[(2, 'line'), (3, 'polygon')], default=3, verbose_name='record type'),
        ),
    ]
