# Generated by Django 2.2.2 on 2019-07-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0004_range_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='species_status',
        ),
        migrations.AddField(
            model_name='species',
            name='cosewic_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cosewic_spp', to='sar_search.SpeciesStatus', verbose_name='SARA status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='sara_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sara_spp', to='sar_search.SpeciesStatus', verbose_name='COSEWIC status'),
            preserve_default=False,
        ),
    ]
