# Generated by Django 2.2.2 on 2019-10-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0004_auto_20191025_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='cosewic_status1',
            new_name='sara_status',
        ),
    ]
