# Generated by Django 2.2.2 on 2019-07-31 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sar_search', '0009_auto_20190725_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='date_last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified'),
        ),
        migrations.AddField(
            model_name='range',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='species',
            name='date_last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified'),
        ),
        migrations.AddField(
            model_name='species',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sar_spp', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
    ]
