# Generated by Django 2.2.2 on 2019-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0009_auto_20191113_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='iucn_red_list_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
