# Generated by Django 2.2.2 on 2019-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0011_auto_20191113_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='nb_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='ns_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='pe_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
