# Generated by Django 2.2.2 on 2019-08-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0017_auto_20190802_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RangePoints',
            new_name='RecordPoints',
        ),
    ]
