# Generated by Django 2.2.2 on 2019-08-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0021_auto_20190802_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpoints',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='sar_search.Record'),
        ),
    ]
