# Generated by Django 2.2.2 on 2019-08-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0024_remove_record_temp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpoints',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='sar_search.Record'),
        ),
    ]
