# Generated by Django 2.2.2 on 2019-08-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0024_auto_20190715_1550'),
        ('sar_search', '0025_auto_20190809_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='County',
            new_name='Region',
        ),
    ]
