# Generated by Django 2.2.2 on 2019-08-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0027_auto_20190816_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='regions', to='shared_models.Province'),
        ),
        migrations.CreateModel(
            name='RegionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='sar_search.Region')),
            ],
            options={
                'ordering': ['region'],
            },
        ),
    ]
