# Generated by Django 2.2.2 on 2019-08-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0030_auto_20190816_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionpolygon',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='sar_search.Region'),
        ),
        migrations.AlterField(
            model_name='regionpolygonpoint',
            name='region_polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='sar_search.RegionPolygon'),
        ),
    ]
