# Generated by Django 2.2.2 on 2019-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0032_regionpolygon_old_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionpolygonpoint',
            options={'ordering': ['region_polygon', 'order']},
        ),
        migrations.AddField(
            model_name='regionpolygonpoint',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
