# Generated by Django 2.2.2 on 2019-08-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0034_auto_20190820_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='records', to='sar_search.Region'),
        ),
    ]
