# Generated by Django 2.2.2 on 2019-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0035_auto_20190820_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesstatus',
            options={'ordering': ['used_for', 'name']},
        ),
        migrations.AddField(
            model_name='speciesstatus',
            name='used_for',
            field=models.IntegerField(blank=True, choices=[(1, 'SARA'), (2, 'Nova Scotia'), (3, 'New Brunswick'), (4, 'Prince Edward Island')], null=True),
        ),
    ]
