# Generated by Django 2.2.2 on 2019-10-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0036_auto_20191023_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='CITESAppendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='english name')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='french name')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='english description')),
                ('description_fre', models.TextField(blank=True, null=True, verbose_name='french description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='english name')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='french name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='species',
            name='iucn_red_list_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'used_for': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='iucn_spp', to='sar_search.SpeciesStatus', verbose_name='IUCN Red Flag status'),
        ),
        migrations.AddField(
            model_name='species',
            name='nb_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'used_for': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nb_spp', to='sar_search.SpeciesStatus', verbose_name='NB status'),
        ),
        migrations.AddField(
            model_name='species',
            name='ns_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'used_for': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ns_spp', to='sar_search.SpeciesStatus', verbose_name='NS status'),
        ),
        migrations.AddField(
            model_name='species',
            name='pe_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'used_for': 4}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pe_spp', to='sar_search.SpeciesStatus', verbose_name='PEI status'),
        ),
        migrations.AlterField(
            model_name='species',
            name='sara_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'used_for': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sara_spp', to='sar_search.SpeciesStatus', verbose_name='COSEWIC status'),
        ),
        migrations.AlterField(
            model_name='speciesstatus',
            name='used_for',
            field=models.IntegerField(choices=[(1, 'SARA / COSEWIC'), (2, 'Nova Scotia'), (3, 'New Brunswick'), (4, 'Prince Edward Island'), (5, 'IUCN Red List')]),
        ),
        migrations.AddField(
            model_name='species',
            name='cites_appendix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spp', to='sar_search.CITESAppendix', verbose_name='CITES appendix'),
        ),
        migrations.AddField(
            model_name='species',
            name='responsible_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spp', to='sar_search.ResponsibleAuthority', verbose_name='responsible authority'),
        ),
    ]
