# Generated by Django 3.2 on 2021-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='planning year')),
                ('client', models.CharField(max_length=250, verbose_name='client')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='description')),
                ('link', models.URLField(blank=True, max_length=250, null=True, verbose_name='link')),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='age_group',
            field=models.CharField(blank=True, choices=[('N', 'Newborn'), ('J', 'Juvenile'), ('A', 'Adult'), ('UnK', 'Unknown')], max_length=255, null=True, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='first_report',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date and time first reported'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('E', 'Entangled'), ('DF', 'DEAD - Floating'), ('DB', 'DEAD - Beached'), ('LS', 'LIVE - Stranded')], max_length=255, null=True, verbose_name='type of Incident'),
        ),
    ]
