# Generated by Django 3.2 on 2021-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0002_auto_20210419_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='planning year')),
                ('client', models.CharField(max_length=250, verbose_name='client')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='description')),
                ('link', models.URLField(blank=True, max_length=250, null=True, verbose_name='link')),
            ],
        ),
    ]
