# Generated by Django 3.1.2 on 2020-12-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0002_fix_verbose_names_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
    ]
