# Generated by Django 3.2 on 2021-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0003_add_planning_links_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='exam',
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reported by'),
        ),
        migrations.AddField(
            model_name='incident',
            name='response',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='was there a response?'),
        ),
        migrations.AddField(
            model_name='incident',
            name='response_by',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='whalebrary.Organisation', verbose_name='response by'),
        ),
        migrations.AddField(
            model_name='incident',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date and time of response'),
        ),
        migrations.AddField(
            model_name='incident',
            name='response_type',
            field=models.CharField(blank=True, choices=[('D', 'Disentanglement'), ('R', 'Refloating'), ('DE', 'Documentation / Examination'), ('N', 'Necropsy'), ('E', 'Education'), ('O', 'Other')], max_length=255, null=True, verbose_name='response type'),
        ),
    ]
