# Generated by Django 3.1.6 on 2021-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0004_auto_20201215_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('E', 'Entangled'), ('DF', 'DEAD - Floating'), ('DB', 'DEAD - Beached'), ('N', 'Necropsy'), ('LS', 'LIVE - Stranded'), ('DS', 'DEAD - Stranded')], max_length=255, null=True, verbose_name='type of Incident'),
        ),
    ]
