# Generated by Django 3.2 on 2021-05-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0004_incident_model_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='reported by')),
                ('resight_date', models.DateTimeField(blank=True, null=True, verbose_name='date and time of resight')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments/details')),
                ('date_email_sent', models.DateTimeField(blank=True, null=True, verbose_name='date resight incident emailed')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resights', to='whalebrary.incident', verbose_name='incident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
