# Generated by Django 3.1.6 on 2021-04-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0005_add_incident_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='lat',
            new_name='latitude',
        ),
    ]
