# Generated by Django 2.2.2 on 2020-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0006_big_transaction_model_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
