# Generated by Django 3.2 on 2021-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0006_fix_planninglink_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='species code'),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('incident_type', 'species', 'first_report')},
        ),
    ]
