# Generated by Django 2.2.2 on 2020-07-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0007_transaction_quantity_positive_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='received date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='whalebrary.Transaction', verbose_name='transaction'),
        ),
    ]
