# Generated by Django 3.2 on 2021-05-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0007_add_species_code_and_incident_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together=set(),
        ),
    ]
