# Generated by Django 3.1.6 on 2021-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0008_auto_20210408_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('name_latin', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (latin)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
