# Generated by Django 3.2.14 on 2022-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0008_alter_incident_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='return_tracker',
            field=models.BooleanField(default=False),
        ),
    ]
