# Generated by Django 3.2.15 on 2022-11-21 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whalebrary', '0010_add_boolean_field_transaction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maint_type', models.CharField(blank=True, choices=[(1, 'Charging'), (2, 'Book Inspection'), (3, 'Other')], max_length=255, null=True, verbose_name='maintenance type')),
                ('schedule', models.DurationField(default=datetime.timedelta(days=30), verbose_name='maintenance schedule')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments/details')),
                ('last_maint_date', models.DateTimeField(blank=True, null=True, verbose_name='date last maintained')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigneds', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintenances', to='whalebrary.item', verbose_name='item')),
                ('last_maint_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintainers', to=settings.AUTH_USER_MODEL, verbose_name='last maintained by')),
            ],
        ),
    ]
