# Generated by Django 3.2.16 on 2023-01-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0013_make_transaction_quantity_mandatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['last_maint_date']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_tracker',
            field=models.BooleanField(default=False, verbose_name='Returned'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Purchase'), (2, 'Use'), (3, 'Lend'), (4, 'Return'), (5, 'Transfer Out'), (6, 'Transfer In')], default=1, verbose_name='tag'),
            preserve_default=False,
        ),
    ]
