# Generated by Django 3.2.16 on 2023-01-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0014_make_transaction_category_choices_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Purchase'), (2, 'Use'), (3, 'Lend'), (4, 'Return'), (5, 'Transfer Out'), (6, 'Transfer In')], verbose_name='type'),
        ),
    ]
