# Generated by Django 2.2.13 on 2020-10-19 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0015_auto_20201016_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 16, 46, 31, 980613), verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='training',
            field=models.ManyToManyField(blank=True, to='whalebrary.Training', verbose_name='training'),
        ),
    ]
