# Generated by Django 3.1.2 on 2020-10-30 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0017_auto_20201020_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 12, 21, 24, 555328), verbose_name='order date'),
        ),
    ]
