# Generated by Django 3.1.2 on 2020-11-16 13:33

from django.db import migrations, models
import django.db.models.deletion
import whalebrary.models


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0020_change_default_date_ordered_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to=whalebrary.models.image_directory_path, verbose_name='image')),
                ('date_uploaded', models.DateTimeField(auto_now=True, verbose_name='date uploaded')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='whalebrary.incident', verbose_name='incident')),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
