# Generated by Django 3.1.2 on 2020-11-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whalebrary', '0022_auto_20201117_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='training',
            new_name='trainings',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='audit',
            new_name='audits',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tag',
            new_name='tags',
        ),
    ]
