# Generated by Django 2.1.4 on 2019-03-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount_requested',
            field=models.FloatField(blank=True, null=True, verbose_name='Funding Requested'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='ihub.EntryType', verbose_name='Entry Type'),
        ),
    ]
