# Generated by Django 2.1.4 on 2019-04-17 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ihub.models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='entryperson',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='entryperson',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Lead'), (2, 'Contact')], null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='file',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=ihub.models.file_directory_path, verbose_name='file'),
        ),
    ]
