# Generated by Django 2.2.2 on 2019-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='type',
            field=models.IntegerField(choices=[(1, 'Action'), (2, 'Next step'), (3, 'Comment'), (4, 'Follow-up (*)')]),
        ),
    ]
