# Generated by Django 2.2.2 on 2020-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='initial_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='initial activity date'),
        ),
    ]
