# Generated by Django 3.1.2 on 2021-01-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='old_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
