# Generated by Django 3.2 on 2021-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0003_auto_20210204_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_faa_required',
            field=models.BooleanField(blank=True, null=True, verbose_name='is an FAA required?'),
        ),
        migrations.AddField(
            model_name='entry',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='response deadline'),
        ),
    ]
