# Generated by Django 2.2.2 on 2020-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0005_auto_20191128_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, verbose_name='level')),
                ('name', models.CharField(max_length=255, verbose_name='name (English)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (French)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
