# Generated by Django 2.1.4 on 2019-01-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0005_auto_20190118_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ihub.Status', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='entrytype',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
