# Generated by Django 3.2.4 on 2021-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0011_alter_sector_unique_together'),
        ('ihub', '0005_entry_response_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='organizations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'grouping__is_indigenous': True}, related_name='entries', to='masterlist.Organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='entries', to='masterlist.Sector', verbose_name='DFO sectors'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=1000, null=True, verbose_name='title'),
        ),
    ]
