# Generated by Django 2.1.4 on 2019-01-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0006_auto_20190129_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
