# Generated by Django 3.2.13 on 2022-05-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0006_auto_20210921_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_faa_issued',
            field=models.BooleanField(default=False, verbose_name='has an FAA been issued?'),
        ),
    ]
