# Generated by Django 3.2.13 on 2022-05-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0007_entry_is_faa_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_faa_issued',
        ),
    ]
