# Generated by Django 2.1.4 on 2019-01-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0007_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ihub.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ihub.Status', verbose_name='status'),
        ),
    ]
