# Generated by Django 3.2.13 on 2022-05-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0008_remove_entry_is_faa_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_faa_issued',
            field=models.BooleanField(blank=True, null=True, verbose_name='has an FAA been issued?'),
        ),
    ]
