# Generated by Django 2.1.4 on 2019-01-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0008_auto_20190129_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='subject',
        ),
    ]
