# Generated by Django 2.1.4 on 2019-02-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0010_auto_20190206_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbrev',
            field=models.CharField(default='xyz', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_eng',
            field=models.CharField(default='xyz', max_length=1000),
            preserve_default=False,
        ),
    ]
