# Generated by Django 2.1.4 on 2019-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0017_remove_entry_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
