# Generated by Django 2.1.4 on 2019-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0021_auto_20190214_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='off_reserve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='on_reserve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_reserves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
