# Generated by Django 2.1.4 on 2019-02-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0023_auto_20190214_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='election_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
