# Generated by Django 2.1.4 on 2019-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0025_auto_20190214_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'ordering': ['position_title']},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='telephone1',
            new_name='phone_1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='telephone2',
            new_name='phone_2',
        ),
        migrations.AddField(
            model_name='person',
            name='fax',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='amount_expected',
            field=models.FloatField(blank=True, null=True, verbose_name='How much funding is expected'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='amount_transferred',
            field=models.FloatField(blank=True, null=True, verbose_name='If yes, how much funding was transferred'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='funding_needed',
            field=models.NullBooleanField(verbose_name='is funding needed'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='funding_requested',
            field=models.NullBooleanField(verbose_name='was funding requested'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='transferred',
            field=models.NullBooleanField(verbose_name='has any funding been transferred'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FIN'),
        ),
    ]
