# Generated by Django 2.1.4 on 2019-02-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0031_auto_20190214_1617'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='organizationmember',
        #     unique_together=set(),
        # ),
    ]
