# Generated by Django 2.1.4 on 2019-02-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0036_remove_organizationmember_member_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='amount_expected',
            new_name='amount_requested',
        ),
    ]
