# Generated by Django 2.1.4 on 2019-02-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0040_entry_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='organization',
            new_name='organizations',
        ),
    ]
