# Generated by Django 2.1.4 on 2019-02-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0043_entry_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='region',
            new_name='regions',
        ),
    ]
