# Generated by Django 2.1.4 on 2019-02-15 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0044_auto_20190214_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberrole',
            name='color',
        ),
        migrations.AlterField(
            model_name='entry',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='ihub.Sector', verbose_name='DFO sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name (English)'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (French)'),
        ),
    ]
