# Generated by Django 2.1.4 on 2019-02-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihub', '0046_auto_20190215_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sectors',
            field=models.ManyToManyField(related_name='entries', to='ihub.Sector', verbose_name='DFO sectors'),
        ),
    ]
