# Generated by Django 2.1.4 on 2019-04-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios2', '0004_auto_20190409_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='category',
            field=models.IntegerField(choices=[(1, 'Calibration'), (2, 'Repair')], verbose_name='category'),
        ),
    ]
