# Generated by Django 2.1.4 on 2019-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios2', '0005_auto_20190409_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehistory',
            options={'get_latest_by': ['service_date']},
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='date_of_last_service',
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='next_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Service Date'),
        ),
    ]
