# Generated by Django 2.0.4 on 2018-10-01 17:26

from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20180703_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=docs.models.img_file_name),
        ),
    ]
