# Generated by Django 2.0.4 on 2018-10-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_delete_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='item_name',
            new_name='title',
        ),
    ]
