# Generated by Django 2.0.4 on 2018-10-01 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20181001_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
