# Generated by Django 3.2.5 on 2021-11-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0002_sample_season_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='season_type',
            field=models.IntegerField(blank=True, choices=[(1, 'spring'), (2, 'fall')], editable=False, null=True, verbose_name='season'),
        ),
    ]
