# Generated by Django 2.1.4 on 2019-04-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0011_auto_20190423_1557'),
        ('herring', '0003_auto_20190423_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='herring_samples', to='shared_models.Port'),
        ),
    ]
