# Generated by Django 2.1.4 on 2019-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0004_sample_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='survey_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='survey identifier'),
        ),
    ]
