# Generated by Django 3.2.14 on 2022-10-31 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herring', '0005_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetail',
            name='is_empty',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='fishdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishdetail',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishdetail',
            name='lab_sampler',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_sampler_fish_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishdetail',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_by_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishdetail',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishdetail',
            name='otolith_sampler',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='otolith_sampler_fish_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='catch_weight_lbs',
            field=models.FloatField(blank=True, help_text='Total weight of the catch from which the sample was collected', null=True, verbose_name='Catch weight (lbs)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='district',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='herring.district'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab_processing_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_by_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='latitude_n',
            field=models.FloatField(blank=True, help_text='In decimal degrees, e.g., 48.67789', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='length_frequencies',
            field=models.ManyToManyField(editable=False, through='herring.LengthFrequency', to='herring.LengthBin'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='longitude_w',
            field=models.FloatField(blank=True, help_text='In decimal degrees, e.g., -64.57819', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='old_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='otolith_processing_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_weight_lbs',
            field=models.FloatField(blank=True, help_text='Total weight of the sample collected', null=True, verbose_name='Sample weight (lbs)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampler_ref_number',
            field=models.IntegerField(blank=True, help_text="This might be a sampler's reference number or a set number from a survey", null=True, verbose_name='field reference number'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='season',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='survey_id',
            field=models.CharField(blank=True, help_text='Usually the mission number of the survey from which the sample came.', max_length=50, null=True, verbose_name='survey identifier'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_fish_measured',
            field=models.IntegerField(blank=True, help_text='How many specimens were measured?', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_fish_preserved',
            field=models.IntegerField(blank=True, help_text='How many specimens were collected?', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Port'), (2, 'Sea')], null=True, verbose_name='Sample type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='vessel_cfvn',
            field=models.IntegerField(blank=True, null=True, verbose_name='vessel CFVN'),
        ),
    ]
