# Generated by Django 2.0.4 on 2018-09-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0007_auto_20180905_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='herring.Vessel'),
        ),
    ]
