# Generated by Django 2.2.2 on 2019-10-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0010_auto_20191023_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sampler_ref_number',
            field=models.IntegerField(blank=True, null=True, verbose_name="Sampler's reference number / set number"),
        ),
    ]
