# Generated by Django 2.0.4 on 2018-09-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0011_auto_20180905_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sampling_protocol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='herring.SamplingProtocol'),
        ),
    ]
