# Generated by Django 2.0.4 on 2018-09-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0015_auto_20180906_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_passed', models.BooleanField(default=False)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_tests', to='herring.Sample')),
            ],
            options={
                'ordering': ('sample', 'test'),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Port'), (2, 'At-sea')])),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='lengthfrequency',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='length_frequency_objects', to='herring.Sample'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='herring.Test'),
        ),
        migrations.AddField(
            model_name='sample',
            name='tests',
            field=models.ManyToManyField(through='herring.SampleTest', to='herring.Test'),
        ),
        migrations.AlterUniqueTogether(
            name='sampletest',
            unique_together={('sample', 'test')},
        ),
    ]
