# Generated by Django 2.0.4 on 2018-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0018_auto_20180907_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='lab_processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='otolith_processing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
