# Generated by Django 3.2.14 on 2022-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0019_fishdetail_will_count_eggs'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='use_fmb',
            field=models.BooleanField(default=False, verbose_name='use fish measuring board by default'),
        ),
    ]
