# Generated by Django 2.0.4 on 2018-09-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0021_auto_20180910_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishdetail',
            old_name='ager2',
            new_name='ager',
        ),
    ]
