# Generated by Django 3.2.14 on 2022-11-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0022_auto_20221116_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='egg_processing_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
