# Generated by Django 2.0.4 on 2018-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0025_auto_20180911_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('somatic_weight', 'Somatic weight'), ('gonad_weight', 'Gonad weight'), ('fish_length', 'Fish length')], max_length=255),
        ),
    ]
