# Generated by Django 2.0.4 on 2018-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0026_auto_20180912_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='scope',
            field=models.IntegerField(choices=[('1', 'Global'), ('3', 'Somatic weight'), ('4', 'Gonad weight'), ('2', 'Fish length')]),
        ),
    ]
