# Generated by Django 2.0.4 on 2018-10-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0033_auto_20181017_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdetail',
            name='otolith_image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
