# Generated by Django 2.0.4 on 2018-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0037_test_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetailtest',
            name='scope',
            field=models.IntegerField(choices=[(1, ' lab_detail'), (2, 'otolith detail')], default=1),
            preserve_default=False,
        ),
    ]
