# Generated by Django 2.0.4 on 2018-10-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0038_fishdetailtest_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='vessel_cfvn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
