# Generated by Django 2.0.4 on 2018-10-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herring', '0039_sample_vessel_cfvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdetail',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_details', to='herring.Sample'),
        ),
    ]
