# Generated by Django 3.1.2 on 2020-12-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='start_date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='end_date',
        ),
    ]
