# Generated by Django 3.2.14 on 2022-07-13 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0002_alter_transect_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='percent_pebble',
            new_name='percent_boulder',
        ),
    ]
