# Generated by Django 3.2.14 on 2022-07-13 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0003_auto_20220713_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='percent_boulder',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='boulder [0-1]'),
        ),
    ]
