# Generated by Django 3.2.14 on 2022-10-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0005_auto_20220823_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='not_sampled',
            field=models.BooleanField(default=False, verbose_name='section not sampled?'),
        ),
        migrations.AlterField(
            model_name='section',
            name='reason_not_sampled',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Complex'), (2, '2 - Other (e.g. low on air, bad visibility)')], null=True, verbose_name='reason section was not sampled'),
        ),
        migrations.AlterField(
            model_name='section',
            name='rock_crab_presence',
            field=models.IntegerField(blank=True, choices=[(None, 'NA'), (0, '0 - no rock crab detected'), (1, '1 - rock crab detected')], null=True, verbose_name='rock crab detection code'),
        ),
    ]
