# Generated by Django 3.2.4 on 2021-07-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0006_auto_20210716_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='transect',
            field=models.ForeignKey(blank=True, help_text='Leave blank if training', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dives', to='scuba.transect', verbose_name='transect'),
        ),
        migrations.AlterField(
            model_name='dive',
            name='width_m',
            field=models.FloatField(blank=True, null=True, verbose_name='width (m)'),
        ),
    ]
