# Generated by Django 3.1.2 on 2021-01-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0006_auto_20201218_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='heading',
            field=models.CharField(blank=True, choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West')], max_length=1, null=True, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='dive',
            name='sample',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='dives', to='scuba.sample', verbose_name='sample'),
        ),
        migrations.AlterField(
            model_name='dive',
            name='side',
            field=models.CharField(blank=True, choices=[('l', 'Left'), ('r', 'Right')], max_length=1, null=True, verbose_name='side'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scuba.section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='dive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scuba.dive', verbose_name='dive'),
        ),
        migrations.AlterField(
            model_name='site',
            name='region',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sites', to='scuba.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transects', to='scuba.site', verbose_name='site'),
        ),
    ]
