# Generated by Django 3.1.2 on 2021-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0009_auto_20210107_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='gas_mix',
            field=models.CharField(blank=True, default='air', max_length=100, null=True, verbose_name='gas mix'),
        ),
        migrations.AddField(
            model_name='dive',
            name='psi_in',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSI in'),
        ),
        migrations.AddField(
            model_name='dive',
            name='psi_out',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSI out'),
        ),
        migrations.AddField(
            model_name='dive',
            name='reach_surface',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reach surface (yyyy-mm-dd hh:mm)'),
        ),
        migrations.AddField(
            model_name='dive',
            name='start_descent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start descent (yyyy-mm-dd hh:mm)'),
        ),
        migrations.AddField(
            model_name='dive',
            name='start_final_ascent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start final ascent (yyyy-mm-dd hh:mm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='datetime',
            field=models.DateField(verbose_name='date (yyyy-mm-dd)'),
        ),
    ]
