# Generated by Django 3.1.2 on 2021-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0010_auto_20210107_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='datetime',
            field=models.DateTimeField(verbose_name='date (yyyy-mm-dd)'),
        ),
    ]
