# Generated by Django 3.2.5 on 2021-11-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0011_auto_20211105_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aphia_id', models.IntegerField(verbose_name='WoRMS AphiaID')),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['code'],
            },
        ),
    ]
