# Generated by Django 3.1.2 on 2021-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0013_auto_20210108_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='certainty_rating',
            field=models.IntegerField(default=1, verbose_name='certainty rating'),
        ),
    ]
