# Generated by Django 3.2.5 on 2021-12-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0015_auto_20211116_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='end_latitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='end latitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='end_latitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='end latitude'),
        ),
        migrations.AddField(
            model_name='sample',
            name='end_latitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='end latitude (minutes)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='end_longitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='end longitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='end_longitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='end longitude'),
        ),
        migrations.AddField(
            model_name='sample',
            name='end_longitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='end longitude (minutes)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='start_latitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='start latitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='start_latitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='start latitude'),
        ),
        migrations.AddField(
            model_name='sample',
            name='start_latitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='start latitude (minutes)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='start_longitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='start longitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='start_longitude_d',
            field=models.IntegerField(blank=True, help_text='Degrees (DD)', null=True, verbose_name='start longitude'),
        ),
        migrations.AddField(
            model_name='sample',
            name='start_longitude_mm',
            field=models.FloatField(blank=True, help_text='Minutes (MM.mmmmm)', null=True, verbose_name='start longitude (minutes)'),
        ),
    ]
