# Generated by Django 3.2.5 on 2021-12-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0016_auto_20211201_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='scuba.region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='transect',
            name='new_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='transect',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transects', to='scuba.region', verbose_name='site'),
        ),
        migrations.AlterUniqueTogether(
            name='transect',
            unique_together={('new_name', 'region'), ('name', 'site')},
        ),
    ]
