# Generated by Django 3.2.5 on 2021-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0017_auto_20211201_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='region',
            name='new_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='name'),
        ),
    ]
