# Generated by Django 3.1.2 on 2021-01-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0017_auto_20210111_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=2, verbose_name='sex'),
        ),
    ]
