# Generated by Django 3.2.5 on 2021-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0018_auto_20211201_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='transect',
            name='old_site_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='name'),
        ),
    ]
