# Generated by Django 3.1.2 on 2021-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0018_auto_20210111_0522'),
    ]

    operations = [

        migrations.AddField(
            model_name='dive',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='start latitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='dive',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='start longitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='transect',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='end latitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='transect',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='end longitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='transect',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='start latitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='transect',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='start longitude (decimal degrees)'),
        ),
    ]
