# Generated by Django 3.2.5 on 2021-12-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0019_auto_20211201_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='latitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude_d',
            field=models.IntegerField(blank=True, null=True, verbose_name='latitude (degrees)'),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude (minutes)'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='longitude (decimal degrees)'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude_d',
            field=models.IntegerField(blank=True, null=True, verbose_name='longitude (degrees)'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude (minutes)'),
        ),
    ]
