# Generated by Django 3.2.5 on 2021-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0022_rename_old_site_name_transect_old_transect_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transect',
            name='old_transect_name',
        ),
        migrations.AddField(
            model_name='transect',
            name='old_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='old name'),
        ),
    ]
