# Generated by Django 3.2.5 on 2021-12-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0024_alter_sample_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='transect',
            field=models.ForeignKey(blank=True, editable=False, help_text='Leave blank if training', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dives', to='scuba.transect', verbose_name='transect'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transects', to='scuba.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transects', to='scuba.site', verbose_name='site'),
        ),
    ]
