# Generated by Django 3.2.5 on 2021-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0027_auto_20211206_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transect',
            name='name',
            field=models.IntegerField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='transect',
            name='old_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='old name'),
        ),
        migrations.AlterUniqueTogether(
            name='transect',
            unique_together=set(),
        ),
    ]
