# Generated by Django 3.1.2 on 2021-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0027_auto_20210121_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='certainty_rating',
            field=models.IntegerField(choices=[(1, '1 - certain'), (0, '0 - uncertain')], default=1, verbose_name='length certainty'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='egg_status',
            field=models.CharField(blank=True, choices=[('0', '0 - no eggs'), ('b', 'b - berried'), ('b1', 'b1 - berried with new eggs'), ('b2', 'b2 - berried with black eggs'), ('b3', 'b3 - berried with developed eggs')], max_length=2, null=True, verbose_name='egg status'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sex',
            field=models.CharField(choices=[('u', '0 - unknown'), ('m', '1 - male'), ('f', '2 - female')], max_length=2, verbose_name='sex'),
        ),
    ]
