# Generated by Django 3.2.5 on 2021-12-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0027_alter_transect_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transect',
            unique_together={('name', 'region')},
        ),
    ]
