# Generated by Django 3.2.5 on 2021-12-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0031_remove_transect_new_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transect',
            name='name',
            field=models.IntegerField(verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='transect',
            unique_together={('name', 'region')},
        ),
    ]
