# Generated by Django 3.2.15 on 2023-01-10 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0034_auto_20221017_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acronym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym_id', models.IntegerField(null=True)),
                ('acronym_letters', models.CharField(max_length=10, null=True)),
                ('acronym_full_name', models.CharField(max_length=100)),
                ('acronym_topic', models.CharField(blank=True, max_length=75, null=True)),
                ('acronym_url', models.URLField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID')),
                ('inventory_id', models.IntegerField(null=True, verbose_name='Inventory ID')),
                ('Approved_By', models.CharField(max_length=50, null=True, verbose_name='Approved By')),
                ('Data_Asset_Name', models.CharField(max_length=125, null=True, verbose_name='Data Asset Name')),
                ('Data_Asset_Steward', models.CharField(max_length=50, null=True, verbose_name='Data Asset Steward')),
                ('Data_Asset_Sorting_Category', models.IntegerField(blank=True, null=True, verbose_name='Data Asset Sorting Category')),
                ('Operational_Or_Analytical_Data', models.CharField(max_length=15, null=True, verbose_name='Operational Or Analytical Data')),
                ('Data_Asset_Acronym', models.CharField(max_length=15, null=True, verbose_name='Data Asset Acronym')),
                ('Data_Asset_Description', models.TextField(blank=True, null=True, verbose_name='Data Asset Description')),
                ('APM_ID', models.IntegerField(blank=True, null=True, verbose_name='APM_ID')),
                ('Non_Salmon_Data', models.CharField(max_length=5, null=True, verbose_name='Non Salmon Data')),
                ('Data_Asset_Status', models.CharField(max_length=25, null=True, verbose_name='Data Asset Status')),
                ('Data_Asset_Format', models.CharField(max_length=50, null=True, verbose_name='Data Asset Format')),
                ('Data_Type', models.CharField(max_length=15, null=True, verbose_name='Data Type')),
                ('Data_Asset_Location', models.CharField(max_length=25, null=True, verbose_name='Data Asset Location')),
                ('Data_Asset_Trustee', models.CharField(max_length=50, null=True, verbose_name='Data Asset Trustee')),
                ('Data_Asset_Custodian', models.CharField(max_length=50, null=True, verbose_name='Data Asset Custodian')),
                ('Application_Data_Asset_is_Associated_With', models.TextField(blank=True, null=True, verbose_name='Application Data Asset is Associated With')),
                ('Application_Description', models.TextField(blank=True, null=True, verbose_name='Application Description')),
                ('Technical_Documentation', models.TextField(blank=True, null=True, verbose_name='Technical Documentation')),
                ('Access_Point', models.TextField(blank=True, null=True, verbose_name='Access Point')),
                ('Policy_Levers_Data_Asset_Supports', models.CharField(max_length=25, null=True, verbose_name='Policy Levers Data Asset Supports')),
                ('Key_Decisions', models.TextField(blank=True, null=True, verbose_name='Key Decisions')),
                ('Impact_to_DFO_Data_Consumers', models.CharField(max_length=125, null=True, verbose_name='Impact to DFO Data Consumers')),
                ('Decision_Supporting_Key_Products', models.TextField(blank=True, null=True, verbose_name='Decision Supporting Key Products')),
                ('Impact_on_Decision_Making', models.CharField(max_length=10, null=True, verbose_name='Impact on Decision Making')),
                ('Uniqueness', models.CharField(max_length=5, null=True, verbose_name='Uniqueness')),
                ('Cost', models.TextField(blank=True, null=True, verbose_name='Cost')),
                ('Data_Asset_Size', models.TextField(blank=True, null=True, verbose_name='Data Asset Size')),
                ('Update_Frequency', models.CharField(max_length=25, null=True, verbose_name='Update Frequency')),
                ('Data_Standards', models.CharField(max_length=50, null=True, verbose_name='Data Standards')),
                ('Metadata_Maturity', models.CharField(max_length=5, null=True, verbose_name='Metadata Maturity')),
                ('Data_Quality_Rating', models.CharField(max_length=15, null=True, verbose_name='Data Quality Rating')),
                ('Naming_Conventions', models.CharField(max_length=15, null=True, verbose_name='Naming Conventions')),
                ('Security_Classification', models.CharField(max_length=15, null=True, verbose_name='Security Classification')),
                ('Inbound_Data_Linkage', models.TextField(blank=True, null=True, verbose_name='Inbound Data Linkage')),
                ('Outbound_Data_Linkage', models.TextField(blank=True, null=True, verbose_name='Outbound Data Linkage')),
                ('Publication_Status', models.TextField(blank=True, null=True, verbose_name='Publication Status')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag_name', models.CharField(max_length=25)),
                ('primary_tag_id', models.IntegerField(blank=True, null=True)),
                ('inventory_id', models.ManyToManyField(related_name='topic', to='pacificsalmondatahub.DataAsset', verbose_name='Topic')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='national administrator?')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pssiDataAsset_users', to='shared_models.region', verbose_name='regional administrator?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pssiDataAsset_user', to=settings.AUTH_USER_MODEL, verbose_name='DM Apps user')),
            ],
            options={
                'ordering': ['-is_admin', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DataGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_glossary_id', models.IntegerField()),
                ('term_name', models.CharField(max_length=25)),
                ('term_description', models.TextField()),
                ('inventory_id', models.ManyToManyField(to='pacificsalmondatahub.DataAsset')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('comment_creator', models.CharField(max_length=25, null=True)),
                ('comment_contact_info', models.CharField(max_length=50, null=True)),
                ('comment_subject', models.CharField(max_length=50)),
                ('comment_contents', models.TextField()),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacificsalmondatahub.dataasset')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_glossary_id', models.IntegerField()),
                ('term_name', models.CharField(max_length=25)),
                ('term_description', models.TextField()),
                ('inventory_id', models.ManyToManyField(to='pacificsalmondatahub.DataAsset')),
            ],
        ),
    ]
