# Generated by Django 3.2.15 on 2023-01-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacificsalmondatahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='Data_Type',
            field=models.CharField(max_length=15, null=True, verbose_name='Data Type'),
        ),
    ]
