# Generated by Django 3.2.15 on 2022-12-21 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0034_auto_20221017_1301'),
        ('pacificsalmondatahub', '0009_alter_acronym_acronym_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glossary',
            new_name='BusinessGlossary',
        ),
        migrations.RenameField(
            model_name='businessglossary',
            old_name='glossary_ID',
            new_name='businessGlossary_ID',
        ),
        migrations.AlterField(
            model_name='inventoryuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pssiDataAsset_users', to='shared_models.region', verbose_name='regional administrator?'),
        ),
        migrations.AlterField(
            model_name='inventoryuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pssiDataAsset_user', to=settings.AUTH_USER_MODEL, verbose_name='DM Apps user'),
        ),
        migrations.RenameModel(
            old_name='DataInventory',
            new_name='DataAsset',
        ),
        migrations.CreateModel(
            name='DataGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataGlossary_ID', models.IntegerField()),
                ('term_Name', models.CharField(max_length=25)),
                ('term_Description', models.TextField()),
                ('Inventory_ID', models.ManyToManyField(to='pacificsalmondatahub.DataAsset')),
            ],
        ),
    ]
