# Generated by Django 3.2.15 on 2022-12-21 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pacificsalmondatahub', '0010_auto_20221220_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
