# Generated by Django 3.2.15 on 2022-12-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacificsalmondatahub', '0013_rename_acronym_acronym_acronym_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acronym',
            name='acronym_ID',
            field=models.IntegerField(null=True),
        ),
    ]
