# Generated by Django 2.0.4 on 2018-11-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowcrab', '0003_auto_20181128_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crab',
            name='shell_condition_mossy',
        ),
        migrations.AlterField(
            model_name='crab',
            name='shell_condition',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='ShellCondition',
        ),
    ]
