# Generated by Django 2.0.4 on 2018-12-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowcrab', '0005_auto_20181128_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crab',
            options={'ordering': ['crab_number']},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['start_time_logbook']},
        ),
        migrations.RemoveField(
            model_name='set',
            name='cruise',
        ),
    ]
