# Generated by Django 2.0.4 on 2018-12-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowcrab', '0007_auto_20181204_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='cruise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sets', to='snowcrab.Cruise'),
            preserve_default=False,
        ),
    ]
