# Generated by Django 2.0.7 on 2018-12-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowcrab', '0010_crab_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crab',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crabs', to='snowcrab.Sex'),
        ),
        migrations.AlterUniqueTogether(
            name='crab',
            unique_together={('crab_number', 'set')},
        ),
    ]
