# Generated by Django 2.0.7 on 2018-08-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resourcecertification',
            table='inventory_resource_certification',
        ),
        migrations.AlterModelTable(
            name='resourceperson',
            table='inventory_resource_people',
        ),
    ]
