# Generated by Django 2.2.2 on 2020-05-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='od_publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date published to Open Data'),
        ),
    ]
