# Generated by Django 2.1.4 on 2019-03-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0011_auto_20190320_1454'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='section1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resources', to='shared_models.Section'),
        ),
    ]
