# Generated by Django 2.2.2 on 2020-03-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecertification',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
