# Generated by Django 2.2.2 on 2020-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_resource_od_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='odip_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ODIP Identifier'),
        ),
    ]
