# Generated by Django 2.2.2 on 2020-04-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200316_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resources', to='shared_models.Section'),
        ),
    ]
