# Generated by Django 3.2.10 on 2022-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location_country_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='Public URL to thumbnail image'),
        ),
    ]
