# Generated by Django 2.0.7 on 2018-08-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180823_1004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='shared_location',
        ),
        migrations.AlterModelTable(
            name='section',
            table='shared_dfo_section',
        ),
    ]
