# Generated by Django 2.2.2 on 2019-08-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190604_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='analytic_software',
            field=models.TextField(blank=True, null=True, verbose_name='Analytic software notes'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='General notes'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='open_data_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open data notes'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='storage_envr_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Storage notes'),
        ),
    ]
