# Generated by Django 2.2.2 on 2020-04-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
        ('inventory', '0004_auto_20200427_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='publication_fy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.FiscalYear'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='last_revision_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of last published revision'),
        ),
    ]
