# Generated by Django 3.2.14 on 2022-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20220425_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='flagged_4_publication',
            field=models.BooleanField(default=False, verbose_name='Flagged for Publication'),
        ),
    ]
