# Generated by Django 2.2.2 on 2019-08-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190815_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='resources', to='inventory.Citation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='resources', to='inventory.Keyword'),
        ),
    ]
