# Generated by Django 2.0.4 on 2018-10-07 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180824_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=inventory.models.file_directory_path)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.Resource')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
