# Generated by Django 3.2.14 on 2022-12-08 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_resource_flagged_4_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecertification',
            name='certification_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date published to FGP'),
            preserve_default=False,
        ),
    ]
