# Generated by Django 2.0.4 on 2018-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='flagged_4_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='flagged_4_publication',
            field=models.BooleanField(default=False),
        ),
    ]
