# Generated by Django 2.2.2 on 2020-05-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200511_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='public_url',
            field=models.URLField(blank=True, null=True, verbose_name="Link to record on Open Gov't Portal"),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
