# Generated by Django 3.2.16 on 2023-01-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20230111_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dma',
            options={'ordering': ['status', 'title'], 'verbose_name': 'Data Management Agreement'},
        ),
        migrations.AlterField(
            model_name='dma',
            name='data_contact_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='other data contacts'),
        ),
        migrations.AlterField(
            model_name='dma',
            name='metadata_contact_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='other metadata contacts'),
        ),
    ]
