# Generated by Django 2.2.2 on 2019-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20191022_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
