# Generated by Django 3.2.16 on 2023-01-12 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_auto_20230112_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dma',
            options={'ordering': ['section__division__branch__sector__region', 'status', 'title'], 'verbose_name': 'Data Management Agreement'},
        ),
        migrations.AddField(
            model_name='resource',
            name='favourited_by',
            field=models.ManyToManyField(editable=False, related_name='resource_favourited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
