# Generated by Django 2.1.4 on 2019-01-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_dataresource_webservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('english_value', models.CharField(max_length=255, verbose_name='Name (French)')),
                ('french_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataresource',
            name='format',
        ),
        migrations.RemoveField(
            model_name='dataresource',
            name='language',
        ),
        migrations.RemoveField(
            model_name='webservice',
            name='format',
        ),
        migrations.RemoveField(
            model_name='webservice',
            name='language',
        ),
        migrations.AlterField(
            model_name='dataresource',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ContentType'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ContentType'),
        ),
    ]
