# Generated by Django 2.2.2 on 2019-12-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_delete_sectionnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='abstract_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract (English)'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='abstract_fre',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract (French)'),
        ),
    ]
