# Generated by Django 3.2.16 on 2023-01-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20230125_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceType',
        ),
        migrations.AddField(
            model_name='resource',
            name='backup_plan',
            field=models.TextField(blank=True, null=True, verbose_name='What procedures will be taken to back-up/secure the data?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='cloud_costs',
            field=models.TextField(blank=True, help_text="e.g., cloud storage is estimated at $1000/yr and will be paid for under the the division manager's budget", null=True, verbose_name='If using cloud storage, what is the estimated annual cost and who will be covering the cost? '),
        ),
        migrations.AddField(
            model_name='resource',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Additional comments to take into consideration (if applicable):'),
        ),
        migrations.AddField(
            model_name='resource',
            name='data_retention',
            field=models.TextField(blank=True, help_text='Please refer to the DFO EOS Retention Policy for clarification.', null=True, verbose_name='What is the retention policy for the data?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='had_sharing_agreements',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is the dataset subject to a data sharing agreement, MOU, etc.?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='metadata_freq_text',
            field=models.TextField(blank=True, help_text='What justification can be provided for the above selection?', null=True, verbose_name='Justification for frequency:'),
        ),
        migrations.AddField(
            model_name='resource',
            name='metadata_update_freq',
            field=models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Annually'), (5, 'Irregular / as needed'), (9, 'Other')], help_text='What should be the expectation for how often the metadata is updated?', null=True, verbose_name='At what frequency should the metadata be updated? '),
        ),
        migrations.AddField(
            model_name='resource',
            name='publication_timeframe',
            field=models.TextField(blank=True, help_text='The answer provided will set the expectation for the open data publication frequency', null=True, verbose_name='How soon after data collection will data be made available?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='publishing_platforms',
            field=models.TextField(blank=True, help_text="The best option is the Government of Canada's Open Data Platform however other platforms / publications are acceptable provided they are freely available to the general public.", null=True, verbose_name='Which open data publishing mechanism(s) will be used?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='raw_data_retention',
            field=models.TextField(blank=True, help_text='This would include instrument data, field sheets, physical samples etc. Please refer to the DFO EOS Retention Policy for clarification)', null=True, verbose_name='What is the retention policy for the raw field data?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_status',
            field=models.IntegerField(choices=[(0, 'Unevaluated'), (1, 'On-track'), (2, 'Complete'), (3, 'Encountering issues'), (4, 'Aborted / cancelled'), (5, 'Pending new evaluation')], default=3, editable=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='sharing_agreements_text',
            field=models.TextField(blank=True, help_text='please provide the name of the organization and the primary contact for each agreement.', null=True, verbose_name='If yes, who are the counterparts for the agreement(s)?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='storage_needed',
            field=models.TextField(blank=True, help_text='This includes raw field data, processed data, and all other data products etc.)', null=True, verbose_name='What is the estimated storage space needed for the above?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='storage_solution_text',
            field=models.TextField(blank=True, help_text='Provide your rational for the selection(s) made above.', null=True, verbose_name='Justification for selection of storage solution(s)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='storage_solutions',
            field=models.ManyToManyField(blank=True, to='inventory.StorageSolution', verbose_name='Which storage solution(s) will be used to house the raw field data, processed data, and all other data products?'),
        ),
    ]
