# Generated by Django 3.2.16 on 2023-01-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0035_auto_20221207_1558'),
        ('inventory', '0014_auto_20230125_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceperson',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='resourceperson',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.personrole', verbose_name='role'),
        ),
        migrations.CreateModel(
            name='ResourcePerson2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_people2', to='shared_models.person')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_people2', to='inventory.resource')),
                ('roles', models.ManyToManyField(blank=True, to='inventory.PersonRole', verbose_name='role')),
            ],
            options={
                'ordering': ['person'],
                'unique_together': {('resource', 'person')},
            },
        ),
    ]
