# Generated by Django 3.1.2 on 2020-11-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200824_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecertification',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_history', to='inventory.resource'),
        ),
    ]
