# Generated by Django 3.2.16 on 2023-01-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20230126_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='analytic_software',
            field=models.TextField(blank=True, null=True, verbose_name='Is any special software required?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='completedness_rating',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='completedness rating'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='completedness_report',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='completedness report'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='data_char_set',
            field=models.IntegerField(blank=True, choices=[(1, 'utf8'), (2, 'usAscii')], help_text='What is the encoding type of the distribution format? If you are using excel, please select ASCII.', null=True, verbose_name='Data character set'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_verified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='flagged_4_deletion',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='flagged_4_publication',
            field=models.BooleanField(default=False, editable=False, verbose_name='Flagged for Publication'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Is this record a child of another metadata record?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='inventory.resource', verbose_name='Parent resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='storage_solution_text',
            field=models.TextField(blank=True, help_text='Provide your rational for the selection(s) made above.', null=True, verbose_name='Justification for selection of storage solution(s)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='translation_needed',
            field=models.BooleanField(default=True, editable=False, verbose_name='translation needed'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
