# Generated by Django 3.2.16 on 2023-01-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20230126_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='had_sharing_agreements',
            field=models.IntegerField(blank=True, choices=[(None, 'Unsure'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Is the dataset subject to a data sharing agreement, MOU, etc.?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='has_dma',
            field=models.BooleanField(default=False, editable=False, verbose_name='Does this record have a formalized data management agreement?'),
        ),
    ]
