# Generated by Django 3.1.2 on 2020-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentalreport',
            name='dfo_it_related',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='gulf_ais_confirmed',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='incorrect_region',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='management_related',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='seeking_general_info_ais',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='seeking_general_info_non_ais',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='species_confirmation',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True),
        ),
    ]
