# Generated by Django 2.0.7 on 2018-11-02 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(default=datetime.datetime(2018, 11, 2, 15, 0, 28, 640821, tzinfo=utc))),
                ('name_of_reporter', models.CharField(max_length=150)),
                ('language', models.IntegerField(choices=[(1, 'English'), (2, 'French')])),
                ('report_type', models.IntegerField(choices=[(1, 'Hotline'), (2, 'Email')])),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_first_occurence', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('call_answered_by', models.CharField(blank=True, max_length=150, null=True)),
                ('call_returned_by', models.CharField(blank=True, max_length=150, null=True)),
                ('location_description', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude_n', models.FloatField(blank=True, null=True)),
                ('longitude_w', models.FloatField(blank=True, null=True)),
                ('sighting_description', models.TextField(blank=True, null=True)),
                ('indentified_by', models.CharField(blank=True, max_length=150, null=True)),
                ('specimens_retained', models.BooleanField(default=False)),
                ('obvservation_type', models.IntegerField(choices=[(1, 'Single observation'), (2, 'Ongoing presence')])),
                ('other_observations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
