# Generated by Django 3.2 on 2021-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0002_alter_incidentalreport_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='is_damaged',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Was the surface damaged?'),
        ),
        migrations.AlterField(
            model_name='gcprobemeasurement',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('l', 'High'), ('m', 'Mid'), ('h', 'Low')], max_length=5, null=True),
        ),
    ]
