# Generated by Django 2.0.7 on 2018-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0005_auto_20181102_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentalreport',
            old_name='name_of_reporter',
            new_name='reporter_name',
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='report_type',
            field=models.IntegerField(choices=[(1, 'Telephone hotline'), (2, 'E-mail')]),
        ),
    ]
