# Generated by Django 2.2.2 on 2020-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0006_probemeasurement_cloud_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='surface_type',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('full', 'full')], default='full', max_length=10),
        ),
    ]
