# Generated by Django 2.2.2 on 2020-02-25 17:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grais', '0008_auto_20200221_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('full', 'full')], default='full', max_length=10, verbose_name='sample type'),
        ),
        migrations.AlterField(
            model_name='species',
            name='green_crab_monitoring',
            field=models.BooleanField(default=False, verbose_name='targeted species in Green Crab Monitoring Program?'),
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (9, 'Unknown')], null=True)),
                ('carapace_color', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('abdomen_color', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('egg_color', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grais.Species')),
                ('trap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='catch_spp', to='grais.Trap')),
            ],
            options={
                'ordering': ['trap', 'species', 'id'],
            },
        ),
    ]
