# Generated by Django 2.0.4 on 2018-11-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0010_auto_20181116_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_by',
            new_name='author',
        ),
    ]
