# Generated by Django 2.0.4 on 2018-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0013_samplenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='collector',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.DeleteModel(
            name='Collector',
        ),
    ]
