# Generated by Django 2.0.4 on 2018-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0016_auto_20181119_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampler',
            name='notes',
        ),
        migrations.AddField(
            model_name='sampler',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sampler',
            name='organization',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sampler',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
