# Generated by Django 2.1.4 on 2019-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0018_gcprobemeasurement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcsample',
            name='temp_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
