# Generated by Django 3.1.6 on 2021-04-07 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grais', '0018_auto_20210407_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='linespecies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linespecies',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linespecies_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linespecies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='linespecies',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linespecies_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='line',
            name='sample',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='grais.sample'),
        ),
        migrations.AlterField(
            model_name='samplespecies',
            name='observation_date',
            field=models.DateTimeField(verbose_name='observation date'),
        ),
    ]
