# Generated by Django 2.0.4 on 2018-11-21 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0020_remove_probemeasurement_last_modified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentalreport',
            old_name='reporter_name',
            new_name='requestor_name',
        ),
        migrations.RenameField(
            model_name='incidentalreport',
            old_name='report_type',
            new_name='report_source',
        ),
        migrations.AddField(
            model_name='incidentalreport',
            name='requestor_type',
            field=models.IntegerField(blank=True, choices=[(1, 'public'), (2, 'academia'), (3, 'private sector'), (4, 'provincial government'), (5, 'federal government')], null=True),
        ),
        migrations.AddField(
            model_name='incidentalreport',
            name='specimens_confirmation',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
