# Generated by Django 3.2 on 2021-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0020_auto_20210408_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentalreport',
            name='date_last_modified',
        ),
        migrations.RemoveField(
            model_name='incidentalreport',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='dfo_it_related',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='DFO IT related?'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='gulf_ais_confirmed',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Confirmed by Gulf AIS team?'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='identified_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name of identifier'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='incorrect_region',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Incorrect region?'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='location_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description of location'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='management_related',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Management related?'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='observation_type',
            field=models.IntegerField(choices=[(1, 'Single observation'), (2, 'Ongoing presence')], verbose_name='type of observation'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='requestor_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Public'), (2, 'Academia'), (3, 'Private sector'), (4, 'Provincial government'), (5, 'Federal government')], null=True),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='season',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='seeking_general_info_ais',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Seeking general information about AIS?'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='seeking_general_info_non_ais',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Seeking general information about non-AIS?'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='sighting_description',
            field=models.TextField(blank=True, null=True, verbose_name='description of sighting'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='species_confirmation',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Was there a species confirmation?'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='specimens_retained',
            field=models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='were specimens retained?'),
        ),
    ]
