# Generated by Django 2.1.4 on 2019-04-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0020_auto_20190402_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crab',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='gcprobemeasurement',
            name='timezone',
            field=models.CharField(blank=True, choices=[('AST', 'AST'), ('ADT', 'ADT'), ('UTC', 'UTC')], default='ADT', max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bycatch',
            unique_together={('trap', 'species')},
        ),
    ]
