# Generated by Django 3.2 on 2021-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0023_auto_20210409_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentalreportspecies',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
