# Generated by Django 3.2 on 2021-04-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grais', '0024_alter_incidentalreportspecies_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentalreportspecies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentalreportspecies',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidentalreportspecies_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentalreportspecies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidentalreportspecies',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidentalreportspecies_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
