# Generated by Django 3.2 on 2021-04-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0025_auto_20210409_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentalreport',
            name='species',
        ),
    ]
