# Generated by Django 2.1.4 on 2019-05-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0027_auto_20190510_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='is_lost',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Was the surface lost?'),
        ),
    ]
