# Generated by Django 3.2 on 2021-04-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0029_auto_20210412_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherconditions',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='gcprobemeasurement',
            name='sample',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='probe_data', to='grais.gcsample'),
        ),
        migrations.AlterField(
            model_name='gcprobemeasurement',
            name='weather_conditions',
            field=models.ManyToManyField(blank=True, to='grais.WeatherConditions', verbose_name='weather conditions (ctrl+click to select multiple)'),
        ),
    ]
