# Generated by Django 2.2.2 on 2019-06-20 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0031_remove_species_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcsample',
            name='bottom_type',
        ),
        migrations.RemoveField(
            model_name='gcsample',
            name='percent_vegetation_cover',
        ),
        migrations.AddField(
            model_name='gcsample',
            name='eelgrass_assessed',
            field=models.NullBooleanField(verbose_name='was eelgrass assessed?'),
        ),
        migrations.AddField(
            model_name='gcsample',
            name='eelgrass_percent_coverage',
            field=models.NullBooleanField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='eelgrass coverage (%)'),
        ),
        migrations.AddField(
            model_name='gcsample',
            name='sediment',
            field=models.IntegerField(blank=True, choices=[(1, 'Sand'), (2, 'Mud'), (3, 'Sand/Mud')], null=True),
        ),
        migrations.AddField(
            model_name='gcsample',
            name='vegetation_species',
            field=models.ManyToManyField(blank=True, to='grais.Species'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='o2_mgl',
            field=models.FloatField(blank=True, null=True, verbose_name='Dissolved oxygen (mg/l)'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='o2_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Dissolved oxygen (%)'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='probe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grais.Probe', verbose_name='Probe name'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='probe_depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Probe depth (m)'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='sal_ppt',
            field=models.FloatField(blank=True, null=True, verbose_name='Salinity (ppt)'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='sp_cond_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Specific conductance (mS)'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='spc_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Conductivity (mS)'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='temp_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp (°C)'),
        ),
        migrations.AlterField(
            model_name='probemeasurement',
            name='time_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date / Time (yyyy-mm-dd hh:mm)'),
        ),
    ]
