# Generated by Django 2.1.4 on 2019-02-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grais', '0035_incidentalreport_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentalreport',
            name='phone1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='incidentalreport',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone 2'),
        ),
    ]
