# Generated by Django 3.2.4 on 2021-09-23 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0015_auto_20210601_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of committee/Working Group')),
                ('is_dfo_chair', models.IntegerField(blank=True, choices=[(None, '---------'), (1, 'Yes'), (0, 'No')], null=True, verbose_name='Does DFO chair/co-chair')),
                ('first_nation_participation', models.BooleanField(default=False, verbose_name='First Nations/Indigenous group participation?')),
                ('provincial_participation', models.BooleanField(default=False, verbose_name='Provincial government participation?')),
                ('meeting_frequency', models.IntegerField(choices=[(0, 'Monthly'), (1, 'Once a year'), (2, '1-2 times per year'), (3, 'Twice a year'), (4, '2-3 times per year'), (5, 'Three times a year'), (6, 'Four times a year'), (7, 'As needed'), (8, 'Every other year'), (9, 'Other')], default=1, verbose_name='Meeting frequency')),
                ('are_tor', models.BooleanField(default=False, verbose_name='Are there terms of reference?')),
                ('location_of_tor', models.TextField(blank=True, null=True, verbose_name='Location of terms of reference')),
                ('main_actions', models.TextField(default='-----', verbose_name='Main actions')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified')),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committee_branch', to='shared_models.branch', verbose_name='Lead DFO Branch')),
                ('dfo_liaison', models.ManyToManyField(related_name='committee_dfo_liaison', to=settings.AUTH_USER_MODEL, verbose_name='DFO liaison/secretariat')),
                ('division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.division', verbose_name='Division')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('other_dfo_branch', models.ManyToManyField(related_name='committee_dfo_branch', to='shared_models.Branch', verbose_name='Other participating DFO branches/regions/area offices')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.IntegerField(choices=[(1, 'Minister meeting'), (2, 'Deputy Minister meeting'), (3, 'Maritimes Region ad hoc meeting'), (4, 'Committee / Working Group meeting'), (5, 'Committee / Working Group correspondence'), (6, 'Ministerial correspondence'), (7, 'Deputy Minister correspondence'), (8, 'Maritimes Region correspondence ')], default=None)),
                ('dfo_role', models.IntegerField(choices=[(1, 'Programs'), (2, 'Manager'), (3, 'Director'), (4, 'Regional Director'), (5, 'Associate Regional Director General'), (6, 'Regional Director General'), (7, 'Director General'), (8, 'Assistant Deputy Minister'), (9, 'Senior Assistant Deputy Minister'), (10, 'Deputy Minister'), (11, 'Minister')], default=None)),
                ('date_of_meeting', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Meeting')),
                ('action_items', models.TextField(default='-----', verbose_name='Main actions')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified')),
                ('committee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='maret.committee', verbose_name='Committee / Working Group')),
                ('dfo_liaison', models.ManyToManyField(related_name='interaction_dfo_liaison', to=settings.AUTH_USER_MODEL, verbose_name='DFO liaison/secretariat')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('main_topic', models.ManyToManyField(related_name='main_topics', to='maret.DiscussionTopic', verbose_name='Main Topic(s) of discussion')),
                ('other_dfo_participants', models.ManyToManyField(related_name='interaction_dfo_participants', to=settings.AUTH_USER_MODEL, verbose_name='Other DFO participants/contributors')),
                ('species', models.ManyToManyField(related_name='species', to='maret.Species', verbose_name='Main species of discussion')),
            ],
        ),
    ]
