# Generated by Django 3.2.4 on 2021-10-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0011_alter_sector_unique_together'),
        ('maret', '0005_auto_20211029_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='N/A', max_length=255, verbose_name='Role')),
                ('contact', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ext_con', to='masterlist.person', verbose_name='Contact')),
            ],
        ),
    ]
