# Generated by Django 3.2.5 on 2021-11-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maret', '0006_auto_20211102_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.IntegerField(choices=[(1, 'Minister meeting'), (2, 'Deputy Minister meeting'), (3, 'Maritimes Region ad hoc meeting'), (4, 'Committee / Working Group meeting'), (6, 'Ministerial correspondence'), (7, 'Deputy Minister correspondence'), (8, 'Maritimes Region correspondence ')], default=None),
        ),
    ]
