# Generated by Django 3.2.5 on 2022-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maret', '0010_contactextension_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationextension',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
