# Generated by Django 3.2.5 on 2022-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0030_remove_river_fishing_area_code'),
        ('maret', '0011_organizationextension_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='other_dfo_areas',
            field=models.ManyToManyField(related_name='committee_dfo_area', to='maret.AreaOffice', verbose_name='Other participating DFO area offices'),
        ),
        migrations.AddField(
            model_name='committee',
            name='other_dfo_regions',
            field=models.ManyToManyField(related_name='committee_dfo_region', to='shared_models.Region', verbose_name='Other participating DFO regions'),
        ),
    ]
