# Generated by Django 3.2.10 on 2022-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0030_remove_river_fishing_area_code'),
        ('maret', '0012_auto_20220210_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='other_dfo_branch',
            field=models.ManyToManyField(related_name='committee_dfo_branch', to='shared_models.Branch', verbose_name='Other participating DFO branches'),
        ),
    ]
