# Generated by Django 3.2.13 on 2022-05-03 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maret', '0018_auto_20220502_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date_of_meeting',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Interaction'),
        ),
    ]
