# Generated by Django 3.2.12 on 2022-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maret', '0018_areaofficeprogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofficeprogram',
            options={},
        ),
        migrations.AlterField(
            model_name='areaofficeprogram',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name (en)'),
        ),
        migrations.AlterUniqueTogether(
            name='areaofficeprogram',
            unique_together={('name', 'area_office')},
        ),
    ]
