# Generated by Django 3.2.12 on 2022-06-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0031_subjectmatter_is_csas_request_tag'),
        ('maret', '0019_auto_20220510_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='area_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_area_office', to='maret.areaoffice', verbose_name='Lead Area Office'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='area_office_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_area_office_program', to='maret.areaofficeprogram', verbose_name='Lead Area Office Program'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_branch', to='shared_models.branch', verbose_name='Lead DFO branch'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.division', verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='other_dfo_areas',
            field=models.ManyToManyField(blank=True, related_name='interaction_dfo_area', to='maret.AreaOffice', verbose_name='Other participating DFO area offices'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='other_dfo_branch',
            field=models.ManyToManyField(blank=True, related_name='interaction_dfo_branch', to='shared_models.Branch', verbose_name='Other participating DFO branches'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='other_dfo_regions',
            field=models.ManyToManyField(blank=True, related_name='interaction_dfo_region', to='shared_models.Region', verbose_name='Other participating DFO regions'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date last modified'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date last modified'),
        ),
    ]
