# Generated by Django 3.2.12 on 2022-06-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0031_subjectmatter_is_csas_request_tag'),
        ('maret', '0021_committee_other_federal_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_branch', to='shared_models.branch', verbose_name='Lead DFO branch'),
        ),
    ]
