# Generated by Django 3.2.12 on 2022-06-21 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0012_alter_person_designation'),
        ('shared_models', '0031_subjectmatter_is_csas_request_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maret', '0023_auto_20220621_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='dfo_national_sectors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'region__name': 'National'}, related_name='committee_sector', to='shared_models.Sector', verbose_name='Participating National Headquarters sectors'),
        ),
        migrations.AddField(
            model_name='committee',
            name='lead_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committee_lead_dfo_region', to='shared_models.region', verbose_name='Lead DFO region'),
        ),
        migrations.AddField(
            model_name='committee',
            name='other_dfo_participants',
            field=models.ManyToManyField(blank=True, related_name='committee_dfo_participants', to=settings.AUTH_USER_MODEL, verbose_name='Other DFO Maritimes region participants/contributors'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='dfo_national_sectors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'region__name': 'National'}, related_name='interaction_sector', to='shared_models.Sector', verbose_name='Participating National Headquarters sectors'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='lead_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_lead_dfo_region', to='shared_models.region', verbose_name='Lead DFO region'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='area_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committee_area_office', to='maret.areaoffice', verbose_name='Lead Maritimes Region area office'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='area_office_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committee_area_office_program', to='maret.areaofficeprogram', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'region__name': 'Maritimes'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committee_branch', to='shared_models.branch', verbose_name='Lead DFO Maritimes Region branch'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='dfo_liaison',
            field=models.ManyToManyField(blank=True, related_name='committee_dfo_liaison', to=settings.AUTH_USER_MODEL, verbose_name='DFO Maritimes Region liaison'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='external_contact',
            field=models.ManyToManyField(blank=True, related_name='committee_ext_contact', to='masterlist.Person', verbose_name='Other external contact(s)'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='municipal_participation',
            field=models.BooleanField(default=False, verbose_name='Local/municipal government participation?'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='other_dfo_areas',
            field=models.ManyToManyField(blank=True, related_name='committee_dfo_area', to='maret.AreaOffice', verbose_name='Other participating DFO Maritimes Region area offices'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='other_dfo_branch',
            field=models.ManyToManyField(blank=True, limit_choices_to={'region__name': 'Maritimes'}, related_name='committee_dfo_branch', to='shared_models.Branch', verbose_name='Other participating DFO Maritimes Region branches'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='other_dfo_regions',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('name__in', ['Maritimes']), _negated=True), related_name='committee_dfo_region', to='shared_models.Region', verbose_name='Other participating DFO regions'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='provincial_participation',
            field=models.BooleanField(default=False, verbose_name='Provincial government participation?'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='area_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_area_office', to='maret.areaoffice', verbose_name='Lead DFO Maritimes Region area office'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='area_office_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_area_office_program', to='maret.areaofficeprogram', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'region__name': 'Maritimes'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_branch', to='shared_models.branch', verbose_name='Lead DFO Maritimes branch'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dfo_liaison',
            field=models.ManyToManyField(blank=True, related_name='interaction_dfo_liaison', to=settings.AUTH_USER_MODEL, verbose_name='DFO Maritimes Region liaison'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='external_contact',
            field=models.ManyToManyField(blank=True, related_name='interaction_ext_contact', to='masterlist.Person', verbose_name='Other external contact(s)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='other_dfo_areas',
            field=models.ManyToManyField(blank=True, related_name='interaction_dfo_area', to='maret.AreaOffice', verbose_name='Other participating DFO Maritimes Region area offices'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='other_dfo_branch',
            field=models.ManyToManyField(blank=True, limit_choices_to={'region__name': 'Maritimes'}, related_name='interaction_dfo_branch', to='shared_models.Branch', verbose_name='Other participating DFO Maritimes Region branches'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='other_dfo_participants',
            field=models.ManyToManyField(blank=True, related_name='interaction_dfo_participants', to=settings.AUTH_USER_MODEL, verbose_name='Other DFO Maritimes region participants/contributors'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='other_dfo_regions',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('name__in', ['Maritimes']), _negated=True), related_name='interaction_dfo_region', to='shared_models.Region', verbose_name='Other participating DFO regions'),
        ),
    ]
