# Generated by Django 3.2.12 on 2022-07-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maret', '0025_auto_20220628_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactextension',
            name='role',
        ),
    ]
