# Generated by Django 2.0.4 on 2018-10-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_uid', models.CharField(max_length=10)),
                ('station', models.IntegerField(blank=True, null=True)),
                ('set', models.IntegerField(blank=True, null=True)),
                ('event', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(choices=[('AST', 'Atlantic Standard Time'), ('ADT', 'Atlantic Daylight Time'), ('UTC', 'Coordinated Universal Time')], max_length=3)),
                ('date_time_UTC', models.DateTimeField(blank=True, null=True)),
                ('sounding_m', models.FloatField(blank=True, null=True)),
                ('bottle_depth_m', models.FloatField(blank=True, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('sal_ppt', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('lat_DDdd', models.FloatField(blank=True, null=True)),
                ('long_DDdd', models.CharField(max_length=255)),
                ('ctd_filename', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=255)),
                ('mission_number', models.CharField(max_length=255)),
                ('vessel_name', models.CharField(max_length=255)),
                ('chief_scientist', models.CharField(max_length=255)),
                ('samplers', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('area_of_operation', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='probe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oceanography.Probe'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='oceanography.Mission'),
        ),
    ]
