# Generated by Django 2.0.4 on 2018-10-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0003_auto_20181003_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='ctd_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='long_DDdd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='remarks',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
