# Generated by Django 2.0.4 on 2018-10-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0004_auto_20181003_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
