# Generated by Django 2.0.4 on 2018-10-04 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oceanography.models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0005_mission_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=oceanography.models.file_directory_path)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='oceanography.Mission')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterField(
            model_name='bottle',
            name='bottle_depth_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Bottle depth (m)'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='date_time_UTC',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date / time (UTC)'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='event',
            field=models.IntegerField(blank=True, null=True, verbose_name='Event #'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='lat_DDdd',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='long_DDdd',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='sal_ppt',
            field=models.FloatField(blank=True, null=True, verbose_name='Salinity (ppt)'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='set',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set #'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='sounding_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Sounding (m)'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='station',
            field=models.IntegerField(blank=True, null=True, verbose_name='Station #'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='temp_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
    ]
