# Generated by Django 2.0.4 on 2018-11-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0009_auto_20181108_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='meds_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
