# Generated by Django 2.0.4 on 2018-11-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0010_mission_meds_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='meds_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MEDS ID'),
        ),
    ]
