# Generated by Django 2.0.4 on 2018-11-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0011_auto_20181114_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='station',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Station'),
        ),
    ]
