# Generated by Django 2.0.4 on 2018-12-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0020_auto_20181206_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='ship_call_sign',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='vessel_name',
        ),
    ]
