# Generated by Django 3.2.13 on 2022-06-03 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0008_auto_20220603_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='additional comments'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='destination',
            field=models.CharField(max_length=255, null=True, verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='primary_driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_reservations', to=settings.AUTH_USER_MODEL, verbose_name='primary driver'),
        ),
    ]
