# Generated by Django 3.2.13 on 2022-06-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20220613_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['question_en', 'id']},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
    ]
