# Generated by Django 3.2.13 on 2022-06-14 18:52

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20220613_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('url_en', models.URLField(blank=True, null=True, verbose_name='url (English)')),
                ('url_fr', models.URLField(blank=True, null=True, verbose_name='url (French)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to=cars.models.ref_mat_directory_path, verbose_name='file attachment (English)')),
                ('file_fr', models.FileField(blank=True, null=True, upload_to=cars.models.ref_mat_directory_path, verbose_name='file attachment (French)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
