# Generated by Django 3.2.13 on 2022-06-22 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0014_referencematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='custodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='custodian'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='cars.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='cars.vehicletype', verbose_name='vehicle type'),
        ),
    ]
