# Generated by Django 3.2.14 on 2022-11-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0034_auto_20221017_1301'),
        ('cars', '0016_alter_reservation_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='shared_models.section', verbose_name='DFO section'),
        ),
    ]
