# Generated by Django 3.1.2 on 2020-10-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0015_auto_20201028_1048'),
        ('missions', '0006_auto_20201028_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruiseinstruments',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_instruments', to='missions.instrument'),
        ),
        migrations.AlterField(
            model_name='cruiseinstruments',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_instruments', to='shared_models.cruise'),
        ),
    ]
