# Generated by Django 3.1.2 on 2020-10-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0015_auto_20201028_1048'),
        ('missions', '0007_auto_20201028_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CruiseInstruments',
            new_name='MissionInstruments',
        ),
    ]
