# Generated by Django 2.2.2 on 2020-02-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20200129_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=250, verbose_name='')),
                ('item_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('owner', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('size', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('container_space', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('type', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_supplier', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('supplier', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('contact_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('last_invoice', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('last_purchased', models.DateTimeField(blank=True, null=True)),
                ('last_purchased_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('serial_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('quantity_oh', models.IntegerField(blank=True, null=True)),
                ('quantity_oo', models.IntegerField(blank=True, null=True)),
                ('last_audited', models.DateTimeField(blank=True, null=True)),
                ('last_audited_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('location_stored', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('bin_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('items_quantity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='vault.Items', verbose_name='items')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('lent_to', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('lent_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='vault.Quantity', verbose_name='items')),
            ],
        ),
    ]
