# Generated by Django 2.2.2 on 2020-01-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20200121_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mediadatapath',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media_data_paths', to='vault.ObservationPlatform'),
            preserve_default=False,
        ),
    ]
