# Generated by Django 2.2.2 on 2020-01-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_species_aphia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
