# Generated by Django 3.1.2 on 2020-11-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_auto_20201123_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certainty',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='certainty',
            name='english_certainty_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='certainty',
            name='french_certainty_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='field_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='fieldname',
            name='used_for',
            field=models.ManyToManyField(blank=True, to='vault.Instrument', verbose_name='used for'),
        ),
        migrations.AlterField(
            model_name='instrumentmetadatum',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrument_metadata', to='vault.instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='mediafilesighting',
            name='original_mediafile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mediafile_sightings', to='vault.originalmediafile', verbose_name='original media file'),
        ),
        migrations.AlterField(
            model_name='mediafilesighting',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='observationsighting',
            name='known_individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='individual', to='vault.individualidentification', verbose_name='known individual'),
        ),
        migrations.AlterField(
            model_name='observationsighting',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='observation_sightings', to='vault.observation', verbose_name='observation'),
        ),
        migrations.AlterField(
            model_name='observationsighting',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='originalmediafile',
            name='filename',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='originalmediafile',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_mediafiles', to='vault.observation', verbose_name='observation'),
        ),
        migrations.AlterField(
            model_name='originalmediafilemetadatum',
            name='original_mediafile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_mediafile_metadata', to='vault.originalmediafile', verbose_name='original media file'),
        ),
        migrations.AlterField(
            model_name='processedmediafile',
            name='filename',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='processedmediafile',
            name='species',
            field=models.ManyToManyField(blank=True, to='vault.Species', verbose_name='species'),
        ),
        migrations.AlterField(
            model_name='processedmediafile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
