# Generated by Django 2.2.2 on 2020-01-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_auto_20200122_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('field_value', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='FieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('used_for', models.ManyToManyField(blank=True, to='vault.Instrument', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='originalmediafile',
            name='metadata',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_mediafiles', to='vault.Metadata', verbose_name=''),
            preserve_default=False,
        ),
    ]
