# Generated by Django 2.2.2 on 2020-01-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_auto_20200127_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilesighting',
            name='health_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mediafile_sightings', to='vault.HealthStatus'),
        ),
        migrations.AddField(
            model_name='observationsighting',
            name='health_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='observation_sightings', to='vault.HealthStatus'),
        ),
    ]
