# Generated by Django 2.2.2 on 2020-01-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_auto_20200127_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='beaufort',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='cloud_percent',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='glare_left',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='glare_right',
        ),
        migrations.AddField(
            model_name='observation',
            name='metadata',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sightings', to='vault.Metadata', verbose_name=''),
            preserve_default=False,
        ),
    ]
