# Generated by Django 2.2.2 on 2020-02-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_auto_20200218_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationplatform',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_authorities', to='vault.Organisation', verbose_name=''),
        ),
        migrations.AddField(
            model_name='observationplatform',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_owners', to='vault.Organisation', verbose_name=''),
        ),
        migrations.AddField(
            model_name='person',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='vault.Organisation', verbose_name=''),
        ),
    ]
