# Generated by Django 2.2.2 on 2020-02-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_auto_20200218_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationplatform',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_authorities', to='vault.Organisation', verbose_name='authority'),
        ),
        migrations.AlterField(
            model_name='observationplatform',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_owners', to='vault.Organisation', verbose_name='owner'),
        ),
    ]
