# Generated by Django 3.1.2 on 2021-02-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0021_change_fields_to_choices_obsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
