# Generated by Django 4.1.6 on 2023-02-22 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllotmentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("color", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AllotmentCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "allotment_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="allotment_codes",
                        to="shared_models.allotmentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name (en)")),
                (
                    "abbrev",
                    models.CharField(max_length=10, verbose_name="abbreviation"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                (
                    "date_last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date last modified"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_admin_branches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="admin",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_branches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="regional director / NCR director general",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch - Directorate (NCR)",
                "verbose_name_plural": "Branches - Directorates (NCR)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name (en)")),
                (
                    "abbrev",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="abbreviation",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                (
                    "date_last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date last modified"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_admin_divisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="admin",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="divisions",
                        to="shared_models.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_divisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="division manager / NCR director",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division - Branch (NCR)",
                "verbose_name_plural": "Divisions - Branches (NCR)",
                "ordering": ["branch__region", "name"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full", models.TextField(blank=True, null=True)),
                ("short", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FishingArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("nom", models.CharField(max_length=25)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LineObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name_eng", models.CharField(max_length=1000)),
                ("description_eng", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_en", models.CharField(max_length=1000)),
                (
                    "location_fr",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Canada", "Canada"),
                            ("United States", "United States"),
                        ],
                        max_length=25,
                    ),
                ),
                ("abbrev_en", models.CharField(blank=True, max_length=25, null=True)),
                ("abbrev_fr", models.CharField(blank=True, max_length=25, null=True)),
                ("uuid_gcmd", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["country", "location_en"],
            },
        ),
        migrations.CreateModel(
            name="PAAItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=255, unique=True, verbose_name="code"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (en)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Probe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nom", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="name (en)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="name (en)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                (
                    "abbrev",
                    models.CharField(max_length=10, verbose_name="abbreviation"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                (
                    "date_last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date last modified"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_admin_regions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="admin",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_regions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="RDG / ADM",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region - National (NCR)",
                "verbose_name_plural": "Regions - National (NCR)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubjectMatter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="name (en)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                (
                    "is_csas_request_tag",
                    models.BooleanField(
                        default=False, verbose_name="used for CSAS request tagging?"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "call_sign",
                    models.CharField(blank=True, max_length=56, null=True, unique=True),
                ),
                (
                    "ices_shipc_ship_codes",
                    models.CharField(blank=True, max_length=56, null=True),
                ),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=56, null=True),
                ),
                (
                    "platform_type",
                    models.CharField(blank=True, max_length=56, null=True),
                ),
                (
                    "platform_owner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("imo_number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name (en)")),
                (
                    "abbrev_en",
                    models.CharField(
                        max_length=10, verbose_name="abbreviation (English)"
                    ),
                ),
                (
                    "abbrev_fr",
                    models.CharField(
                        max_length=10, verbose_name="abbreviation (French)"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                (
                    "date_last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date last modified"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_admin_sectors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="admin",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_sectors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Director General / Associate Deputy Minister",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sectors",
                        to="shared_models.region",
                        verbose_name="region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name (en)")),
                (
                    "abbrev",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="abbreviation",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                (
                    "date_last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date last modified"
                    ),
                ),
                (
                    "shortish_name",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "full_name_en",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "full_name_en_ver1",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "full_name_fr",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "full_name_fr_ver1",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_admin_sections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="admin",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sections",
                        to="shared_models.division",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_models_sections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="section head  / NCR team lead",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section - Team (NCR)",
                "verbose_name_plural": "Sections - Teams (NCR)",
                "ordering": [
                    "division__branch__region",
                    "division__branch",
                    "division",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="name (en)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (en)"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (fr)"
                    ),
                ),
                ("script", models.CharField(max_length=1000, verbose_name="script")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="last_mod_by_ocean_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="River",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("maritime_river_code", models.IntegerField(blank=True, null=True)),
                ("old_maritime_river_code", models.IntegerField(blank=True, null=True)),
                (
                    "cgndb",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="GCNDB key",
                    ),
                ),
                (
                    "parent_cgndb_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Parent GCNDB key",
                    ),
                ),
                (
                    "nbadw_water_body_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="NDADW water body ID"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fishing_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rivers",
                        to="shared_models.fishingarea",
                    ),
                ),
                (
                    "parent_river",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="children_rivers",
                        to="shared_models.river",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResponsibilityCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="name (en)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                (
                    "abbrev_eng",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="abbreviation (English)",
                    ),
                ),
                (
                    "abbrev_fre",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="abbreviation (French)",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Canada", "Canada"),
                            ("United States", "United States"),
                        ],
                        max_length=25,
                        verbose_name="country",
                    ),
                ),
                (
                    "date_last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date last modified"
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last modified by",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "project_lead",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "default_allotment_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.allotmentcode",
                    ),
                ),
                (
                    "default_business_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.businessline",
                    ),
                ),
                (
                    "default_line_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.lineobject",
                    ),
                ),
                (
                    "default_responsibility_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="projects",
                        to="shared_models.responsibilitycenter",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province_code",
                    models.CharField(
                        choices=[
                            ("1", "NS"),
                            ("2", "NB"),
                            ("3", "PE"),
                            ("4", "QC"),
                            ("5", "NL"),
                        ],
                        max_length=1,
                    ),
                ),
                ("district_code", models.CharField(max_length=2)),
                ("port_code", models.CharField(max_length=2)),
                ("port_name", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "herring_fishing_area_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nafo_unit_area_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("alias_wharf_id", models.IntegerField(blank=True, null=True)),
                (
                    "alias_wharf_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": [
                    "port_name",
                    "province_code",
                    "district_code",
                    "port_code",
                ],
                "unique_together": {("province_code", "district_code", "port_code")},
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="last name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        max_length=255, null=True, verbose_name="affiliation"
                    ),
                ),
                (
                    "job_title_en",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="job title (en)",
                    ),
                ),
                (
                    "job_title_fr",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="job title (fr)",
                    ),
                ),
                ("old_id", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dmapps_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="linkage to DM Apps User",
                    ),
                ),
                (
                    "expertise",
                    models.ManyToManyField(
                        blank=True,
                        to="shared_models.subjectmatter",
                        verbose_name="expertise",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="people",
                        to="shared_models.language",
                        verbose_name="language preference",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="unique identifier",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name (en)")),
                (
                    "abbrev",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="abbreviation",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="address"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="city"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="postal code"
                    ),
                ),
                (
                    "is_dfo",
                    models.BooleanField(
                        default=True, verbose_name="Is this a DFO location?"
                    ),
                ),
                (
                    "full_address",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "full_name_and_address_en",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "full_name_and_address_fr",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, null=True
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="name (en)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name (fr)"
                    ),
                ),
                (
                    "abbrev",
                    models.CharField(max_length=255, verbose_name="abbreviation"),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Cruise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission_number",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Mission Number"
                    ),
                ),
                (
                    "mission_name",
                    models.CharField(max_length=255, verbose_name="Mission Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, null=True, verbose_name="Purpose"),
                ),
                (
                    "chief_scientist",
                    models.CharField(max_length=255, verbose_name="Chief Scientist"),
                ),
                (
                    "samplers",
                    models.TextField(blank=True, null=True, verbose_name="Samplers"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "area_of_operation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Area of Operation",
                    ),
                ),
                (
                    "number_of_profiles",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Profiles"
                    ),
                ),
                (
                    "meds_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="MEDS ID"
                    ),
                ),
                ("season", models.IntegerField(blank=True, null=True)),
                (
                    "west_bound_longitude",
                    models.FloatField(
                        blank=True,
                        help_text="Westernmost longitude of the sampling (decimal degrees, negative for Western Hemisphere longitude)",
                        null=True,
                        verbose_name="West Bound Longitude",
                    ),
                ),
                (
                    "east_bound_longitude",
                    models.FloatField(
                        blank=True,
                        help_text="Easternmost longitude of the sampling (decimal degrees, negative for Western Hemisphere longitude)",
                        null=True,
                        verbose_name="East Bound Longitude",
                    ),
                ),
                (
                    "north_bound_latitude",
                    models.FloatField(
                        blank=True,
                        help_text="Northernmost latitude of the sampling (decimal degrees, negative for Southern Hemisphere latitude)",
                        null=True,
                        verbose_name="North Bound Latitude",
                    ),
                ),
                (
                    "south_bound_latitude",
                    models.FloatField(
                        blank=True,
                        help_text="Southernmost latitude of the sampling (decimal degrees, negative for Southern Hemisphere latitude)",
                        null=True,
                        verbose_name="South Bound Latitude",
                    ),
                ),
                (
                    "funding_agency_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="funding agency name",
                    ),
                ),
                (
                    "funding_project_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="funding project title",
                    ),
                ),
                (
                    "funding_project_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="funding project ID",
                    ),
                ),
                (
                    "research_projects_programs",
                    models.TextField(
                        blank=True, null=True, verbose_name="research projects programs"
                    ),
                ),
                (
                    "references",
                    models.TextField(blank=True, null=True, verbose_name="references"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="A list of dmapps user who can edit this cruise",
                        related_name="cruise_editors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="editors",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cruises",
                        to="shared_models.institute",
                    ),
                ),
                (
                    "probe",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.probe",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cruises",
                        to="shared_models.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["mission_number"],
            },
        ),
        migrations.CreateModel(
            name="CosigneeCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name_eng", models.CharField(max_length=1000)),
                ("rc_list", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.region",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(blank=True, null=True, verbose_name="title (en)"),
                ),
                (
                    "nom",
                    models.TextField(blank=True, null=True, verbose_name="title (fr)"),
                ),
                (
                    "authors",
                    models.TextField(blank=True, null=True, verbose_name="authors"),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="year"),
                ),
                (
                    "pub_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="publication number",
                    ),
                ),
                (
                    "url_en",
                    models.TextField(blank=True, null=True, verbose_name="URL (en)"),
                ),
                (
                    "url_fr",
                    models.TextField(blank=True, null=True, verbose_name="URL (fr)"),
                ),
                (
                    "abstract_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="abstract (en)"
                    ),
                ),
                (
                    "abstract_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="abstract (fr)"
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="series"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="region"
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared_models.publication",
                        verbose_name="publication name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="branch",
            name="region",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="branches",
                to="shared_models.region",
                verbose_name="region",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="branches",
                to="shared_models.sector",
                verbose_name="sector",
            ),
        ),
    ]
