# Generated by Django 2.1.4 on 2019-03-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_allotmentcategory_allotmentcode_businessline_lineobject_responsibilitycenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_lead', models.CharField(blank=True, max_length=500, null=True)),
                ('default_allotment_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.AllotmentCode')),
                ('default_business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.BusinessLine')),
                ('default_line_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.LineObject')),
                ('default_responsibility_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='shared_models.ResponsibilityCenter')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
