# Generated by Django 2.1.4 on 2019-03-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_auto_20190318_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Region', verbose_name='region'),
            preserve_default=False,
        ),
    ]
