# Generated by Django 2.2.2 on 2020-05-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_paaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paaitem',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='code'),
        ),
    ]
