# Generated by Django 2.1.4 on 2019-03-18 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0005_auto_20190318_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shared_models_sections', to=settings.AUTH_USER_MODEL, verbose_name='section head'),
        ),
    ]
