# Generated by Django 3.1.2 on 2021-02-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_auto_20210217_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='shared_models.division'),
        ),
    ]
