# Generated by Django 2.1.4 on 2019-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='herring_fishing_area_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='nafo_unit_area_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
