# Generated by Django 2.2.2 on 2020-08-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0007_auto_20200617_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='east_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='East Bound Longitude'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='funding_agency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding Agency Name'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='funding_project_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding Project ID'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='funding_project_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding Project Title'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='north_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='North Bound Latitude'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='references',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='References'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='research_Projects_Programs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Research Projects Programs'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='south_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='South Bound Latitude'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='west_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='West Bound Longitude'),
        ),
        migrations.AddField(
            model_name='institute',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Region'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='ices_shipc_ship_codes',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='imo_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='platform_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='platform_type',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='area_of_operation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area of Operation'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='chief_scientist',
            field=models.CharField(max_length=255, verbose_name='Chief Scientist'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='mission_name',
            field=models.CharField(max_length=255, verbose_name='Mission Name'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='mission_number',
            field=models.CharField(max_length=255, verbose_name='Mission Number'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='number_of_profiles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Profiles'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='samplers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Samplers'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='call_sign',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
