# Generated by Django 2.1.4 on 2019-03-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0007_auto_20190318_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='name (English)')),
                ('nom', models.CharField(blank=True, max_length=1000, null=True, verbose_name='name (French)')),
                ('abbrev_eng', models.CharField(blank=True, max_length=25, null=True, verbose_name='abbreviation (English)')),
                ('abbrev_fre', models.CharField(blank=True, max_length=25, null=True, verbose_name='abbreviation (French)')),
                ('country', models.CharField(choices=[('Canada', 'Canada'), ('United States', 'United States')], max_length=25, verbose_name='country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='abbrev',
            field=models.CharField(default=1, max_length=10, verbose_name='abbreviation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institute',
            name='abbrev',
            field=models.CharField(max_length=255, verbose_name='abbreviation'),
        ),
    ]
