# Generated by Django 3.2 on 2021-04-21 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0008_auto_20210419_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cc_grad',
        ),
        migrations.RemoveField(
            model_name='person',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notification_preference',
        ),
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
    ]
