# Generated by Django 2.2.13 on 2020-10-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0009_auto_20201023_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Branch - Directorate (NCR)', 'verbose_name_plural': 'Branches - Directorates (NCR)'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name'], 'verbose_name': 'Division - Branch (NCR)', 'verbose_name_plural': 'Divisions - Branches (NCR)'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region - Sector (NCR)', 'verbose_name_plural': 'Regions - Sectors (NCR)'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['division__branch__region', 'division__branch', 'division', 'name'], 'verbose_name': 'Section - Team (NCR)', 'verbose_name_plural': 'Sections - Teams (NCR)'},
        ),
    ]
