# Generated by Django 2.1.4 on 2019-03-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0010_auto_20190320_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Branch', verbose_name='branch'),
        ),
    ]
