# Generated by Django 3.2 on 2021-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0012_auto_20210423_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='job title (en)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='job title (fr)'),
        ),
    ]
