# Generated by Django 2.1.4 on 2019-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0012_auto_20190424_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
