# Generated by Django 3.1.2 on 2020-10-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0013_auto_20201028_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='references',
            field=models.TextField(blank=True, null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='research_projects_programs',
            field=models.TextField(blank=True, null=True, verbose_name='Research Projects Programs'),
        ),
    ]
