# Generated by Django 3.1.2 on 2020-10-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0014_auto_20201028_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruise',
            options={'ordering': ['mission_number'], 'verbose_name': 'mission', 'verbose_name_plural': 'missions'},
        ),
    ]
