# Generated by Django 2.1.4 on 2019-06-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0015_cosigneecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosigneecode',
            name='rc_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cosigneecode',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Region'),
            preserve_default=False,
        ),
    ]
