# Generated by Django 3.2.4 on 2021-08-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0015_auto_20210601_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='full_name_and_address',
            new_name='full_name_and_address_en',
        ),
    ]
