# Generated by Django 2.2.2 on 2019-07-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0017_auto_20190605_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fishing_area_code', models.CharField(blank=True, max_length=255, null=True)),
                ('maritime_river_code', models.IntegerField(blank=True, null=True)),
                ('cgndb', models.IntegerField(blank=True, null=True)),
                ('river_hierarchy', models.CharField(blank=True, max_length=1000, null=True)),
                ('parent_cgndb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nbadw_water_body_id', models.IntegerField(blank=True, null=True)),
                ('stream_order', models.IntegerField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('latitude_n', models.FloatField(blank=True, null=True)),
                ('longitude_w', models.FloatField(blank=True, null=True)),
                ('epsg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinate_resolution', models.FloatField(blank=True, null=True)),
                ('coordinate_precision', models.FloatField(blank=True, null=True)),
                ('coordinate_accuracy', models.FloatField(blank=True, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rivers', to='shared_models.Province')),
            ],
            options={
                'ordering': ['province', 'name'],
            },
        ),
    ]
