# Generated by Django 2.2.2 on 2019-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0020_river_old_maritime_river_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='cgndb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
