# Generated by Django 3.1.2 on 2020-10-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0022_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_mod_by_ocean_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
