# Generated by Django 3.2.4 on 2021-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0023_subjectmatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='shared_models.SubjectMatter', verbose_name='expertise'),
        ),
    ]
