# Generated by Django 3.2.4 on 2021-10-13 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0027_auto_20211012_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='unique identifier'),
        ),
    ]
