# Generated by Django 3.1.2 on 2020-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0027_auto_20201125_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('abbrev', models.CharField(blank=True, max_length=255, null=True, verbose_name='abbreviation')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
