# Generated by Django 3.2.5 on 2021-11-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0029_auto_20211126_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='fishing_area_code',
        ),
    ]
