# Generated by Django 3.1.2 on 2021-01-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0033_auto_20210107_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='title (en)')),
                ('nom', models.TextField(blank=True, null=True, verbose_name='title (fr)')),
                ('authors', models.TextField(blank=True, null=True, verbose_name='authors')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('pub_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='publication number')),
                ('url_en', models.TextField(blank=True, null=True, verbose_name='URL (en)')),
                ('url_fr', models.TextField(blank=True, null=True, verbose_name='URL (fr)')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='abstract (en)')),
                ('abstract_fr', models.TextField(blank=True, null=True, verbose_name='abstract (fr)')),
                ('series', models.CharField(blank=True, max_length=1000, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.publication', verbose_name='publication name')),
            ],
        ),
    ]
