# Generated by Django 4.1.6 on 2023-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fisheriescape", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hexagon",
            index=models.Index(["grid_id"], name="grid_id"),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(["english_name"], name="english_name"),
        ),
        migrations.AddIndex(
            model_name="week",
            index=models.Index(["week_number"], name="week_number"),
        ),
    ]
