# Generated by Django 3.2.5 on 2021-11-24 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fisheriescape.models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0002_ordering_fishery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(53), django.core.validators.MinValueValidator(1)], verbose_name='week')),
            ],
        ),
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Catch per Unit Effort'), (2, 'Fishing Effort'), (3, 'Fisheriescape Index')], null=True, verbose_name='type')),
                ('image', models.FileField(upload_to=fisheriescape.models.image_directory_path, verbose_name='image')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysess', to='fisheriescape.species', verbose_name='species')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weeks', to='fisheriescape.week', verbose_name='week')),
            ],
        ),
    ]
