# Generated by Django 3.1.2 on 2021-01-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0002_fishery_area_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisheryarea',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date of season'),
        ),
        migrations.AlterField(
            model_name='fisheryarea',
            name='species',
            field=models.ManyToManyField(related_name='fisheryareas', to='fisheriescape.Species', verbose_name='species'),
        ),
        migrations.AlterField(
            model_name='fisheryarea',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date of season'),
        ),
    ]
