# Generated by Django 3.1.2 on 2021-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0003_dates_not_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='website'),
        ),
    ]
