# Generated by Django 4.1.6 on 2023-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fisheriescape", "0003_alter_score_unique_together_fisheryarea_layer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="VulnerableSpecies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="english name",
                    ),
                ),
                (
                    "french_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="french name",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="scientific name",
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="website"
                    ),
                ),
            ],
            options={
                "ordering": ["english_name"],
            },
        ),
        migrations.RenameIndex(
            model_name="species",
            new_name="species_english_name",
            old_name="english_name",
        ),
        migrations.AddIndex(
            model_name="vulnerablespecies",
            index=models.Index(["english_name"], name="vulnerablespecies_english_name"),
        ),
    ]
