# Generated by Django 3.2.5 on 2021-11-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0006_add_ref_text_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyses',
            old_name='ref_test',
            new_name='ref_text',
        ),
    ]
