# Generated by Django 4.1.6 on 2023-03-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fisheriescape", "0007_alter_score_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("hexagon", "week", "species")},
        ),
    ]
