# Generated by Django 3.1.2 on 2021-01-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0007_add_polygon_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisheryarea',
            name='layer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='layer id'),
        ),
    ]
