# Generated by Django 3.1.2 on 2021-01-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0009_model_reorganize_add_fishery_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineMammals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='english name')),
                ('french_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='french name')),
                ('latin_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='scientific name')),
                ('cosewic_status', models.CharField(blank=True, choices=[('Not at Risk', 'Not at Risk'), ('Special Concern', 'Special Concern'), ('Threatened', 'Threatened'), ('Endangered', 'Endangered'), ('Extirpated', 'Extirpated'), ('Extinct', 'Extinct')], max_length=255, null=True, verbose_name='cosewic status')),
                ('website', models.CharField(blank=True, max_length=250, null=True, verbose_name='website')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fisheryarea',
            options={'ordering': ['layer_id', 'name']},
        ),
        migrations.AlterField(
            model_name='species',
            name='english_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='french_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='french name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='latin_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='scientific name'),
        ),
        migrations.AddField(
            model_name='fishery',
            name='marine_mammals',
            field=models.ManyToManyField(related_name='fisherys', to='fisheriescape.MarineMammals', verbose_name='marine mammals'),
        ),
    ]
