# Generated by Django 3.2.5 on 2021-12-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0011_hexagon_unique_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['species', 'week']},
        ),
    ]
