# Generated by Django 3.1.2 on 2021-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0011_add_marine_mammal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineMammal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='english name')),
                ('english_name_short', models.CharField(blank=True, max_length=250, null=True, verbose_name='short english name')),
                ('french_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='french name')),
                ('french_name_short', models.CharField(blank=True, max_length=250, null=True, verbose_name='short french name')),
                ('latin_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='scientific name')),
                ('sara_status', models.CharField(blank=True, choices=[('Not at Risk', 'Not at Risk'), ('Special Concern', 'Special Concern'), ('Threatened', 'Threatened'), ('Endangered', 'Endangered'), ('Extirpated', 'Extirpated'), ('Extinct', 'Extinct')], max_length=255, null=True, verbose_name='sara status')),
                ('cosewic_status', models.CharField(blank=True, choices=[('Not at Risk', 'Not at Risk'), ('Special Concern', 'Special Concern'), ('Threatened', 'Threatened'), ('Endangered', 'Endangered'), ('Extirpated', 'Extirpated'), ('Extinct', 'Extinct')], max_length=255, null=True, verbose_name='cosewic status')),
                ('website', models.URLField(blank=True, max_length=250, null=True, verbose_name='website')),
            ],
        ),
        migrations.DeleteModel(
            name='MarineMammals',
        ),
        migrations.AlterField(
            model_name='fishery',
            name='marine_mammals',
            field=models.ManyToManyField(blank=True, related_name='fisherys', to='fisheriescape.MarineMammal', verbose_name='marine mammals'),
        ),
    ]
