# Generated by Django 3.2.5 on 2021-12-23 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0014_hexagon_srid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexagon',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=102001),
        ),
    ]
