# Generated by Django 3.2.10 on 2022-01-17 20:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0016_hexagon_srid_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexagon',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
