# Generated by Django 3.2.12 on 2022-03-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0021_add_mgmt_sysyem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigation_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='mitigation type')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='fishery',
            name='gear_primary_colour',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('Green', 'Red'), ('Yellow', 'Yellow'), ('White', 'White'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('Red/White Pattern', 'Red/White Pattern')], max_length=255, null=True, verbose_name='gear primary colour'),
        ),
        migrations.AddField(
            model_name='fishery',
            name='gear_secondary_colour',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('Green', 'Red'), ('Yellow', 'Yellow'), ('White', 'White'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('Red/White Pattern', 'Red/White Pattern')], max_length=255, null=True, verbose_name='gear secondary colour'),
        ),
        migrations.AddField(
            model_name='fishery',
            name='gear_tertiary_colour',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('Green', 'Red'), ('Yellow', 'Yellow'), ('White', 'White'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('Red/White Pattern', 'Red/White Pattern')], max_length=255, null=True, verbose_name='gear tertiary colour'),
        ),
        migrations.AddField(
            model_name='fishery',
            name='mitigation',
            field=models.ManyToManyField(related_name='mitigations', to='fisheriescape.Mitigation', verbose_name='mitigation type'),
        ),
    ]
