# Generated by Django 3.2.12 on 2022-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0024_fix_monitoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishery',
            name='license_type',
            field=models.CharField(blank=True, choices=[('Single', 'Single Species'), ('Multi', 'Multi Species')], max_length=255, null=True, verbose_name='type of license'),
        ),
    ]
