# Generated by Django 3.2.12 on 2022-03-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0036_fix_relatedname_fishery_mgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishery',
            name='participant_detail',
            field=models.TextField(blank=True, null=True, verbose_name='participant detail'),
        ),
        migrations.AlterField(
            model_name='fishery',
            name='gear_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='avg gear amount per participant'),
        ),
    ]
