# Generated by Django 3.2.12 on 2022-03-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheriescape', '0038_add_avg_soak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishery',
            name='comments',
        ),
        migrations.AddField(
            model_name='fishery',
            name='fishery_comment',
            field=models.TextField(blank=True, null=True, verbose_name='general comments'),
        ),
        migrations.AddField(
            model_name='fishery',
            name='mitigation_comments',
            field=models.TextField(blank=True, null=True, verbose_name='mitigation comments'),
        ),
        migrations.AlterField(
            model_name='fishery',
            name='gear_soak',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='avg rope soak time'),
        ),
    ]
