# Generated by Django 2.2.2 on 2020-04-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmutools', '0003_quantity_quantity_avail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='quantity_avail',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='quantity_lent',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='quantity_oh',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='quantity_oo',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='item',
            name='container',
            field=models.BooleanField(default=False, verbose_name='Is this item a container with more items inside it?'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Serial Number'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='lent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lendee', to='mmutools.Lending', verbose_name='Lent To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='status',
            field=models.CharField(choices=[(1, 'On hand'), (2, 'On Order'), (3, 'Lent Out')], default='None', max_length=255, verbose_name='Status'),
        ),
    ]
