# Generated by Django 2.2.2 on 2020-04-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmutools', '0008_auto_20200421_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:mm:ss', null=True, verbose_name='expected return date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='french name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='english description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_fra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='french description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.CharField(choices=[('None', 'No previous experience'), ('Novice', '1-2 Necropsies'), ('Intermediate', '3-5 Necropsies'), ('Advanced', 'More than 5 Necropsies')], default='None', max_length=255, verbose_name='experience level'),
        ),
        migrations.AlterField(
            model_name='file',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='mmutools.Supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='geartype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='geartype',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='french name'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='age_group',
            field=models.CharField(blank=True, choices=[('J', 'Juvenile'), ('YA', 'Young Adult'), ('A', 'Adult')], max_length=255, null=True, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments/Details'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='data_folder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='data folder'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='exam',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='examination conducted?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='first_report',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:mm:ss', null=True, verbose_name='date and time first reported'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='gear_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gear description'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='gear_presence',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='gear Presence?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('E', 'Entangled'), ('DF', 'DEAD - Floating'), ('DB', 'DEAD - Beached'), ('N', 'Necropsy')], max_length=255, null=True, verbose_name='type of Incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude (DD)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude (DD)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='necropsy',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='necropsy conducted?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photos',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='photos?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='region',
            field=models.CharField(blank=True, choices=[('Gulf', 'Gulf'), ('Mar', 'Maritimes'), ('NL', 'Newfoundland'), ('QC', 'Quebec')], max_length=255, null=True, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='results',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='results'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('UnK', 'Unknown')], max_length=255, null=True, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='species'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='species_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='species count'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='submitted',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='incident report submitted by Gulf?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='mmutools.Category', verbose_name='category of equipment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.BooleanField(default=False, verbose_name='is this item a container with more items inside it?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='container_space',
            field=models.IntegerField(blank=True, null=True, verbose_name='container Space Available (if applicable)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gear_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='mmutools.GearType', verbose_name='type of equipment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='name of item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owners', to='mmutools.Owner', verbose_name='owner of equipment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='size (if applicable)'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lendings', to='mmutools.Item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='lent_date',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:mm:ss', null=True, verbose_name='lent date'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='lent_to',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='lent to'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='quantity_lent',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity lent'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='abbrev_name',
            field=models.CharField(max_length=255, verbose_name='english abbreviated name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='abbrev_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='french abbreviated name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='french name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='french name'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='exp_level',
            field=models.ForeignKey(help_text='Novice 1-2 necropsy, Intermediate 3-5, Advanced more than 5', on_delete=django.db.models.deletion.DO_NOTHING, related_name='xp', to='mmutools.Experience', verbose_name='experience level'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='mmutools.Organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='training',
            field=models.ManyToManyField(to='mmutools.Training', verbose_name='training'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='bin_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='bin id'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantities', to='mmutools.Item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='last_audited',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:mm:ss', null=True, verbose_name='last audited'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='last_audited_by',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='last audited by'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='lent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lendee', to='mmutools.Lending', verbose_name='lent to'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='location_stored',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='location stored'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='status',
            field=models.CharField(choices=[('on hand', 'On Hand'), ('on order', 'On Order'), ('lent out', 'Lent Out')], default='ON_HAND', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suppliers', to='mmutools.Item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_invoice',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='last invoice'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_purchased',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:mm:ss', null=True, verbose_name='last purchased'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_purchased_by',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='last purchased by'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='supplier'),
        ),
    ]
