# Generated by Django 2.2.2 on 2020-05-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmutools', '0022_change_status_field_to_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='gear_types',
            new_name='gear_type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='owners',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sizes',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='locations',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='statuses',
            new_name='status',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_name', 'size')},
        ),
    ]
