# Generated by Django 2.2.2 on 2020-05-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmutools', '0023_make_field_names_singular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantities', to='mmutools.Location', verbose_name='location stored'),
        ),
    ]
