# Generated by Django 3.2.13 on 2022-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcrbatch',
            name='run_program',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' qPCR run program'),
        ),
    ]
