# Generated by Django 3.1.2 on 2021-03-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='filtration_type',
        ),
        migrations.AddField(
            model_name='sample',
            name='filtration_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections', to='edna.filtrationtype', verbose_name='filtration type'),
            preserve_default=False,
        ),
    ]
