# Generated by Django 3.1.2 on 2021-03-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0002_auto_20210311_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='filtration_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections', to='edna.filtrationtype', verbose_name='filtration type'),
        ),
    ]
