# Generated by Django 3.2.13 on 2022-05-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0002_alter_pcrbatch_run_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcr',
            options={'ordering': ['pcr_plate_well_prefix', 'pcr_plate_well_suffix', 'pcr_batch', 'extract__id', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['datetime', 'id']},
        ),
        migrations.AddField(
            model_name='pcr',
            name='pcr_plate_well_prefix',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pcr',
            name='pcr_plate_well_suffix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
