# Generated by Django 3.2.16 on 2023-01-23 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edna', '0003_auto_20220503_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date received at facility')),
                ('sent_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Received from')),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Storage Location at Reception')),
                ('default_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='edna.collection', verbose_name='project')),
                ('operators', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Received by')),
            ],
            options={
                'verbose_name_plural': 'Sample Collection / Receipt',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='edna.samplebatch', verbose_name='sample collection / receipt'),
        ),
    ]
