# Generated by Django 3.1.2 on 2021-03-15 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edna', '0004_auto_20210315_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionbatch',
            name='operators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='operator(s)'),
        ),
        migrations.AlterField(
            model_name='filtrationbatch',
            name='operators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='operator(s)'),
        ),
        migrations.AlterField(
            model_name='pcrbatch',
            name='operators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='operator(s)'),
        ),
    ]
