# Generated by Django 3.2.16 on 2023-01-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0004_samplebatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='edna.samplebatch', verbose_name='sample batch'),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('bottle_id', 'sample_batch')},
        ),
    ]
