# Generated by Django 3.2.16 on 2023-01-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0005_set_initial_sample_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='edna.samplebatch', verbose_name='sample collection / receipt'),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('bottle_id', 'sample_batch')},
        ),
    ]
