# Generated by Django 3.2.4 on 2021-07-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0006_auto_20210715_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='unique_sample_identifier',
        ),
        migrations.AddField(
            model_name='sample',
            name='bottle_id',
            field=models.IntegerField(blank=True, max_length=255, null=True, unique=True, verbose_name='bottle ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='edna.collection', verbose_name='collection'),
        ),
    ]
