# Generated by Django 3.2.16 on 2023-01-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0006_auto_20230123_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcrbatch',
            name='default_collection',
        ),
        migrations.AddField(
            model_name='pcrbatch',
            name='default_collection',
            field=models.ManyToManyField(to='edna.Collection', verbose_name='project(s)'),
        ),
    ]
