# Generated by Django 3.2.4 on 2021-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0007_auto_20210715_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='bottle_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='bottle ID'),
        ),
    ]
