# Generated by Django 3.2.16 on 2023-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0008_auto_20230201_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='tube_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='tube ID'),
        ),
    ]
