# Generated by Django 3.1.2 on 2021-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0010_auto_20210317_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaextract',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='comments'),
        ),
    ]
