# Generated by Django 3.1.2 on 2021-03-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edna', '0012_auto_20210317_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnaextract',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dnaextract_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dnaextract',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dnaextract_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcr',
            name='pcr_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcrs', to='edna.pcrbatch', verbose_name='PCR batch'),
        ),
    ]
