# Generated by Django 3.1.2 on 2021-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0015_auto_20210317_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcr',
            options={'ordering': ['pcr_batch', 'extract', 'pcr_number_suffix']},
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='ct_1',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='ct_2',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='ct_3',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='edna_conc_1',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='edna_conc_2',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='edna_conc_3',
        ),
        migrations.AddField(
            model_name='speciesobservation',
            name='ct',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cycle threshold (ct)'),
        ),
        migrations.AddField(
            model_name='speciesobservation',
            name='edna_conc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='eDNA concentration (Pg/L)'),
        ),
    ]
