# Generated by Django 3.2.4 on 2021-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0016_auto_20210716_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='bottle_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='bottle ID'),
        ),
    ]
