# Generated by Django 3.1.2 on 2021-03-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0017_auto_20210317_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesobservation',
            old_name='undetermined',
            new_name='is_undetermined',
        ),
    ]
