# Generated by Django 3.2.4 on 2021-07-19 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edna', '0017_alter_sample_bottle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lod', models.FloatField(blank=True, null=True, verbose_name='LOD value')),
                ('loq', models.FloatField(blank=True, null=True, verbose_name='LOQ value')),
                ('a_coef', models.FloatField(blank=True, null=True, verbose_name='formula A coefficient')),
                ('b_coef', models.FloatField(blank=True, null=True, verbose_name='formula B coefficient')),
                ('is_ipc', models.BooleanField(default=False, verbose_name='is this assay being used as an IPC?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assay_created_by', to=settings.AUTH_USER_MODEL)),
                ('species', models.ManyToManyField(blank=True, to='edna.Species', verbose_name='species')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assay_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCRAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ct', models.FloatField(blank=True, null=True, verbose_name='cycle threshold (ct)')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='cycle threshold (ct)')),
                ('is_undetermined', models.BooleanField(default=False, verbose_name='undetermined?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('edna_conc', models.FloatField(blank=True, editable=False, null=True, verbose_name='eDNA concentration (Pg/L)')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pcr',
            name='ipc_added',
        ),
        migrations.RemoveField(
            model_name='pcr',
            name='plate_id',
        ),
        migrations.RemoveField(
            model_name='pcr',
            name='position',
        ),
        migrations.RemoveField(
            model_name='pcr',
            name='qpcr_ipc',
        ),
        migrations.RemoveField(
            model_name='pcr',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='pcr',
            name='plate_well',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='qPCR plate well'),
        ),
        migrations.AddField(
            model_name='pcrbatch',
            name='control_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Ok'), (1, 'No good')], null=True, verbose_name='control status'),
        ),
        migrations.AddField(
            model_name='pcrbatch',
            name='machine_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='qPCR machine number'),
        ),
        migrations.AddField(
            model_name='pcrbatch',
            name='plate_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='qPCR plate ID'),
        ),
        migrations.AddField(
            model_name='pcrbatch',
            name='run_program',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='qPCR run program'),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='filtrationbatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='pcrbatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='collection date/time'),
        ),
        migrations.DeleteModel(
            name='SpeciesObservation',
        ),
        migrations.AddField(
            model_name='pcrassay',
            name='assay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qcr_assays', to='edna.pcrbatch', verbose_name='PCR batch'),
        ),
        migrations.AddField(
            model_name='pcrassay',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcrassay_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcrassay',
            name='pcr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qcr_assays', to='edna.pcr', verbose_name='PCR'),
        ),
        migrations.AddField(
            model_name='pcrassay',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcrassay_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcr',
            name='master_mix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcrs', to='edna.mastermix', verbose_name='master mix'),
        ),
        migrations.AlterUniqueTogether(
            name='pcrassay',
            unique_together={('pcr', 'assay')},
        ),
    ]
