# Generated by Django 3.2.4 on 2021-07-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0019_auto_20210720_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr',
            name='is_duplex',
            field=models.BooleanField(default=False, verbose_name='Is this a duplex qPCR?'),
        ),
        migrations.AlterField(
            model_name='pcr',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name=' qPCR comments'),
        ),
        migrations.AlterField(
            model_name='pcr',
            name='pcr_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcrs', to='edna.pcrbatch', verbose_name=' qPCR batch'),
        ),
        migrations.AlterField(
            model_name='pcr',
            name='plate_well',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=' qPCR plate well'),
        ),
        migrations.AlterField(
            model_name='pcrassay',
            name='assay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcr_assays', to='edna.pcrbatch', verbose_name='assay'),
        ),
        migrations.AlterField(
            model_name='pcrassay',
            name='ct',
            field=models.FloatField(blank=True, null=True, verbose_name='Ct'),
        ),
        migrations.AlterField(
            model_name='pcrassay',
            name='threshold',
            field=models.FloatField(blank=True, null=True, verbose_name='threshold'),
        ),
        migrations.AlterField(
            model_name='pcrbatch',
            name='control_status',
            field=models.IntegerField(blank=True, choices=[(1, 'OK'), (0, 'Bad')], null=True, verbose_name='control status'),
        ),
        migrations.AlterField(
            model_name='pcrbatch',
            name='machine_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=' qPCR machine number'),
        ),
        migrations.AlterField(
            model_name='pcrbatch',
            name='plate_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=' qPCR plate ID'),
        ),
        migrations.AlterField(
            model_name='pcrbatch',
            name='run_program',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=' qPCR run program'),
        ),
    ]
