# Generated by Django 3.2.4 on 2021-07-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0025_auto_20210722_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrassay',
            name='is_undetermined',
            field=models.BooleanField(default=False, verbose_name='Undetermined?'),
        ),
        migrations.AlterField(
            model_name='pcrassay',
            name='edna_conc',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name=' eDNA concentration (Pg/L)'),
        ),
        migrations.AlterField(
            model_name='pcrassay',
            name='result',
            field=models.IntegerField(choices=[(8, 'in progress'), (1, 'positive'), (0, 'negative'), (90, 'no assay :('), (91, 'LOD missing :(')], default=8, editable=False, verbose_name='result'),
        ),
    ]
