# Generated by Django 3.2.4 on 2021-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0026_auto_20210722_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='bottle_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bottle ID'),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('bottle_id', 'collection')},
        ),
    ]
