# Generated by Django 3.2.4 on 2021-07-23 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0027_auto_20210723_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnaextract',
            options={'ordering': ['filter', 'id']},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['sample', 'id']},
        ),
        migrations.AddField(
            model_name='assay',
            name='alias',
            field=models.CharField(default='test', help_text='This is the name that will be used to reference this assay on import spreadsheets.', max_length=50, verbose_name='target name / alias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnaextract',
            name='extraction_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='extraction number'),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date/time'),
        ),
        migrations.AlterField(
            model_name='filtrationbatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date/time'),
        ),
        migrations.AlterField(
            model_name='pcrbatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date/time'),
        ),
    ]
