# Generated by Django 3.2.4 on 2021-08-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0028_auto_20210723_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcr',
            options={'ordering': ['pcr_batch', 'plate_well']},
        ),
        migrations.AlterModelOptions(
            name='pcrassay',
            options={'ordering': ['pcr', 'assay']},
        ),
    ]
