# Generated by Django 3.2.5 on 2021-12-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0029_auto_20210818_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnaextractionprotocol',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='filtrationtype',
            options={'ordering': ['name']},
        ),
    ]
