# Generated by Django 3.2.10 on 2022-03-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0033_auto_20220301_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcrassay',
            name='pcr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='edna.pcr', verbose_name='PCR'),
        ),
    ]
