# Generated by Django 3.2.10 on 2022-04-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0031_subjectmatter_is_csas_request_tag'),
        ('edna', '0034_alter_pcrassay_pcr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='location_description',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='program_description',
            new_name='description',
        ),
    ]
