# Generated by Django 3.2.10 on 2022-04-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0037_alter_sample_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['filtration_batch', 'order']},
        ),
        migrations.AddField(
            model_name='filter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='edna.collection', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='filter',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
