# Generated by Django 3.2.10 on 2022-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0041_dnaextract_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='project description'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='duration_min',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='filtration duration (min)'),
        ),
    ]
