# Generated by Django 3.2.10 on 2022-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0042_auto_20220426_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaextract',
            name='order',
            field=models.IntegerField(default=0, editable=False, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='pcr',
            name='order',
            field=models.IntegerField(default=0, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='order',
            field=models.IntegerField(default=0, editable=False, verbose_name='order'),
        ),
    ]
