# Generated by Django 3.2.10 on 2022-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edna', '0044_auto_20220427_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_field_blank',
            field=models.BooleanField(default=False, verbose_name='is this a field blank?'),
        ),
    ]
