# Generated by Django 3.2.14 on 2022-08-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20220819_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('-sent_at',)},
        ),
    ]
