# Generated by Django 2.2.2 on 2019-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20190719_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitsummary',
            name='date',
            field=models.DateField(),
        ),
    ]
