# Generated by Django 2.2.2 on 2019-07-19 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0006_auto_20190719_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsummary',
            name='user',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='visitsummary',
            unique_together={('date', 'application_name', 'user')},
        ),
        migrations.DeleteModel(
            name='UserSummary',
        ),
    ]
