# Generated by Django 2.2.2 on 2019-08-06 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrecipitationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiverSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='site name')),
                ('stream_order', models.IntegerField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True, verbose_name='elevation (m)')),
                ('latitude_n', models.FloatField(blank=True, null=True)),
                ('longitude_w', models.FloatField(blank=True, null=True)),
                ('epsg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinate_resolution', models.FloatField(blank=True, null=True)),
                ('coordinate_precision', models.FloatField(blank=True, null=True)),
                ('coordinate_accuracy', models.FloatField(blank=True, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
                ('exclude_data_from_site', models.BooleanField(default=False, verbose_name='Exclude all data from this site?')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='river_sites', to='shared_models.Province')),
                ('river', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='river_sites', to='shared_models.River')),
            ],
            options={
                'ordering': ['province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WindDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='english name')),
                ('common_name_fre', models.CharField(blank=True, max_length=255, null=True, verbose_name='french name')),
                ('abbrev', models.CharField(max_length=10, unique=True, verbose_name='abbreviation')),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tsn', models.IntegerField(blank=True, null=True, verbose_name='ITIS TSN')),
                ('aphia_id', models.IntegerField(blank=True, null=True, verbose_name='AphiaID')),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('life_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='species', to='trapnet.LifeStage')),
            ],
            options={
                'ordering': ['common_name_eng'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(verbose_name='arrival date/time')),
                ('departure_date', models.DateTimeField(verbose_name='departure date/time')),
                ('air_temp_arrival', models.FloatField(blank=True, null=True, verbose_name='air temperature on arrival(°C)')),
                ('min_air_temp', models.FloatField(blank=True, null=True, verbose_name='minimum air temperature (°C)')),
                ('max_air_temp', models.FloatField(blank=True, null=True, verbose_name='maximum air temperature (°C)')),
                ('percent_cloud_cover', models.FloatField(blank=True, null=True, verbose_name='cloud cover (%)')),
                ('precipitation_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('water_depth_m', models.FloatField(blank=True, null=True, verbose_name='water depth (m)')),
                ('water_level_delta_m', models.FloatField(blank=True, null=True, verbose_name='water level delta (m)')),
                ('discharge_m3_sec', models.FloatField(blank=True, null=True, verbose_name='discharge (m3/s)')),
                ('water_temp_shore_c', models.FloatField(blank=True, null=True, verbose_name='water temperature at shore (°C)')),
                ('water_temp_trap_c', models.FloatField(blank=True, null=True, verbose_name='water temperature at trap (°C)')),
                ('rpm_arrival', models.FloatField(blank=True, null=True, verbose_name='RPM at start')),
                ('rpm_departure', models.FloatField(blank=True, null=True, verbose_name='RPM at end')),
                ('operating_condition_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('samplers', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wheel_sample_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('operating_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.OperatingCondition')),
                ('precipitation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.PrecipitationCategory')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.SampleType')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.RiverSite')),
                ('wind_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.WindDirection')),
                ('wind_speed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.WindSpeed')),
            ],
            options={
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('last_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True, verbose_name='frequency')),
                ('fork_length', models.FloatField(blank=True, null=True, verbose_name='fork length (mm)')),
                ('total_length', models.FloatField(blank=True, null=True, verbose_name='fork length (mm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight (g)')),
                ('smolt_age', models.IntegerField(blank=True, null=True)),
                ('location_tagged', models.CharField(blank=True, max_length=500, null=True)),
                ('date_tagged', models.DateTimeField(blank=True, null=True, verbose_name='date tagged')),
                ('scale_id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='scale ID number')),
                ('tags_removed', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='trapnet.Origin')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trapnet.Sample')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='trapnet.Sex')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='trapnet.Species')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='trapnet.Status')),
            ],
        ),
    ]
