# Generated by Django 3.2.2 on 2021-06-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='water_temp_c',
        ),
    ]
