# Generated by Django 3.2.14 on 2022-11-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='fork_length_bin_interval',
            field=models.FloatField(default=1, verbose_name='fork length bin interval (mm)'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='maturity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='specimens', to='trapnet.maturity'),
        ),
    ]
