# Generated by Django 3.2.2 on 2021-06-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0006_auto_20210611_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origin',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='entry',
            name='tag_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tag_number'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='total_length',
            field=models.FloatField(blank=True, null=True, verbose_name='total length (mm)'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)'),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='status',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)'),
        ),
    ]
