# Generated by Django 3.2.5 on 2021-11-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0006_auto_20210617_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='electrofisher_output',
        ),
        migrations.AddField(
            model_name='sample',
            name='electrofisher_output_high',
            field=models.FloatField(blank=True, null=True, verbose_name='electrofisher output, high (amps)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='electrofisher_output_low',
            field=models.FloatField(blank=True, null=True, verbose_name='electrofisher output, low (amps)'),
        ),
    ]
