# Generated by Django 3.2.13 on 2022-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0006_samplefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='tags_removed',
        ),
        migrations.AlterField(
            model_name='observation',
            name='fork_length',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='fork length (mm)'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='total_length',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total length (mm)'),
        ),
    ]
