# Generated by Django 3.2.5 on 2021-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0007_auto_20211101_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='max_overhanging_veg_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Overhanging Vegetation (m) - Left'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='max_overhanging_veg_right',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Overhanging Vegetation (m) - Right'),
        ),
    ]
