# Generated by Django 3.2.13 on 2022-06-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0007_auto_20220527_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='time_released',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time released'),
        ),
    ]
