# Generated by Django 3.2.2 on 2021-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0008_auto_20210611_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='tag_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='tag number'),
        ),
    ]
