# Generated by Django 3.2.5 on 2021-11-04 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0008_auto_20211103_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='percent_bedrock',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='bedrock'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_boulder',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='boulder'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_cobble',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='cobble'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_fine',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='fine silt or clay'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_flat',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='flat'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_gravel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='gravel'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_pebble',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pebble'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_pool',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pool'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_riffle',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='riffle'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_rocks',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rocks'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_run',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='run'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent_sand',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='sand'),
        ),
    ]
