# Generated by Django 2.2.2 on 2019-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0008_auto_20190715_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='trap',
            name='operating_condition_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
