# Generated by Django 3.2.13 on 2022-06-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0009_auto_20220601_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='date_tagged',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='location_tagged',
        ),
    ]
