# Generated by Django 2.2.2 on 2019-07-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0010_auto_20190716_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trap',
            name='operating_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traps', to='trapnet.OperatingCondition'),
        ),
    ]
