# Generated by Django 3.2.2 on 2021-06-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0010_auto_20210614_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riversite',
            old_name='longitude_w',
            new_name='longitude',
        ),
    ]
