# Generated by Django 3.2.14 on 2022-12-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0013_auto_20221208_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='smart_river_age',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='smart_river_age_type',
            field=models.IntegerField(blank=True, choices=[(1, 'scale'), (2, 'length-frequency, manual'), (3, 'length-frequency, auto')], editable=False, null=True),
        ),
    ]
