# Generated by Django 3.2.2 on 2021-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0013_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['sample__arrival_date', 'species', 'tag_number']},
        ),
    ]
