# Generated by Django 3.2.2 on 2021-06-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0015_observation_sweep_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='age',
            new_name='river_age',
        ),
    ]
