# Generated by Django 2.2.2 on 2019-07-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0015_auto_20190716_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='trapnet.Sample'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='operating_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.OperatingCondition'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='precipitation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.PrecipitationCategory'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.RiverSite'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='trap_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.TrapType'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='wind_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.WindDirection'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='wind_speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.WindSpeed'),
        ),
    ]
