# Generated by Django 3.2.5 on 2021-11-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0015_auto_20211117_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='trapnet.status'),
        ),
    ]
