# Generated by Django 2.2.2 on 2019-07-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0016_auto_20190716_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='trap_type',
        ),
    ]
