# Generated by Django 3.2.14 on 2022-11-10 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0016_auto_20221110_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='overhanging_veg_left',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overhanging Vegetation (%) - Left'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='overhanging_veg_right',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overhanging Vegetation (%) - Right'),
        ),
    ]
