# Generated by Django 3.2.5 on 2021-11-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0016_alter_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='trapnet.status'),
        ),
    ]
