# Generated by Django 3.2.2 on 2021-06-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0016_rename_age_observation_river_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maturity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='age_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Fry'), (2, 'Parr')], null=True, verbose_name='age type'),
        ),
        migrations.AddField(
            model_name='observation',
            name='fish_size',
            field=models.IntegerField(blank=True, choices=[(1, 'Fry'), (2, 'Parr')], null=True, verbose_name='fish size'),
        ),
        migrations.AddField(
            model_name='observation',
            name='ocean_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='ocean age'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date_tagged',
            field=models.DateTimeField(blank=True, null=True, verbose_name='original date tagged'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='river_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='river age'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sweep_number',
            field=models.FloatField(blank=True, null=True, verbose_name='sweep number'),
        ),
        migrations.AddField(
            model_name='observation',
            name='maturity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='trapnet.maturity'),
        ),
    ]
