# Generated by Django 3.2.2 on 2021-06-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0017_auto_20210616_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrofisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='crew_dipnet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='creq (dipnet)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='crew_extras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='creq (extras)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='crew_probe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='creq (probe)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='crew_seine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='creq (seine)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='electrofisher_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='electrofisher frequency (Hz)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='electrofisher_output',
            field=models.FloatField(blank=True, null=True, verbose_name='electrofisher output (amps)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='electrofisher_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='electrofisher voltage (V)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sweep_time',
            field=models.IntegerField(blank=True, help_text='in seconds', null=True, verbose_name='sweep time'),
        ),
        migrations.AddField(
            model_name='sample',
            name='water_cond',
            field=models.FloatField(blank=True, help_text='THe measurement is to 1 decimal place in micro siemens (µS)', null=True, verbose_name='Water Conductivity (Specific)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='water_temp_c',
            field=models.FloatField(blank=True, help_text='In Celcius, to 1 decimal place', null=True, verbose_name='water temperature at trap (°C)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='electrofisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='trapnet.electrofisher', verbose_name='electrofisher'),
        ),
    ]
