# Generated by Django 3.2.14 on 2022-11-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0020_alter_sweep_sample'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sweep',
            unique_together={('sample', 'sweep_number')},
        ),
    ]
