# Generated by Django 3.2.2 on 2021-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0020_auto_20210617_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='bank_length_left',
            field=models.FloatField(blank=True, null=True, verbose_name='bank length - left (m)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bank_length_right',
            field=models.FloatField(blank=True, null=True, verbose_name='bank length - right (m)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_1_lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #1 - lower (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_1_middle',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #1 - middle (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_1_upper',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #1 - upper (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_2_lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #2 - lower (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_2_middle',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #2 - middle (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_2_upper',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #2 - upper (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_3_lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #3 - lower (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_3_middle',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #3 - middle (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_3_upper',
            field=models.IntegerField(blank=True, null=True, verbose_name='depth #3 - upper (cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='width_lower',
            field=models.FloatField(blank=True, null=True, verbose_name='width - lower (m)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='width_middle',
            field=models.FloatField(blank=True, null=True, verbose_name='width - middle (m)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='width_upper',
            field=models.FloatField(blank=True, null=True, verbose_name='width - upper (m)'),
        ),
    ]
