# Generated by Django 3.2.5 on 2021-11-25 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0021_auto_20211125_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='duty_cycle',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='duty cycle'),
        ),
        migrations.AddField(
            model_name='sample',
            name='electrofisher_pulse_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Standard pulse '), (2, 'Direct current'), (3, 'Burst of pulses')], null=True, verbose_name='type of pulse'),
        ),
    ]
