# Generated by Django 3.2.5 on 2021-11-25 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0022_auto_20211125_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='duty_cycle',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='duty cycle (%)'),
        ),
    ]
