# Generated by Django 3.2.14 on 2022-11-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0025_auto_20221123_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='observation',
            new_name='specimen',
        ),
    ]
