# Generated by Django 2.2.2 on 2019-07-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0027_auto_20190718_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trapnet.Sample'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='trapnet.Species'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='departure_date',
            field=models.DateTimeField(verbose_name='departure date/time'),
        ),
    ]
