# Generated by Django 2.2.2 on 2019-07-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0030_species_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='abbrev',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='abbreviation'),
        ),
    ]
