# Generated by Django 2.2.2 on 2019-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapnet', '0032_auto_20190726_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='abbrev',
            field=models.CharField(max_length=10, unique=True, verbose_name='abbreviation'),
        ),
    ]
