# Generated by Django 2.2.2 on 2020-04-29 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('level', models.CharField(max_length=150)),
                ('interpretation', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Predator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stomach_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='stomach ID')),
                ('processing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='processing date')),
                ('set', models.IntegerField(blank=True, null=True)),
                ('fish_number', models.IntegerField(blank=True, null=True)),
                ('somatic_length_cm', models.FloatField(blank=True, null=True, verbose_name='body length (cm)')),
                ('stomach_wt_g', models.FloatField(blank=True, null=True, verbose_name='stomach weight (g)')),
                ('content_wt_g', models.FloatField(blank=True, null=True, verbose_name='content weight (g)')),
                ('comments', models.TextField(blank=True, null=True)),
                ('stratum', models.IntegerField(blank=True, null=True)),
                ('somatic_wt_g', models.FloatField(blank=True, null=True, verbose_name='body weight (g)')),
                ('old_seq_num', models.IntegerField(blank=True, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cruise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='predators', to='shared_models.Cruise')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processing_date'],
            },
        ),
        migrations.CreateModel(
            name='Sampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('common_name_fre', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abbrev', models.CharField(blank=True, max_length=255, null=True)),
                ('tsn', models.IntegerField(blank=True, null=True, verbose_name='ITIS TSN')),
                ('aphia_id', models.IntegerField(blank=True, null=True, verbose_name='AphiaID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somatic_length_mm', models.FloatField(blank=True, null=True, verbose_name='body length (mm)')),
                ('length_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_prey', models.IntegerField(blank=True, null=True, verbose_name='number of prey')),
                ('somatic_wt_g', models.FloatField(blank=True, null=True, verbose_name='body weight (g)')),
                ('comments', models.TextField(blank=True, null=True)),
                ('censored_length', models.BooleanField(default=False)),
                ('stomach_wt_g', models.FloatField(blank=True, null=True, verbose_name='stomach weight (g)')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('digestion_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diets.DigestionLevel')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('predator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prey_items', to='diets.Predator')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prey_items', to='diets.Species')),
            ],
        ),
        migrations.AddField(
            model_name='predator',
            name='samplers',
            field=models.ManyToManyField(blank=True, to='diets.Sampler'),
        ),
        migrations.AddField(
            model_name='predator',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predators', to='diets.Species', verbose_name='predator species'),
        ),
    ]
