# Generated by Django 2.1.4 on 2019-03-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_auto_20190326_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='vessel',
        ),
        migrations.AlterField(
            model_name='predator',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predators', to='shared_models.Cruise'),
        ),
        migrations.AlterField(
            model_name='predator',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predators', to='diets.Species', verbose_name='predator species'),
        ),
        migrations.AlterField(
            model_name='predator',
            name='stomach_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='stomach ID'),
        ),
        migrations.DeleteModel(
            name='Cruise',
        ),
        migrations.DeleteModel(
            name='Vessel',
        ),
    ]
