# Generated by Django 2.1.4 on 2019-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_auto_20190326_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predator',
            name='stomach_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='stomach ID'),
        ),
    ]
