# Generated by Django 2.1.4 on 2019-01-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_auto_20190102_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='prey',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
