# Generated by Django 2.1.4 on 2019-01-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_auto_20190102_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predator',
            name='prey_items',
        ),
        migrations.AlterField(
            model_name='prey',
            name='predator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prey_items', to='diets.Predator'),
        ),
    ]
