# Generated by Django 2.1.4 on 2019-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_auto_20190102_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=150)),
                ('interpretation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='predator',
            options={'ordering': ['-processing_date', 'species']},
        ),
        migrations.AlterField(
            model_name='predator',
            name='processing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processing date (dd-mm-yyyy)'),
        ),
    ]
