# Generated by Django 2.2.2 on 2019-07-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_auto_20190730_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prey',
            old_name='sensor_used',
            new_name='censored_length',
        ),
    ]
