# Generated by Django 2.1.4 on 2019-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0009_delete_digestioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=150)),
                ('interpretation', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
