# Generated by Django 2.1.4 on 2019-01-03 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0011_auto_20190103_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predator',
            name='cruise',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.DO_NOTHING, related_name='predators', to='diets.Cruise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predator',
            name='processing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='processing date (dd-mm-yyyy)'),
        ),
    ]
