# Generated by Django 2.1.4 on 2019-02-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0015_digestionlevel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestionlevel',
            name='code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
