# Generated by Django 2.1.4 on 2019-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0018_auto_20190226_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='prey',
            name='number_of_prey',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of prey'),
        ),
    ]
