# Generated by Django 2.2.2 on 2020-02-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_merge_20200213_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='app',
            field=models.CharField(blank=True, choices=[('general', 'n/a'), ('esee', 'ESEE (not part of site)'), ('necropsy', 'Necropsy Tools and Marine Mammal Section Inventory'), ('plankton', 'Plankton Net (not part of site)'), ('tickets', 'Data Management Tickets'), ('vault', 'Marine Megafauna Media Vault')], default='general', max_length=25, null=True, verbose_name='application name'),
        ),
    ]
