# Generated by Django 2.2.2 on 2020-03-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20200303_1407'),
        ('tickets', '0010_auto_20200316_2122'),
    ]

    operations = [
    ]
