# Generated by Django 2.1.4 on 2019-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190423_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='message',
            field=models.TextField(verbose_name='follow up message'),
        ),
    ]
