# Generated by Django 2.1.4 on 2019-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20190423_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='github_issue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
