# Generated by Django 2.2.2 on 2020-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20200422_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='app',
            field=models.CharField(blank=True, choices=[('general', 'n/a'), ('esee', 'ESEE (not part of site)'), ('inventory', 'Metadata Inventory'), ('plankton', 'Plankton Net (not part of site)'), ('projects', 'Science project planning'), ('tickets', 'Data Management Tickets'), ('travel', 'Travel Management System')], default='general', max_length=25, null=True, verbose_name='application name'),
        ),
    ]
