# Generated by Django 3.2.12 on 2022-07-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='allocated_capital',
            field=models.FloatField(blank=True, null=True, verbose_name='Allocated capital'),
        ),
        migrations.AddField(
            model_name='review',
            name='allocated_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Allocated salary'),
        ),
        migrations.AlterField(
            model_name='review',
            name='allocated_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Allocated O&M'),
        ),
    ]
