# Generated by Django 3.2.12 on 2022-08-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0002_auto_20220712_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-is_primary_lead', '-is_lead', 'employee_type', 'level']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='allocated_capital',
        ),
        migrations.RemoveField(
            model_name='review',
            name='allocated_salary',
        ),
        migrations.AddField(
            model_name='capitalcost',
            name='allocated_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='amount allocated (CAD)'),
        ),
        migrations.AddField(
            model_name='omcost',
            name='allocated_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='amount allocated (CAD)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='allocated_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='amount allocated (CAD)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_primary_lead',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False, verbose_name='primary project lead'),
        ),
        migrations.AlterField(
            model_name='review',
            name='allocated_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Allocated budget'),
        ),
        migrations.CreateModel(
            name='SalaryAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='amount (CAD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('funding_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.fundingsource', verbose_name='funding source')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.projectyear', verbose_name='project year')),
            ],
            options={
                'ordering': ['funding_source'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OMAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='amount (CAD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('funding_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.fundingsource', verbose_name='funding source')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.projectyear', verbose_name='project year')),
            ],
            options={
                'ordering': ['funding_source'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='amount (CAD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('funding_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.fundingsource', verbose_name='funding source')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.projectyear', verbose_name='project year')),
            ],
            options={
                'ordering': ['funding_source'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='capitalcost',
            name='allocated_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.capitalallocation', verbose_name='Allocation Source'),
        ),
        migrations.AddField(
            model_name='omcost',
            name='allocated_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.omallocation', verbose_name='Allocation Source'),
        ),
        migrations.AddField(
            model_name='staff',
            name='allocated_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.salaryallocation', verbose_name='Allocation Source'),
        ),
    ]
