# Generated by Django 3.2.12 on 2022-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0003_capitalallocation_omallocation_salaryallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='allocated_capital',
        ),
        migrations.RemoveField(
            model_name='review',
            name='allocated_salary',
        ),
        migrations.AlterField(
            model_name='review',
            name='allocated_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Allocated budget'),
        ),
    ]
