# Generated by Django 3.2.12 on 2022-07-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0005_staff_is_primary_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-is_primary_lead', '-is_lead', 'employee_type', 'level']},
        ),
        migrations.AddField(
            model_name='capitalcost',
            name='allocated_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='amount (CAD)'),
        ),
        migrations.AddField(
            model_name='capitalcost',
            name='allocated_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.capitalallocation', verbose_name='Allocation Source'),
        ),
        migrations.AddField(
            model_name='omcost',
            name='allocated_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='amount (CAD)'),
        ),
        migrations.AddField(
            model_name='omcost',
            name='allocated_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.omallocation', verbose_name='Allocation Source'),
        ),
        migrations.AddField(
            model_name='staff',
            name='allocated_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='amount (CAD)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='allocated_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.salaryallocation', verbose_name='Allocation Source'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_primary_lead',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False, verbose_name='primary project lead'),
        ),
    ]
