# Generated by Django 3.2.12 on 2022-10-20 17:40

from django.db import migrations, models
import ppt.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0006_auto_20221005_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='checklist_file',
            field=models.FileField(blank=True, null=True, upload_to=ppt.models.ref_mat_directory_path, verbose_name='Feedback Checklist'),
        ),
    ]
