# Generated by Django 3.2.15 on 2022-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0007_review_checklist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='excess_funds',
            field=models.BooleanField(default=False, verbose_name='are there remaining funds?'),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='excess_funds_amt',
            field=models.IntegerField(blank=True, null=True, verbose_name='remaining funds amount'),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='excess_funds_comment',
            field=models.TextField(blank=True, null=True, verbose_name='suggested uses for remaining funds'),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='insuficient_funds',
            field=models.BooleanField(default=False, verbose_name='do you wish to request additional funding?'),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='insuficient_funds_amt',
            field=models.IntegerField(blank=True, null=True, verbose_name='additional funding request amount'),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='insuficient_funds_comment',
            field=models.TextField(blank=True, null=True, verbose_name='additional funding request description'),
        ),
    ]
