# Generated by Django 3.2.15 on 2022-12-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0010_alter_dma_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (en)')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (fr)')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(1, 'Milestone'), (2, 'Deliverable')], verbose_name='Milestone or Deliverable?'),
        ),
        migrations.AddField(
            model_name='activity',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ppt.activityclassification', verbose_name='Type'),
        ),
    ]
