# Generated by Django 3.2.5 on 2021-12-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0030_remove_river_fishing_area_code'),
        ('ppt', '0012_alter_csrfclientinformation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csrfpriority',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='csrfclientinformation',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.fiscalyear', verbose_name='fiscal year'),
        ),
        migrations.AlterField(
            model_name='csrfclientinformation',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='csrfclientinformation',
            name='nom',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='name (fr)'),
        ),
    ]
