# Generated by Django 3.2.10 on 2021-12-17 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppt', '0015_auto_20211217_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='target_end_date',
            new_name='target_start_date',
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible_parties',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='responsible parties'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='responsible party notes'),
        ),
    ]
