# Generated by Django 3.2.10 on 2022-01-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0021_auto_20220112_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='dma',
            name='storage_solutions',
            field=models.ManyToManyField(blank=True, to='ppt.StorageSolution', verbose_name='Which storage solution(s) will be used to house the raw field data, processed data, and all other data products?'),
        ),
    ]
