# Generated by Django 3.2.10 on 2022-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0022_dma_storage_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dma',
            name='storage_solution_text',
            field=models.TextField(blank=True, help_text='Provide your rational for the selection(s) made above.', null=True, verbose_name='Justification for selection of storage solution(s)'),
        ),
    ]
