# Generated by Django 3.2.10 on 2022-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0024_alter_activity_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectyear',
            name='has_ship_needs',
            field=models.BooleanField(default=False, verbose_name='Ship (Coast Guard, charter vessel) Requirements?'),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='ship_needs',
            field=models.TextField(blank=True, null=True, verbose_name='Description of Ship (Coast Guard, charter vessel) Requirements'),
        ),
    ]
