# Generated by Django 3.2.10 on 2022-04-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0031_subjectmatter_is_csas_request_tag'),
        ('ppt', '0026_auto_20220323_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmareview',
            name='fiscal_year',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ppt_dma_reviews', to='shared_models.fiscalyear'),
        ),
    ]
