# Generated by Django 3.2.10 on 2022-04-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0027_alter_dmareview_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dma',
            name='cloud_costs',
            field=models.TextField(blank=True, help_text="e.g., cloud storage is estimated at $1000/yr and will be paid for under the the division manager's budget", null=True, verbose_name='If using cloud storage, what is the estimated annual cost and who will be covering the cost? '),
        ),
    ]
