# Generated by Django 3.2.10 on 2022-04-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0031_alter_dma_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmareview',
            options={'ordering': ['fiscal_year', '-created_at']},
        ),
    ]
