# Generated by Django 3.2.10 on 2022-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0032_alter_dmareview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dma',
            name='metadata_url',
            field=models.URLField(blank=True, help_text='Full link to any metadata records available online, if applicable', null=True, verbose_name='Please provide any URLs to the metadata'),
        ),
    ]
