# Generated by Django 3.2.10 on 2022-04-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0033_alter_dma_metadata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dma',
            name='metadata_url',
            field=models.CharField(blank=True, help_text='Full link to any metadata records available online, if applicable', max_length=1000, null=True, verbose_name='Please provide any URLs to the metadata'),
        ),
    ]
