# Generated by Django 3.2.10 on 2022-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0036_auto_20220502_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_fr',
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='requires_abl_services',
            field=models.BooleanField(default=False, editable=False, verbose_name='Does this project require the services of Aquatic Biotechnology Lab (ABL)?'),
        ),
    ]
