# Generated by Django 2.0.4 on 2018-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20180716_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
