# Generated by Django 2.0.7 on 2018-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_bug_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='application',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'grAIS'), (3, 'Data Inventory'), (4, 'HerMorrhage'), (5, 'Ticketing System')], max_length=2),
        ),
    ]
