# Generated by Django 2.0.4 on 2018-11-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_auto_20180823_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='application',
            field=models.IntegerField(choices=[(1, 'General'), (6, 'Accounts'), (2, 'grAIS'), (3, 'Data Inventory'), (4, 'HerMorrhage'), (5, 'Ticketing System'), (7, 'CAMP')]),
        ),
    ]
