# Generated by Django 2.1.4 on 2019-01-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0010_auto_20181203_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='application',
            field=models.IntegerField(choices=[(1, 'General'), (6, 'Accounts'), (2, 'grAIS'), (3, 'Data Inventory'), (4, 'HERMorrhage'), (5, 'Ticketing System'), (7, 'CAMP'), (8, 'Snow Crab'), (9, 'Diets')]),
        ),
    ]
