# Generated by Django 2.1.4 on 2019-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0013_auto_20190118_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='application',
            field=models.IntegerField(choices=[(1, 'General'), (6, 'Accounts'), (2, 'grAIS'), (3, 'Data Inventory'), (4, 'HERMorrhage'), (5, 'Ticketing System'), (7, 'CAMP'), (8, 'Snow Crab'), (9, 'Diets'), (10, 'Project Planning'), (11, 'Indigenous Hub'), (12, 'SciFi')]),
        ),
    ]
