# Generated by Django 3.1.2 on 2020-11-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0002_auto_20201106_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundingSourceType',
        ),
    ]
