# Generated by Django 3.1.2 on 2021-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0003_remove_project_fiscal_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='is_competitive',
            field=models.BooleanField(default=False, verbose_name='is competitive funding?'),
        ),
    ]
