# Generated by Django 3.1.2 on 2020-11-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0003_auto_20201109_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborativeagreement',
            name='project_years',
        ),
        migrations.AddField(
            model_name='collaborativeagreement',
            name='project_year',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='projects2.project', verbose_name='project year'),
            preserve_default=False,
        ),
    ]
