# Generated by Django 3.1.2 on 2021-01-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0004_fundingsource_is_competitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments_for_staff',
            field=models.TextField(blank=True, null=True, verbose_name='questions and comments for project leads'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approver_comment',
            field=models.TextField(blank=True, null=True, verbose_name='general comments'),
        ),
    ]
