# Generated by Django 3.1.2 on 2020-11-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0004_auto_20201109_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='project_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='projects2.projectyear', verbose_name='project year'),
        ),
    ]
