# Generated by Django 3.1.6 on 2021-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_auto_20210225_1538'),
        ('projects2', '0006_auto_20210322_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fiscal_years',
            field=models.ManyToManyField(editable=False, to='shared_models.FiscalYear', verbose_name='fiscal years'),
        ),
    ]
