# Generated by Django 3.1.2 on 2020-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0024_auto_20201102_1135'),
        ('projects2', '0006_project_fiscal_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(editable=False, to='projects2.FundingSource', verbose_name='complete list of funding sources'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fiscal_years',
            field=models.ManyToManyField(editable=False, to='shared_models.FiscalYear', verbose_name='fiscal years'),
        ),
    ]
