# Generated by Django 3.1.6 on 2021-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0007_project_fiscal_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='staff_search_field',
            field=models.CharField(blank=True, editable=False, max_length=5000, null=True),
        ),
    ]
