# Generated by Django 3.1.2 on 2020-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0008_auto_20201106_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectyear',
            name='chemical_needs',
        ),
        migrations.AddField(
            model_name='projectyear',
            name='other_lab_support_needs',
            field=models.TextField(blank=True, null=True, verbose_name='Describe other laboratory requirements relevant for project planning purposes.'),
        ),
        migrations.AddField(
            model_name='projectyear',
            name='requires_other_lab_support',
            field=models.BooleanField(default=False, verbose_name='Does this project require other specialized laboratory support or services (provide details below)?'),
        ),
    ]
