# Generated by Django 3.1.2 on 2020-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0008_auto_20201110_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectyear',
            name='administrative_notes',
            field=models.TextField(blank=True, null=True, verbose_name='administrative notes'),
        ),
    ]
