# Generated by Django 3.1.2 on 2020-11-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0025_auto_20201110_2058'),
        ('projects2', '0009_projectyear_administrative_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allotment_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='existing_project_codes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsibility_center',
        ),
        migrations.AddField(
            model_name='projectyear',
            name='allotment_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects2', to='shared_models.allotmentcode', verbose_name='allotment code (if known)'),
        ),
        migrations.AddField(
            model_name='projectyear',
            name='existing_project_codes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='shared_models.Project', verbose_name='existing project codes (if known)'),
        ),
        migrations.AddField(
            model_name='projectyear',
            name='responsibility_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_projects2', to='shared_models.responsibilitycenter', verbose_name='responsibility center (if known)'),
        ),
    ]
