# Generated by Django 3.1.2 on 2020-11-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0012_auto_20201112_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Target date (optional)'),
        ),
    ]
