# Generated by Django 3.1.2 on 2021-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0016_auto_20210113_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrfsubtheme',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='priority for research (en)'),
        ),
    ]
