# Generated by Django 3.1.2 on 2020-11-02 16:51

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0024_auto_20201102_1135'),
        ('projects', '0018_auto_20201029_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencematerial',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_materials', to='shared_models.region', verbose_name='region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referencematerial',
            name='file',
            field=models.FileField(upload_to=projects.models.ref_mat_directory_path, verbose_name='file attachment'),
        ),
    ]
