# Generated by Django 3.1.2 on 2020-11-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0020_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='project_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects2.projectyear'),
        ),
    ]
