# Generated by Django 3.1.2 on 2021-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0034_citation_publication'),
        ('projects2', '0021_auto_20210113_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='references',
            field=models.ManyToManyField(blank=True, editable=False, related_name='projects', to='shared_models.Citation', verbose_name='References'),
        ),
    ]
