# Generated by Django 3.1.2 on 2020-11-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects2', '0021_auto_20201123_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='allocated_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Allocated budget'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_denied',
            field=models.BooleanField(default=False, verbose_name='Project is not approved (do not proceed)'),
        ),
        migrations.AddField(
            model_name='review',
            name='notification_email_sent',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Notification Email Sent'),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_mod_by_projects_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='modified_by',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='project_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='projects2.projectyear'),
        ),
    ]
