# Generated by Django 3.1.2 on 2021-01-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0025_auto_20210114_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csrfclientinformation',
            options={'ordering': ['csrf_priority__code', 'name']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='objectives_methods',
        ),
        migrations.AlterField(
            model_name='activity',
            name='impact',
            field=models.IntegerField(blank=True, choices=[(1, '1-Negligible'), (2, '2-Low'), (3, '3-Medium'), (4, '4-High'), (5, '5-Extreme')], null=True, verbose_name='what will be the impact if the risks occurs'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='likelihood',
            field=models.IntegerField(blank=True, choices=[(1, '1-Very unlikely'), (2, '2-Unlikely'), (3, '3-Low'), (4, '4-Likely'), (5, '5-Almost certain')], null=True, verbose_name='what is the likelihood of the risks occurring'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='mitigation_measures',
            field=models.TextField(blank=True, null=True, verbose_name='what measures will be used to mitigate the risks'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='risk_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of risks and their consequences'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_information1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects1', to='projects2.csrfclientinformation', verbose_name='Additional info supplied by client (#1) (CSRF)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_information2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects2', to='projects2.csrfclientinformation', verbose_name='Additional info supplied by client (#2) (CSRF)'),
        ),
    ]
