# Generated by Django 3.1.2 on 2021-01-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0026_auto_20210114_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='expertise',
            field=models.TextField(blank=True, null=True, verbose_name='key expertise'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.TextField(blank=True, null=True, verbose_name='role in the project'),
        ),
    ]
