# Generated by Django 3.1.2 on 2021-01-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0027_auto_20210114_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_information1',
            new_name='client_information',
        ),
    ]
