# Generated by Django 3.1.2 on 2020-11-25 15:22

from django.db import migrations, models
import projects2.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0028_auto_20201125_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencematerial',
            name='file_fr',
            field=models.FileField(blank=True, null=True, upload_to=projects2.models.ref_mat_directory_path, verbose_name='file attachment (French)'),
        ),
        migrations.AlterField(
            model_name='referencematerial',
            name='file_en',
            field=models.FileField(upload_to=projects2.models.ref_mat_directory_path, verbose_name='file attachment (English)'),
        ),
    ]
