# Generated by Django 3.1.2 on 2021-01-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0028_auto_20210114_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_information2',
        ),
        migrations.AddField(
            model_name='project',
            name='second_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects2', to='projects2.csrfpriority', verbose_name='Linkage to second priority (CSRF)'),
        ),
    ]
