# Generated by Django 3.1.2 on 2021-01-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0031_auto_20210115_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrfclientinformation',
            old_name='nom',
            new_name='description_fr',
        ),
    ]
