# Generated by Django 3.1.2 on 2020-12-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0034_auto_20201201_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects2.projectyear'),
        ),
    ]
