# Generated by Django 3.1.2 on 2020-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0037_auto_20201201_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='impact',
            field=models.IntegerField(blank=True, choices=[(1, '1-Negligible'), (2, '2-Low'), (3, '3-Medium'), (4, '4-High'), (5, '5-Extreme')], null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='likelihood',
            field=models.IntegerField(blank=True, choices=[(1, '1-Very unlikely'), (2, '2-Unlikely'), (3, '3-Low'), (4, '4-Likely'), (5, '5-Almost certain')], null=True),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='deliverables',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='deliverables / activities'),
        ),
    ]
