# Generated by Django 3.1.2 on 2020-12-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0032_auto_20201201_1040'),
        ('projects2', '0038_auto_20201201_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experimental_protocol',
            field=models.TextField(blank=True, null=True, verbose_name='experimental protocol (ACRDP only)'),
        ),
        migrations.AddField(
            model_name='project',
            name='orgranization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='shared_models.organization', verbose_name='physical location (ACRDP only)'),
        ),
        migrations.AddField(
            model_name='project',
            name='rationale',
            field=models.TextField(blank=True, null=True, verbose_name='project problem / rationale (ACRDP only)'),
        ),
        migrations.AddField(
            model_name='project',
            name='species_involved',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='species involved (ACRDP only)'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_description',
            field=models.TextField(blank=True, null=True, verbose_name='description of team and required qualifications (ACRDP only)'),
        ),
    ]
