# Generated by Django 2.2.2 on 2019-07-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_models', '0019_auto_20190712_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream_order', models.IntegerField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('latitude_n', models.FloatField(blank=True, null=True)),
                ('longitude_w', models.FloatField(blank=True, null=True)),
                ('epsg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinate_resolution', models.FloatField(blank=True, null=True)),
                ('coordinate_precision', models.FloatField(blank=True, null=True)),
                ('coordinate_accuracy', models.FloatField(blank=True, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='river_sites', to='shared_models.Province')),
                ('river', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='river_sites', to='shared_models.River')),
            ],
            options={
                'ordering': ['province', 'name'],
            },
        ),
    ]
