# Generated by Django 2.2.2 on 2019-07-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_observation_operatingcondition_origin_precipitationcategory_sampler_sex_species_status_trap_winddire'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
