# Generated by Django 2.2.2 on 2019-07-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0003_auto_20190712_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trap',
            name='samplers',
        ),
    ]
