# Generated by Django 2.2.2 on 2019-07-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0004_remove_trap_samplers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sampler',
        ),
    ]
