# Generated by Django 2.2.2 on 2019-07-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0005_delete_sampler'),
    ]

    operations = [
        migrations.AddField(
            model_name='trap',
            name='samplers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
